### PR TITLE
Issue #2309: The 'Startup' tag must be placed into the 'Defaults' section

### PR DESCRIPTION
**Pull request by peter-perot**
This PR corrects a mistake in the docs. See https://github.com/dotnet/orleans/issues/2309.

### CODE REVIEW

**Comment by ReubenBond** [comment]
Thanks, LGTM!

I wonder if you would make one more adjustment & fix the `OrleansConfiguration.xsd` file so that it includes the `<Startup>` section under the `NodeConfiguration` complexType.

That's not on this branch, so I'll merge this anyway.

**Comment by peter-perot** [comment]
@ReubenBond: What's the correct branch for the XSD fix: `master` or `1.3.0`?

Anyway: Is the `Startup` tag only allowed in the `Defaults` section, or can one configure a different startup per node such that the tag is also allowed in the `Override` section?

**Comment by ReubenBond** [comment]
@peter-perot `master`. `Startup` is defined in `NodeConfiguration`, so It ought to be accessible in both `Defaults` and `Override`.

**Comment by peter-perot** [comment]
XSD has been adjusted. See PR #2314.

**Comment by sergeybykov** [comment]
@peter-perot For some reason there's a merge conflict in #2314.

**Pull request merged**
