### PR TITLE
Add project logos c/o Albel Derais

### PR DESCRIPTION
**Pull request by ReubenBond**
More of bel's work can be found here: https://www.behance.net/Albel

### CODE REVIEW

**Comment by jdom** [comment]
This is great, although let's not check in binaries in the master branch. Once in there it will be on the repository history for ever. 
We could either have a separate branch or a separate repo for this kind of things

**Comment by ReubenBond** [comment]
Should I drop all but the svg, then?

**Comment by veikkoeeva** [comment]
@jdom, @ReubenBond I didn't notice this, but [I dropped a few lines in Gitter](https://gitter.im/dotnet/orleans?at=57622ffadfb1d8aa45a3edb0) that we could make use of large file storage and convert existing files (old ones can be purged too from the history, but that's basically a rebase on master and a bit painful).

**Comment by sergeybykov** [comment]
We have https://github.com/dotnet/orleans/tree/gh-pages/Images and https://github.com/dotnet/orleans/tree/gh-pages/Icons for binary images. I suspect we'll end up with more than one PNG, for different sizes, etc.

So I suggest we put PNGs to gh-pages for now. If we later decide to move away from gh-pages, we'll reconsider.

**Comment by jdom** [comment]
@sergeybykov 
> So I suggest we put PNGs to gh-pages for now. If we later decide to move away from gh-pages, we'll reconsider.

I assume you meant that we put all image assets (PNG, SVG, and all) in that branch, correct? I would not treat this SVG as a special case just because it ended up being small this time around.

**Comment by sergeybykov** [comment]
Fine with me.

**Comment by veikkoeeva** [comment]
If I may chime in to clear any potential confusion (for anyone following the chatter here and elsewhere), the *SVG* file is XML and if not large, there might not be a problem otherwise than making a policy on how to treat asset files, large files and binary files. I think I for one are on somewhat on the same line as @jdom.

As for specifically *SVG*, a point of note that due to its nature, it's usually not edited by hand, like *md* files, so this is a case some prefer using a binary diff. With some searching, [this issue elsewhere](https://github.com/Danimoth/gitattributes/issues/45) has nice looking discussion about.

**Comment by sergeybykov** [comment]
@ReubenBond Let's out the assets to the gh-pages branch for now. As we refactor how the docs are built, we'll move things around if necessary.

**Comment by ReubenBond** [comment]
I've opened #1873 to pull into the `gh-pages` branch instead.

**Pull request closed without merging**
