### PR TITLE
Downgrade Benchmark to target netcoreapp2.1 instead of 2.2

### PR DESCRIPTION
**Pull request by sergeybykov**
No need to target 2.2 at this point as that increases friction with compiling sources.

### CODE REVIEW

**Comment by sergeybykov** [comment]
@dotnet-bot test bvt

**Comment by ReubenBond** [comment]
@dotnet-bot test functional

**Comment by ReubenBond** [comment]
@dotnet-bot test functional

**Comment by ReubenBond** [comment]
@dotnet-bot test functional

I think the server may've dropped the request

**Pull request merged**
