### PR TITLE
Prepare syntax highlighting in orleans documentation on github pages.

### PR DESCRIPTION
**Pull request by ksuszka**
Current version of Orleans documentation on github pages does not have source code syntax highlighting enabled. I've made a few changes so it can be added:
- changed default markdown rendering engine to "redcarpet" as [AFAIK](https://github.com/blog/832-rolling-out-the-redcarpet) it is a precursor of the engine used on github (however, not in github pages by default) and [set some options](http://stackoverflow.com/a/28114624/3568443) to make it close to the one from github.
- added simple css file for syntax highlighter similar to default Visual Studio style. I used following command:

    ```pygmentize -S vs -f html > assets/themes/twitter/css/syntax.css```

- set csharp syntax for highlighter on My-First-Orleans-Application page to prove it worked

You can check final effect [here](http://ksuszka.github.io/orleans/Step-by-step-Tutorials/My-First-Orleans-Application)

### CODE REVIEW

**Comment by richorama** [comment]
very nice!

**Comment by jthelin** [comment]
Nice!

@ksuszka - would you want to merge this branch now, or leave it open for a while so you can convert more samples on this same PR?

Looks like the main part of the PR is setting up the rendering infrastructure to make this work, and the conversion of each code snipped is fairly mechanical after that? 8121a84 

Thanks again for making this initiative :)

**Comment by richorama** [comment]
@jthelin  if you merge the PR now, I don't mind pitching in to do some of the grunt work!

**Comment by sergeybykov** [comment]
Code looks so much better now. Thank you, @ksuszka!

Is there a trick to add search to GitHub pages? :-)

**Comment by richorama** [comment]
@sergeybykov google site search??? https://cse.google.com/cse/

**Comment by sergeybykov** [comment]
@richorama Sorry, I am almost modern-web-illiterate. :-) Though I don't think we want to bring ads to our GitHub pages. GitHub doesn't have a full-text index for pages, only for code?

**Comment by akoeplinger** [comment]
> GitHub doesn't have a full-text index for pages, only for code?

GitHub only indexes the default branch, so it knows nothing about the gh-pages branch.

Over at the Mono project we decided to keep it simple and just have the search form submit to google, it works surprisingly well (e.g. for orleans: https://www.google.com/search?q=Storage+site:dotnet.github.io%2Forleans)

**Comment by sergeybykov** [comment]
So we just need to add a text box and a button to the header and have it show results in a new window?

**Comment by akoeplinger** [comment]
Yes, that is exactly what we're doing, just a [form with a button](https://github.com/mono/website/blob/04954faa6742617863de4b32de8142d6f162b020/_layouts/base.html#L52-L62).

**Comment by gabikliot** [comment]
This is awesome @ksuszka!

**Comment by richorama** [comment]
this form should do the job using bing...

```
<form onsubmit="document.getElementById('q').value = 'site:dotnet.github.io/orleans ' + document.getElementById('query').value" action="https://www.bing.com/search" method="get">
    <div class="row collapse">
        <input id="q" name="q" type="hidden" />
        <input id="query" type="text" placeholder="Search..." />
        <button type="submit">Search</button>
    </div>
</form>

```

**Comment by sergeybykov** [comment]
Nice! I like Bing color scheme better. :-) How do we add it to the page header?

**Comment by gabikliot** [comment]
I think we need to devise the header first. 
http://www.mono-project.com/ has it very nicely. I love how their web site looks like. The header provides clear links to the most important stuff.
We might be ready for the next iteration of web site re-wamp.

**Comment by richorama** [comment]
agreed

**Pull request merged**
