### PR TITLE
TraceSource writers

### PR DESCRIPTION
**Pull request by amccool**
You will have to forgive my lack of git fitness.   There are a few items that should not be in this pull request

./Build
./Nuget
./src/OrleansProvider
./test

### CODE REVIEW

**Comment by sergeybykov** [comment]
I am confused. What exactly is the problem/goal here? This seems to overlap with https://github.com/dotnet/orleans/pull/1026.

**Comment by amccool** [comment]
I believe #1026 is more ambitious in means of diagnostics data points.   This PR was for two use cases:
1) Allow configuration of the five TraceSources to hook up to different TraceListeners.   E.G. sending Grain traces to say a loggly listener, and Runtime Traces to a database listener
2) Reducing the trace message field vebosity (the formatted string with all the data as a single string) and instead let the TraceListener's formatting of the data point (e.g. timestamp to a timestamp column, thread name to a thread name column)

hope that clears the confusion.   I'm also more than happier to attempt to clean up this PR to a more simple set of changes.

**Comment by sergeybykov** [comment]
@amccool Now that https://github.com/dotnet/orleans/pull/1026 is merged, can you rebase this one against the master, so that the added value is clearly visible?

**Comment by amccool** [comment]
Question before the rebase.  Should I include the single file per class commits, or only the added class file and it's plumbing changes? The example is the ILogConsumer.cs containing multiple interfaces.

**Comment by sergeybykov** [comment]
I'm fine either way with a slight preference for keeping trivial derived interfaces within the same source file as the interface they extend as opposed to adding nearly empty separate source files for them.

**Comment by amccool** [comment]
#1026 was a big enough change that you're right it obsoletes any valid work in this PR.   Go ahead and reject this PR.  I will create a new PR for TraceSource based off ITraceTelemetryConsumer.

**Comment by sergeybykov** [comment]
Sounds good.

**Pull request closed without merging**
