### PR TITLE
Fixes for 2.4.5 cherry-picked from master

### PR DESCRIPTION
**Pull request by sergeybykov**

### CODE REVIEW

**Comment by ReubenBond** [comment]
We can either ignore CI or add a global.json

**Comment by sergeybykov** [comment]
Let's try to add global.json. I don't understand what needs to be there though.

**Comment by ReubenBond** [comment]
It's because I edited the CI pipeline to make builds on .NET Core 3.1 work for the multi-target work. Master had a global.json already, but the 2.x branch doesn't.

**Comment by sergeybykov** [comment]
Looks like it still breaks on Linux and MacOS. I can't set it to 3.1.100 without fixing building of F# libraries. Maybe it's not worth fixing in 2.4.* anyway.

**Pull request merged**
