### PR TITLE
Bump fsharp sample to 1.3.1

### PR DESCRIPTION
**Pull request by serbrech**
Part of #2359

### CODE REVIEW

**Comment by serbrech** [comment]
looks like a flaky test failure again.

**Comment by ReubenBond** [comment]
@dotnet-bot test this please

**Comment by attilah** [comment]
@serbrech Please update the [F# project file](https://github.com/dotnet/orleans/blob/master/Samples/FSharpHelloWorld/Grains/Grains.fsproj#L62) to use ```FSharp.Core``` NuGet package isntead of the F# assembly in the GAC. And cleanup/update the fsproj to look like the new [template](https://github.com/dotnet/orleans/blob/master/src/OrleansVSTools/VSProjectTemplateGrainImplementationFSharp/ProjectTemplate.fsproj) (TargetFSharpCoreVersion, Reference (just what needed), etc).

Thanks, with your help we're getting there 👍

**Comment by attilah** [comment]
@serbrech  Thanks for the update!

**Pull request merged**
