### PR TITLE
Add validator for ClusterOptions

### PR DESCRIPTION
**Pull request by benjaminpetit**
Currently we check that `ClusterId` is set but not `ServiceId`. I added a validator to test this.

### CODE REVIEW

**Comment by veikkoeeva** [comment]
Seems like relevant to #4351.

**Comment by xiazen** [comment]
@dotnet-bot test functional please

**Comment by xiazen** [comment]
Orleans.Runtime.OrleansConfigurationException : Configuration for ClusterOptions is invalid. A non-empty value for ServiceId is required. See $https://aka.ms/orleans-troubleshooting for more information.

looks like a lot of our tests actually have invalid service id haha. this make the functional fail

**Comment by jdom** [comment]
This is a big breaking change, as services already deployed will have to set this now, and effectively change their service's `ServiceId`. Do we have a way to opt-out of this validation and treat it like an explicitly empty service id? Also, what is the rationale for requiring a non-empty ServiceId? You might already have your cluster's storage isolated from anything else. Or you might even have no storage, reminders or stream providers that require a ServiceId... Maybe each of the providers that require ServiceId should add the validator (if it was not already added)? This way users don't have to fill in something they might not use

**Comment by sergeybykov** [comment]
I don't consider this a breaking change. Service ID is required and was always required. It's implicitly used in multiple places. That requirement was masked by `Guid` defaulting to empty GUID prior to 2.0. I don't think we should provide an opt-out option or complicate things here. Service ID is easy to specify.

**Comment by jdom** [comment]
Then perhaps explain 8n the exception message that if you are porting from 1.x and you were not explicitly setting the serviceid, then they might want to use `Guid.Empty.ToString()` (or whatever it is so that it matches the deployed service)

**Comment by xiazen** [comment]
+1 on @jdom 's comment. if the user wasn't aware of setting serviceId before, and doesn't know the importance of keeping serviceId consistent in between deployments, it is highly possible they end up set a new serviceId, which is not `Guid.Empty.ToString()` (the old defaults) and end up losing state from previous deployments.

**Comment by xiazen** [comment]
this kind of subtle breaking change should be called out clearly, though exception message and docs (we already called it out in docs). But exception message add double safty and more obvious

**Comment by sergeybykov** [comment]
We called it out in http://dotnet.github.io/orleans/Documentation/Migration/Migration1.5.html#provider-configuration. Although that may not be easy to discover.

**Comment by xiazen** [comment]
Orleans.Runtime.OrleansConfigurationException : Configuration for ClusterOptions is invalid. A non-empty value for ServiceId is required. See $https://aka.ms/orleans-troubleshooting for more information.

tests are failing because no valid serviceId was set for them.

**Comment by benjaminpetit** [comment]
So the issue is that now `ServiceId` is mandatory, but there is no way to configure it via the legacy `ClientConfiguration`. And the static legacy `GrainClient` is initialized only with this configuration object.

Our options:

- Remove the static `GrainClient`
- Add a parameter `ServiceId` (and probably another one for `ClusterId`) to `GrainClient.Initialize`
- Add a static delegate that takes a `IClientBuilder` to allow customization of the static `GrainClient`.

The later solution is probably the best since we might have missed some other stuff in the transition to the builder pattern for the static `GrainClient`... But maybe it is time to remove this class.

**Comment by jdom** [comment]
Why does the client need to know about the ServiceId? It should just care about which cluster it's connecting to, but seems like ServiceId should be an implementation detail of the the silos that clients should not be bothered with.

**Comment by benjaminpetit** [comment]
Some providers that run on the client need the `ServiceId` (for example streaming)

**Comment by jdom** [comment]
When it's needed on the client, must it always reflect what's configured in the service? If the answer is yes (which I assume it is), shouldn't this setting be transparently propagated from the Silo as soon as the client connects?
I would expect a similar thing should be done to the entire configuration, with the possibility for the client to override some values, but especially useful to avoid defining the EventHub connection strings on the client for example, just flow it from the Silo.
Also some knobs such as response timeout, etc could have defaults coming from the Silo instead of constant values.
I know that's a bigger change, but at least the ServiceId seems like it should have never belonged on the client, and it's very easy to have them mismatch and not know about it

**Comment by ReubenBond** [comment]
@jdom should ClusterId be globally unique or scoped to ServiceId? I believe it *should* be the latter.
In that case, we ought to be setting ServiceId at configuration time, as we are.

**Comment by ReubenBond** [comment]
`ServiceId + ClusterId` -> cluster membership
`ServiceId` -> anything service-wide (storage, streams)

One issue with silos flowing service id to clients is that ServiceId is a part of ClusterOptions, which means that it must be known ahead of time, otherwise having options flow like that (at first connection time) messes with a core assumption we have about options.

**Comment by ReubenBond** [comment]
If people decide otherwise, I won't push back too hard, but that's my reasoning anyway

**Comment by benjaminpetit** [comment]
So what I did:

- I added the ServiceId as a Guid in the legacy client configuration
- I added it too in the XML parsing logic.

Why a Guid? To replicated what is in the Silo legacy configuration. I didn't ant to have a string in one and a guid in another. If we want to change both, let's do it in another PR

**Pull request merged**
