### PR TITLE
Add Analyzers to Orleans

### PR DESCRIPTION
**Pull request by mholo65**
- Setup basic Analyzer project
- Setup basic Tests project
- Create analyzer for AlwaysInterleaveAttribute

### CODE REVIEW

**Comment by mholo65** [comment]
Basics for Analyzers.

Are there any docs on how to create new projects? It seems that if I try to copy samples from the other projects (e.g. removing `<TargetFramworks>` from .csproj), then Visual Studio will convert my project to a legacy project. Also, where should a new test project be hooked up in order to be run by CI? Is it sufficient to add a new line to `Test.cmd`?

ping @ReubenBond

**Comment by ReubenBond** [comment]
I pushed some changes, @mholo65 & I rebased on top of master

**Comment by ReubenBond** [comment]
I'll merge when tests complete - your tests are running in CI now.

**Comment by ReubenBond** [comment]
Thank you, @mholo65! 🎉

**Comment by mholo65** [comment]
Thanks @ReubenBond! In order to make use of Analyzers by default, it might be wise to have `Orleans.Core.Abstractions` depend on `Orleans.Analyzers`. This is how EF does it. https://github.com/aspnet/EntityFrameworkCore/blob/99fb2d4e3d52f8a3be67fe6815a4fc288e63fe50/src/EFCore/EFCore.csproj#L43

**Comment by jdom** [comment]
Notice there that it's being added to EFCore, not EFCore.Abstractions. We shouldn't be adding a dependency to the abstractions project that will make it release with a faster cadence, as we've been there already, and it's not fun

**Comment by ReubenBond** [comment]
I'm not sure where to add it just yet. Grain/grain interface projects only require a reference to the .Abstractions project. We could also add it to the CodeGenerator package, but that feels awkward

**Pull request merged**
