### PR TITLE
Fix DI scope issue in azure blob

### PR DESCRIPTION
**Pull request by Alxandr**
Closes: #5543

### CODE REVIEW

**Comment by Alxandr** [comment]
Turns out this happens more places. Will get it working and update PR.

**Comment by Alxandr** [comment]
Are there flacky timings in the functional tests? Cause I can't see how I broke any of the tests that have failed.

**Comment by xiazen** [comment]
Yes sometimes. I think your PR is fine, since both bvt and functional passed. The AzureOps one are new, and run identical tests as bvt and functional. They are more flacky.

**Comment by xiazen** [comment]
Thanks for the contribution! although I think the right fix here is to use constructor injection, instead of resolving it directly from DI. We probably just missed those cases when we move our configurator to use Options. If you can help fix that, it would be great!!

Thanks again :)

**Comment by Alxandr** [comment]
Some functional tests should probably be made/updated to use the strict DI scope checks to see if there are more of these errors btw. I just caught the `IOptionsSnapshot` one.

**Comment by xiazen** [comment]
Yes you are right. I will put out a PR for it.

**Pull request merged**
