### PR TITLE
added 2 presentations for VM4 and VM 8.5. Updated index to point to downloadable files

### PR DESCRIPTION
**Pull request by centur**

### CODE REVIEW

**Comment by centur** [comment]
don't accept it yet, as index links are incorrect

**Comment by centur** [comment]
Sorry, actually links will become correct once merged. my bad

**Comment by centur** [comment]
how to sign CLA for contribution ?

**Comment by sergeybykov** [comment]
@centur No need for CLA for this kind of changes. The bot should have sent you an email with instructions how to sign the CLA (via DocuSign).

**Pull request merged**
