### PR TITLE
[WIP] migrate sample adventuredotnetcli to new csproj

### PR DESCRIPTION
**Pull request by serbrech**
The migration to the new csproj is done.  

It was noted that a dotnetcli sample not targeting dotnet core made little sense.  
Should I attempt to migrate the sample to the dotnet core bits? Or is it too early?  

part of #2359

### CODE REVIEW

**Comment by attilah** [comment]
@serbrech My RC3 changes got merged during weekend, please update the PR against those changes. It involves more cleanup of csproj files, since a lot more default information is coming from SDK targets files.

**Comment by attilah** [comment]
@serbrech do you have an ETA for the update?

**Comment by serbrech** [comment]
@attilah I was under the impression that I should just wait for 1.4.0 release. that's why I didn't do any other updates. I wrote a script to bump the packages instead

**Comment by attilah** [comment]
@serbrech Ahh, cool! 1.4.0 released ;-) I think it would be ok to checkin the sample updating script too into the Samples root folder.

**Comment by jdom** [comment]
Is this compatible with the RTM tooling? If so, is there something else preventing us merging it?

**Comment by attilah** [comment]
Not at all, further updates needed for this, I don't know if @serbrech will do the update?

**Comment by sergeybykov** [comment]
The sample has been migrated - https://github.com/dotnet/orleans/tree/master/Samples/2.0/Adventure. Closing this.

**Pull request closed without merging**
