### PR TITLE
Added  #pragma warning disable  CS1591 to supress warnings in the source generated code

### LINKED ISSUE #8290: CodeGenerator not suppress Missing XML comment
when project `<GenerateDocumentationFile>True</GenerateDocumentationFile>`
Generator file have many warning `CS1591`, can we suppress them in CodeGenerator ?

### PR DESCRIPTION
**Pull request by m3nax**
# Description
Added `#pragma warning disable CS1591` and `"#pragma warning restore CS1591` to the source generated file to supress warnings when projects contains `<GenerateDocumentationFile>True</GenerateDocumentationFile>`

Fixes #8290

### CODE REVIEW

**Comment by ReubenBond** [comment]
Thank you for opening this PR, @m3nax!

I was looking for the Roslyn-native way to do this. It might look something like this, in CodeGenerator.cs before we return the `CompilationSyntax` but I haven't tested this yet:

```csharp
            var disabledWarnings = new List<string>();
            assemblyAttributes[0] = assemblyAttributes[0]
                .WithLeadingTrivia(
                    SingletonList(
                        PragmaWarningDirectiveTrivia(
                            Token(SyntaxKind.DisableKeyword),
                            SeparatedList(disabledWarnings.Select(w => (ExpressionSyntax)w.GetLiteralExpression())), isActive: true)));
            
            return CompilationUnit()
                .WithAttributeLists(List(assemblyAttributes))
                .WithMembers(List(namespaces));
```

**Comment by m3nax** [comment]
I Will test It tomorrow

**Comment by m3nax** [comment]
@ReubenBond I have updated the implementation as you suggested but, as it is the first time I have modified a source generator, I did not understand how to remove the double quotes from the list of warnings to be suppressed

Output of  orleans.g,cs is like this:
``` CSHARP
#pragma warning disable "CS1591"
[assembly: global::Orleans.ApplicationPartAttribute("ConsoleApp1")]
[assembly: global::Orleans.ApplicationPartAttribute("Orleans.Core.Abstractions")]
[assembly: global::Orleans.ApplicationPartAttribute("Orleans.Serialization")]
[assembly: global::Orleans.Serialization.Configuration.TypeManifestProviderAttribute(typeof(OrleansCodeGen.ConsoleApp1.Metadata_ConsoleApp1))]
namespace OrleansCodeGen.ConsoleApp1
{

// CODE

}
#pragma warning restore "CS1591"
```

Do you have any suggestions?

**Comment by m3nax** [comment]
@ReubenBond Problem fixed

**Review by ReubenBond — APPROVED** [review]

**Comment by ReubenBond** [comment]
Fantastic, thank you, @m3nax!

**Pull request merged**
