### PR TITLE
add indexes to MySql tables

### PR DESCRIPTION
**Pull request by bronsh**
Improve MySql performance by using indexes

### CODE REVIEW

**Comment by sergeybykov** [comment]
@shayhatsor and @veikkoeeva are the SQL wizards. I wonder what they think.

**Comment by veikkoeeva** [comment]
@bronsh I'm curious to know if you have analysis to share?

Here's what I think: `OrleansMembershipTable` and `OrleansMembershipVersionTable` have fairly low row count, so most likely they're cached in memory and indexing won't have a perceptible advantage or disadvantage. Indexing `OrleansRemindersTable` like that might help or be counterproductive. I think it's a fair assumption there are not many distinct `serviceId`s, so the index will likely be ignored as it's really discriminating the rows (it's maintenance costs, though). Indexing `GrainHash` will most likely help, but I'd be delighted to see someone share insight on `SELECT/UPDATE/INSERT` statistics. That aside, beneficial candinates would be also `GrainId` and `ReminderName`, but they're potentially a bit fattier indices and there are other issues too...

... Which leads to https://github.com/dotnet/orleans/issues/2429. In general adding indexes have merit and adding them judiciously make a positive effect, but to scale up reminders (and stats), the constructs would need a bit overhauling, I believe.

**Comment by sergeybykov** [comment]
Should we close this for now?

**Comment by veikkoeeva** [comment]
@sergeybykov, @bronsh Indices on `GrainId` and `ReminderName` could be beneficial and perhaps indexing the hash range, but indexing `ServiceId` might be (I haven't measured) hurtful because maintenance isn't free and it doesn't really filter the set effectively. Also `OrleansMembership*Table` likely is always quite shallow (i.e. in memory and processed quickly), so without further measuring, at least for me it's difficult to tell if it has impact or not.

Having sane defaults are useful, but I'm not sure these proposed measures.

**Comment by sergeybykov** [comment]
@veikkoeeva I'm trying to decide what we should do here. Keep the PR open until there are perf benefits measurements?

**Comment by sergeybykov** [comment]
I'll close it for now. Please reopen when we figure out the benchmarking strategy.

**Pull request closed without merging**
