### PR TITLE
Move some configuration to typed options

### PR DESCRIPTION
**Pull request by jdom**
- Move ServiceId to SiloOptions

### CODE REVIEW

**Comment by xiazen** [comment]
@dotnet-bot test this please

**Comment by xiazen** [comment]
code LGTM. but there is build failure. you might want to take a look

**Comment by jdom** [comment]
Yup, there's many build failures, none of them currently related to the PR. @attilah is trying to address them here: https://github.com/dotnet/orleans/pull/3780

**Comment by jdom** [comment]
@dotnet-bot test this please
Reason: all completely unrelated failures. No test is failing though, just the known issue when executing the tests, so feel free to merge if you want to

**Comment by jdom** [comment]
@dotnet-bot test this please

**Comment by attilah** [comment]
@jdom LMK when you're comfortable with merging this after a few test passes.

**Comment by jdom** [comment]
Heh, it was ready even with the other failures, hehe, so please merge it

**Pull request merged**
