### PR TITLE
Allowing for a IGrainStateMapFactory to be created in a external assembly

### PR DESCRIPTION
**Pull request by amccool**
in order to be able to create a IGrainStateMapFactory in non orleans assembly I need these internals to be public.

### CODE REVIEW

**Comment by amccool** [comment]
@sergeybykov I'm not up to date on the master branch.   If your happy with this PR, could it get pulled into master without me?

**Comment by sergeybykov** [comment]
@amccool Sure.

LGTM

**Comment by jthelin** [comment]
LGTM

**Comment by jthelin** [comment]
Created PR #1329 to apply this change to master branch.

**Comment by jthelin** [comment]
Having thought about this overnight, i realized i goofed by merging this to the 1.1.2 branch.

From a semantic and release versioning perspective, 1.1.2 branch should be fixed and immutable.

I will reset the `1.1.2` branch to the previous commit d21dab5d4b1ad754b2b9e3b7a2c567923de24c7c which was the actual released version of the code.

PR 1329 applies the change in this PR to master instead.

**Comment by sergeybykov** [comment]
I deleted 1.1.2 branch to prevent future confusion (should have done that right after the 1.1.2 release).

**Pull request merged**
