### PR TITLE
Journaled Storage Provider

### PR DESCRIPTION
**Pull request by jkonecki**
I've added a Journaled Storage Provider in OrleansEventSourcing assembly.

Now I need a bit of assistance with the following issue.

1. Storage Providers are managed by `StorageProviderManager`,
2. `ProviderLoader<IStorageProvider>` is used to load storage providers,
3. I create a separate interface `IJournaledStorageProvider` in `OrleansEventSourcing` assembly,

This causes following problems:

1. I cannot create `ProviderLoader<IJournaledStorageProvider>` in `StorageProviderManager` as that requires a reference from `Orleans` to `OrleansEventSourcing`
2. Even if the `IJournaledStorageProvider` existed in `Orleans` I think we would need to add `<JournaledStorageProviders>` node under `<Global>` in OrleansConfiguration.xml so the provider validation wouldn't fail in ProviderLoaders.

### CODE REVIEW

**Comment by yevhen** [comment]
Why are you hesitating to include ES stuff to core assembly? I don't understand. It's just fews interfaces and base classes without any dependencies. 

Why all this hassle? Overthinking?

**Comment by yevhen** [comment]
The nuget package which contain only 2 types and that have no other dependencies than dependency on core will be looking strange as well. it's too much overhead. Too much decoupling is also bad ...

**Comment by gabikliot** [comment]
Agree with @yevhen, adding just the interfaces to Orleans core is not a problem.

**Comment by jkonecki** [comment]
I've push following changes:

 - Base event-sourcing interfaces and classes are moved back to Orleans assembly,
 - Orleans configuration contains a new `JournaledStorageProviders` under `Globals`,
 - Created `JournaledStorageProviderManager` and updated `Silo` and `Catalog`

I would like to propose a following potentially breaking change: 
I feel we are right now missing an abstraction over `IStorageProvider` and `IJournaledStorageProvider`. For me `IStorageProvider` should describe common behaviour of all storage providers regardless of what and how is actually being stored. `IJournaledStorageSprovider` and `IStateStorageProvider` should derive from it. In that way `Silo` and `Catalog` could depend on the base, common interface. What do you think?

The test is still failing as I haven't finished making changes to the `Catalog` yet.

**Comment by jason-bragg** [comment]
@jkonecki - "cannot create  ProviderLoader<IJournaledStorageProvider>  in  StorageProviderManager "
To me this makes sense since IJournaledStorageProvider is not an IStorageProvider.  Any new storage provider will need to conform to the IStorageProvider interface to fit into the existing framework.  How would moving the interfaces into Orleans change this?

@gabikliot - "adding just the interfaces to Orleans core is not a problem"
I agree that adding a few interfaces to core is not a big deal, but I think the issues @jkonecki is encountering -may- indicate flaws in our approach or extensibility issues in our storage provider story.  In general, it should not be difficult for Orleans users to contribute new provider types without requiring changes to core; If this can't be done, the causes should be examined.

@jkonecki - "For me  IStorageProvider  should describe common behavior of all storage providers regardless of what and how is actually being stored. "
Does it not?  In general I agree, but this assumes there is a common pattern that is applicable to all storage providers.
What would this new abstraction look like?

Is IJournalStorageProvider really a storage provider?  
If it is it should fit into the storage provider infrastructure, if it is not then shouldn't it be orthogonal?
Are we trying to couple two unrelated sets of functionality because they are conceptually similar?

**Comment by jkonecki** [comment]
> Is IJournalStorageProvider really a storage provider?

That is a good question.
For me it seems it should be - I understand storage provider is a way for a
grain to persist itself. I think the current implementation of storage
providers was geared towards hydrating the state - that's natural as this
was the desired behaviour for the first usages of the framework.

I think we could use this exercise as an opportunity to clean up and better
define the abstractions.

One more thing that I found slightly confusing was the Bridge between grain
and storage provider. It wasn't clear to me what is the purpose of it...

**Comment by jason-bragg** [comment]
"One more thing that I found slightly confusing was the Bridge between grain
and storage provider. It wasn't clear to me what its purpose is"
Do you mean GrainStateStorageBridge?
Others may have a clearer view of it's history, but grains use implementations of IStorage to manage the grain state.  GrainStateStorageBridge is an implementation of IStorage that uses storage providers to manage the grain state, so they act as a 'bridge' between the grain and storage providers.

Interesting question though...  From this, it looks to me like different storage patterns, say those that don't conform to the IStorageProvider interface, could be supported by using a different 'bridge'.  This being the case, I'm wondering if the StorageProviderAttribute should be an instance of StorageAttribute that grains use to get their IStorage object instead of the IStrageProvider, since IStorage is a higher level abstraction.

If Orleans grain state storage worked this way, anyone could add there own FoogaziStorageAttribute derived from StorageAttribute which specifies which implementation of IFoogaziStorageProvider to use, where IFoogaziStorageProvider follows some storage pattern not currently supported in Orleans.  The FoogaziStorageAttribute would provide its own implementation of IStorage (FoogaziStorageBridge) that uses IFoogaziStorageProviders to manage grain state.
In our case replace 'Foogazi; with 'Journaled' and we're done, right..?
Thoughts?

**Comment by sebastianburckhardt** [comment]
We had a similar situation for our work on geo-replicated grains (I will talk more about this during the virtual meetup). Our solution right now is to use a QueuedGrain class, which is a variation of Grain, with its own type of bridge, and for which various storage or replication providers can be specified.  

Perhaps it would be worth to come up with a way to support such customizations in general:
1)  Support grain variations like JournaledGrain or QueuedGrain that have a custom storage API. For each such storage API, there is a corresponding bridge object stored in the grain.
2) User can choose provider implementation using an attribute. 

It sometimes even makes sense to let users mix & match storage APIs and storage providers
(for example, you could use a traditional storage API on top of a journaling provider, or a JournaledGrain on top of a traditional storage provider). This can be supported by using a "translation bridge".

What we did in our case is to have the provider be a "bridge factory", and delegate the whole storage API to the bridge. The provider can at construction time choose the desired type of object for the bridge, which is very flexible.

**Comment by sergeybykov** [comment]
I had a rather different mental picture of `IJournaledStorageProvider`. I expected it to have methods like `AppendEvent`, `SaveSnapshot`, `LoadAllEvents`, `LoadLatestSnapshotAndEventsSince` or something along those lines. Meaning that it would be fundamentally different from `Read/Write/ClearStateAsync`. Some or all of these methods I thought would be exposed to the grain code via the `JournaledGrain` base class just like `Read/Write/ClearStateAsync` are exposed today via `Grain<T>`.

In the current form, `IJournaledStorageProvider` is identical to `IStorageProvider` except for the base type for grain state. Since there is already a desire to move away from requiring `GrainState` as a base class for state classes (as in https://github.com/dotnet/orleans/issues/865), the difference between these two interface will completely disappear.

There is a separate but very related question about how to connect storage providers of different APIs to the grain code, via 'bridges' as part of the base classes or somehow else. But the first order question to me is the programming model one: What is the API that would be most natural for ES grains? I thought `Read/Write/ClearStateAsync` wouldn't be it.

**Comment by sebastianburckhardt** [comment]
I agree with @sergeybykov - we should carefully control the top-level storage API that the client sees (i.e. all the things you can call on the grain, and that show up in intellisense), and (other than being useful)  it should be discoverable: the names of the methods should be as self-explanatory as possible, and the semantics should be as free of surprises as possible.. 

Looks like right now, we have four top-level APIs implemented or drafted:

* traditional `Grain<T>` with members `State`, `ReadStateAsync`, `WriteStateAsync`, `ClearStateAsync`
* current `JournaledGrain<T>` with members `State`,  `ReadStateAsync`, `WriteStateAsync`, `ClearStateAsync`, `RaiseEvent`
* Sergey's proposal for `JournaledGrain<T>` with members  `State`, `AppendEvent`, `SaveSnapshot`, `LoadAllEvents`, `LoadLatestSnapshotAndEventsSince`, ...
* Our caching/queueing grain `QueuedGrain<T>` with members  `TentativeState`, `ConfirmedState`, `PendingUpdates`, `EnqueueUpdate`, ...

(the last one is the one we are working on for georeplication scenarios, it queues updates and writes them to storage asynchronously)

Perhaps the first question is: how can the framework cleanly support a variety of such interfaces? I don't believe a single interface can cover all scenarios (trying to unify them is going to end up ugly and hard to understand). 

I think the nicest thing we can do for users is to let them *choose* the grain storage API that matches their thinking and is right for their reliability/performance needs (i.e. for which they can choose an appropriate provider implementation). I think the simplest way to choose the storage API is to choose the superclass (`Grain<T>` vs. `JournaledGrain<T>` vs. `QueuedGrain<T>`). The framework can then construct the appropriate grain version. This is what we have currently implemented for the QueuedGrain.

Independently, the user can also choose providers using attributes. For example, we could have three types of providers:

* storage providers. Same as before. Can be used for all grain types.
* streaming storage providers. Providers that use streams for storing updates. Can be used for `JournaledGrain<T>` and  `QueuedGrain<T>`
* replication providers. Providers that use replication in multiple clusters. Can be used for `JournaledGrain<T>` and  `QueuedGrain<T>`

It is possible we can merge the last two, that is, devise a common provider API for both replication providers and streaming storage providers. Since they have an internal API (not the one directly used by the user), it would be o.k. to make it a bit more complicated.

**Comment by jkonecki** [comment]
@sebastianburckhardt Sebastian, I can't wait till the meetup to hear more about `QueuedGrains` - I think they will massively help with better design of the storage story. I like your idea of separate top-level grain types - that would mean that we cannot derive `JournaledGrain<T>` from `Grain<T>` (since we don't want the base class methods like `ReadStateAsync`) and probably a new `GrainBase` abstraction is needed (btw, I hate xxxBase naming ;-) )

@sergeybykov - I must say I had a different mental picture ;-) - my understanding was that the storage provider should implement the whole logic of persisting the grain state and I was confused by the `IStorage` interface which IMHO should represent the abstraction of the physical storage and be used by storage providers.

I'm sure after the meetup I will have a better understanding of the different ways the grains can be persisted.

**Comment by sergeybykov** [comment]
The meetup should provide a perspective from yet another angle. There is also a parallel desire to make the abstraction for storage much more sophisticated than the simplistic version we have today. @jason-bragg has some thoughts there about partial reads/writes, etc.

My hunch is that we'll likely need more than persistence provider APIs for different scenarios. At the same time, I see a danger of providing too many options that would make it hard to choose the right one. I think we need to strike the right balance here between flexibility and simplicity.

I was hoping that `QuededGrain<T>` and `JournaledGrain<T>` could end up using the same persistence API. It's unclear to me yet if this hope is realistic.

**Comment by ReubenBond** [comment]
I'm hoping this will fit our scenarios, so I have a couple of questions.
Does this support (nested) transactions?
Is there any practical cap on the number of events on a grain? Some of my grains end up having a fairly large number of events on them.
Does this support snapshots? Just in case... people tend to want snapshots even if they usually don't add much benefit.

**Comment by yevhen** [comment]
@ReubenBond What do you mean by "(nested) transactions?" Usually, an Aggregate (Actor) which is backed by a single stream represents a consistency boundary, ie changes are atomic. Changes across aggregates are eventually consistent, ie no cross-stream transactions.

Regarding snapshots. I think that could be added easily by end users. I don't think there is a single-size-fits-all solution. There various trade-offs around implementing snapshot storage. But I think it could be abstracted behind an interface, like in NEventStore, so end users can plug (choose) different implementations based on the needs.

**Comment by ReubenBond** [comment]
@yevhen Maybe it doesn't apply to this design, because events are stored in an in-memory list which is committed atomically (or aborted and the actor is reset).

Snapshots should probably leverage the existing Grain state system rather than some new thing.

The other question is regarding how this would scale to a large number of events in a given actor.

**Comment by sergeybykov** [comment]
I'm closing this PR as @jkonecki suggested to merge this discussion with the geo-distributed replication work.

**Pull request closed without merging**
