### PR TITLE
Adding a default value to EndpointOptions.AdvertisedIPAddress

### LINKED ISSUE #7456: `EndpointOptions.AdvertisedIPAddress` should be set to something by default.
See the `ConfigureEndpoints` helper method for how this could be done (the overload which doesn't take a hostname).

https://github.com/dotnet/orleans/blob/d3e58ce277ccdd5c2d95abeb787c02a78ab41893/src/Orleans.Runtime/Hosting/EndpointOptionsExtensions.cs#L72

### PR DESCRIPTION
**Pull request by brunolins16**
Fixes #7456 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/orleans/pull/7457)

### CODE REVIEW

**Review by ReubenBond — APPROVED** [review]
We *should* add a non-async version of `ConfigUtilities.ResolveIPAddress` which calls `Dns.GetHostAddresses(addrOrHost)` instead of the async variant. The current pattern requires two threads, which can be slower and lead to issues (thread pool starvation), even though it's only called once, on startup.

If you'd like, do that in this PR and rename the method to `ResolveIPAddressBlocking`. Otherwise, I'm happy to merge as-is.

**Comment by brunolins16** [comment]
> We _should_ add a non-async version of `ConfigUtilities.ResolveIPAddress` which calls `Dns.GetHostAddresses(addrOrHost)` instead of the async variant. The current pattern requires two threads, which can be slower and lead to issues (thread pool starvation), even though it's only called once, on startup.
> 
> If you'd like, do that in this PR and rename the method to `ResolveIPAddressBlocking`. Otherwise, I'm happy to merge as-is.

@ReubenBond , I can do that.

**Comment by ReubenBond** [comment]
@brunolins16 rethinking this, I think we should change `ResolveIPAddress` to return null instead of throwing when no good candidate is found (and change its name to something like `ResolveIPAddressOrDefaultBlocking`) and catch any exceptions which are thrown regardless. We can default to `IPAddress.Loopback` if we're unable to resolve a valid IP.

Since we ought to be logging that exception, we should register a `IPostConfigureOptions<EndpointOptions>` to set the default value instead of doing it in the constructor.

Apologies for not catching that earlier.

**Comment by brunolins16** [comment]
> @brunolins16 rethinking this, I think we should change `ResolveIPAddress` to return null instead of throwing when no good candidate is found (and change its name to something like `ResolveIPAddressOrDefaultBlocking`) and catch any exceptions which are thrown regardless. We can default to `IPAddress.Loopback` if we're unable to resolve a valid IP.
> 
> Since we ought to be logging that exception, we should register a `IPostConfigureOptions<EndpointOptions>` to set the default value instead of doing it in the constructor, since we can inject an `ILogger<T>` into the implementation.
> 
> Apologies for not catching that earlier.

Since the ResolveIPAddress is only used by non-async operations in the repo I changed it without change the name and also added a new overload to call it without the `addOrHost` parameter. Let me know if make sense

**Review by ReubenBond — APPROVED** [review]

**Pull request merged**
