### PR TITLE
ReminderTableAssembly and MembershipTableAssembly in SystemStore Config

### PR DESCRIPTION
**Pull request by kucheruk**
Trying to write custom remindersTable and membershipTable storages 
related to #69

### CODE REVIEW

**Comment by gabikliot** [comment]
may I ask what kind of other custom system store you are planning to write?

**Comment by kucheruk** [comment]
i have been thinking about storing membership information and reminder entries in something different from Sql Server (can't use azure)
Something like mongo or postgresql.

**Comment by gabikliot** [comment]
You know that we already have Zookeeper fully integrated?
And also, just to restate the obvious, what ever other store you are planning to use, it needs to be highly available by itself. Otherwise if it only runs on one server and this server crashes you won't be able to join or declare dead failed silos and won't be able to create new reminders.

**Comment by kucheruk** [comment]
Zookeeper are very good option, but requires some effort to adapt it, unfortunately i can't just decide to use any software 
Maybe its will be easier to write two little plugins and to use already deployed big mongo replicasets in two datacenters

**Comment by veikkoeeva** [comment]
@kucheruk I can help with PostgreSQL.What you need is to translate [CreateOrleansTables_SqlServer](https://github.com/dotnet/orleans/blob/master/src/OrleansProviders/SQLServer/CreateOrleansTables_SqlServer.sql) to, say, CreateOrleansTables_PostgreSQL.sql and fix https://github.com/dotnet/orleans/issues/569. If you want to just debug, one quick way of doing that without fixing #569 is to just hardcode it everwhere you there's ``WellKnownRelationalInvariants.SqlServer`` used, like [here](https://github.com/dotnet/orleans/blob/bf1ca659ca16e09f0e327a9f52618926bf76392e/src/Orleans/Messaging/SqlMembershipTable.cs#L50).

There are more instructions related to testing at [Runtime Implementation Details: Relational Storage](https://dotnet.github.io/orleans/Runtime-Implementation-Details/Relational-Storage). I might add that I've had a plan to make relational testing so that it checks which databases are installed with default configurations, see which scripts are provided and test all the backends that way. That augmented with explicit configuration might be a good way to plug in any relational storage easily.

**Comment by kucheruk** [comment]
@veikkoeeva ok! i will try to look at #569 in a few days

**Comment by veikkoeeva** [comment]
@kucheruk All right, I'm glad to hear that! Do note that I think it requires input from the core Orleans team: @gabikliot, @sergeybykov and @jthelin. Mainly how the configuration should look.

I think the biggest piece of work is to translate the SQL script, but what is wortwhile to note is that in the SQL Server version half (or more, actually) is related to optimizations and tuning on different editions and so not strictly needed when making a port.

**Comment by jthelin** [comment]
One of the outstanding work items is to split out the SqlServer / DB dependencies from core runtime into separate [dynamically loaded] assembly, similar to the recent changes to split our Azure and ZooKeeper dependencies from core. 

This was something that was discussed when @veikkoeeva created his relational enhancements originally, but the splitting out the other dynamic dependencies from core wasn't in place at that time so was tabled and not included in that change.

As we start adding more additional and diverse extensions, i think we need to resuscitate that work item and work towards having that clean separation (which is partly what this PR is attempting to do).

I can see arguments both ways about whether it is better to end up with keeping `Orleans.SqlServer.dll` and `Orleans.MongoDb.dll` separate, or squish them together into a single `Orleans.Db.dll`.

Thoughts?

**Comment by veikkoeeva** [comment]
@jthelin The relational database specific code uses only vendor agnostic ADO.NET libraries and the only differentiator is the vendor specific ``.sql`` script. In that vein there should be ``Orleans.SqlServer.dll`` which is the same for all relational databases. No code changes required. Splitting the ADO.NET specific code, even if it is core .NET, to a different assembly would be warranted in my opinion. As a general note to people reading this, this vendor neutral ADO.NET code does load vendor specific database libraries, which is the point of #569.

If thinking split like this, then there should be a different ``Orleans.MongoDb.dll`` as it does not use, as far as I know, vendor agnostic ADO.NET libraries. I'm also not aware if MongoDb has common library with other document databases. If there are, then it would make sense to introduce ``Orleans.DocumentDb.dll``, which would just load the correct driver depending on the actual backend document db implementation.

**Comment by gabikliot** [comment]
@kucheruk , this looks good.
If you can make the fixes I asked above in the comments I will merge it.
Thanks you.

**Comment by gabikliot** [comment]
@kucheruk, you also need t do a similar fix to support Custom for [GatewayProvider](https://github.com/dotnet/orleans/blob/master/src/Orleans/Messaging/GatewayProviderFactory.cs).

**Comment by jthelin** [comment]
Reminder: @kucheruk also needs to sign CLA before we can merge this.

/cc: @gabikliot

**Comment by gabikliot** [comment]
The fixes look good.
Evgeniy, please sign the CLA and we will merge this.

**Pull request merged**
