### PR TITLE
Repro for #1484; Json deserialization of POCO with object generic argument

### PR DESCRIPTION
**Pull request by dVakulen**
Repro for the #1484; 
Also the [```GuidJsonTestConverter```](https://github.com/dotnet/orleans/blob/master/test/Tester/SerializationTests/SerializationTests.JsonTypes.cs#L74) is duplicate of the [```GuidJsonConverter```](https://github.com/dotnet/orleans/blob/master/src/Orleans/Serialization/OrleansJsonSerializer.cs#L239), and probably should be removed.

### CODE REVIEW

**Comment by sergeybykov** [comment]
I'm confused with what we are testing here. Newtonsoft.Json.JsonConvert? Does it work correctly if we don't call `settings.Converters.Add(new GuidJsonTestConverter())`, and adding `GuidJsonTestConverter` breaks it?

**Comment by gabikliot** [comment]
I think that is what @dVakulen  is trying to say, yes.

The real test will be not to use Test converter, but to use Orleans's Json serializer from the grain in a full setup with storage provider and that should break in the same way as in the test.

If that is indeed the case, I am actually not surprized. Based on what  @Allon-Guralnek explained in #1269 (which was after we added `GuidJsonConverter`) I think I understand the Json rationale better now. Basically, the fundamental point is that **it can not, BY DESIGN, work on ANY arbitrary POCO object that combines different primitives and dictionary** and what not. For example, Guid does not deserialize to Guid, BY DESIGN (comparability with Json standard Guid has to be serialized as string). Same for how Dictionaries are serialized BY DEFAULT. One can customize a lot, but whether it is possible to customize to be 100% compatible with .NET serializer is an open question, for which I "think" the answer is negative. I might be wrong. But that does not really matter. What matters, in my opinion, is what Orleans has to do about it. Here is what I think we have to do:

1) Orleans has to make sure all Orleans types that can ever get Json serialized have to be natively Json-serializable. What that means is they have to define inside themselves how they serialize. That can be done either via Json attributes on fields or by defining ISerializable interface. **What is important is that serialization is defined by the type itself and will work in the same way with ANY Json serializer settings**. That means we have to stop using JsonConverter added to Json settings. Instead, all have to be defined on the type itself.
2) **We should avoid wrapping application types that have to Json-serialize into any other type or put them into any dictionaries/lists**. They have to be passed to Json serializer as is and not as part of dictionary fields. That means that in storage provides we need to pass the state POCO as is to json, and not inside the dictionary.
3) **We have to provide a way for application to fully control and change/redefine Json serializer that is used**. We can provider our own default one, but the key point I am trying to make is that will never be enough, due to what I wrote above. So we have to provide a way to overwrite Orleans default Json serializer. We don't allow that now in Azure Storage provider.

I think, based on my current understanding of how Josn works, that as long as we don't do all the 3 above, we will keep running into issues with various edge cases on application types that don't deserialize correctly. By doing what I suggested above we will take ourselves out of the business of limiting and controlling Json serialization and will allow applications to be in full control of it.

**Comment by sergeybykov** [comment]
I'm maybe overreacting, but 1) & 2) makes me think that we should avoid JSON scenarios in the runtime like plague. I don't think we want to get into the business of generating JSON serializers at compile time.

3) is relatively easy if we add a way for storage providers to call back into the app for serialization.

**Comment by dVakulen** [comment]
Yes,  it work correctly if we don't call settings.Converters.Add(new GuidJsonTestConverter()) and its breaking with full setup with storage provider in the same way as in the test. I've wrote this test the way I did to point out the problem, after the fix it will be better to rewrite test to use full Orleans json serializer.
 As for 
>it can not, BY DESIGN, work on ANY arbitrary POCO object that combines different primitives and dictionaries/lists and what not. For example, Guid does not deserialize to Guid, BY DESIGN (comparability with Json standard Guid has to be serialized as string). Same for how Dictionaries are serialized BY DEFAULT

 that's not quite true - if Json.Net can infer the type from collection type (e.g. deserializing `Dictionary<string, Guid>` into `Dictionary<string, Guid>` and not `Dictionary<string, object>` into `Dictionary<string, object>`) - it works fine for Guid's and other types most of the times (excepting some edge cases) without custom serializers. The main reasons why Json.Net was selected as fallback serializer is his ability to serialize almost every type without requiring that type to implement `ISerilalizable` or defining custom serialization methods on it, and its prevalence (even https://github.com/aspnet/Mvc using it, not to mention which package on Nuget have the most downloads count).

**Comment by gabikliot** [comment]
We discussed that with @sergeybykov  offline and clarified it.
I think there was a general agreement on the plan I outlined above. There are multiple ways to provide number 3.

@dVakulen , I think you are only making my point stronger: it can work with `Dictionary<string, Guid>` but not with `Dictionary<string, object>`. Of course one can change it to the right `Dictionary`, IN THAT PARTICULAR case, but IN GENERAL, over all possible scenarios of all different Orleans customers, there will always be a case that won't work. The conclusion is: **"We have to provide a way for application to fully control and change/redefine Json serializer that is used."**

**Comment by sergeybykov** [comment]
@gabikliot explained to me the idiosyncratic ways JSON serialization works "by design".

Stepping a bit back, I see five areas where JSON serialization potentially applies.

A. Grain state objects.
B. Orleans public types that app code is expected to persist, such as `GrainReference` and its subclasses, implementations of `IAsyncStream<T>`, etc.
C. Arguments and return values of app grain interfaces' methods.
D. Various runtime types that get sent over the wire.
E. Various runtime types that get persisted, e.g. membership and reminders data.

A is a no-brainer - app code needs to be able to define how app state gets serialized, with JSON or not, including all possible JSON serialization settings.
B is also obvious - app code needs to serialize those handful of types in various scenarios.

The case for C is that we cannot guarantee that there will be an Orleans generated serializer for sending all app types over the wire. Today we fall back to .NET binary serializer, and not all types are binary serializable. Plus .NET binary serializer that is going away in CoreCLR. 

D & E don't seem to have any clear benefits from using JSON instead of Orleans binary serializers. Considering the pitfalls of how JSON deals with common data structures and no obvious way to test all runtime types for correct JSON serialization, I see no reason to use JSON here. Today we only optionally use it for pub-sub grain state to make the data human readable for debugging, but because it is implemented as grain state, it falls under A.

So maybe the plan should be to: 
I) explicitly separate in the runtime code C from D, and make sure only Orleans binary serializer is always used for D. If we want to use JSON for some special cases in E, that should done with a separate instance of JSON serializer where app code cannot change settings configured by the runtime code;
II) Fill any gaps in B and cover each of the types with unit tests that would catch any future regressions.
III) Expose publicly settings of the JSON serializer used for A & C that app will have full control of. Via DI?

What did I misunderstand this time?

**Comment by dVakulen** [comment]
@sergeybykov Makes sense. For now I've updated the PR to fix the issue with failing azure storage provider tests through reverting changes which were made for the https://github.com/dotnet/orleans/issues/1187. It will better to open a separate issue which will contain the points that you and @gabikliot stated in here.

**Comment by sergeybykov** [comment]
It seems to me that we can merge this, but I'll wait for @gabikliot to nod.

**Comment by gabikliot** [comment]
@sergeybykov , your latest description is accurate. 
The only point you did not mention is number 2 on my list: "We should avoid wrapping application types that have to Json-serialize into any other type or put them into any dictionaries/lists." We need to pass application types to Json serializer as is.

**Comment by sergeybykov** [comment]
Thank you, @dVakulen!

@gabikliot, you are right, I missed that point.

I'll open an issue with this description.

**Pull request merged**
