### PR TITLE
Add test case for combining IControllable + bootstrap provider

### PR DESCRIPTION
**Pull request by jthelin**
- Test silo discovery and cmd operation of bootstrap providers that implement IControllable.

- Tweak test categories from original import.

- Test bootstrap providers should be MarshalByRefObject for testability.

- ~~Migrate bootstrap provider tests from internal VSO depot.~~ -- this part was merged seperately in PR #1233

### CODE REVIEW

**Comment by jthelin** [comment]
@sergeybykov - FYI, there is some overlap between this PR and PR #1233

I will hold off on this change until PR #1233 is merged in, and then tweak this change set on top of that.

There is an additional test case BootstrapProvider_Controllable in here which is useful addition to the test suite to confirm the `IControllable` functionality works with bootstrap providers [which i needed to confirm works OK in Orleans core for other project reasons].

**Comment by sergeybykov** [comment]
@jthelin Ningna prepared two more branches with migrated tests before the end of the year. That should cover nearly all of them. I'm trying to get them in ASAP, so that we finish that work now that she got moved to a different project. So if you could hold off this one for a couple of days (hopefully), that would make migration easier.

**Comment by jthelin** [comment]
Still work in progress.

**Comment by sergeybykov** [comment]
@jthelin Are you still working on this one?

**Comment by jthelin** [comment]
Yes @sergeybykov - i am still trying to diagnose what is happening inside silo, although it is a P2 background activity ATM.
My bootstrap provider get's loaded when silo starts, but then doesn't seem to be known about later when test tries to send control message to it. Very strange. :(

**Comment by jthelin** [comment]
Very interesting. Looks like the problem with test failures for this PR was our old friend MsTest!
After rebasing to master HEAD 7c1e35466fde08fcf1c2caf64fa304d25e60e045 which contained the switch to xunit, this test case magically works without any code changes.
I think this PR is now OK to merge @sergeybykov .

**Pull request merged**
