### PR TITLE
Fix for Visual Studio Gallery readiness

### PR DESCRIPTION
**Pull request by pherbel**
- added a preview image to the VSTools project.
- changed the name and description
- added 'Orleans' category. Now the projects/items will appear under the Orleans category
- added other VS Targets

fixes for #78

### CODE REVIEW

**Comment by pherbel** [comment]
I think we should move the VS Tools source code to a separeted repository

**Comment by jthelin** [comment]
> I think we should move the VS Tools source code to a separeted repository

Yes, that would probably be cleaner.

I'll merge this change, then maybe @pherbel you would like to create a separate issue thread to talk about how to make the separation?

**Comment by pherbel** [comment]
@jthelin Thanks. I created one #620

**Comment by sergeybykov** [comment]
Published as https://visualstudiogallery.msdn.microsoft.com/36903961-63bd-4eec-9ca4-cf2319dc75f4.

Thank you, @pherbel!

**Pull request merged**
