### PR TITLE
allow for extraneous keys in OrleanQuery table (#11)

### PR DESCRIPTION
**Pull request by amccool**
#1726 - reverse the Except query to match the db values to the `DbStoredQueries` consts

### CODE REVIEW

**Comment by sergeybykov** [comment]
@shayhatsor @veikkoeeva What's your opinion?

**Comment by shayhatsor** [comment]
I agree that the error message is misleading, it should say exactly what's missing/extraneous.
But i don't agree we should allow extraneous keys in OrleanQuery table. If a user has more queries than is expected, he's probably running an incompatible Orleans and db script versions.

**Comment by amccool** [comment]
if we are going to tie the query keys to a specific version, why keep them in the database at all?  Are they only there to allow for someone to modify the query content?

**Comment by shayhatsor** [comment]
@amccool, yep that was the reason. The keys themselves change very rarely, the actual queries might change from time to time to improve performance, add fields, fix bugs etc. Usually, you don't need to start from a clean DB when you update Orleans, in this case we had to make breaking changes in order to optimize the tables and queries.

**Comment by veikkoeeva** [comment]
Firstly, I think me neither @shayhatsor (I think) expect these core queries change much anymore, but we need more tests. @amccool has been one of the keenest people to work on issues on the channel on elsewhere, so it'd be great if he has time to work on issues. I understood he plan's to introduce some tests on this.

I'm not sure if tying query keys to specific deployments makes sense. At least it has not been my intention. What I think could be useful is to add version information to the database. Possibly information with which binaries it is compatible and maybe a reason as to why not if there's a break. This could be checked and/or printed out when starting a silo. I had the the intention to print the SQL Server view information upon startup. The original issues is [here](https://github.com/dotnet/orleans/issues/255), by the way.

I would like to add some more concerns I have and why this arrangment. As I'm the one who designed this in the first place, I probably should share the rationale better here too, as it's currently spread around in various places. This takes a bit longer tour and is not all about why the queries are in the table and not in the code and it touches also on why not EF, NHibernate or some other "fat ORM", but it helps to understand the relation of the queries to the tables and to specific deployments.

Premises.

1. Orleans cannot know the physical deployment environment. This means no "best fit" queries are possible in general. But it is always possible to tune the queries, indexing strategy or others things per-deployment. This might mean using vendor specific strengths (the things one pay for). I believe it is general knowledge even slight chances can have a great impact on running parameters, "performance".
2. One may need to tune queries or indexing strategy or other things as data size changes during running. Or due to industry compliance issues. Maybe some data needs to be encrypted, or using some specific schema that needs to be protected in certain ways (compliance with specific industry standards), and not all databases have the concept of SQL Server "schema" as such.
3. Orleans deployment may not have the rights to alter tables and correspondingly queries. Maybe due to security concerns Orleans does not have the rights more than to operate on `INSERT`, `UPDATE`, `DELETE` and `SELECT`. Or maybe just `INSERT` and `SELECT`.
4. Human factors that one knows better some characteristics after running a while, but it's a no-go to break the SLA to merely "refactor".

All of the "problems" in the premises can be solved if there is one central places to update queries and tables even when running a deployment. Which one is easier:

1. Deploying custom built Orleans binaries?
2. Tweaking scripts and reloading them from the database with a silo restart where all is in plain sight? General opinion allowing, I would like to introduce a capability to reload queries even without a silo restart. Naturally I'm all for it if someone else does it.

Especially when the queries and tables are "close" so one can ascertain onself what will happen if the query contents are update in flight. Even maybe tables are updated in flight.

Lately I've become a great believer in what is described at [Using Stored Procedures to Provide an Application’s Business-Logic Layer](https://www.simple-talk.com/sql/t-sql-programming/using-stored-procedures-to-provide-an-application%E2%80%99s-business-logic-layer/). In short the reasons are:
1. It is possible to interrogate the DB the queries it receives and they have a clear name. A name that is not "some query" one needs to go searching in the code where it came from.
2. It is possible to fine-tune locking and querying strategies. These are very important (especially as MS charges more for SQL Server and customers give less cores and memory) and they depend on deployment and data size (it is especially easy to have "partial transactions" with ORMs).
3. It is easy to do `2.` in-flight, when the database is running.

Not all databases support stored procedures, TVPs or there are bugs/performance fluctuations (an ORM update can have a really bad effect on performance due to generated queries being different) version-by-version that need to be worked around. Orleans can't know these and one may not want to introduce "stagnation" or "version lifting projects".

These concerns I have come from some business SLAs. Unfortunately it looks like that if one isn't working one's own product but for a customer (a lot of MSs enterprise bread and butter) and if the SLA is tight and things are going progressively towards worse, it likely is not possible to take database offiline with corresponding application changes (say how EF is being used or if the entities should be updated). My experience comes from working on MES (manufacturing executing systems, factory software), payment processing in one of the biggest retailers in Nordics (and others as large I can't disclose) as well as in Finnish Post (and I haven't been the DB guru). Much of the problems can be fixed by "stabbing the DB", in a way or another provided the application does nee to be touched. Some of this is a contractual thing or a problem on how long it takes to take action when the DB is hosted on an outsourced data centre (maybe even HW characteristics changing on the fly). These are usually the kinds of systems that could benefit using something like Orleans (in fact, Finnish Post is using something akin to it (Akka, and various DB strategies)).

A public case in point I linked somewhere is VS Online [A bit more on the Feb 3 and 4 incidents](https://blogs.msdn.microsoft.com/bharry/2016/02/06/a-bit-more-on-the-feb-3-and-4-incidents/). There especially the part <blockquote>When a table is small, it almost doesn’t matter what the query plan is.  When it’s medium an OK query plan is fine.  When it’s huge (millions upon millions or billions of rows) a tiny, slight variation in query plan can kill you.  So, we hint our sensitive queries heavily.  We encourage the query optimizer to pick a plan that we know may not always perform the absolute best for every possible scenario but performs well and will never perform horribly for any scenario.

I’ve highlighted the query plan hints in green.  I’ve generally found this kind of hinting to be viable/maintainable and critical at scale.  I’ve also highlighted in yellow the short term fix we put in to cap the memory grant.  This change is not viable/maintainable in the long term but ended the incident while we work with the SQL team on a long term fix.</blockquote>

I've certainly found myself in that situation too many times. If I've been lucky, I've seen the name of the query (a view name or a stored procedure name, that is, without quessing where in effin does it originate from the codebase) and have been able to just tweak it a bit and modify in transaction and things have smoothed out just in time. Smaller companies can actually go bankcrupt on fines like 50 000 € a minute or a hour on more severe indicents. In this particular VS Online case, if it were running Orleans or having a stretegy similar to this, someone would have just tested the new query, update the table and restart a silo to see if it helped and thereafter the rest of the silos.

Currently Orleans concerns itself only that is has a certain key and it can use it to retrieve a query, which has a certain shape. Namely it takes input with certain parameter names and types and it returns certain values using some types. The rest can be changed. Currently the situation is so only a silo-restart can (re-)read the queries from the DB, but I see no reason this could not change in the future.

Some particular examples in case of Orleans could be the current [persistence provider](https://github.com/dotnet/orleans/pull/1682) I'm working on (slowly, I confess). It may need tweaking while running to be "optimal" if there's a lot of data. One case could simply be:

1. Introduce a `SWITCH-CASE` to `INSERT` and put some data to a purpose-built table for whatever reason (performance, security, SSD/HDD pricing).
2. Make corresponding changes to the `SELECT` clause.
3. Update the queries in transaction.
4. Restart silos one-by-one (currently).

This mighe become useful on ES too (one way to realize it is to use materialized/indexed views for output). Like if one happens to run [PipelineDb](https://www.pipelinedb.com/), it's not a problem. It should work provided the data shape and names is what's expected. Or maybe use [PolyBase](https://msdn.microsoft.com/en-us/library/mt652315.aspx) for storage provider/ES on some data? Go for it! If the query works, Orleans code will accept it (I'm not sure enither NHibernate nor EF would accept such references).

One particularly interesting case, which might have compliance importance would be to modify the membership protocols such that the current `UPDATE` clauses would be `INSERT` and `SELECT` would pick the latest. That could be an interesting way to examine issues combined with statistics too.

**Comment by shayhatsor** [comment]
@veikkoeeva, first of all, thanks for explaining (again) your thought process when you designed the relational storage maybe you should update [this](https://github.com/dotnet/orleans/issues/1264#issuecomment-181019760) I have yet to add it to the documentation.
about adding tests for testing silos with different membership providers, I looked into it and it's much easier than I thought. I just had to make some minor fixes they work. I'm going to make a PR about this soon.

**Comment by veikkoeeva** [comment]
@amccool Sorry for being slow. Your change looks correct: the intention is to check which keys are defined to be used in the code and match those to the extracted from the database. This is what the application needs to find. If it would be a good idea to include more logging (e.g. for the extraneous keys), it can be added in another change set.

@shayhatsor I can do that or update the docs too. I think I'll try to finish the persistence provider this month (tests and maybe sharding too) and either to update the issue or the docs.

**Comment by shayhatsor** [comment]
@veikkoeeva, I personally prefer to keep the queries check as strict as possible, I see no benefit in relaxing the check. About the documentation - no need to hurry, I was just pointing out the fact the you've generously explained the design rationale several times.

**Comment by sergeybykov** [comment]
@amccool Do you think we still need this PR? Looks like @shayhatsor and @veikkoeeva have a different approach in mind.

**Comment by amccool** [comment]
I would have preferred to be able to even have extra records in that table  (if even to test a different query execution).   However this is not my call.

**Comment by shayhatsor** [comment]
@sergeybykov, I'm OK with @amccool's change. It doesn't matter either way.

**Comment by veikkoeeva** [comment]
@sergeybykov, @amccool, @shayhatsor Would it make sense that the silo should always start if it finds the keys it needs? Then the missing and extraneous would be logged? This feels the most appropriate choice as it is the most robust against failure to run.

**Comment by shayhatsor** [comment]
@veikkoeeva, as I said, It's OK with me.

**Comment by sergeybykov** [comment]
@veikkoeeva I don't have a problem with that.

**Pull request closed without merging**
