### PR TITLE
Support EventHubsTransportType on EventHub streams

### PR DESCRIPTION
**Pull request by fuocor**
Allows configuration of EventHubsTransportType when using EventHub stream

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/orleans?pullRequest=6813) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/orleans?pullRequest=6813) before we can accept your contribution.<br/><br/>:x: fuocor [sign now](https://cla.dotnetfoundation.org/dotnet/orleans?pullRequest=6813)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/orleans?pullRequest=6813) it.</sub>

**Comment by fuocor** [comment]
The test failure is unrelated to the changes I implemented

**Comment by benjaminpetit** [comment]
Thanks, do you need it backported to 3.4.0?

**Comment by fuocor** [comment]
I have my CI building against source for now, so there is no rush to package it into a release

**Pull request merged**
