### PR TITLE
Add UnitTest nuget package

### PR DESCRIPTION
**Pull request by pherbel**
It could be useful if we are able to add unit test silo host with a nuget package.

### CODE REVIEW

**Comment by jthelin** [comment]
Looks good. Just a couple of minor comments:

- For consistency, I would suggest it best if the NuGet package name directly aligned with the assembly name. So in this case, if assembly name is ```OrleansUnitTestHost``` then package name should probably be ```Microsoft.Orleans.UnitTestHost``` [but also see below.]

- Before we incur the wrath of the Testing Police :wink: it might be best to drop "unit" from the name her and just call this assembly / project something like "OrleansTestingHost" -- and package would then be ```Microsoft.Orleans.TestingHost```. 
There have been lots of discussion in the Orleans issues list / forums chat room recently related to what we called "unit testing" really is "integration testing" and that [isolated] unit testing really should be done standalone rather than inside a test silo. Xref: #362

Overall though, creating this separate package for unit [sic] test infrastructure seems like a good move to me. :+1: 
 
Thanks for the contribution! :smile:

TODO: Convert Tester* projects to use this new assembly, to eliminate code duplication.

**Comment by gabikliot** [comment]
Sorry, I did not get it: we just copied all the files from Tester project? And now we have those files duplicated?

**Comment by veikkoeeva** [comment]
I think there's a merit to this, but as far as I see, further refactoring would make this more useful in developer silo hosting, hosting one's own unit tests and perhaps even refactoring the current unit tests. This is the approach I took with my spike to better understand Orlans (#252). There's [WindowsServerHost](https://github.com/dotnet/orleans/blob/master/src/OrleansHost/WindowsServerHost.cs), but it feels "rigid", or put other way, I don't have "my way" as easily.

That being written, I put a small gist of [a F# version](https://gist.github.com/veikkoeeva/4414609e828375c898f3) to communicate one possible direction to refactor. It's what I did in #252. It doesn't handle anything but in-memory configuration currently. Though only small changes are needed to do that and there are other "small wrinkles" on how the configuration would be more robust and less painless. To me, at least, having something like this packaged in the Orleans itself would be tempting. I've been thinking to expand this to handle all configurations plus add hosting in separate process (maybe MAF, I don't know yet) partly just to see how things would go. Though I'm occupied with the SQL Server stuff currently. :)

**Comment by pherbel** [comment]
@jthelin Good points. I agree with the OrleansTestingHost name. I thought it will be useful until the unit testing approach will be consolidated (perhaps even afterward) and it is also good opportunity to distribute some testing utilities in this library.

@gabikliot As a developer I would like to add this lib into my test project in a simple way. I have multiple testing projects and I copied these files into my repo by hand, but I realized that I need a separated lib with these files. So, the best way if we create this library in the original Orleans repo. I hope another Orleans developer will find it useful.

Later maybe we can create project template and project item template for the testing as well.

@jthelin  Should the Tester project change be in this pull request? I didn't want change it before the feedback about this package.

**Comment by gabikliot** [comment]
I meant of course that we now have the same files twice: once in the Tester project and once in the new project. It is the same comment as @jthelin gave "TODO: Convert Tester* projects to use this new assembly, to eliminate code duplication." We basically need to change the Tester to use this project instead.

**Comment by jthelin** [comment]
I think it will be best to merge the changes that @pherbel has so far, then  iterate with the outstanding work items.

There are a few additional places that "UnitTest" appears in file / class names which we need to fix, but that is more easily done at same time as some minor refactoring that would make this package easier to understand and use -- mainly splitting the major public classes out their own files.
Then there are a few additional things to add to this package, primarily the default testing silo / client config files and a NuGet install.ps1 script to include them properly by NuGet [similar to what is done in the Orleans.Client and Orleans.Server packages now]. It was quicker for me to just do these than try to explain what changes were needed ;) 

Then finally we need to update the existing Tester* projects to use the new TestingSiloHost base classes, to eliminate the code duplication as @gabikliot mentions.

I'll send around a separate PR containing these last 2 bits shortly, so you can take a look before we lock in the final structure.

**Comment by jthelin** [comment]
PR #408 contains the second part of this change.

**Comment by veikkoeeva** [comment]
This got merged already, but I have a question: is there be a difference between a unit test silo and just some silo that will be used in a testing scenario? If so, should there be?

I ask beceause if there shouldn't be, this approach feels a bit rigid machinery (perhaps I'm mistaken?) for what I'd like to be more like "launch an Orleans cluster as in some production configuration configuration, but now locally and drive various tests while I observe it" and it'd be nice if I could drive basically this "production like configuration" as my development configuration too, though perhaps Orleans isn't quite there yet. What I'm thinkin is something like "Owin" and the small gist I made is more to that direction. Yes, I know my gist won't cover all the scenarios there are in tests, not currently, perhaps never. :)

**Comment by pherbel** [comment]
Thanks @jthelin  It is becoming a very useful package with your #408 PR. Are you planning to make a new Orleans nuget package release? I hope it will be part of that.

**Comment by jthelin** [comment]
@veikkoeeva Good point. It should already be quite straight forward to run a "normal" in-process silo -- see the DevTestSIlo silo shim code in ```OrleansHostWrapper.cs``` in the HelloWorld sample.

This Testing package is slightly different because it simulates a "realistic" distributed deployment scenario of 2 silos and 1 client, but does that by running everything in same process so has to does some extra munging of configs to bootstrap all those things in same process. 

I can't really imagine any scenario when you would want to run 2 silos in same process except for testing. Running 2 silos locally in 2 different processes would be better than that

Let's continue this discussion on PR #408 thread because that is the follow-on to this particular change to get things into final proposed. I just needed to merge this change to allow PR #408 to show the proposed integrated picture, which should allow more context and informed discussion on what end-goal is and how to get there.

I am very interested in understanding the test scenario you have in mind.

**Pull request merged**
