### PR TITLE
Make build warning free

### PR DESCRIPTION
**Pull request by attilah**
- Fix XML warnings in release builds
- Remove unused parts of SiloAssemblyLoader (LoadApplicationAssemblies). The "strict" parameter was never used with other then true value so it was removed
- Remove extra App.config
- Use newer (fixed) System.Reflection.Type.Extensions version
- Bump System.Net.Http version to latest (fixed) version

### CODE REVIEW

**Comment by ReubenBond** [comment]
@dotnet-bot test netfx-bvt
@dotnet-bot test netstandard-win-bvt

**Comment by ReubenBond** [comment]
@dotnet-bot test netfx-functional

**Comment by ReubenBond** [comment]
netfx builds are failing

**Comment by attilah** [comment]
@ReubenBond yes, it failed because that LoadApplicationAssemblies call was needed in netfx, now it is not removed, just the unused var at the end and its usage.

**Comment by attilah** [comment]
@dotnet-bot test netfx-bvt
@dotnet-bot test netstandard-win-functional

**Pull request merged**
