### PR TITLE
Updated VSTooling VSIX and project template references to 1.0.9. Fixes #498

### LINKED ISSUE #498: VS Tooling version and project templates still contains 1.0.7 references
The VSIX manifest and several other project tempalte files and packages.config.txt contains 1.0.7 references instead of current 1.0.9 version.

### PR DESCRIPTION
**Pull request by attilah**

### CODE REVIEW

**Comment by sergeybykov** [comment]
@attilah You also downgraded references to Azure Storage from 4.3 to 4.2 and to its dependencies. This shouldn't be necessary, so long as binding redirects are present in app.configs.

**Comment by attilah** [comment]
The cause of the downgrade is to have the SAME version everywhere ;-)

Besides these verison changes I think that Azure Configuration Manager should be update to 2.0.3 since that contain fixes I think and that is the last version in the 2.x range.
Newtonsoft.Json should be update to 6.0.8 since 5.0.6 is quite old ;-( but I did not made these updates yet.

**Comment by sergeybykov** [comment]
Wait, I think we want samples to reference 1.0.8, which is the last published official build. That what people that get the NuGets and the SDK msi will need. At the same time, we do want the VSIX to target 1.0.9. Looks like these are two unrelated changes really, and it would be better to handle them as such, I think.

**Comment by attilah** [comment]
Before the release of the 1.0.9 you'll update these to reference 1.0.9 then, right? I think samples must be point to the latest versions in the master branch.

One more idea: What about doing a daily nightly build as prerelease nuget onto myget like the asp.net webapi team does? and if someone trying out the samples he can get the latest bits?

**Comment by sergeybykov** [comment]
@attilah Yes, we should update them to 1.0.9 when we publish 1.0.9. I think samples need to point to the latest published version of NuGets because we have many people using them without building Orleans. If we reference 1.0.9 today, the samples won't compile with building a local set 1.0.9 NuGets and upgrading to them, which I'm sure would derail many people trying to explore Orleans. On the other hand, people that are comfortable building Orleans from sources I expect will have no problem upgrading NuGets in the sample to the version they build locally.

If somebody knows a way to get the VSIX build without installing VS SDK, this wouldn't be much simpler. I tried a while back and couldn't get it to build.

I like the idea of publishing pre-release NuGets in principle. They would have to have an auto-incremented minor version (1.0.9.xxxx), right? However, we currently do not have a process/script for auto-publishing NuGets, and we are not supposed (by security policy) to store NuGet.org credentials anywhere. I'm not sure how WebAPI folks do that.

**Comment by attilah** [comment]
@sergeybykov regarding the myget publishing I think the CI server needs to access the credentials somehow, Eric Lipton (MSFT) is the owner of the asp.net webapi nightly packages: https://www.myget.org/gallery/aspnetwebstacknightly
I think it is easy for you to contact him :-)

**Comment by sergeybykov** [comment]
Thanks! I'll check with Eric. It always helps to know the name. :-)

**Pull request merged**
