### PR TITLE
Consul clustering enhancements

### PR DESCRIPTION
**Pull request by satishviswanathan**
Following changes have been included in this PR.

1. Consul ACL integration.
2. Creating the cluster folder under a specific folder at the root of KV store.

Consul ACL integration
************************
The current orleans clustering consul package is not having an import feature i.e ACL integration, which is a security features of Consul that restricts unauthorized access on the cluster KV folder. 

Sample code

 var client = new ClientBuilder().Configure<ClusterOptions>(options =>
            {
                options.ClusterId = ConfigurationManager.AppSettings["ClusterId"];
                options.ServiceId = ConfigurationManager.AppSettings["ServiceId"];
            })
                .UseConsulClustering(gatewayOptions =>
                {
                    gatewayOptions.Address =
                        new Uri(ConfigurationManager.AppSettings["ServiceDiscoverEndPoint"]);
                    gatewayOptions.AclClientToken = ConfigurationManager.AppSettings["ServiceDiscoveryToken"];
                    gatewayOptions.KvRootFolder = ConfigurationManager.AppSettings["KvFolderName"];

                })
                .ConfigureApplicationParts(parts =>
                    parts.AddApplicationPart(typeof(ICustomerRule).Assembly).WithReferences())
                .Build();

            await client.Connect();
            return client;

Creating the cluster folder under a specific folder at the root of KV store.
****************************************************************************

When we have multiple projects using the orleans framework then all the cluster folder gets created at the root level of the KV store, to organize it in a better way I've added an ability to configure the folder name where the cluster folder should be created.

.UseConsulClustering(gatewayOptions =>
                {
                    gatewayOptions.Address =
                        new Uri(ConfigurationManager.AppSettings["ServiceDiscoverEndPoint"]);
                    gatewayOptions.AclClientToken = ConfigurationManager.AppSettings["ServiceDiscoveryToken"];
                    gatewayOptions.KvRootFolder = ConfigurationManager.AppSettings["KvFolderName"];

                })

### CODE REVIEW

**Comment by sergeybykov** [comment]
@dotnet-bot test functional

**Comment by sergeybykov** [comment]
@dotnet-bot test functional

**Comment by sergeybykov** [comment]
Thank you, @satishviswanathan!

**Comment by satishviswanathan** [comment]
@sergeybykov Thank you for accepting the PR.

**Pull request merged**
