### PR TITLE
Coreclr compatibility: Type -> TypeInfo 

### PR DESCRIPTION
**Pull request by pherbel**
It would be a starting point for the Contribution idea: Port Orleans to coreclr #368.

It contains:
* API changes for Type - > TypeInfo
* API SHA256 Hashing
* New vNext files
 * solution file (Microsoft.Orleans.vNext.sln)
 * project file (Microsoft.Orleans.Core.xproj + proejct.json)
 * global.json
 * some gitignore changes for vNext files

### CODE REVIEW

**Comment by pherbel** [comment]
Microsoft.Orleans.Core.xproj is in the Orleans directory and it contains the same files what Orleans.csproj contains.
It is very useful to check the API changes with this new vNext project and later if it is ready we are able to drop the old proejct file.
Current status of the Core project:
dnx451: build without error
dnxcore50: has 700 build error (first time it was 3K :smile:)

I'm also planning to create new proejct for hosting.

**Comment by gabikliot** [comment]
Great! Thank you @pherbel ! We will check this out.

**Comment by grahamehorner** [comment]
@pherbel minor observation with regards your PR - in a number of places you have multiple calls to type.GetTypeInfo() which has a performance impact; if you call this once and store the result in a local var performance wont be impacted as much; it also makes it easier to read the code ;) otherwise :+1:

**Comment by gabikliot** [comment]
That's what I was afraid exactly and referred to at https://github.com/dotnet/orleans/issues/368#issuecomment-122089961 about perf. of reflection.
Most of the places are in code gen code and I am less worried about those. But the code that runs in the silo hot path, on the messaging path, is very important to keep optimized and not make redundant reflection calls. For example, it may sometimes be better to call one of the IsXXX once when `ActivationData` is created and cache it inside  `ActivationData` and re-use later on, instead of calling type.GetTypeInfo().IsXXX. Again, not in the code gen code, but in the silo code.

**Comment by grahamehorner** [comment]
@gabikliot @pherbel we could use an extension method which looks at a singleton dictionary<type,typeinfo> if the type is found in the dictionary return the typeinfo otherwise call the type.GetTypeInfo() and add it to the dictionary ready for next time ;)

**Comment by gabikliot** [comment]
Do we know if there is really a perf. price for  `type.GetTypeInfo()`? It may be returning something that is already cached inside the type object so has a zero cost, or it maybe very costly. If its a zero cost, adding a global singleton dictionary (will need to be `ConcurrentDictionary) will actually have a negative impact.
I found out in the past that perf of reflection APIs is very un-intuitive to reason about. Some seem innocent but are actually heavy, other are very light.
That is what I wanted to test before accepting this PR, but haven't got time for.

**Comment by grahamehorner** [comment]
A simple test looks like the GetTypeInfo() is not cached and hits the cpu 
image

**Comment by gabikliot** [comment]
Can you please compare some calls on Type vs. on TypeInfo: 
`type.IsAbstract` vs. `type.GetTypeInfo().IsAbstract`?

**Comment by pherbel** [comment]
I thought that we need to deal with the performance issues. I just wanted to get some feedback first.
@gabikliot Could you please help to identify which are the classes or methods under the hot path?

**Comment by gabikliot** [comment]
Sure, provided those here: https://github.com/dotnet/orleans/pull/617#issuecomment-122354233

**Comment by gabikliot** [comment]
Should we close that issue now, that #618 and #619 were merged and we have #617 for `TypeInfo`?

**Comment by pherbel** [comment]
We have separated PRs.

**Pull request closed without merging**
