### PR TITLE
Added testing reference from 1.5 for 2.0.

### LINKED ISSUE #5083: 1.5 -> 2.0 testing documentation
Looking at the [1.5 testing docs](https://dotnet.github.io/orleans/1.5/Tutorials/Unit-Testing-Grains.html), there is guidance on how to mock the cluster and grains, but that documentation isn't carried forward into 2.0. There is also a constructor signature change, as well:

```c#
// old
TestCluster();

// new
TestCluster(TestClusterOptions options, IReadOnlyList<IConfigurationSource> configurationSources)
```

The docs don't explain what the change is nor does the code give too many hints on proper usage.

### PR DESCRIPTION
**Pull request by mxplusb**
Also added reference around dependency injection after a conversation
with @ReubonBond.

Fixes #5083.

Signed-off-by: Mike Lloyd <mike@reboot3times.org>

### CODE REVIEW

**Comment by sergeybykov** [comment]
I'll merge this even though there is no link to the page yet. @JillHeaden will find a way to integrate it into the tutorial she is working on. Tee page might need to move to a different folder.

Thank you, @mxplusb!

**Comment by mxplusb** [comment]
Thanks @sergeybykov! I wasn't sure where to put it, so I just put it somewhere that seemed similar to the 1.5 docs - I'm not particular on where it lives so much as it's somewhere easy to find. 👍

**Comment by mxplusb** [comment]
@sergeybykov & @JillHeaden, just wanted to see if there was an update to this. I was looking through the docs today and I didn't see anything.

**Comment by sergeybykov** [comment]
Sorry, it fell through the cracks. I just moved the page to tutorials and added it to the menu - http://dotnet.github.io/orleans/Documentation/tutorials_and_samples/index.html.

Thanks again for your help!

**Comment by mxplusb** [comment]
All good, thanks!

**Pull request merged**
