### PR TITLE
Minor compaction of message header data.

### PR DESCRIPTION
**Pull request by jason-bragg**
Translated message header strings into byte enums.
Should reduce size and header access speed.

### CODE REVIEW

**Comment by veikkoeeva** [comment]
This brings a bit of a itchy feeling of a need of a ``CustomComparer`` too to avoid using the default comparer, which might generate garbage and reserve heap space unexpectedly due to boxing. I'm at work and somewhat unavailable for the next 30 hours so and I apologize just dumping some links with quick searches:
http://beardseye.blogspot.fi/2007/08/nuts-enum-conundrum.html
http://stackoverflow.com/questions/7143948/efficiency-of-using-iequalitycomparer-in-dictionary-vs-hashcode-and-equals
http://stackoverflow.com/questions/3256713/enum-and-performance
http://www.codeproject.com/Articles/33528/Accelerating-Enum-Based-Dictionaries-with-Generic

**Comment by veikkoeeva** [comment]
That being written, I think enums are a great option here.

**Comment by jason-bragg** [comment]
The articles linked seem fairly old, leaving me wondering if this was still the case, after all the language is always being improved.  This article is fairly recent and seems to suggest that this has been addressed in .net.  
http://stackoverflow.com/questions/26280788/dictionary-enum-key-performance

I've not found much else on this, so my suspicion is that it has not been addressed in the framework.  I'll tinker with this tomorrow.  Thanks for pointing this out.  This change was intended as an optimization so perf really matters here.

**Comment by gabikliot** [comment]
Thank you @veikkoeeva ! Great stuff.
After reading the articles, it seems like we should either keep using enum and define `CustomComparer` for this enum, or maybe simpler is to define our new value type: 
struct HeaderType : IEquatable<HeaderType >
{
   int value;
}
and not use enums at all.
As this article states http://stackoverflow.com/questions/7143948/efficiency-of-using-iequalitycomparer-in-dictionary-vs-hashcode-and-equals, if your value type is IEquatable, no boxing will occur. The 2nd is easier since were don't need to make sure we are passing the `CustomComparer` to all dictionaries that we create with this enum key.

**Comment by veikkoeeva** [comment]
@gabikliot That may be even better suited than an enum. If it had a public constructor taking a byte and a readonly property ``Value``, defined like that it'd be almost what [F# union](http://fsharpforfunandprofit.com/posts/enum-types/) would be. I think F# union would define also [IStructuralEquatable](https://msdn.microsoft.com/en-us/library/system.collections.istructuralequatable%28v=vs.110%29.aspx) and a parameterless constructor. To think of it now, perhaps we should too. Some reading on why IStructuralEquatable [here](https://stackoverflow.com/questions/3609823/what-problem-does-istructuralequatable-and-istructuralcomparable-solve).

**Comment by gabikliot** [comment]
We use structural equivalence almost everywhere in Orleans. We don't use much of structs, almost never. Only in some very are cases. Most of the time we define our own classes and make them implement `IEquatable` and of course as part of implementing `Equals()` we also **always** implement `GetHashCode`. Look at all our types, `GrainId`, `QueueId`, `StreamId`, ...
I did not know there is an interfaace that has both `Equals()` and `GetHashCode` (`IStructuralEquatable`), but as a I said, de facto, we always implemented it.

**Comment by jason-bragg** [comment]
After investigation, there is an issue.  enum Header : byte is boxed, as was the concern.  However the simplest fix is to remove the 'byte' constraint.  enum header : int or simply enum Header does not perform boxing as the dictionary container has been optimized to avoid enum boxing on the default integer enums.

From Dictionary.CreateComparer()
            // If T is an int-based Enum, return an EnumEqualityComparer<T>
            // See the METHOD__JIT_HELPERS__UNSAFE_ENUM_CAST and METHOD__JIT_HELPERS__UNSAFE_ENUM_CAST_LONG cases in getILIntrinsicImplementation
            if (t.IsEnum && Enum.GetUnderlyingType(t) == typeof(int))
            {
                return (EqualityComparer<T>)RuntimeTypeHandle.CreateInstanceForAnotherGenericParameter((RuntimeType)typeof(EnumEqualityComparer<int>), t);
            }

Perf testing has confirmed this.

**Comment by veikkoeeva** [comment]
@jason-bragg You are right. There doesn't seem to be a space concern present. Ints might be better for registers too in this scenario (if we are really concerned :)).

**Pull request merged**
