### PR TITLE
this page was made redundant by #1969

### PR DESCRIPTION
**Pull request by shayhatsor**

### CODE REVIEW

**Comment by gabikliot** [comment]
@ReubenBond , you need to resolve the conflict with this page.

**Comment by ReubenBond** [comment]
@gabikliot as far as I am aware, it's up to the submitter to keep the branch mergeable - isn't that how we've usually done things? I can't push to the PR's branch, which belongs to @shayhatsor.

**Comment by gabikliot** [comment]
Sorry, of course, I thought it was your pr.

**Comment by shayhatsor** [comment]
yep, i'll fix it. this PR is just about removing this file altogether. since nothing links to it anymore.

**Pull request closed without merging**
