### PR TITLE
Move away from dating terminology

### PR DESCRIPTION
**Pull request by sergeybykov**
Renamed "hookup" to "hook".

Even though the project is for mature audience, I think this is more appropriate naming.

### CODE REVIEW

**Comment by gabikliot** [comment]
I see you started cleaning the code towards spelling/style/compliance review before Orleans turns into `System.Distributed.Actors`?

**Comment by sergeybykov** [comment]
Yes, I was concerned about it turning into `System.Distributed.HookupActors`.

**Comment by jdom** [comment]
yeah, like that would never happen in RL :smile:

**Comment by ReubenBond** [comment]
I hope we don't start going around the codebase trying to find places where something could be misconstrued, it would be a waste of valuable time.

**Comment by sergeybykov** [comment]
"TestHookup" has annoyed me for quite some time. This change should only raise my productivity due to elimination of the annoyance. :-)

**Comment by ReubenBond** [comment]
:smile: ok, no problem

**Pull request merged**
