### PR TITLE
Azure storage update clean

### PR DESCRIPTION
**Pull request by jkamstra**

### CODE REVIEW

**Comment by gabikliot** [comment]
@jkamstra The branch gabikliot:AzureStorageUpdate-CLEAN  is a Candidate, it is still not ready to be merged back into master. We are still testing it. Once we feel confident enough, of course we will submit a pull request and merge it back into master.
Closing this pull request for now.

**Comment by jkamstra** [comment]
Thanks. Stubbed my mouse toe. Apologies.

**Comment by jkamstra** [comment]
This  looks good. Thanks! 

Minor nit - the AzureWebSamples silos project is still referencing storage 1.7 assembly, which replacement will cause a few issues in the WorkerRole:SetupEnvironmentChangeHandlers() -- or maybe there is a separate work item for cleanup of samples.

**Comment by gabikliot** [comment]
Yes, moving the samples will be done in a separate step. The AzureWebSample actually does work now with Orleans core updated to Azure storage 4.2. The AzureWebSample uses StorageClient.dll and silo uses Storage.dll and they can coexist side by side. Both are using the same version of Configuration.dll.

**Comment by jkamstra** [comment]
Thanks @gabikliot, I did finally get it to work, but it makes it hard for those that are new to the project and trying to learn by mimicking the samples in domain specific test apps. Just my .02c.

**Comment by gabikliot** [comment]
Do you mean the fact that samples are using the older Azure storage library? Definitely our plan is to upgrade the samples very soon after we upgrade the core Orleans.

**Comment by jkamstra** [comment]
Yes. If you take the common path of using the AzureWebSample as an example, create a new solution using all the goodness of the VS tools included in the 1.0 SDK release, you will encounter what I found - deprecations in CloudStorageAccount if the silo is referencing storage.dll vs storageclient.dll - which leads to more searching, followed by readme updates (which noone reads) and internal team wiki entries, etc. I'll stop whining now - got some investigation to do :)

**Comment by gabikliot** [comment]
The samples issue depending on older version of Azure storage and service runtime has been fixed now in: https://github.com/dotnet/orleans/pull/249.

**Pull request closed without merging**
