### PR TITLE
Fix detection of SQL Server 2008 version

### PR DESCRIPTION
**Pull request by joeecz**
According to this article https://support.microsoft.com/en-us/kb/321185 the SQL Server 2008 version number is formatted as follows '10.0.6000.29'. Cutting 5 characters from left and 2 from right would result in '0.' string which is not convertible to number – the following error is then reported: "Conversion failed when converting the nvarchar value '0.' to data type int."

### CODE REVIEW

**Comment by veikkoeeva** [comment]
@joeecz Do you care to attempt a fix? :) Arguably this is not used by Orleans as of yet to nothing more than as a trouble-shooting help on the forums.

Some future plan would be versioning the schema (and perhaps tables) and query the information out of that view along with other information.

**Comment by veikkoeeva** [comment]
Ooh, I see, you fixed already! Good job. :+1: I can't run it currently, but I suppose you have tried and it worked!

**Comment by joeecz** [comment]
Yes, I have tried that. I have the SQL Server 2008 version and the script was failing.

**Comment by joeecz** [comment]
@veikkoeeva Sorry if it was not clear. I made the fix and this conversation chain was created as a part of Pull request. It is possible that I did something wrong. I am new on the github.

**Comment by veikkoeeva** [comment]
@joeecz You did the right thing. I just had some dirt in my eye and didn't catch your commit before writing. :)

**Comment by joeecz** [comment]
@veikkoeeva I see, ok. Thanks. There is also another way how to fix that implementation: to read just the first letter and convert it to number to check if it is 0 or 5. Not sure which one would be preferred. This one works and keeps reading of both characters :)

**Pull request merged**
