### PR TITLE
Adjust documentation to include information about new Microsoft.Orleans.CodeGenerator.MSBuild code generation package

### PR DESCRIPTION
**Pull request by RamanBut-Husaim**
The documentation has been updated to include description for the new code generation package `Microsoft.Orleans.CodeGenerator.MSBuild`. Information has been taken from:

+ https://github.com/dotnet/orleans/issues/5245 - PR was created to address the gap mentioned in the issue;
+ https://blogs.msdn.microsoft.com/orleans/2018/10/01/announcing-orleans-2-1/

Additional changes:

+ clean-up trailing spaces in the changed docs;
+ adjust docs with suggestions from markdown lint - surrounding lines, header levels, language indicator in code sections.

### CODE REVIEW

**Comment by RamanBut-Husaim** [comment]
@ReubenBond Hello. Please take a look.

**Comment by RamanBut-Husaim** [comment]
@ReubenBond Hello. Maybe you had a change to take a look at this? Thanks.

**Comment by ReubenBond** [comment]
Fantastic, thank you for updating those! Apologies for the slow response

**Comment by RamanBut-Husaim** [comment]
@ReubenBond Awesome. I understood that you guys have a lot of work with the community so everything is ok.

Thanks a lot!

**Pull request merged**
