### PR TITLE
[7.x] Avoid resending unchanged ClusterManifest to clients

### PR DESCRIPTION
**Pull request by ReubenBond**
Backport of #8728
cc @453873 @HermesNew if you want a 7.x version of the PR to try, try this one

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/orleans/pull/8772)

### CODE REVIEW

**Comment by HermesNew** [comment]
Ok, we will release a local version to test the issue has been fixed.

**Comment by ReubenBond** [comment]
Great, thank you @HermesNew

**Comment by HermesNew** [comment]
@ReubenBond I have push a pr to branch 7.x .
pr#8778

**Comment by HermesNew** [comment]
After testing, the issue with # 8722 has been fixed.

**Comment by ReubenBond** [comment]
@HermesNew I cherry-picked your commit onto this PR since it has not been merged yet. I'll close #8778.

**Comment by HermesNew** [comment]
Ok, that's right.Hope to release the version as soon as possible.

**Comment by ReubenBond** [comment]
We should be able to release a new version next week

**Comment by HermesNew** [comment]
@ReubenBond I have push a pr #8782 
GetClusterManifestUpdate() may be return null and needs to be processed.

**Comment by ReubenBond** [comment]
Thank you @HermesNew - I should not have removed that part. I've incorporated your change into this PR and have added some feedback on top

**Pull request merged**
