### PR TITLE
Adds assembly version printing to logs

### PR DESCRIPTION
**Pull request by veikkoeeva**
It might be useful to print the version of Orleans
libraries to output logs in order to make troubleshooting
on public forums easier.

### CODE REVIEW

**Comment by veikkoeeva** [comment]
This is not ready yet and doesn't do anything, but I put it here on public for feedback if this would be a suitable addition. If so: 

1. What could be a a good place to print assembly information?
2. What should be printed?
3. Any other pointers things to note about? CoreCLR compatibility (I haven't checked).

Usage is something like
```C#
var assemblyInfoCollector = new AssemblyInfoCollection(typeof(StationTimerService));
return new Xyz 
{
    ServiceMainAssemblyDescription = assemblyInfoCollector.Description,
    ServiceMainAssemblyFileName = assemblyInfoCollector.FileName.ToUpperInvariant(),
    ServiceMainAssemblyFileVersion = assemblyInfoCollector.FileVersion,
    ServiceMainAssemblyVersion = assemblyInfoCollector.AssemblyVersion.ToString().ToUpperInvariant(),
    AssemblyFileLastModified = assemblyInfoCollector.AssemblyFileLastModified.ToUniversalTime().ToString(CultureInfo.InvariantCulture)
};
 
```

**Comment by gabikliot** [comment]
@veikkoeeva 
1) https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/Silo/Silo.cs#L194
2) The more the better. Print it in a separate log statement: Assembly Details.
3) Need to check CoreCLR compatibility  with the tool or with [Coreclr api search](https://packagesearch.azurewebsites.net/)

**Comment by veikkoeeva** [comment]
@gabikliot Thanks. The code works when using non-CoreCLR .NET. I'll try to see quickly how would this get turned into CoreCLR version so as to document it already. I see there's something like ``Microsoft.Framework.Runtime.LibraryManager``, for instance, which might be useful.

**Comment by veikkoeeva** [comment]
I got carried away too fast, Orleans already in fact does print version information using [RuntimeVersion](https://github.com/dotnet/orleans/blob/master/src/Orleans/Runtime/RuntimeVersion.cs). I believe this PR wouldn't be more than a bit of refactoring, which doesn't seem like warranted. I'll proceed to close this PR.

**Pull request closed without merging**
