### PR TITLE
Modify JenkinsHash to be stateless.

### PR DESCRIPTION
**Pull request by attilah**
Modify JenkinsHash to be stateless.

### CODE REVIEW

**Comment by jdom** [comment]
LGTM

**Comment by gabikliot** [comment]
Why? There was a reason it was done this way.

**Comment by jdom** [comment]
Could you explain more? The reason is not apparent. We started seeing bugs due to multi-threaded usages of this, which of course could be fixed to use thread local (or local) instances instead, but the reality is that there is no apparent reason not to make this class thread safe and stateless, and be less error prone in the usage.

**Comment by gabikliot** [comment]
I will look at this and try to recall.

As a side general note, if you do seek my feedback, please try to provide a bit more details in the PR. The level of details u provided now is good enough, but without it I have no way to know if you found some kind of bug in this code, or it is just a code cleanup, or something else.

**Comment by jdom** [comment]
Agree on that more context should be added by default. I was aware of this context due to an in-person standup meeting, but sometimes I miss context too and have to explicitly request it.

**Comment by gabikliot** [comment]
Looks good, and simpler and even more efficient this way.  I can't see a good reason why we didn't do it this way in the first place.

**Comment by sergeybykov** [comment]
Thanks, @gabikliot, for confirming it.

**Pull request merged**
