### PR TITLE
Serialization test for JObject

### PR DESCRIPTION
**Pull request by gabikliot**
Addresses https://github.com/dotnet/orleans/issues/299.

### CODE REVIEW

**Comment by ReubenBond** [comment]
Fantastic, thank you!

So the gist of the change is that you exposed the FindSerializationInfo method so that we can register our serializers during bootstrap. Looks good.

**Comment by gabikliot** [comment]
There was no change @ReubenBond. I did **NOT** expose FindSerializationInfo method, it is still internal method. There was no code change required in Orleans, it worked correctly all the time. I just added a unit test that proves it works.

**Comment by ReubenBond** [comment]
Ha, even better 😊  my bad for not noticing

**Comment by gabikliot** [comment]
No worries.

**Pull request merged**
