### PR TITLE
Clarified that not only SQL Server but other vendors too

### PR DESCRIPTION
**Pull request by veikkoeeva**
There were some spots which had only SQL Server mentioned or
weren't clear that other than SQL Server is supported too. A
few other inconsistencies fixed too.

### CODE REVIEW

**Comment by veikkoeeva** [comment]
This is ready now. At least I didn't find any other spots where I could clarify about the relational data.

I noticed one could add a mention about ZooKeeper to ``Cluster-Management.md``, but I don't have a good idea how to do it.

**Comment by gabikliot** [comment]
I will rewrite the `Cluster-Management.md` to talk about membership table abstractly and then a section about different impls: Azure, Relational, ZK.

**Comment by veikkoeeva** [comment]
A good point. With that in mind, should I just close this?

**Comment by gabikliot** [comment]
No, don't worry. I merged it and will re-write accordingly.

**Comment by shayhatsor** [comment]
@gabikliot & @veikkoeeva - I am available to add the zookeeper documentation to <code>Cluster-Management.md</code>

**Comment by gabikliot** [comment]
@shayhatsor , @veikkoeeva , I have updated the http://dotnet.github.io/orleans/Runtime-Implementation-Details/Cluster-Management with new restructured section about Membership Table. It would be great if you guys could revisit it and submit updates for SQL and ZK based implementation.

**Pull request merged**
