### PR TITLE
Build only one configuration in Build.cmd

### PR DESCRIPTION
**Pull request by jdom**
Build only 1 configuration instead of both Debug and Release in Build.cmd
Default local development environment to Debug, but CI environment to Release.

### CODE REVIEW

**Comment by jdom** [comment]
@dotnet-bot test ci please

**Comment by benjaminpetit** [comment]
It seems that in CI it build Debug instead of Release, and xunit is only expecting dlls in the Release subfolder of the projects.

It could be nice too to be able to launch the test on debug?

**Comment by jdom** [comment]
@dotnet-bot test this please
Reason: Yes, the groovy file change did not kick in yet, that's why I tested CI first, and now we should be able to run the modified CI with the change that sets BuildConfiguration to Release

**Comment by jdom** [comment]
@dotnet-bot test GenPRTest/bvt_prtest

**Comment by jdom** [comment]
@benjaminpetit yup, I missed that, thanks, we should be able to run tests in the specified (or default) build configuration.

Also, this is a run with the updated groovy file that runs in release mode:
BVT: https://ci.dot.net/job/dotnet_orleans/job/master/job/GenPRTest/job/bvt_prtest/2/
Functional: https://ci.dot.net/job/dotnet_orleans/job/master/job/GenPRTest/job/functional_prtest/1/

**Comment by jdom** [comment]
The temporary jobs building in Release mode where deleted (the CI builds expires after a few hours), but they built and tested the Release configuration successfully.

**Pull request merged**
