### PR TITLE
Ports HelloWorld sample to use Nuget packages

### LINKED ISSUE #186: Port all samples that use Azure to the new Azure Storage libraries.
Mentioned here:
https://github.com/dotnet/orleans/pull/149#issuecomment-75172571

### PR DESCRIPTION
**Pull request by veikkoeeva**
Adds HelloWorldNuget example to the repository

This PR adds HelloWorldNuget example to use the publicly available
1.0.3 Nuget packages. Other than the Nuget packages and the hello
message this is exactly the same example as the HelloWorld one based
on the MSI package.

* This makes verifying #174 easy as the sample is small. First the silo
  starts, after running "Update-Package" from the Package Manager
  Console the silo won't start anymore.

* This uses the current Nugets which have a dependency to Azure SDK 2.5.
  It may be necessary to update this example after the new packages are public.

* This conversion may help others with issues as described in #192, with
  reference to conversion instructions currently at
  https://github.com/dotnet/orleans/wiki/Convert-Orleans-v0.9-csproj-to-Use-v1.0-NuGet.

* Even if using the Nuget packages, the SDK is needed as per issue #213.

### CODE REVIEW

**Comment by veikkoeeva** [comment]
All right, that became interesting when first on command line and then thinking to use the GitHub Client. Hmm...

**Comment by jthelin** [comment]
LGTM. I won't merge this just yet in case others want to add some other comments.

**Comment by veikkoeeva** [comment]
@jthelin Indeed. As for the bullet to fix to #186 I meant that if this is all right, I can convert the rest of examples too.

**Comment by gabikliot** [comment]
There are 2 separate questions:
1)  porting all samples to new Azure storage - definitely should be done, no arguments. 
2)  porting all samples to Nugets - I am not sure about that one. For example, one argument against can be that when samples consume Orleans from SDK it is easy to update to the latest master version - install new SDK and the samples already point there, no need to change anything. While if samples consume Orleans via Nugets, at the least you need to update them but it is actualy worse - we don't publish new Nugets on every tiny change to the master branch.

**Comment by veikkoeeva** [comment]
@gabikliot I think your second point is a valid one, especially considering arranging test projects when developing Orleans. Collecting the Nuget packages and distributing them around after modifications for testing is a bit slow, at least for what I tried when examining a short while the reflection bug. So, what should we do? Convert only this example or some other or none? You decide, I'll modify my commit message accordingly. :)

**Comment by jthelin** [comment]
The build.cmd will create updated NuGet packages locally, so it is always possible to add a "local repository directory" setting to your visual studio NuGet manager config to pick up most recent copies.

The bigger problem though seems to be distinguishing the new "temporary" local replacements pkgs from the "official" ones from NuGet.org.
This seems to be a general problem with NuGet not just for Orleans.

Maybe a first step to enabling that local pkg scenario to work more smoothly might be if build assigns incremental micro-versioning eg 1.0.3.x based on some epoch calculation?

**Comment by jthelin** [comment]
It is also worth noting that allowing binary assembly references to change silently through sideways install of new version of OrleansSDK violates the software engineering principle of "Repeatable Builds".

http://www.eugeneduvenage.com/2011/11/continuous-integration-basics-part-2repeatable-builds-with-build-automation/

**Comment by gabikliot** [comment]
My recommendation would be to:
1) Port all samples to the new Azure storage libraries, without yet changing the way dependencies are consumed.
2) Change one sample only HelloWolrd to use Nugets. Maybe rename it to HelloWorld-Nuget. That way we have examples for both ways.
3) Leave the other samples as is, until we find a better way to solve what @jthelin mentioned: "distinguishing the new "temporary" local replacements pkgs from the "official" ones from NuGet.org"

**Comment by veikkoeeva** [comment]
@jthelin I haven't thought about that before. I haven't produced Nuget packages before. One lives, one learns. :)

@gabikliot  Sounds like a plan. I'll produce a HelloWorld-Nuget example in a day or two (I need to go sleep soon). I may produce a new PR. I'll see if it isn't that much a trouble to port the other examples to newer storage and do that too in the near future (unless someone else gets there first).

**Comment by gabikliot** [comment]
Thanks @veikkoeeva!

**Comment by veikkoeeva** [comment]
@jthelin and @gabikliot See the updated PR. I tried to be careful to have new guids and names in appropriate places -- and a slightly modified hello grain message to make this version more distinquishable. Otherwise the new project is just a copy of the non-grain version.

**Comment by veikkoeeva** [comment]
Good catches! I'll fix in about 14 hours!

**Pull request merged**
