### PR TITLE
Add a timeout for socket connection

### PR DESCRIPTION
**Pull request by benjaminpetit**
Fix for #2788 

It seems that the value by default is around 20 seconds.

I added a method in `SocketManager` to be able to specify a timeout from the configuration, and use it for client->gw and silo->silo socket connect.

### CODE REVIEW

**Comment by xiazen** [comment]
aww.  'Socket' does not contain a definition for 'BeginConnect' and no extension method 'BeginConnect' accepting a first argument of type 'Socket' could be found (are you missing a using directive or an assembly reference?) [D:\j\workspace\netstandard-w---f16d272e\vNext\src\Orleans\Orleans.csproj]

without much investigation , I think in netstandard, Socket may not have an method of BeginConnect. You need to find an alternative for that

**Comment by benjaminpetit** [comment]
Great... I Have to use the over complicated ConnectAsync for that...

**Comment by benjaminpetit** [comment]
@dotnet-bot Test this please

**Comment by gabikliot** [comment]
LGTM.

**Pull request merged**
