### PR TITLE
HelloWorldNuGet-PkgRestore

### PR DESCRIPTION
**Pull request by jthelin**
- Enable package restore in the HelloWorldNuget sample app.

- Visual Studio auto-corrected the project reference name/guid between grain class and interface projects.

- Removed unnecessary config / schema files from this sample app, although the underlying bug in nuget packages that cause then to be included in the first place still exists -- Partly documented in Issue #218

- This sample app also requires PR #228 to cleanly handle first-time-compile from fresh install / repo.

### CODE REVIEW

**Comment by jthelin** [comment]
This is a follow-on changes from PR #204 by @veikkoeeva and PR #218 by @ToddShelton which discovered the problems with the NuGet packages including extra config / xsd schema where they should not be.

**Comment by veikkoeeva** [comment]
@jthelin This looks like the Nuget restore prior to 2.7 with *nuget.exe* and config files. [Looking at the documentation](http://docs.nuget.org/consume/package-restore), the Nuget team recommend other approaches. Is this a valid note or did I just miss something?

**Comment by akoeplinger** [comment]
I agree with @veikkoeeva, the old-style package restore needs to die in a :fire:, automatic package restore is recommended and much better today.

**Comment by jthelin** [comment]
Hmm. Yes, I think you are both right. 

It was late, and I foolishly assumed that VS would be doing the right thing for me when is prompted to set up package restore, since I already have NuGet Manager 2.8 installed, but apparently not! :cry: 

That's a long doc you linked to @veikkoeeva but I eventually worked out it does leads to these step-by-step instructions for converting into the 2.7+ nirvana:
http://docs.nuget.org/Consume/Package-Restore/Migrating-to-Automatic-Package-Restore

I'll take another stab at this change. Thanks for the insight guys :+1:

**Comment by akoeplinger** [comment]
FYI, the "Enable package restore" context menu will be removed in NuGet 3.0 to avoid leading more people into this confusion: https://nuget.codeplex.com/workitem/4019.

The general rule now is that NuGet should "just work" without enabling anything explicitly.

**Comment by veikkoeeva** [comment]
It's a trap!

**Comment by jthelin** [comment]
That latest commit fd92ec1 is definitely the right way that NuGet restore is now "supposed" to be done as far as i can tell, but the current Orleans NuGet packages don't work with this approach. :crying_cat_face: 

http://docs.nuget.org/Consume/Package-Restore/Migrating-to-Automatic-Package-Restore

The codegen.exe is not getting located correctly. More investigation required...

BTW, i used the ```migateToAutomaticPackageRestore.ps1``` script below to make the changes, and it worked very well for me. 
https://github.com/owen2/AutomaticPackageRestoreMigrationScript

**Comment by veikkoeeva** [comment]
@jthelin It looks good to my eyes, without actually running it. If there's something, I'm sure it's minor things now and is fixable when noticed.

**Pull request merged**
