### PR TITLE
Added new presentation on Balancing Techniques in Orleans.

### PR DESCRIPTION
**Pull request by gabikliot**

### CODE REVIEW

**Comment by sergeybykov** [comment]
It seems odd to me that we'd have a top-level Presentations folder with a single deck on a level 300-400 topic and nothing else there. I suspect it may confuse people.

Also, putting binary files (I know it's a compressed XML under the covers but it is treated as a binary file) to Git is a practice frown upon. I wonder if there a better place to put such files outside of the repo.

**Comment by sergeybykov** [comment]
Never mind. I missed that this is for the gh-pages branch.

**Comment by gabikliot** [comment]
:-)

**Comment by sergeybykov** [comment]
I need more sleep time. :-)

**Pull request merged**
