### PR TITLE
Streams doc

### PR DESCRIPTION
**Pull request by ashkan-saeedi-mazdeh**

### CODE REVIEW

**Comment by ashkan-saeedi-mazdeh** [comment]
I think my commits of #1042 are mixed with this. How can I fix it? Git beginner at best.

The things meant for this were streaming doc changes and standalone silo

**Comment by gabikliot** [comment]
Please separate the stream docs from other doc changes. You need to create a branch from master and do only stream changes there (you probably applied your stream changes over other yet not merged changes).

**Comment by gabikliot** [comment]
Waiting for this to be rebased on the latest gh-pages branch, which already has some of the fixes in this PR merged. In particular, in this PR please only include the streaming changes.

**Comment by ashkan-saeedi-mazdeh** [comment]
@gabikliot  I have a new clean branch with those changes only.
What should I do?

**Comment by gabikliot** [comment]
push hard your local one into this remote one: http://stackoverflow.com/questions/10510462/force-git-push-to-overwrite-remote-files.

**Comment by ashkan-saeedi-mazdeh** [comment]
@gabikliot  Thanks
Then it should be ready to merge now!

**Comment by gabikliot** [comment]
I merged and made some corrections. Thank you @ashkan-saeedi-mazdeh !

**Pull request merged**
