### PR TITLE
Coreclr compatibility: Process.Handle -> Process.SafeHandle

### PR DESCRIPTION
**Pull request by dVakulen**
Related to #368. Also increased  .Net framework version to 4.6.

### CODE REVIEW

**Comment by galvesribeiro** [comment]
@dVakulen Great suff, but you must revert back projects to 4.5. 

We are not moving to 4.6 so soon. 

There is a "pseudo-rule" in the project that we always stay on .net version "currentVersion - 1". Of course an exception is being made for coreCLR for now since there is a huge demand for that(specially to make it work with NanoServer and Azure containers) as long as we keep the previous rule in play as much as we can. 

Besides, .Net 4.6 (IMHO) isn't stable enough now with several know issues being handled.

**Comment by gabikliot** [comment]
Can't move to 4.6 yet.
https://github.com/dotnet/orleans/issues/918

**Comment by galvesribeiro** [comment]
Just as #918 says, Orleans is not built with 4.6 but can run on it. Now that the new codegen is merged, as soon as we get the new release published, people will be able to have 4.6-based grain projects without any problem so, we don't need worry with update the core projects to 4.6 so soon. Maybe when Azure fully supports it on its Guest OS family, would be a good time.

**Comment by dVakulen** [comment]
The existence of separate "coreclr-compatibility" branch isn't makes much sense if it only can contain code that could've been contributed to master with same effect. For now I've increased the version to be able to test the changes while the core Clr build can't be built. Eventually the main codebase will be moved to the 4.6, and the merge most likely won't cause major problems as non coreClr compatible code isn't subject to frequent changes. Also with release of .NET Framework 4.6.1 RC major part of bugs were fixed.

**Comment by sergeybykov** [comment]
`Process.SafeHandle` is available in 4.5. So this change doesn't require 4.6, correct?

**Comment by dVakulen** [comment]
No, its available only 4.6: https://msdn.microsoft.com/en-us/library/system.diagnostics.process.safehandle(v=vs.110).aspx. And updating to .Net 4.6 would allow leveraging <code>System.Threading.AsyncLocal\<T\></code> instead of <code>System.Runtime.Remoting.Messaging.CallContext</code>.

**Comment by sergeybykov** [comment]
My bad - I got confused by the ".NET Framework 4.6 and 4.5" statement at the top of the page.

**Comment by galvesribeiro** [comment]
Yes... SafeHandler isn't there on 4.5.x unfortunately... Humm, I think we will have to move for 4.6 before we think... Need have a look on 4.6.1 RC...

**Comment by sergeybykov** [comment]
@dVakulen  Can we #ifdef this for now, so that @galvesribeiro can compile it for CoreCLR?

**Comment by gabikliot** [comment]
We should just write a wrapper function that on 4.5 uses process.Handle and on 4.6 and DNX uses process.SafeHandle, with  #ifdef.

**Comment by dVakulen** [comment]
Updated.

**Comment by gabikliot** [comment]
Looks good. Thanks.

**Pull request merged**
