### PR TITLE
Manual stats dump #6310

### PR DESCRIPTION
**Pull request by OracPrime**
As per #6310, allow users to dump statistics on demand, rather than just on a timer.

### CODE REVIEW

**Comment by ReubenBond** [comment]
I'd prefer a name more specific to your use case - eg, IStatisticsDumper or IDumpLogStatistics. The interface doesn't currently have any methods related to management.

Be aware that we may remove these statistics entirely in future and replace them with .NET Core `EventCounters` - likely with purpose-built interfaces for you to intercept them and do with them what you wish

**Comment by OracPrime** [comment]
I can push another commit with IStatisticsDumper if you like? I'm not attached to the name; just thought that it was the public face of the managers.  The fact that the only public management is controlling when things are dumped is just the current state.

**Comment by ReubenBond** [comment]
This is fine, I'll merge when tests complete

**Comment by sergeybykov** [comment]
Thank you, @OracPrime!

**Pull request merged**
