### PR TITLE
refactor(blazor sample): use asp.net core hosting like the webapi template

### PR DESCRIPTION
**Pull request by ElderJames**

### CODE REVIEW

**Comment by ReubenBond** [comment]
Thanks for the PR! Could you change it to avoid using the `Startup` class and instead configure the Web builder directly? You can still have separate methods for ConfigureServices/etc.

**Comment by ElderJames** [comment]
I think using the `Startup` class is more like the .net sdk template.

**Comment by ElderJames** [comment]
I fix it now.

**Comment by ReubenBond** [comment]
Thank you, @ElderJames!

**Pull request merged**
