### PR TITLE
Orleans.TestingHost: support for .NET Standard

### PR DESCRIPTION
**Pull request by ReubenBond**

### CODE REVIEW

**Comment by sergeybykov** [comment]
Does it make sense to move `Orleans.TestingHost.AppDomain` to test\Orleans.TestingHost.AppDomain?

**Comment by sergeybykov** [comment]
I see a bunch of
>System.IO.FileNotFoundException : Could not load file or assembly 'Orleans.TestingHost.AppDomain, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

error in functionals in VSTS.

**Comment by ReubenBond** [comment]
Tests failing because of shared static `CounterStatistic`

**Comment by ReubenBond** [comment]
@dotnet-bot test functional

**Comment by ReubenBond** [comment]
@dotnet-bot test functional

**Comment by galvesribeiro** [comment]
@dotnet-bot test functional

**Comment by sergeybykov** [comment]
There are some functional test failures - https://orleans.visualstudio.com/Orleans/_build/index?buildId=9399&_a=summary&tab=ms.vss-test-web.test-result-details.

**Comment by ReubenBond** [comment]
It might be that some failing tests aren't fully isolated, but I want to run with this rebased version before investigating more deeply.

**Comment by ReubenBond** [comment]
This is passing here and in VSO. The last commit is not needed, so I'll remove it. It's benign

**Comment by galvesribeiro** [comment]
:shipit:

**Pull request merged**
