### PR TITLE
Include transactions tests in CI

### PR DESCRIPTION
**Pull request by jdom**
This PR should not be merged until we fix the non-deterministic issues with the Transactions tests

### CODE REVIEW

**Comment by jason-bragg** [comment]
Should be able to merge after:
Fixed intermittent transaction orchestration test failures #3547 
Limit request context to messaging layer #3546

**Comment by jason-bragg** [comment]
@dotnet-bot test this please

**Comment by xiazen** [comment]
@dotnet-bot test this please

**Comment by jason-bragg** [comment]
@dotnet-bot test this please

**Comment by jdom** [comment]
@dotnet-bot test functional
@dotnet-bot test bvt
Reason: try a few times

**Comment by jdom** [comment]
@dotnet-bot test functional
@dotnet-bot test bvt
Reason: try a few times

**Comment by jdom** [comment]
@dotnet-bot test functional
@dotnet-bot test bvt
Reason: try a few times

**Pull request merged**
