### PR TITLE
Cherry-picked commits from master to go in 1.4.0 final

### PR DESCRIPTION
**Pull request by sergeybykov**
It's pretty much everything since 1.4.0-beta except for the commits related to non-static `SerializationManager` work.

### CODE REVIEW

**Comment by ReubenBond** [comment]
LGTM, I can't think of other commits which really need to make it into 1.4.0 except for the upgrade to Bond

**Comment by sergeybykov** [comment]
Let me add https://github.com/dotnet/orleans/pull/2691 when it's merged before merging this.

**Comment by sergeybykov** [comment]
Ready now.

**Comment by ReubenBond** [comment]
There's no CI run needed, right?

**Comment by sergeybykov** [comment]
>There's no CI run needed, right?

Right. We build and test this in VSO.

**Comment by sergeybykov** [comment]
Oh, you squashed them? I don't think we want that. I'll reset the branch and resubmit the PR, so that we keep individual commits in the history.

**Comment by ReubenBond** [comment]
oh that's bad! you're right, I'll revert

**Comment by sergeybykov** [comment]
I force-pushed 1.4.0 and submitted https://github.com/dotnet/orleans/pull/2694.

**Pull request merged**
