### PR TITLE
Migrate AdoGrainStorage to the new grain serializer

### PR DESCRIPTION
**Pull request by benjaminpetit**
To simplify `AdoGrainStorage` and make the configuration experience similar to the other persistence provider, the serializer for `AdoGrainStorage` will be configured using `AdoNetGrainStorageOptions.GrainStorageSerializer`

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/orleans/pull/8081)

### CODE REVIEW

**Comment by benjaminpetit** [comment]
There is some errors in some SQL scripts, but test are green... I will open another PR to fix the tests, do not merge this one yet

**Comment by benjaminpetit** [comment]
Will close #8077 once merged

**Comment by ElanHasson** [comment]
@benjaminpetit does this mean that JSON is no longer an option?

**Comment by ElanHasson** [comment]
@benjaminpetit we should also probably flatten the SQL scripts into one per ado engine

**Comment by benjaminpetit** [comment]
> @benjaminpetit does this mean that JSON is no longer an option?

It's still possible, it's even the default. You can configure the serializer you want in the option.

**Comment by veikkoeeva** [comment]
@ElanHasson We should do that that flattening. At the same go, remove the preprocessor directives in the code (haven't checked the PR). :P

**Pull request merged**
