### PR TITLE
#1918 from @dsarfati rebased and fixed

### PR DESCRIPTION
**Pull request by sergeybykov**
I rebased #1918, fixed it, so that it builds, and made minor adjustments to the code on top of @dsarfati's commit.

### CODE REVIEW

**Comment by sergeybykov** [comment]
@jdom I think we can merge this, so that @dsarfati doesn't need to do anything. His commit is included here.

**Comment by jdom** [comment]
I think this PR minimizes the side effects of mocking at an odd level. Instead of relying on the concrete `GrainCreator` and concrete `GrainStateStorageBridge` as in https://github.com/dotnet/orleans/pull/1919/files#r70298407 I would strongly recommend that you do not try to use `GrainCreator` for this. Just use your own way of instantiating the grain (which you are partially doing already in that PR, when it comes to generic grains), and setting an explicit mock of IStorage. That way you would isolate your tests better, and also this change would not be needed.
Am I missing a scenario here @dsarfati?

**Comment by sergeybykov** [comment]
I think we should close it then along with #1918, until @dsarfati or somebody else has time to update the code.

**Comment by dsarfati** [comment]
Sorry for not responding back earlier. I was on paternity leave while you guys were making these comments and I never got a chance to respond. I think the concern with the constructor method was that it forces us to have code that is only ever used for testing and left a bad taste. This intention of this PR was to allow us to create the grain using the same constructor that orleans will use. This seems especially important if we are using a DI container. If there is a better approach to this I'm all ears.

**Comment by dsarfati** [comment]
The real issue here is that there is currently no way to call SetStorage since IStatefulGrain is internal. Maybe a better approach would be to make IStatefulGrain a public interface and make GrainGreator internal. That way anyone can create their own methods for instantiating grains for testing (like in my PR) and not be forced to use the GrainCreator to set the IStorage on those grains.

**Comment by sergeybykov** [comment]
@dsarfati, congratulations with the baby! No worries, family is more important. :-)

@ReubenBond @jason-bragg, what do you think here?

**Comment by jason-bragg** [comment]
LGTM but still has some conflicts.  Please update and I'll merge.

**Comment by sergeybykov** [comment]
@jason-bragg What do you think of @jdom's comment above?
>I think this PR minimizes the side effects of mocking at an odd level. Instead of relying on the concrete GrainCreator and concrete GrainStateStorageBridge as in https://github.com/dotnet/orleans/pull/1919/files#r70298407 I would strongly recommend that you do not try to use GrainCreator for this. Just use your own way of instantiating the grain (which you are partially doing already in that PR, when it comes to generic grains), and setting an explicit mock of IStorage. That way you would isolate your tests better, and also this change would not be needed.

**Comment by dsarfati** [comment]
I was able to accomplish the same effect using reflection to set the private variables for Runtime, identity, storage...  it makes me feel dirty but I now have traditional unit tests running without any silos. I was thinking about making this an OrleansContrib project so others could use it. If we decided to include this PR then I will update the tests to use the grain creator instead of reflection.

**Comment by jason-bragg** [comment]
While I agree that this PR does not put us at an ideal end-state, it is an incremental change in the right direction.  As the grain has no direct dependency on the storage provider, only the storage class, this change improves separation of concerns, flexibility, extensibility and testability.  Given a choice between an incremental change in the right direction, or holding off for a more complete refactor, I'd vote for the incremental change.

**Comment by sergeybykov** [comment]
I rebased it and kicked of tests.

**Comment by sergeybykov** [comment]
Functional tests passed.

**Pull request merged**
