### PR TITLE
Add flag to disable FastKill on CTRL-C

### PR DESCRIPTION
**Pull request by benjaminpetit**
Fix for #3094

### CODE REVIEW

**Comment by ReubenBond** [comment]
I believe we should just get out of the Ctrl+C business altogether, but especially in `Silo.cs` - what are the advantages for it?

**Comment by sergeybykov** [comment]
I believe the original reason to intercept Ctrl+C was to speed up cluster reconfiguration by having the silo going down mark itself dead in the membership table, so that there is less of a delay and fewer failing requests while failure of the node is being detected by the membership protocol. I'm not sure how frequently this happens in production deployments, but it is useful during development when deployment ID is reused between multiple test runs.

**Comment by sergeybykov** [comment]
@dotnet-bot test netstandard-win-functional

**Comment by jdom** [comment]
I'm with Reuben, that this is not a concern of the Silo itself. Perhaps of SiloHost or some Console-specific host. But I'm OK with the change for now, but it should definitely be moved out once we move to Silo Builder.

**Comment by bboyle1234** [comment]
https://github.com/dotnet/orleans/issues/4151

**Pull request merged**
