### PR TITLE
[Abstractions] Move IStreamProvider and its dependencies to Abstractions

### PR DESCRIPTION
**Pull request by benjaminpetit**
This change is needed because `Grain` uses `IIStreamProvider`

### CODE REVIEW

**Comment by benjaminpetit** [comment]
@dotnet-bot test this

**Comment by benjaminpetit** [comment]
@dotnet-bot test bvt
@dotnet-bot test functional

**Comment by xiazen** [comment]
LGTM

**Comment by xiazen** [comment]
Configuration\GlobalConfiguration.cs(1079,79): error CS0419: Ambiguous reference in cref attribute: 'IStreamProvider'. Assuming 'IStreamProvider', but could have also matched other overloads including 'IStreamProvider'. [D:\j\workspace\bvt_prtest3cca9be5\src\Orleans\Orleans.csproj]
the build failure error. 

I think the build is confusing System.Xml.IStreamProvider with Orleans.Stream.IStreamProvider. I think you just need to be more specific

**Comment by benjaminpetit** [comment]
Weird, I don't repro this error locally, at least with VS
________________________________

**Comment by xiazen** [comment]
have u tried build from cmd locally

**Comment by benjaminpetit** [comment]
Yes and it works...

**Comment by benjaminpetit** [comment]
Crazy that was not working because of the doc build :)

**Comment by benjaminpetit** [comment]
@dotnet-bot test bvt
@dotnet-bot test functional

**Comment by xiazen** [comment]
@dotnet-bot test bvt

**Comment by jdom** [comment]
@dotnet-bot test bvt

**Pull request merged**
