### PR TITLE
#6908 - change the ETag options when writing to Azure Blob Storage Provider

### PR DESCRIPTION
**Pull request by richorama**

### CODE REVIEW

**Comment by ReubenBond** [comment]
LGTM, thank you @richorama! Did you run into this issue?

**Comment by richorama** [comment]
Ha, no, only by searching for an unrelated problem in the issues. Saw it and thought it would be trivial to knock off.

**Comment by oising** [comment]
This seems serious enough to warrant a backport to 3.x, no? /cc @ReubenBond

**Comment by ReubenBond** [comment]
Thanks for pointing that out, @oising, we should aim to include it in 3.5.1

**Pull request merged**
