### PR TITLE
Add Analyzer and CodeFix for duplicate method aliases (ORLEANS0011)

### LINKED ISSUE #8661: ORLEANS0011: Report error on duplicate aliases
Create analyzer & code fixer which detects duplicate `AliasAttribute("XXX")`, where XXX is duplicated within grain interface methods due to method overloading.

Key: ORLEANS0011
Category: Usage
Severity: Error

cc @ReubenBond: as per convo in #8643

### PR DESCRIPTION
**Pull request by ledjon-behluli**
cc @ReubenBond 
close #8661 

Analyzer:
alias-clash-analyzer

Fixer:
alias-clash-codefix

Tests:
alias-clash-tests

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/orleans/pull/8662)

### CODE REVIEW

**Comment by ledjon-behluli** [comment]
Note, this PR is based on #8643 (*which has not yet been merged*), thats why it contains the  `GenerateAliasAttributesAnalyzer` code

**Comment by ReubenBond** [comment]
image
image
image
Should this be `Echo2` instead of `Echo11`?

**Comment by ledjon-behluli** [comment]
@ReubenBond If "Fix for Document" than yes, it changes to 'Echo1' and 'Echo2'

image

But if you change them 1-by-1 its actually quite the problem, let me explain why:
A "duplicate" is defined only if its the same alias (as in the same text), if analyzed all other "EchoX" in order to determine the 'X' its going to get very ambiguous what really is a "Echo".

image

Thats why if the user applies the code fix for the document, and there are multiple "Echo"s it will go 1, 2, 3. But if the above is true, than we look the only "true" duplicate which would be "Echo" and assign the next number which would be "Echo1"

image

I hope I make sense here

**Comment by ReubenBond** [comment]
In your example, I would expect the result to be "Echo1". If there was a method with the alias "Echo1" already, then I would expect the result to be "Echo2", and so on until there is no conflict. The method name does not matter (the developer could have aliased a method named GetFoo as "Echo" and the result should be the same), but the resulting alias value does.

**Comment by ledjon-behluli** [comment]
"The method name does not matter" - I see what you mean, i'll address it 👍

**Comment by ledjon-behluli** [comment]
@ReubenBond Maybe it makes sense to hold off on approving the other PRs which are based on this (since some common code is shared), until this is resolved and i'll port the change to the other 2 PRs. You could still review and leave comments ofc.

**Comment by ledjon-behluli** [comment]
@ReubenBond It should work as expected now

**Comment by ledjon-behluli** [comment]
@ReubenBond are we good with this, so we can move onto the other?

**Comment by ReubenBond** [comment]
I am tweaking the suffix incrementing code a little, but otherwise LGTM

**Review by ReubenBond — APPROVED** [review]

**Comment by ReubenBond** [comment]
@ledjon-behluli if you can rebase, I'm ready to merge.

**Comment by ReubenBond** [comment]
@ledjon-behluli I performed a squash merge + force push of your latest, since it included changes from main which made final review harder.

**Comment by ledjon-behluli** [comment]
@ReubenBond whatever it takes, stuff got mangled up

**Review by ReubenBond — APPROVED** [review]

**Review by ReubenBond — APPROVED** [review]

**Comment by ReubenBond** [comment]
Includes #8664 & #8672

**Pull request merged**
