### PR TITLE
Populate application parts from generated code

### PR DESCRIPTION
**Pull request by ReubenBond**
Application Parts are a pain. This PR attempts to alleviate some of that pain for the typical case by automatically populating application parts with the precise set of assemblies which contain grains, interfaces, and serializable types.

### CODE REVIEW

**Comment by jdom** [comment]
This changes the default behavior... I assume it can be an important breaking change?

**Comment by ReubenBond** [comment]
It's for 4.0, so a change in default behavior is acceptable. App Parts are also a pain today. This aligns our behavior more closely with ASP.NET, as well: they are using similar generation already.

**Comment by jdom** [comment]
Ok, I agree. BTW, since samples weren't updated, I want to confirm whether this change will make it that you don't have to configure silo parts at all if you want the new default (which is that parts for the executable and its references will be used)? And if you want to be explicit, you'll have to explicitly first clear the app parts?

**Comment by pentp** [comment]
Is the only way to opt-out from this scanning of every assembly during startup by providing my own `IApplicationPartManager`?
For ASP.NET it's possibly to bypass their scanning logic by using `HostBuilder` and for Orleans we currently just call `ConfigureApplicationParts` to add our assemblies, but now this same call would scan basically all assemblies just to create the `ApplicationPartManager` with no way of bypassing it?

**Comment by jdom** [comment]
can you edit the description a little to explain how it alleviates the pain? I'm still not 100% sure of what it does, since samples weren't updated. I have some assumptions, but with the many abstractions, I prefer you tell us explicitly what the change actually does.

**Comment by ReubenBond** [comment]
Updated description. Users should never have to touch application parts in the usual case. They should only need to be customized for non-typical cases, such as when filtering out assemblies/providers or dynamic assembly loading (where the asm isn't linked to any of the the main application assemblies)

**Pull request merged**
