### PR TITLE
When deactivating a grain, do not stop timers if there are running requests 

### PR DESCRIPTION
**Pull request by benjaminpetit**
Fix for #4774 

Thanks @yevhen , I was able to repro this issue 100% with this test. Like said in the issue, this will fix only part of the issue.

### CODE REVIEW

**Comment by yevhen** [comment]
Oh, cool! Thank you for the fix!

**Comment by benjaminpetit** [comment]
@dotnet-bot test functional please

**Comment by benjaminpetit** [comment]
@dotnet-bot test functional please

**Comment by benjaminpetit** [comment]
@dotnet-bot test functional please

**Comment by ReubenBond** [comment]
@dotnet-bot test functional please

**Comment by ReubenBond** [comment]
@dotnet-bot test functional

**Pull request merged**
