### PR TITLE
Removed vNext files to fix current build

### PR DESCRIPTION
**Pull request by galvesribeiro**
Removed vNext files in order to get solution to build and avoid error:

"Couldn't find the required information in the lock file. Make sure you have .NETFramework,Version=v4.5 mentioned in your targets."

### CODE REVIEW

**Comment by ReubenBond** [comment]
Several of us have had this problem when opening Orleans in VS 2015.

DNX support is not yet ready, so we should work on it in a separate branch (not master). Leaving these files in master raises the barrier to entry for new contributors.

Thank you, @galvesribeiro :)

**Comment by galvesribeiro** [comment]
By mistake I messed up this PR. I was trying to create a separate PR for the last Commit which is related to a problem when deserializing grain states which contains circular references...

**Comment by KodrAus** [comment]
@ReubenBond Totally agree. It's made it difficult for me to get into it

**Comment by gabikliot** [comment]
Agree to remove, to have zero friction for master.

**Comment by ReubenBond** [comment]
Note that we should wait for @galvesribeiro to force-push an update to this PR which doesn't include https://github.com/galvesribeiro/orleans/commit/1628e8d812b6415b5ff8933c69d0afdc7b98ea59 - it was an accident

**Comment by jthelin** [comment]
+1. Merging.

**Comment by jthelin** [comment]
I'm confused @ReubenBond 

`ICircularStateTestGrain.cs` isn't in the list of files changes in this PR.

https://github.com/dotnet/orleans/pull/939/files

**Comment by jthelin** [comment]
Oops. A GitHub race condition just hit us! 
The files list just updated to include `ICircularStateTestGrain.cs` which wasn't in a1cebd174a08731f5ea0f5a3c83f2e33a0ea4506 [although my copy of this web page still doesn't show the new change] :(
I reverted the extra commit.

**Comment by galvesribeiro** [comment]
@jthelin we need to removed the second commit... Its not related to this bug o.O

**Comment by jthelin** [comment]
OK. Commit b074c11ceb5a5c32a37573c97338ba4c4a3838dc undoes the second commit, 
We should be good now, I think.

**Comment by galvesribeiro** [comment]
Nice! Thank you @jthelin  :)

**Comment by jthelin** [comment]
For a "distributed version control system" it is funny how bad GitHub is at handling race conditions. Eventual consistency for the win. ;)

**Comment by galvesribeiro** [comment]
Yes @jthelin.... I have my concerns about github usability/functionalities... If MS opens VSO for OSS projects.... :)

**Pull request merged**
