### PR TITLE
make sure ETag is set on insertion to membership table

### PR DESCRIPTION
**Pull request by amccool**
RE: issue  https://github.com/dotnet/orleans/issues/1341

### CODE REVIEW

**Comment by sergeybykov** [comment]
Looks good to my limited understanding of the SQL stuff. I wonder what @veikkoeeva and @shayhatsor think.

**Comment by amccool** [comment]
I agree their input is highly encouraged.  More importantly of what importance is the ETag?
I will reference this:
`Orleans.Runtime.OrleansException: The target silo is no longer active: target was S172.18.124.93:11111:191451380, but this silo is S172.18.124.93:11111:191609531. The rejected message is Request S172.18.124.91:11111:191609335*grn/7483D9D2/00000000@110379bd->S172.18.124.93:11111:191451380SiloControl@S0000000c #35363: global::Orleans.ISiloControl:GetRuntimeStatistics().`

**Comment by gabikliot** [comment]
I will take a look as well, but I would really like to hear what  Shay has to say. Lets wait for his input.

**Comment by sergeybykov** [comment]
ETag is critical for preventing concurrent writes. Like in the Azure Table version, we want a write to a row to succeed only if the passed ETag matches the one currently in the table.

**Comment by veikkoeeva** [comment]
@amccool Have you observed this before or recently? A few notes by looking at the diff (it looks like the script hasn't changed other than adding whitespace?):

* The version column is of type [ROWVERSION](https://msdn.microsoft.com/en-us/library/ms182776.aspx), it is updated automatically whenver a row is created or updated.
* In the code you modify code that has read the the membership data from the DB and is constructing a `Membership` instance of it. The creation is [here](https://github.com/dotnet/orleans/blob/bffa131489a8930d048707f7b6e00de2286b7e8c/src/OrleansSQLUtils/Storage/RelationalOrleansQueries.cs#L643).
* The type `@versionEtag` you see in the code is used for `[OrleansMembershipVersionTable]` (it might be more clear if the name of the table column in the database would be renamed correspondingly to, say, `[VersionEtag]`. So, if looking at using it to [create](https://github.com/dotnet/orleans/commit/bffa131489a8930d048707f7b6e00de2286b7e8c#diff-884ba45bfcf853bcd6d499c449e96401R807) the `MembershipEntry` doesn't look right.

Ah, it looks like the changeset changed while I was reading it. I'll leave the notes here.

**Comment by gabikliot** [comment]
> More importantly of what importance is the ETag?

http://dotnet.github.io/orleans/Runtime-Implementation-Details/Cluster-Management

Exactly like @veikkoeeva said, we might not need an explicit etag column in SQL tables at all, if it is handled and validated automatically with ROWVERSION. Same in Consul - the Consul CAS has a built in special field for concurrency control. And actually same in Azure Table - AT has a built in etag, which is NOT part of the application data. So I am not convinced there is any problem at all in SQL in the first place. It might all just work OK. I will check more.

**Comment by veikkoeeva** [comment]
@gabikliot To use automatic versioning, one needs one column of type `ROWVERSION` per table, name can whatever, it's rarely named `Etag`, but I kept the Orleans conventions and maybe that is more familiar to people in general.

**Comment by shayhatsor** [comment]
[here](https://github.com/dotnet/orleans/pull/1008#issuecomment-155603066) I commented:
> Following #985 the  Version  field in  OrleansMembershipVersionTable  is redundant. It should be removed from the scripts and the code. The  ETag  is the version. This change can be done later and will further reduce the hassle of introducing new relational implementations.

regarding this PR, there first version is 0 and shouldn't be set on `INSERT`.
the needed PR is to remove the Version field.

**Comment by amccool** [comment]
i tried a test where I pulled out the ETag field from the membership table, and that made one of the tests fail (https://github.com/dotnet/orleans/issues/1341) .   The PR let all the tests pass.  I don't fully understand the purpose of the ETag so I must defer judgement.    I have the PR in my environment and haven't seen adverse behavior.

I will read up on https://github.com/dotnet/orleans/pull/985 and https://github.com/dotnet/orleans/pull/1008#issuecomment-155603066

**Comment by amccool** [comment]
this PR was based on observations in https://github.com/dotnet/orleans/issues/1341.
I was seeing that the ETag field in `[OrleansMembershipTable]` was ALWAYS 0x0000000 regardless of how many silos, or duration of the lives of those silos

**Comment by veikkoeeva** [comment]
@amccool It looks like @shayhatsor points out the `Version` column, not the `ETag` one. But see my comments on that if you put `@versionEtag` to `[OrleansMembershipTable]` [here](https://github.com/amccool/orleans/blob/SQLServer-ETag/src/OrleansSQLUtils/CreateOrleansTables_SqlServer.sql#L332), it is wrong, because as far as Orleans is concerned, it is the etag of the `[OrleansMembershipVersionTable]` and that is what is sent from the code unless the code is wrong or it has been modified (which it hasn't in this latest PR). You can also see it applied just below in the query.

Did you observe this problem only during tests? Because the first insert will always create a zero on `Etag` column, but subsequent membership updates should bump it up.

**Comment by amccool** [comment]
In my cluster of 3 silo, running for days, at no point did `[OrleansMembershipTable].[ETag]` ever change from 0x0000000.   That seems wrong to me

**Comment by veikkoeeva** [comment]
@amccool True. And this for 1.1.2 release, I believe.

For the record, I just ran `MembershipTable_SqlServer_UpdateRow` from the *latest master* and saw a correct update.

**Comment by gabikliot** [comment]
@shayhatsor , there is an eTsg column in the SQL table, in addition to Version.
Do you think it is handled correctly?

**Comment by shayhatsor** [comment]
To make sure we're all on the same page, we are talking about `OrleansMembershipVersionTable` and not `OrleansMembershipTable`.
In a previous comment I said:
> the needed PR is to remove the Version field.

That was wrong, I used the `Version` field instead of the `ETag` for concurrency control.
The `Etag` is the one that is redundant and should be removed from the scripts and code. 
the removal from code isn't that trivial, so i left it for later. So it's currently there and will always be 0.

**Comment by gabikliot** [comment]
No, i think we are actually talking about the other, main, table. Look at the PR changes.

**Comment by shayhatsor** [comment]
in issue #1341, the problem described is with `OrleansMembershipVersionTable`.
about the contents of this PR, i've previously commented in this PR:
> regarding this PR, the first version is 0 and shouldn't be set on INSERT.

I actually don't understand the contents of this PR. @amccool puts some initial version when inserting to `OrleansMembershipTable`, I'm pretty sure he made a mistake and meant to do that to `OrleansMembershipVersionTable`.

**Comment by sergeybykov** [comment]
@amccool What do you think? Is this still needed but in a different form or should we close it?

**Comment by amccool** [comment]
I haven't had a chance to fully test https://github.com/dotnet/orleans/pull/1360  but it looks like it cuts to the root of the issue.
I will close this PR and I can reopen a new issue if https://github.com/dotnet/orleans/pull/1360 doesnt correct the issue.

**Pull request closed without merging**
