### PR TITLE
Repro for #1056 -replaces #1057

### PR DESCRIPTION
**Pull request by ca-ta**
See #1056 and #1057 for background information

### CODE REVIEW

**Comment by ca-ta** [comment]
The failing tests have the ```BVT``` trait commented out - please uncomment when they pass.

Please note  that some of them fail only under certain circumstances - more specifically,   the ```SerializationTests_...``` tests only fail if run together with the ```FSharpGrains_...``` tests. I suspect it has something to do with type identity.

Notes about F# NuGet packages:
* the new F# project (```testFSharp```) uses
  * [```FSharp.Core```](https://www.nuget.org/packages/FSharp.Core/) nugget package to reference the **F# 4.0 runtime** (FSharp.Core 4.4.0.0) and 
  * [```FSharp.Compiler.Tools```](https://www.nuget.org/packages/FSharp.Compiler.Tools/) nuget package to  perform the build (see notes on build behavior) using the **F# 4.0 compiler**.
* the ```Tester``` project uses [```FSharp.Core```](https://www.nuget.org/packages/FSharp.Core/) nuget package to reference the F# 4.0 runtime (FSharp.Core 4.4.0.0)

> Important notes on build behavior - please improve it if you know how to (NuGet and VS got the best of me):

The fsc.exe F# compiler provided by the  [```FSharp.Compiler.Tools```](https://www.nuget.org/packages/FSharp.Compiler.Tools/) nuget package is used to build the ```FSharpTest``` project  **if and only if either of the following is true**:

 1. the build is run from the command line (using Build.bat)
 2. the build is run from within Visual Studio **AND** the solution has been opened in Visual Studio  **AFTER** the  [```FSharp.Compiler.Tools```](https://www.nuget.org/packages/FSharp.Compiler.Tools/) nuget package has been restored (e.g. by either having previously built the solution using build.bat, and/or having restored the nugget packages using nuget.exe command line)

If the solution is opened in VS **BEFORE** the  [```FSharp.Compiler.Tools```](https://www.nuget.org/packages/FSharp.Compiler.Tools/) nuget package has been restored, the following compilers will be used:
 * VS 2013 *with F# tooling installed* : the **F# 3.1 compiler** from ```C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\fsc.exe```
 * VS 2015 *with F# tooling installed*: the **F# 4.0 compiler** from ```C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\fsc.exe```
 * I do not know what happens if one tries to build the solution  in VS **BEFORE** the  [```FSharp.Compiler.Tools```](https://www.nuget.org/packages/FSharp.Compiler.Tools/) nuget package has been restored **AND** *without* the F# tools installed. Note that:
  * VS 2013 Ultimate comes with the F# tools installed by default (though the can be out of date, of course)
 * VS 2015 ultimate *does not* install the F# build tools by default
 * I have no idea what other editions do.

Why? Well, it appears that the Visual Studio behavior is such that the conditions in the various (MSBuild) projects within the solutions are evaluated  at the time the projects are loaded by Visual Studio and **not** at the time the projects are built. Hence, the presence of a given resource (e.g. target file installed by a package) is determined *before* NuGet has the chance to restore it. 
This means that dictating within the project the loading of targets installed by a package that has not yet been restored at the time the project is loaded will cause the project to not load. Additionally, the VS-NuGet integration will *not* load packages for projects that have failed to load. Yay...

@jthelin:
- The PR does build in CI, with the correct compilers and runtime. 
 - Note that I have run the build on a pristine VM and Orleans *as a whole* **does not** build with just the .Net 4.5 SDK installed, due to some projects (e.g. ```Tester```) referencing ```Microsoft.VisualStudio.QualityTools.unitTestFramework.dll``` - which is (as per its licensing) only installed with VS.
- the PR *does* build from within both VS 2013 and VS 2015 (with the above caveats).
- I strongly recommend using VS 2015 and/or the command-line builds for consistency's sake.
- I vaguely remember a trick involving recursively building a project in order to work around the above issues, but it also remember it is beyond ugly - I'll look into it though.

**Comment by jthelin** [comment]
This is a great step forward @ca-ta - thanks for working so hard to get this ready :)

LGTM.

BTW, for context, one of the reasons i am personally very hesitant to to jump wholesale to VS2015 just yet is because i have seen some very weird version specific issues with VS2015 C# compiler in VSO in another project  :(
https://github.com/Microsoft/SparkCLR/issues/39
https://github.com/Microsoft/SparkCLR/issues/8

**Comment by ca-ta** [comment]
@jthelin  - 

Thanks for the review comments and for looking into this (thank you @davidpodhola  and @veikkoeeva, as well).
Regarding VS 2015: Got it. I guess we have not stumbled upon any issues since the vast majority of the code we write these days is F#. Also, Orleans builds just fine in VS 2015

**Comment by ca-ta** [comment]
@jthelin 

I think this is ready to merge.

I was able to change the project file so that the F# compiler provided by the  [```FSharp.Compiler.Tools```](https://www.nuget.org/packages/FSharp.Compiler.Tools/)  nuget package is used to build the  FSharpTest  project *at all times*, irrespective of whether the build is run form the command line or from VS, and irrespective of the version of F# tools installed on the machine (if at all). 

This means that now the F# project *always* builds using the F# 4.0 compiler and the F# 4.0 runtime.
I've also tested building from within VS 2013 - it works.

Making this work form within Visual Studio was a bit of a nightmare - the NuGet/MSBuild/VS integration is a major hindrance, as it fails to reevaluate project conditions after packages have been restored. The only way I could make it work was to use MSBuild to recursively build the project (and yes, I know it's convoluted... but it's the only thing that worked - take a look at the latest check-in for details).

**Comment by jthelin** [comment]
Thanks @ca-ta - Looking very promising :)
I'll take a look later today, but looks like head has moved a little and this branch now needs a minor rebase for merging other `Tester.csproj` changes.

**Comment by ca-ta** [comment]
@jthelin - would you like me to rebase it or will you do it as part of the merge? Either way works for me - let me know.

**Comment by jthelin** [comment]
Yes, please rebase and then force push to this PR branch, which will make GH update the change set and rerun all the build/merge checks again.

I am a very strong believer in "proposer-makes-good" responsibility for merge conflicts and PR build issues in distributed development teams :)
https://github.com/dotnet/orleans/pull/937

**Comment by ca-ta** [comment]
Works for me :-) - rebased & forced push (thanks for the pointers).

**Comment by jthelin** [comment]
The change works as described on my machine :)

I do see an problem reported from the choco package creator when I run the build locally, but it is unrelated to this change, so I'll merge this PR now so we can more forward and I'll fix that issue separately.

Failure mode:

```
===== Build Orleans Chocolatey packages from E:\Depot\GitHub\orleans\Binaries\Release\
...
CPACK_CMD= choco pack "E:\Depot\GitHub\orleans\src\Chocolatey\orleans.nuspec" --Version=1.1.0
File not found: '..\..\Binaries\Release\Microsoft.WindowsAzure.Configuration.dll'.
...
call "E:\Depot\GitHub\orleans\src\Build\PostBuild.cmd"
exited with code 2. 
[E:\Depot\GitHub\orleans\src\TesterInternal\TesterInternal.csproj]
```

**Comment by jthelin** [comment]
The choco build problem is fixed by 7636520d47d184fcfab06e9f5f44cd7b08f2d765

**Comment by ca-ta** [comment]
Cool - thank you Jorgen!

**Pull request merged**
