### PR TITLE
PubSubRendezvousGrain: clear empty state on activation (follow-up to #336)

### PR DESCRIPTION
**Pull request by ca-ta**
Small addition to #336 - missed the case where the grain can end up with no producers or consumers during activation.

Did not add a call to ```DeactivateOnIdle()```, as the reasons for the grain being activated may include adding consumers/producers.

### CODE REVIEW

**Comment by gabikliot** [comment]
@ca-ta , is this the fix for #378?

**Comment by ca-ta** [comment]
No, I wish... I don't know yet how to fix #379 - I could use some help on that one.

It's unrelated - just something I've noticed  could be improved, related to #336.
________________________________

**Comment by gabikliot** [comment]
I will be looking into #378 tomorrow.

As for this PR, will hold it until we investigate #378.

**Comment by ca-ta** [comment]
Thanks - and yes, this can definitely wait.

**Comment by ca-ta** [comment]
Closing this for now, will re-issue after #378 is addressed

**Pull request closed without merging**
