### PR TITLE
Update changelog for 1.5.1

### PR DESCRIPTION
**Pull request by jdom**
After this is merged, I'll update in master also

### CODE REVIEW

**Comment by benjaminpetit** [comment]
LGTM

**Comment by ReubenBond** [comment]
LGTM. Do we need a known issue for DI 2.0?

**Comment by jdom** [comment]
I'm not sure we understand it exactly. If the issue is just with the BuildServiceProvider part, then there is a workaround, which is to provide your own Startup type, and explicitly use the 2.0.0 BuildServiceProvider method.

**Comment by xiazen** [comment]
should #3348 be included also?

**Comment by jdom** [comment]
Added (actually #3344 targets the 1.5.1 branch). Thanks.

I'll add a known issue regarding DI 2.0.0 in the release itself, not the changelog anyway

**Pull request merged**
