### PR TITLE
Migrate from packages.config to project.json

### PR DESCRIPTION
**Pull request by jdom**
This migrates our usage of packages.config (and all references in .csproj) to the new nuget transitive restore approach that uses project.json. Project.json itself might be renamed by Nuget in the future, given that dotnet is no longer moving away from MSBuild, but still the approach will remain the same.
This requires NuGet 3.0 to be installed to develop Orleans itself, but it's not a requirement for users of Orleans. Users will not notice any difference, it's just a productivity boost for Orleans developers, and prepares us to do work on .NET Core (this PR does NOT do cross compiling though, it only changes how nuget packages are restored).

Some notes:
- Test FSharp projects were not migrated to project.json, as I couldn't make them work with it.
- OrleansVSTools was not migrated either, as the tooling was not finding the nuget packages... might be doable but I was not able to in a reasonable amount of time.
- Samples were not migrated (by design). We want to still support Visual Studio 2013 with older version of NuGet, so we consider these as usage of Orleans itself, which still supports the old way of referencing nuget packages.

### CODE REVIEW

**Comment by jdom** [comment]
@dotnet-bot retest Windows Debug and Release please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_orleans/job/innerloop_prtest/1397/
// Retest reason: not failing locally

**Comment by jthelin** [comment]
FYI 
https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/

**Comment by jdom** [comment]
Thanks @jthelin, we are aware project.json is going away as a project file, but the NuGet tooling will remain (potentially be renamed to packages.json, and only keep the `dependencies` section).
NuGet was already released as stable/official, not bundled with the RC2 tooling.
This PR only moves the nuget dependencies, but is not leveraging project.json for anything other than NuGet, and it's still using `.csproj`.
You can see/watch this: http://www.talkingdotnet.com/news-project-json-asp-net-core-going-away/
> Project.json may stay or get renamed as it will be still having nuget package dependencies.

**Comment by jdom** [comment]
@dotnet-bot retest Windows Debug and Release please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_orleans/job/innerloop_prtest/1399/
// Retest reason: not failing locally

**Comment by jdom** [comment]
Since this is going to be changing very soon (once CoreCLR RTMs), I'm not investing any time to fixing the CI server right now. Closing and will reopen afterwards

**Comment by jdom** [comment]
Reopening since the new tooling is still very far out after RTM and also they promised that once the final tooling is released, it will update whatever is using the preview tooling.
Since we want to start the .NET core work, having the NuGet packages already using project.json will make it a lot easier to diff between the branches

**Comment by benjaminpetit** [comment]
Looks good to me!

**Pull request merged**
