### PR TITLE
Revert #1604

### PR DESCRIPTION
**Pull request by sergeybykov**
Reverting #1604 per https://github.com/dotnet/orleans/issues/1624.

I opened https://github.com/dotnet/orleans/issues/1655 and https://github.com/dotnet/orleans/issues/1656 for the failing tests that I skipped here.

@dVakulen What I don't understand yet is why contrary to what you said in https://github.com/dotnet/orleans/pull/1625 `Generic_CastGenericInterfaceToNonGenericInterfaceBeforeActivation` is still failing - https://github.com/dotnet/orleans/issues/1656. Did I miss something?

### CODE REVIEW

**Comment by dVakulen** [comment]
@sergeybykov The original test that i've submitted wasn't unskipped -  https://github.com/dotnet/orleans/blob/master/test/Tester/ProviderTests.cs#L80, but now it will pass.
As for https://github.com/dotnet/orleans/issues/1656 - this is actually my fault - I haven't reviewed thoroughly enough commit from @jasonholloway in which those tests were added to https://github.com/dotnet/orleans/pull/1625/commits. Even though it'll be good to at least throw more meaningfull exception - the original case that I tested, but haven't submitted is different kind of cast. In failing `Generic_CastGenericInterfaceToNonGenericInterfaceBeforeActivation` test grain impements 2 grain interfaces at the same time - https://github.com/dotnet/orleans/pull/1625/commits/25a1b5c89baf4c0dcfcb3a7b9c74c26c1e1fc471#diff-0b8e4c7041f12f0891823f612560c2ecR640 thus it will fail even without casting if one will try to get non generic grain reference like that : `var grain = GrainFactory.GetGrain<INonGenericCastGrain>(Guid.NewGuid());   
var result = await grain.Hello();`, but I meant downcasting\upcasting, e.g. `IGenericGrain<string> : INonGenericGrain` - for this case upcast from instance of type `IGenericGrain<string>` and following call will succeed after revert.

**Comment by sergeybykov** [comment]
@dVakulen Thanks. I unskipped `Providers_ActivateNonGenericExtensionOfGenericInterface`.

You are right - those tests should fail even without casting. Yes, those additional tests will help.

**Comment by jdom** [comment]
@sergeybykov Please squash all the "Revert XXX" commits into a single commit `Revert "Generic reference casting #1604"`.

Otherwise I can just squash the entire commit into 1 when merging, but I'd prefer the former. Let's not have a revert span multiple commits.

**Comment by sergeybykov** [comment]
@jdom Squashed.

**Comment by jasonholloway** [comment]
Wait, wait, I don't understand why the test *should* fail - is it that a concrete grain type isn't allowed to implement multiple grain interfaces? And therefore casts can only be done within the interface hierarchy?

I agree that ``var grain = GrainFactory.GetGrain<INonGenericCastGrain>(Guid.NewGuid())`` *should* fail (in a nice manner), but this is a completely different situation from casting to ``INonGenericCastGrain`` from an established reference, isn't it?

These are genuine questions - I'm confused.

**Comment by sergeybykov** [comment]
@jasonholloway A grain class can implement multiple grain interfaces. However, it the grain class is generic but gets activated by a call to a non-generic interface, the runtime doesn't have type arguments to instantiate the grain object.

I suspect part of the confusion here is because until the grain is invoked in those tests by a call made to its `Hello()` method, it doesn't get activated. `GetGrain()` and `AsReference<T>` are local operations that do not cause activation of the target grain.

**Comment by jdom** [comment]
Also, have in mind that even if a grain implements 2 different interfaces, a client reference is and should be unaware of this. If you want to have a reference that implements the 2 interfaces, then create another interface that implements the 2, otherwise they are not interchangeable. At runtime you might be getting a reference to a grain that implements only 1 of the interfaces. The client shouldn't make any assumptions, and should consider them as 2 different references regardless of how the grain is actually implemented.

**Comment by gabikliot** [comment]
> However, it the grain class is generic but gets activated by a call to a non-generic interface, the runtime doesn't have type arguments to instantiate the grain object.

@sergeybykov , based on my analysis in the https://github.com/dotnet/orleans/issues/1624#issuecomment-204841469 I think such grain reference should not be allowed to be created (and of course actual grain not activated). It should throw on attempt to create the grain ref. This is what I called "half baked" GR.
This is like if I asked to allocate List<?> without specifying T. It is not allowed in C#.

**Comment by gabikliot** [comment]
@jdom, you got me very confused with what you wrote above. It may be correct or not, but do please read what I wrote in https://github.com/dotnet/orleans/issues/1624#issuecomment-204841469.
1) Lets be consistent in what we are telling customers.
2) Lets agree of what SHOULD be, and what is the current imperfect state of our generics support. These are not the same.
3) Better to use concrete short code samples as example of what is allowed and what not, otherwise I personally find it super confusing.

**Comment by jasonholloway** [comment]
My opinion on this has completely flipped, to the point that I can't think of any legitimate use for ``IGrain.Cast<>()`` at all - the only allowable casting on a virtual grain should be upcasting, and CLR polymorphism handles this automatically anyway, without any recreating of ``GrainReference``.

The only complication to this is when an abstract grain is a gatekeeper to another - which is very common in a network of actors, obviously - and its concrete implementation wants to masquerade as the one it abstractly links to.

As so:
```csharp
class LakeGrain : ILakeGrain, IRemoteBag<Fish> 
{
    Task<IRemoteBag<Fish>> ILakeGrain.Fish() => this.AsReference<IRemoteBag<Fish>>();

    //etc...
}
```

**Comment by sergeybykov** [comment]
I think there is a legitimate case that is encoded in `Generic_CastGenericInterfaceToNonGenericInterfaceBeforeActivation()`.

```csharp
var grain = GrainFactory.GetGrain<IGenericCastableGrain<string>>(Guid.NewGuid());
var castRef = grain.AsReference<INonGenericCastGrain>();
var result = await castRef.Hello();
```

Reference `grain` is created with a type argument of `string`. If we preserve the argument when we cast the reference to `INonGenericCastGrain`, then calls to the grain via `castRef` would succeed whether or not the grain is already activated at the time of the call.

I think `AsReference<T>` has to check compatibility of the interfaces and their type arguments. Since a grain reference includes a type code that uniquely identifies the grain class, we can check if the class is generic, and now many type arguments it requires for instantiation. That would allow to throw with a proper error message in case of an attempt of an illegal cast.

**Comment by gabikliot** [comment]
Exactly Sergey. I wrote that case exactly in my summary comment. I called it down cast. It should preserve the original generic arg.
Basically, the type system of grain references must work totally unrelated to what was activated.

Did you read my earlier comment about that?

**Comment by sergeybykov** [comment]
@gabikliot I did. I was replying to @jasonholloway comment before mine.
>I can't think of any legitimate use for  IGrain.Cast<>()  at all - the only allowable casting on a virtual grain should be upcasting, and CLR polymorphism handles this automatically anyway, without any recreating of  GrainReference .

I should have stated it explicitly.

**Comment by gabikliot** [comment]
OK, cool. So we in agreement that grain reference should always have all the type info (of the actual implementation grain type), and be always valid, unrelated to activations?

**Comment by sergeybykov** [comment]
@gabikliot Yes, that's I think the semantics we want.

**Pull request merged**
