### PR TITLE
categorize tests for extentions into its own project

### PR DESCRIPTION
**Pull request by xiazen**
-add GoogleUtils.Tests
-add BondUtils.Tests
-add ServiceBus.Tests
-add PSUtils.Tests
-add AWSUtils.Tests

### CODE REVIEW

**Comment by galvesribeiro** [comment]
Thank you @xiazen! Was to do that for AWSUtils and PSUtils so I can add them to vNext solution as well.

Will wait this PR get merged to add them there. Great work! 👍

**Comment by xiazen** [comment]
if merge , plz squash two commits into one, discard the second commit

**Comment by ReubenBond** [comment]
Did this pass BVTs? I'm seeing some issues with Newtonsoft.Json in Protobuf & Bond, and some issues in PSUtils. I'm not sure if it's related, but it seems to be.

How can `ScriptCallTest` pass if the folder it lives in changed from `PSClientTests` to `PSClient`, [but the reference in that test still points to the old path](https://github.com/dotnet/orleans/pull/2578/files#diff-bf397b3e47c425c826754c537b53c196L78)? 

Are these tests maybe not being run in CI because of this change? (i.e, the ~Test.cmd files need updating)

**Comment by galvesribeiro** [comment]
PSUtils used to run as BVT, not sure about the rest.

**Comment by ReubenBond** [comment]
@galvesribeiro I'm saying that these tests were not run before this PR was merged because Test.cmd does not include the new projects:
```cmd
set TESTS=%OutDir%\Tester.dll,%OutDir%\TesterInternal.dll,%OutDir%\Orleans.NonSiloTests.dll,%OutDir%\Tester.AzureUtils.dll,%OutDir%\Tester.SQLUtils.dll,%OutDir%\DefaultCluster.Tests.dll
```

**Comment by galvesribeiro** [comment]
OH, ok I got it.

**Comment by xiazen** [comment]
I totally forget to include that. thanks for the heads up @ReubenBond

**Pull request merged**
