### PR TITLE
Reduce usage of static GrainClient in test code

### PR DESCRIPTION
**Pull request by ReubenBond**
This changes many files, but the changes are quite simple: reduce the use of static `GrainClient` in test code.

This will help to make subsequent PRs along the same vein much easier to review.

* SerializationTestEnvironment moved from `Orleans` to `TestExtension`
* Less initialization in CounterControl: I tested it locally and it's not needed (done since SerializationTestEnvironment has moved and I didn't want to ref TestExtension)

This is a non-breaking change

### CODE REVIEW

**Comment by ReubenBond** [comment]
@dotnet-bot please test this

**Comment by ReubenBond** [comment]
@dotnet-bot test this please

**Comment by ReubenBond** [comment]
@dotnet-bot test this please

**Comment by ReubenBond** [comment]
:) BVTs are green, I'm running functionals in VSO.

**Comment by ReubenBond** [comment]
@dotnet-bot test this please

**Comment by ReubenBond** [comment]
@dotnet-bot test this please

**Comment by ReubenBond** [comment]
Functionals are green

**Comment by attilah** [comment]
Then it is LGTM. Keep 'em coming @ReubenBond!

**Pull request merged**
