### PR TITLE
Avoid sending cluster manifest to client if client already has the latest version

### LINKED ISSUE #8722: ClientClusterManifestProvider has serious performance problem,When there are multiple Silos and clients, it will cause network IO and CPU to increase by a multiple of the number of clients.
For example:
The cluster hava 3silos,3clients.

After the cluster is started, the CPU and network IO will rapidly increase, especially network IO, where the amount of data transmitted per second to ClusterManifest reaches 80MB.CPU is burdened by the network and also increases with it.

After analysis, we have identified the problem.

### PR DESCRIPTION
**Pull request by 453873**
Fixes #8722

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/orleans/pull/8728)

### CODE REVIEW

**Comment by 453873** [comment]
@dotnet-policy-service agree

**Comment by HermesNew** [comment]
Sorry, we found that there was a code omission when submitting the PR. We will submit another PR later.

`private ConcurrentDictionary<SiloAddress, MajorMinorVersion> siloAddressVersionMap = new ConcurrentDictionary<SiloAddress, MajorMinorVersion>();`

**Comment by 453873** [comment]
I find bug, every silo address need compare clusterManifest version

**Comment by HermesNew** [comment]
@ReubenBond There are two items that have not passed the test. Could you please check them?

**Comment by ReubenBond** [comment]
@HermesNew the current version in this PR should accomplish that - do you see issues with the implementation here?

**Comment by ReubenBond** [comment]
@HermesNew @453873, please take a look at the current version and let me know if you have any issues with it. I will merge and we can include it in the next set of releases (7.2.5 & 8.0.0)

**Comment by HermesNew** [comment]
@ReubenBond Sorry, I've been very busy these past few days. Tomorrow we will release a version ourselves to verify whether this issue has been resolved.

**Comment by ReubenBond** [comment]
No problem at all, thank you @HermesNew!

**Comment by ReubenBond** [comment]
@HermesNew We can backport this to the 7.x branch - usually, we would do that after merging the PR

**Review by ReubenBond — APPROVED** [review]

**Pull request merged**
