### PR TITLE
Orleans.Client.Hosting - client integration into .net core generic hosting and controller DI

### PR DESCRIPTION
**Pull request by rossbuggins**
With this on a IServiceCollection you can:

```
   services.AddOrleansClient(options =>
            {
                options.Gateways = new int[2] { 30000, 30001 };
            });
```

And then in any controller (or class using standard DI):

```
public  OrleansExampleController(
              IOrleansClientAccessor clientAccessor)
        {
            this.clientAccessor = clientAccessor;
            }
```

And then use the client:

```
this.clientAccessor.Client.GetGrain<MyGrain>()
```

### CODE REVIEW

**Comment by rossbuggins** [comment]
I realise the lifetime of the IHostedService isn't correct as they are transient now, not singleton
https://github.com/aspnet/Extensions/issues/553

**Comment by ReubenBond** [comment]
Thanks for the PR!

I'm not convinced we should be using static gateways here. Having a builder API would be preferable - similar to ASP.NET & the existing ISiloBuilder / IClientBuilder. Most users are not using static gateway

**Comment by rossbuggins** [comment]
That's quick code i just knocked up to give example of what I'm doing with it now - yes, agreed it totally needs a builder API

**Comment by lfzm** [comment]
Welcome to this  [Orleans.MultiClient](https://github.com/lfzm/Orleans.MultiClient), or can you embed it in Orleans

**Comment by rossbuggins** [comment]
Updated it to use the standard IClientBuilder and have multi client support

**Comment by jdom** [comment]
Hi @rossbuggins, did you check out this design/discussion already? #4744

**Comment by rossbuggins** [comment]
Hi @jdom, no I hadn't come across that. I'll have a re-read and think especially regarding having distinct client apps re DI etc.

FYI, how I'm using this at the moment is:


```
 services.AddOrleansHostedClient(hostedClientBuilder =>
            {
                hostedClientBuilder
                    .AddOrleansClient("MainClientOne", clientBuilder =>
                    {
                        clientBuilder.UseLocalhostClustering(new int[1] { 30000 })
                        .Configure<ClusterOptions>(options =>
                        {
                            options.ClusterId = "dev";
                            options.ServiceId = "OrleansBasics";
                        })
                        .ConfigureLogging(logging => logging.AddConsole());
                    })
                    .AddOrleansClient("MainClientTwo", clientBuilder =>
                    {
                        clientBuilder.UseLocalhostClustering(new int[1] { 30001 })
                        .Configure<ClusterOptions>(options =>
                        {
                            options.ClusterId = "dev2";
                            options.ServiceId = "OrleansBasics2";
                        })
                        .ConfigureLogging(logging => logging.AddConsole());
                    });
            });
```

**Comment by ReubenBond** [comment]
Hi @rossbuggins, are you still pursuing this one? How does this & the [aforementioned Orleans.MultiClient](https://github.com/dotnet/orleans/pull/5760#issuecomment-512064969) relate? Should they become one thing?

**Comment by rossbuggins** [comment]
Hi, got a bit sidetracked with a few other things, will pick up again soon. Looking at multiclient, it’s the same idea - but looking at other posts there are some extra issues to bear in mind which I want to dig into

________________________________

**Comment by sergeybykov** [comment]
I'll close this for now due to inactivity as we are finalizing 3.0.0. Feel free to reopen/resubmit.

**Pull request closed without merging**
