### PR TITLE
Upgrade to dotnet 8 and bump Orleans version

### PR DESCRIPTION
**Pull request by benjaminpetit**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/orleans/pull/8666)

### CODE REVIEW

**Comment by ReubenBond** [comment]
Need to fix the CI build

**Comment by turowicz** [comment]
When release 🐵

**Comment by turowicz** [comment]
Also, is NativeAOT support planned for 8.x?

**Comment by turowicz** [comment]
is NativeAOT support planned for 8.x? @benjaminpetit @ReubenBond

**Comment by ReubenBond** [comment]
That depends on what you mean by NativeAOT support, but not explicitly. This would be worth opening an issue for to discuss and get expectations. Native AOT is rarely turn-key.

**Pull request merged**
