### PR TITLE
Repro for Issue #1447 - Code generator exits with error code 3 when struct contains a static variable

### PR DESCRIPTION
**Pull request by peter-perot**
I have created a repro test for issue #1447. By simply adding the struct `StructWithPublicStaticReadonlyNullableVariable` to the grain interface assembly `TestInternalGrainInterfaces.dll`, the test in `CodeGeneratorTests_KnownAssemblyAttribute` (`TesterInternal.dll`) fail.

Has anyone an idea where this issue comes from? Is it a Roslyn or an Orleans bug?

### CODE REVIEW

**Comment by dVakulen** [comment]
I think this is nether Orleans nor Roslyn bug, as such syntax causes cycle in the struct layout generally in .Net. (Struct can not contain field of struct's type)

**Comment by peter-perot** [comment]
@dVakulen: That is correct for an **instance** field, but here we have a **static** field. It's pretty common to define **static "default" properties or read-only variables** for the type itself. Evidence: It compiles and works. ;-) But code generation fails.

**Comment by dVakulen** [comment]
@peter-perot I couldn't manage to compile this even without Orleans.

**Comment by peter-perot** [comment]
Wow, that is strange.

The following program compiles und executes flawlessly:

````csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApplication1
{
	class Program
	{
		static void Main(string[] args)
		{
			var x = MyStruct.Empty;
		}

		public struct MyStruct
		{
			public static readonly MyStruct Empty = new MyStruct();
		}
	}
}
````

But now it's getting weird: This code compiles, but it throws a `TypeLoadException`:

````csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApplication1
{
	class Program
	{
		static void Main(string[] args)
		{
			var x = MyStruct.Empty;
		}

		public struct MyStruct
		{
			public static readonly MyStruct? Empty = null;
		}
	}
}
````

This is a compiler bug I think!

**Comment by peter-perot** [comment]
@dVakulen: Seems to be a compiler bug. VS 2013 issues an error during compilation, VS 2015 does not. I started a discussion here: http://stackoverflow.com/questions/36222117/maybe-a-c-sharp-compiler-bug-in-visual-studio-2015

**Comment by sergeybykov** [comment]
https://github.com/dotnet/orleans/issues/1447 will stay open to track the compile bug.

Thank you, @peter-perot, for digging into this!

**Pull request closed without merging**
