### PR TITLE
Replace bootstrap in Blazor app with MudBlazor

### PR DESCRIPTION
**Pull request by IEvangelist**
Rewrote the frontend for the Shopping Cart example.

Tagging @bradygaster and @Garderoben

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/orleans/pull/7698)

### CODE REVIEW

**Comment by Garderoben** [comment]
@IEvangelist really solid implementation of MudBlazor here, hands down.

I already pointed out the dark menu color but the only thing I personally would change myself is maybe rethink how you display the data. Every page is pretty much Table based but they are contained by MudContainers leaving much space out.

I made this real fast as a suggestion, nothing advanced, if it's something you would like i can send you a try.mud with my changes?
localhost_60983_shop

**Comment by IEvangelist** [comment]
> @IEvangelist really solid implementation of MudBlazor here, hands down.
> 
> I already pointed out the dark menu color but the only thing I personally would change myself is maybe rethink how you display the data. Every page is pretty much Table based but they are contained by MudContainers leaving much space out.
> 
> I made this real fast as a suggestion, nothing advanced, if it's something you would like i can send you a try.mud with my changes? localhost_60983_shop

This is awesome, thank you very much! Yes, please send over the try.mud! I will implement that way.

**Comment by Garderoben** [comment]
> > @IEvangelist really solid implementation of MudBlazor here, hands down.
> > I already pointed out the dark menu color but the only thing I personally would change myself is maybe rethink how you display the data. Every page is pretty much Table based but they are contained by MudContainers leaving much space out.
> > I made this real fast as a suggestion, nothing advanced, if it's something you would like i can send you a try.mud with my changes? localhost_60983_shop
> 
> Hi @Garderoben This is awesome, thank you very much! Yes, please send over the try.mud! I will implement that way.

Here you go, note that this will not actually compile/run on try.mud. I have an idea for the cart as well will get back to you with a proposal later.
https://try.mudblazor.com/snippet/wucmEemcBMHUzkKb

**Comment by Garderoben** [comment]
> Hi @Garderoben - I think we're getting close to finishing this. Do you have any more suggestions, you mentioned potential updates to the cart page?

i will send you my cart suggestion, in just a few hours, sorry for delay busy week.

**Comment by Garderoben** [comment]
> Hi @Garderoben - I think we're getting close to finishing this. Do you have any more suggestions, you mentioned potential updates to the cart page?

Sorry for delay again but here it goes, minor update to cart. Mainly new way of displaying everything.
image

Optional i got rid of the save button, and runs the save function on change on the numeric input. As well as a small dummy button for Checkout that automatically gets disabled if cart is empty

shopping_cart_flow
.

**Comment by Garderoben** [comment]
TrySnippet for above code, tell me if you want the raw files over email instead, i know Try.MudBlazor can sometimes make weird stuff with code formating.

https://try.mudblazor.com/snippet/QawQYScDiyMODhGo

**Comment by Garderoben** [comment]
> Awesome, thanks @Garderoben - much appreciated.

Anytime man, happy to help. I tried to hold back as much as i could to keep everything clean and simple enough for your actual samples.

**Pull request merged**
