### PR TITLE
Update to Microsoft.Extensions.Options 2.1.1 and remove duplicated classes

### PR DESCRIPTION
**Pull request by xiazen**
for #4703

### CODE REVIEW

**Comment by ReubenBond** [comment]
Did you fix those odd build issues you were running into with `dynamic`?

**Comment by xiazen** [comment]
@ReubenBond  yes! that was because I upgraded newtonjson package when it is not needed. I think the new newtonjson package 11.0.3 has some compatibility issue

**Comment by sergeybykov** [comment]
@dotnet-bot test functional

**Comment by ReubenBond** [comment]
@dotnet-bot test functional

**Pull request merged**
