### PR TITLE
[CoreCLR port] Type -> TypeInfo 

### PR DESCRIPTION
**Pull request by galvesribeiro**
Moved calls from Type -> TypeInfo to comply with CoreCLR API compatibility at #368

For now, just moved all calls made directly to Type.XXX to TypeInfo.XXX in order to be compatible with CoreCLR apis.

The idea was to keep current Orleans code as is, and only change what is necessary. Later on, I'll create another PR (after coreclr is fully supported on Orleans) and change all APIs that uses Type to use TypeInfo since everything from Type can be accessible from TypeInfo members. (refactor task)

Feedback is always welcome.

### CODE REVIEW

**Comment by gabikliot** [comment]
I would recommend breaking this PR into a number of smaller, logically isolated,3-4 PRs. Having such a big PR greatly reduces its chances to be merged: much harder to review, if there is a perf. issue much harder to point where (I cant even look at it via browser, it gets stuck).=. 
Evidence: https://github.com/dotnet/orleans/pull/617 is open for quite a long time  now.

I like the slow but steady approach of @dVakulen.

Also please remove the updated API portability file. We should sure update it, but as a separate PR.
Thanks.

**Comment by gabikliot** [comment]
I provided a lot of context in https://github.com/dotnet/orleans/pull/617#issuecomment-122354233 about where this switch is safe and where we should be careful w.r.t perf. You may find it useful.

**Comment by galvesribeiro** [comment]
@gabikliot I understand your concerns... basically, if did right, it should not introduce any perf changes since TypeInfo inherits from Type so the calls are just must cosmetic. The intention from coreclr team with this inheritance was to make the reflection-based APIs easily portable on blind eye. Later one, Type will keep the "limited new scope" and everything else will be on TypeInfo and the inheritance could be safely removed without break anyone.

Also, I took care to read the other PR and all your comments. No typeInfo is generated under a loop or have unecessary GetTypeInfo() calls.

@sergeybykov mentioned earlier that he would run the functional/perf tests before merge anything got considered merged, so no rush on that.

This case was simple, more a typing work than anything and I tough it could be made on a single PR since in all changes, there was the object was the same everywhere.

Next PRs are more surgical and yes, will definitively make separated PRs, no worry.

Thanks for the feedback, I hope to get coreCLR on board asap, it was kept on hold for so much, and its going to be released this month.

(Btw, review in browser sucks on GH as we discussed before...)

**Comment by gabikliot** [comment]
@galvesribeiro , did you see that: https://github.com/dotnet/orleans/pull/590#issuecomment-122142932?

**Comment by galvesribeiro** [comment]
Also, I believe an important change is to completely move from Type to use TypeInfo everywhere as I suggested as a later refactory task and that would be made with very caution...

**Comment by galvesribeiro** [comment]
Yes I saw it. That is why I stored in most of the places typeInfo whenever GetTypeInfo() is called more than once on the same path unlike that PR. 

Have a look here: https://github.com/dotnet/coreclr/blob/bc146608854d1db9cdbcc0b08029a87754e12b49/src/mscorlib/src/System/Reflection/IntrospectionExtensions.cs

Each IReflectableType has its own implementation so, if this will be throwing a performance problem, you will have on any Type.IsXXXX as well, since it is just intruspection for API portability and all them, inherits from Type (https://github.com/dotnet/coreclr/blob/bc146608854d1db9cdbcc0b08029a87754e12b49/src/mscorlib/src/System/Reflection/TypeInfo.cs).

Anyway, will do some tests here and will post the results here soon.

Thanks

**Comment by galvesribeiro** [comment]
Just made a simple loop calling Type.IsClass and TypeInfo.IsClass with the profiler running... Like I said, just introspection... Nothing changed... Look at the reports:
image
(Left Type, right TypeInfo)

For deep details look at detailed reports (can't update here since I don't have write access to the repo, ping me on gitter)...

**Comment by gabikliot** [comment]
Ok, no problem, @sergeybykov will be able to run a comprehensive test suite. If perf. stays the same, very good. Great work, thank you!

**Comment by sergeybykov** [comment]
I'll test this once @ReubenBond and I figure out what's currently breaking execution of the functional tests.

**Comment by sergeybykov** [comment]
We had a major power failure over the weekend in the container where our distributed and performance tests run. We can't perf test this at the moment, unfortunately.

**Comment by sergeybykov** [comment]
Thank you, @galvesribeiro!

**Comment by galvesribeiro** [comment]
THank you @sergeybykov ! As soon as I got the APM stuff done, will get back to CoreCLR again. Lets keep working! :)

**Comment by gabikliot** [comment]
No perf. impact @sergeybykov ? Great! Good progress on coreclr!

**Comment by galvesribeiro** [comment]
@gabikliot  can you please update the main issue crossing this one as done? Thanks

**Comment by gabikliot** [comment]
done already.

**Comment by galvesribeiro** [comment]
Thanks! ☺

**Comment by sergeybykov** [comment]
I rebased coreclr-compatibility branch against master, merged coreclr-compatibility to master, and pushed both.

> No perf. impact @sergeybykov ?

I didn't see any.

**Pull request merged**
