### PR TITLE
Minor documentation fixes

### PR DESCRIPTION
**Pull request by olivierdagenais**
Most of the fixes were converting `<T>` to `&lt;T&gt;` so the generic type references would be rendered as intended.

Alternatively, we could backtick quote all inline references such as type names, interface names, method names, keywords, etc. and then they don't need to be escaped if they contain angle brackets.  Let me know if you would like me to do that, instead.

Manual testing
--------------

1. Made my edits using MardownPad 2, which has a real-time preview pane, allowing me to verify my fixes.
2. Ran `jekyll build` and opened a few of the affected pages under `_site/` to confirm my fixes were applied the same way as in MarkdownPad 2.

Mission accomplished!

### CODE REVIEW

**Comment by akoeplinger** [comment]
> Alternatively, we could backtick quote all inline references such as type names, interface names, method names, keywords, etc. and then they don't need to be escaped if they contain angle brackets. 

:+1: on this, it reads much nicer both in the markdown source and the rendered page.

**Comment by olivierdagenais** [comment]
Still waiting for the e-mail from DocuSign.  In the meantime, I pushed b6e7a19bc57a9eca42c13f51d4bc875c8fe5e1da; let me know if that's cool and I'll do the other files, too.

**Comment by akoeplinger** [comment]
I think it looks great (but I'm just a community contributor, the Orleans team decides in the end :smile: )

**Comment by richorama** [comment]
nice one!

**Comment by jthelin** [comment]
Nice. :smile:

**Comment by olivierdagenais** [comment]
So, I assume b6e7a19 is good and I'm good to do the rest of the files that way??

**Comment by gabikliot** [comment]
Yes, I think backtick quote  is much better. Can you just please try to do all those changes in one big commit (or a small number of commits). Thank you.

**Pull request merged**
