### PR TITLE
Updated all nuspec to use new icon.

### PR DESCRIPTION
**Pull request by galvesribeiro**
Just update the nuspecs to use the new icons from #1989

### CODE REVIEW

**Comment by jdom** [comment]
Awesome! Could it be an issue that the new image is several times bigger than an icon? Did you check if NuGet's UI displays it correctly?

**Comment by galvesribeiro** [comment]
Just found out that that size don't work on nuget. @ReubenBond  already fixed that on #2002 so when it gets merged I'll update this PR.

**Comment by jdom** [comment]
Reuben's PR is merged

**Comment by galvesribeiro** [comment]
image

Now the icon is correct with the adjusted icon. :)

**Comment by galvesribeiro** [comment]
Thanks!

**Pull request merged**
