### PR TITLE
Object Disposed exception in networking layer.

### PR DESCRIPTION
**Pull request by jason-bragg**
Logging durring error handling in networking layer could request the enpoint from a disposed socket, causing silo to cycle.
We now store the enpoint in the connection context durring socket assignment and use that value for error logging.

### CODE REVIEW

**Comment by jason-bragg** [comment]
@dVakulen,
Can't seem to assign this to you, not sure why, but thought I'd tag you as you know this code better than most.

**Comment by jdom** [comment]
LGTM. This would definitely address this issue in particular, that was aborting the test run abruptly:
```
2016-10-14T18:32:32.8500905Z System.ObjectDisposedException: Cannot access a disposed object.
2016-10-14T18:32:32.8500905Z Object name: 'System.Net.Sockets.Socket'.
2016-10-14T18:32:32.8500905Z    at System.Net.Sockets.Socket.get_RemoteEndPoint()
2016-10-14T18:32:32.8500905Z    at Orleans.Runtime.Messaging.IncomingMessageAcceptor.StartReceiveAsync(Socket sock, SocketAsyncEventArgs readEventArgs, IncomingMessageAcceptor ima) in D:\build\_work\3\s\src\OrleansRuntime\Messaging\IncomingMessageAcceptor.cs:line 387
2016-10-14T18:32:32.8500905Z    at Orleans.Runtime.Messaging.IncomingMessageAcceptor.ProcessReceive(SocketAsyncEventArgs e) in D:\build\_work\3\s\src\OrleansRuntime\Messaging\IncomingMessageAcceptor.cs:line 489
2016-10-14T18:32:32.8500905Z    at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
2016-10-14T18:32:32.8500905Z    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
2016-10-14T18:32:32.8500905Z    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
2016-10-14T18:32:32.8500905Z    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
2016-10-14T18:32:32.8500905Z    at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
2016-10-14T18:32:32.8500905Z    at System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
2016-10-14T18:32:32.8500905Z    at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

**Comment by dVakulen** [comment]
LGTM. You can assign issues only to ones who are marked as contributors.

**Comment by gabikliot** [comment]
I can swear for 100% that I fixed that bug in the past. It was probably re-introduced in one of the later refactorings.

**Pull request merged**
