### PR TITLE
Fallback to ILBasedSerializer when BinaryFormatter is disabled

### PR DESCRIPTION
**Pull request by ReubenBond**
Fix for #7028 & #6805.
Developers can enable BinaryFormatter on .NET 5.0+ using the workaround here: https://github.com/dotnet/orleans/issues/6805#issuecomment-717778302
Otherwise, ILBasedSerializer will be used as the fallback on .NET 5.0+

### CODE REVIEW

**Comment by turowicz** [comment]
@ReubenBond which formatter should we prefer? The unsafe one?

**Comment by ReubenBond** [comment]
I would stick with what works for now. They are only used as a fallback, eg for exceptions.

**Comment by SebastianStehle** [comment]
What is the long term plan here?

I thought ILBasedSerializer has been marked as obsolete and a new serializer has been developed a while ago but is not stable?

And how do these serializers with exceptions that have custom properties?

**Comment by ReubenBond** [comment]
@SebastianStehle yes, it was a roller coaster: `ILBasedSerializer` was developed in response to `BinaryFormatter`'s removal from early .NET Core versions (1.0?). It was eventually marked `[Obsolete]` when the .NET team reversed that decision, since we didn't want another serializer just for the sake of it. `BinaryFomatter` was selected as the default. Now that `BinaryFormatter` has actually been disabled for .NET 5.0 and above, we are to `ILBasedSerializer` where necessary. We should probably remove the `[Obsolete]` attribute from it, since it's really the only option for Orleans 3.x on .NET 5.0 without explicitly opting-in to allowing it.

The long term plan is already in-place in main:
* A new, version-tolerant serializer has been added, which supports exceptions with a fallback exception type
* `ILBasedSerialier` is entirely removed
* All other serializers are entirely removed
* (in-progress) Grain persistence supports per-provider configurable serializers

We will likely need some options for developers who are serializing grain state using the current serialization framework, at some point. 4.x is not wire-compatible with 3.x, so rolling upgrades are not supported between those major versions.

**Comment by SebastianStehle** [comment]
Thanks a lot of your good explanation.

**Pull request merged**
