### PR TITLE
Check to see if stream batches should be delivered even if no filter is provided.

### PR DESCRIPTION
**Pull request by jason-bragg**
We were only checking to see if the batch should be delivered if there was a filter specified.  Batch can now be filtered even if no filter is applied.

### CODE REVIEW

**Comment by gabikliot** [comment]
Default always true filter instead of null check to do the same? Why?

Also, your explanation reads very weirdly, doesn't makes sense (the code does, although I have the question above about its benefit, while the explanation does not).

**Comment by jason-bragg** [comment]
@gabikliot "Default always true filter instead of null check to do the same? Why?"
They were not exactly the same.  With null filter, we don't even call the batch's ShouldDeliver, so the batch has no opportunity to determine if it should be delivered or not.  By providing a default filter, the batch always get's a say in whether it is delivered or not.

Description updated.  Hope it's more clear now.

**Comment by gabikliot** [comment]
What batch?
`public bool ShouldReceive(IStreamIdentity stream, object filterData, object item)` has no batch in the signature.

"Specifying protocols via interfaces".

The default filter does not give neither the batch nor the object item  "the final say in whether it is delivered or not". I don't understand.

**Comment by jason-bragg** [comment]
@gabikliot Please examine lines 486-501 in PersistentStreamPullingAgent.cs (in PR).  These lines were unchanged.  The filter is passed to the batch, and batch is authoritative on whether it is delivered.  However, this was only done if a filter was provided.  By providing a default filter, the batch now always determines if it is delivered, even if a filter is not provided by the subscriber.

**Comment by gabikliot** [comment]
:+1:  Thanks for clarifying.

**Pull request merged**
