### PR TITLE
Removed filtering from streaming infrastructure

### PR DESCRIPTION
**Pull request by benjaminpetit**
Replace #5408

### CODE REVIEW

**Comment by cata** [comment]
Please see [this comment](https://github.com/dotnet/orleans/pull/5408#issuecomment-528568705) and #5939, which is still open.
Can you please share more information as to what the plan is regarding the above?

**Comment by benjaminpetit** [comment]
For now: no defined plan, except cleaning.

We want first to have clean, reliable, and consistent API across all providers. This current implementation of stream filtering does not satisfy these requirements.

But we are open to suggestion and PR! I've read your issue; we can chat a bit and see what we can do.

**Comment by ReubenBond** [comment]
One conflict

**Comment by benjaminpetit** [comment]
Rebased

**Pull request merged**
