### PR TITLE
Run .NET Standard tests in CI

### PR DESCRIPTION
**Pull request by jdom**
Added scripts to run vNext tests from command line
Created an additional build in Jenkins to run .NET Standard tests

### CODE REVIEW

**Comment by jdom** [comment]
@dotnet-bot test ci please

**Comment by ReubenBond** [comment]
So we will now have two builds for every PR so that we can see Full .NET vs .NET Standard?
LGTM. 

The label here is a bit messed up:
image

**Comment by jdom** [comment]
yes, we will have 2, and those are not the names... this is a meta PR, I'm testing changes to Jenkins at the same time, so it looks weird. Please do not merge yet as I'm playing with Jenkins still

**Comment by ReubenBond** [comment]
No probs, you're assigned to this so you can merge when you're happy with it

**Comment by jdom** [comment]
BTW, now the new builds kicked off. Those are the final names:
 - netstandard-win Windows Debug and Release
 - netfx Windows Debug and Release

**Comment by jdom** [comment]
LOL, I assigned myself because I needed to manually tweak things in Jenkins to make sure it runs correctly. That's done and it works well. It's ready to merge. There is currently a BVT failing in vNext... I think it makes sense to fix that one first and then merge, otherwise people will start to see that the new build in their PRs fail, and assume they broke it.

**Comment by galvesribeiro** [comment]
image

Is that correct? To me appear 4 builds.

**Comment by jdom** [comment]
Yes, as I mentioned there is some weirdness because this is a meta PR that affects how PRs would build. We will have only 2 builds later

**Pull request merged**
