### PR TITLE
Fix race condition on cancelling of gcts

### PR DESCRIPTION
**Pull request by dVakulen**
A *bit* late fix for https://github.com/dotnet/orleans/issues/1891/ 

Description of the fix can be found in comment at https://github.com/dotnet/orleans/pull/3168/files#diff-ad4d2634c223caffc7ddb1eddec5ca43R95

### CODE REVIEW

**Comment by dVakulen** [comment]
The test failures is unrelated to PR changes.

**Comment by ReubenBond** [comment]
@dotnet-bot test netfx-functional netstandard-win-functional

**Comment by ReubenBond** [comment]
@dotnet-bot test netstandard-win-functional

**Comment by dVakulen** [comment]
@dotnet-bot test netstandard-win-functional

**Comment by dVakulen** [comment]
@dotnet-bot test netstandard-win-functional

**Comment by jdom** [comment]
@dotnet-bot test netstandard-win-functional
Reason: unrelated failure

**Comment by jdom** [comment]
@dotnet-bot test netstandard-win-functional
Reason: unrelated failure. It should have been solved now by a PR we just merged

**Comment by sergeybykov** [comment]
Thank you, @dVakulen!

**Pull request merged**
