### PR TITLE
Refactor testing host infrastructure

### PR DESCRIPTION
**Pull request by jdom**
Basically I created a parallel implementation of `TestingSiloHost` (called `TestCluster`), since the changes would be breaking a lot of users otherwise. 
`TestingSiloHost` will be obsoleted in the future (but not yet in 1.2.0), and we will recommend using the new implementation from now on

This new infrastructure focuses heavily on programmatic configuration of the cluster and client (although you can still explicitly load an XML config if you want to, but programmatic is encouraged in real deployment, and it makes even more sense in unit tests).
The main goal of this new public testing host infrastructure is to be used by Orleans application developers. Making it usable to test every internal detail of the Orleans core itself is a non-goal, and will only be supported if it doesn't make the main goal more complex and less usable by app developers.

I'm just migrating the `Tester` project, but not all of the tests in `TesterInternal` for this PR.Currently ALL tests in Tester have been migrated and are passing in the new infrastructure.

### CODE REVIEW

**Comment by veikkoeeva** [comment]
I see this is a start on a journey and the purpose is on testing and programmatic configuration of the silos and the client. I’d like to share some observations and ideas related to this refactoring and how maybe to remove code and unify configuration and hosting, thus making the code simpler: less to study and to maintain.

#### Some observations

1. OrleansTestHost uses [TestHostOptions](https://github.com/dotnet/orleans/pull/1643/files#diff-1363e89e8e5295605284ab1b06f7cfe4R14) to arrange a testing configuration.
2. [OrleansTestHost](https://github.com/dotnet/orleans/pull/1643/files#diff-06e5fd54f02afffcdaf6a5385df89801R70) is wired to use `TestHostOptions` and this cannot be changed without refactoring.
3. In addition to `OrleansHost` and `TestHostOptions` being wired together, the concept of [deployment configuration](http://dotnet.github.io/orleans/Orleans-Configuration-Guide/Typical-Configurations) is implicitly assumed to be that of *local development*. For instance, it looks like currently it is not possible to test in *reliable configuration*.
4. As the aforementioned use [SiloHost]( https://github.com/dotnet/orleans/pull/1643/files#diff-06e5fd54f02afffcdaf6a5385df89801R28) both *3.* and *4.* could be separated with little work.

This is how things have been and this refactoring seeks to clarify the current situation and provide some improvements. It looks to me one way to further improve the situation would be to further separate the concerns of silo, cluster of silos and the configuration of them. It looks like to me this could be achieved with small rearrangements and at the same time opening further refactoring possibilities.

#### To consider, to synchronize view points

We could separate the concept of *cluster manager* from `OrleansTestHost`. For that we would need to introduce the concept of `SiloHost` or `SiloProxy` that would do what [LoadSiloInNewAppDomain](https://github.com/dotnet/orleans/pull/1643/files#diff-06e5fd54f02afffcdaf6a5385df89801R622) does  with the Silo and Assembly. Instead of returning one separately and storing the other to a member variable (maybe a smallest refactoring would be return a pair, tuple, and let the caller handle both of the values), we could introduce an interface `ISiloHost: IDisposable` or `ISiloProxy: IDisposable` with members `SiloType SiloType { get; set; }` and `string SiloName { get; set; }`, `Task StartAsync()` and implement it in a concrete type of `InProcessHost: ISiloHost`, which would wrap both the ` Orleans.Runtime.Silo` and `AppDomain`. The purpose of this wrapper is either to store some silo information or know the details how to communicate with the `Silo` instance regardless of how it is hosted. It could be in a separate `AppDomain` and in the current process, or in a separate process, or maybe a Docker or a Hyper-V container. An added benefit here would be that `OrleansTestHost` would not need to [explicitly have the concept of primary silo]( https://github.com/dotnet/orleans/pull/1643/files#diff-06e5fd54f02afffcdaf6a5385df89801R28), but it could query the list of silos it manages if any of them is a primary one. Consequently, one could also run tests in a reliable configuration locally or use the same code to host in reliable mode in a console program.

For this to function in the general case, we would need to have a builder that knows how to validate a given configuration and how to create valid new silos from the configuration. For instance, if using the just sketched `InProcessHost` instances the builder should know that the same port cannot be reused due to a port conflict. For that we could introduce an interface `IClusterManager: IDisposable { ClusterConfiguration Configuration { get; set; } }` with members `Task AddSilo(string name)`, `Task StopSilo(string name)`, `Task RemoveAllSilos()` and whatever would be useful. Internally this manager would use the configuration given to it as a template to create new silos with the parameters given explicitly as parameters to the respective functions. Such a builder in current implementation is, in some way [TestHostOptions](https://github.com/dotnet/orleans/pull/1643/files#diff-1363e89e8e5295605284ab1b06f7cfe4R14) in cooperation with `OrleansTestHost`.

I think what I propose in that is closer to current [SiloHandle](https://github.com/dotnet/orleans/blob/master/src/OrleansTestingHost/SiloHandle.cs) than to [SiloHost](https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/Silo/SiloHost.cs), which some specific implementations ([AzureSilo](https://github.com/dotnet/orleans/blob/master/src/OrleansAzureUtils/Hosting/AzureSilo.cs),  [WindowsServerHost](https://github.com/dotnet/orleans/blob/master/src/OrleansHost/WindowsServerHost.cs)) use. It feels it is a bit unclear now how to add new hosting options and how should one configure them. That is, if I look at [FileInfo parameter in SiloHost](https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/Silo/SiloHost.cs#L103) or having a function [ParseArguments](https://github.com/dotnet/orleans/blob/master/src/OrleansHost/WindowsServerHost.cs#L115) bundled in the host instead of taking a configuration object the look more purpose-built (and added studying and maintenance) than if the hosts would implement a common interface.

From this point of view and looking at the [Silo]( https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/Silo/Silo.cs#L143) constructor, in the future with this arrangement maybe it would be possible to give [IStartupBuilder]( https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/Silo/Silo.cs#L205) as a parameter from the outside and it could be used to configure the silo in any hosting environment. Locally this could mean refactoring steps such as grain assemblies are searched and loaded only once and then reused in each of the silos (without hooks or tricks). Or in some other configuration they could be loaded from a share account, over a network.

For instance with regards to assemblies, it looks like if there were an explicit `IAssemblyLoader`, of which one implantation could be [AssemblyLoader](https://github.com/dotnet/orleans/blob/master/src/Orleans/AssemblyLoader/AssemblyLoader.cs#L10). This loader could then, for instance, cache the loaded assemblies and give them when asked, load them from some (network) location or what would be the situation then. `Silo` could refresh the assemblies from this location according the `IAssemblyLoader` implementation. Thinking of hot updates, maybe one strategy would be a shared storage account and one implementation of `IAssemblyLoader` would load them from over a network location whereas in another one from a local file system.

**Comment by jdom** [comment]
Thanks @veikkoeeva for the suggestions.
> 1. OrleansTestHost uses TestHostOptions to arrange a testing configuration.
2. OrleansTestHost is wired to use TestHostOptions and this cannot be changed without refactoring.

That's not entirely true. OrleansTestHost uses ClusterConfiguration and ClientConfiguration to drive everything. I has an additional constructor that receives TestHostOptions, but you can use it without it. Nevertheless, I think it might be OK to reverse that dependency, and use the TestHostOptions to build an OrleansTestHost.

> 3. In addition to OrleansHost and TestHostOptions being wired together, the concept of deployment configuration is implicitly assumed to be that of local development. For instance, it looks like currently it is not possible to test in reliable configuration.

That is true, and it's aligned with the main goal, to be used in testing and local development. Local reliable configuration is not a goal nor would be advised for production use. Normally silos fail due to the machine it's running goes down or looses connectivity. It's really uncommon for a single silo process to crash (albeit not impossible). Also, currently Orleans assumes it's running fairly in isolation and that has most of it's CPU for itself, so it's very greedy about it (see comment [here](https://github.com/dotnet/orleans/pull/1202#issuecomment-176913777)). Sure, that can change in the future.

As we talked over private IM, we should consider deployment options like Docker or SF. Basically have the same prod deployment configuration but run it locally too. I think that would be a lot more closer to you prod deployment than what we can get here with a simple cluster manager, since the frontends, side services, etc, play a big role in having something that gives the developer the feel of the entire system. Also, you'd be running in a mature ecosystem with Docker, instead of hacking some AppDomain magic (which will not even work in core clr, that's why we'll have to hack a way of starting new processes that should be monitored so they are not left orphan).
I definitely feel running in dev the same way as in prod is a noble goal, but not constrained to Orleans only.
a fast an easy way to spin up a cluster of silos for unit tests (without worrying about the frontend, as these are unit tests) is very much a concern of Orleans core itself, hence this infrastructure in this PR.

But don't get me wrong, I do like the suggestion, I just don't see it collapsing 100% with this unit testing implmentation... but I am keeping it in mind from now on, to separate responsibilities that could be re-used.
As for accomplishing what you want, I would LOVE something being done and incorporated into Orleans. Maybe in the form of Docker/SF deployment scripts, that might take 5 minutes for a new developer to spin up a cluster and guide him in a way so that it emulates the prod deployment without much issues, including his other roles (frontends, other services, etc)

**Comment by veikkoeeva** [comment]
@jdom
> As we talked over private IM, we should consider deployment options like Docker or SF. Basically have the same prod deployment configuration but run it locally too. I think that would be a lot more closer to you prod deployment than what we can get here with a simple cluster manager, since the frontends, side services, etc, play a big role in having something that gives the developer the feel of the entire system. [...]
>
But don't get me wrong, I do like the suggestion, I just don't see it collapsing 100% with this unit testing implmentation... but I am keeping it in mind from now on, to separate responsibilities that could be re-used.

I won't get wrong, it was a good chat. :) Indeed the bigger picture it's also the other goals than "one-box deployment and development". It looks [Docker on Windows is maturing](https://blogs.msdn.microsoft.com/stevelasker/2016/02/18/f5-developing-in-docker-containers-version-0-10-of-docker-tools-for-visual-studio/), it might help with more complex deployments.

I have been looking at Nano VMs, like at [Run 350 Nano Server Virtual Machines on a Lenovo ThinkPad P50 with Hyper-V in Windows 10](http://mikefrobbins.com/2016/03/17/run-350-nano-server-virtual-machines-on-a-lenovo-thinkpad-p50-with-hyper-v-in-windows-10/). It looks likely one would run in VMs and not in containers in production, but this does require something like a Hyper-V manager on the dev machine (considering the xplat choice coming, it might not be a choice that one can easily rely on in the future).

**Comment by jdom** [comment]
BTW, I'm not convinced with the `OrleansTestHost` name. Should I rename to `TestClusterHost` and `ClusterHostOptions` (or `TestClusterHostOptions`)?
@sergeybykov any other suggestions?

**Comment by veikkoeeva** [comment]
I don't know which we I should reference, but https://github.com/dotnet/orleans/issues/1648. It looks to me that while maybe not an immediate concern, steps should be taken to suss out valid testing scenario and if it would be feasible to realize them without "test hooks". So, I could add to the long list using DI things like fault-injection when applicable.

**Comment by sergeybykov** [comment]
@jdom Can you rebase this?

**Comment by jdom** [comment]
Yup, I was already on it :) done

**Comment by sergeybykov** [comment]
Functional tests completed with a single seemingly unrelated failure. So I'll merge this.

**Pull request merged**
