### PR TITLE
Vsix dev test silo 1.0.6

### PR DESCRIPTION
**Pull request by jthelin**
Update VSIX templates to use Orleans v1.0.6 packages.

### CODE REVIEW

**Comment by jthelin** [comment]
This is follow-on TODO work item from #335

**Comment by gabikliot** [comment]
what do you mean by: "Remove Debug build configs - we only ever do Release build. "
We support Debug builds. Anyone can build the whole code in Debug. Our CI maybe builds only release, but we still want to support Debug, right?

**Comment by sergeybykov** [comment]
We didn't publish 1.0.6, only used it internally. If we need to reference NuGets higher than 1.0.5, then I think we better bump up Version.txt to 1.0.7 and reference 1.0.7.

**Comment by jthelin** [comment]
@gabikliot  This is for building the .vsix templates, not for the main code base.

**Comment by gabikliot** [comment]
Got it.

**Comment by jthelin** [comment]
@sergeybykov I'm confused - the Version.txt file in _this_ repo says 1.0.6

https://github.com/dotnet/orleans/blob/master/src/Build/Version.txt

**Comment by jthelin** [comment]
Smoking gun: 31ec56a6811ae8df8464b72e63afb1c202dfe077

;)

**Comment by sergeybykov** [comment]
No smoke, no gun here. Yes we bumped up Version.txt some time ago, but did not publish 1.0.6 NuGets on nugget.org. We only consumed them internally. To pick up a new build internally, we'll need to bump up Version.txt again - to 1.0.7. All I'm saying is let's do that now because we will not publish 1.0.6 in any case. We will publish 1.0.7 or higher.

**Comment by jthelin** [comment]
OK, so I should bump the build Version.txt to 1.0.7 and change the templates .vsix to use that version?

**Comment by jthelin** [comment]
@sergeybykov and I have talked about some additional ways that the Dev-Test experience can be further streamlined, but that will be longer term work item(s).

**Pull request merged**
