### PR TITLE
Fix SQL Server Metrics Update Queries

### PR DESCRIPTION
**Pull request by michaelahern**
The silo and client metrics update queries are missing where clauses to scope the update to the appropriate rows.

### CODE REVIEW

**Comment by sergeybykov** [comment]
Looks good to me. I wonder what @veikkoeeva and others think.

**Comment by michaelahern** [comment]
While we have a few others who are familiar with the SQL bits here, want to propose and get thoughts on another change. The MembershipReadAll view is the only table/view that is not prefixed with "Orleans", which can be confusing when the database also contains non-Orleans objects. Any thoughts if we rename this to OrleansMembershipReadAll, or just get rid of this view altogether?  Only two queries depend on this view today, and these could be easily updated to not rely on it.

**Comment by veikkoeeva** [comment]
This looks good. Renaming the view sounds good too, getting rid of works too. I think removing it wouldn't cause harm either as Orleans reads the queries from the DB upon startup and operates on query name, which points to table (/view) name, column names and types.

I suppose you are the same group with @amccool, so he can share other thoughts related to this too. Like that with using schemas, which are user dependent.

If you have time, please do share more thoughts on things like statistics logging. :)

Hmm, and I have also a half-made MySQL script in case someone needs it before I finish it.

**Comment by amccool** [comment]
@michaelahern that's almost it.

there are two "statement" for each query (the sql server 2000, then the other)
line: 522 and 1058 for the client
line: 590 and 1126 for the silo

**Comment by veikkoeeva** [comment]
@michaelahern Just learnt you aren't related, you happen to be on the case simulatenously. :)

**Comment by michaelahern** [comment]
@amccool Good catch, I should have noticed that..

@veikkoeeva I'll submit a separate PR to remove the MembershipReadAll view. I like the idea of an Orleans schema, but I'm also happy if all the objects are just prefixed with Orleans so I can easily spot and identify them. I haven't done much with the statistics logging yet -- I've just had it enabled to reference it during debugging. Will ping back any ideas once I have some time to take a closer look..

**Comment by sergeybykov** [comment]
Is this ready to be merged?

**Comment by michaelahern** [comment]
It's all set from my side after fixing the second set of queries @amccool noticed.

**Comment by sergeybykov** [comment]
Thank you, @michaelahern!

**Pull request merged**
