### PR TITLE
Added missing /Documentation/ to some broken links

### PR DESCRIPTION
**Pull request by galvesribeiro**
Related to #2117

### CODE REVIEW

**Comment by ReubenBond** [comment]
LGTM, thanks. By the way, are docs still going to gh-pages or are we going to use master?

**Comment by galvesribeiro** [comment]
@ReubenBond as far as I understood, it will be kept on gh-pages and later one when we have the docfx build process automated, it will be pushed to another repo like OrleansDocs or something.

**Comment by sergeybykov** [comment]
BTW, without rerunning DocFx, this change only went to the .md file, but not to the .html. It'll get picked up next time somebody runs DocFx. But it you want a change like this to appear in the docs immediately after the PR is merged, you need to run DocFx to update them.

**Comment by galvesribeiro** [comment]
Ahhh I though we needed merge rights @sergeybykov np. Will do it on next time. Thanks for the tip

**Comment by sergeybykov** [comment]
No big deal. It's more important to improve the 'sources' of the docs.

**Pull request merged**
