### PR TITLE
Turn off console logging on tests

### PR DESCRIPTION
**Pull request by xiazen**
Make `DefaultSiloBuilderFactory` to be just configured with a `FileLoggerProvider`. Orleans tests are just configured with a FileLoggerProvider also. 

If user want to turn on console logging on TestCluster, they can configure it through `ISiloBuilder` or `IClientBuilder` and `ISiloBuilderFactory`. Or they can turn on `TraceToConsole` in `TestClusterOptions`, if we bring this feature back using #3486

### CODE REVIEW

**Comment by xiazen** [comment]
yes I thinkthat's correct!

**Comment by xiazen** [comment]
will remove it .

**Comment by liyao0409** [comment]
How can i add console log now

**Comment by xiazen** [comment]
```
siloBuilder.ConfigureSiloName(siloName)
                .ConfigureApplicationParts(parts => parts.AddFromAppDomain())
                .UseConfiguration(clusterConfiguration)
                .ConfigureLogging(loggingBuilder => loggingBuilder.AddConsole()));
```

You can add `Microsoft.Extension.Logging.Console.ConsoleLoggerProvider`to `ILoggingBuilder` when you configure silo or client . Above is a code sample, hope this helps. `ConsoleLoggerProvider` is in `Microsoft.Extension.Logging.Console` nugget package

**Pull request merged**
