### PR TITLE
Move Relational Storage code into a separate assembly

### PR DESCRIPTION
**Pull request by dVakulen**
Addresses: #892

### CODE REVIEW

**Comment by veikkoeeva** [comment]
@dVakulen A few points I noticed.

* Overall it looks like a job well done. I didn't run the code, but looks good, down to namespaces and other things you spotted.

* Nuget package is still coming, I trust? :)

* While at it, please yank my comment `//Retrieving by ordinal is slightly (immeasurably?) faster. Perhaps something to refactor.`. It's not perhaps to refactor anymore since I commented in the SQL script already it's the names and types both for inbound and outbound data that counts.

* It would look better to have only the first letter in acronym ``SQL`` being capitalized. See more at [Capitalization Conventions](https://msdn.microsoft.com/en-us/library/ms229043(v=vs.110).aspx):
> The PascalCasing convention, used for all identifiers except parameter names, capitalizes the first character of each word (including acronyms over two letters in length), as shown in the following examples:
>
PropertyDescriptor
HtmlTag
>
A special case is made for two-letter acronyms in which both letters are capitalized, as shown in the following identifier:

* Capitalizing constants and putting underscores makes them more consistent with the current code, but then pushes the code further way from .NET conventions. There's on issue already open for doing a "R# Sweep" on the codebas to ".NETilize it". I don't think it matters much here, but maybe @sergeybykov, the resident Orleans guy, could share a thought of the larget picture.

And so we are riding smoothly. :+1:

**Comment by dVakulen** [comment]
@veikkoeeva Thank you for the review, one question about nuget package that is supposed to come - what should I do to make it happen?

**Comment by veikkoeeva** [comment]
@dVakulen I'm not sure. Maybe one way around is to take a peek at `src\Nuget\Microsoft.Orleans.OrleansAzureUtils.nuspec` and see what it has eaten. Maybe also run a text search on all the source folders to see where it is referenced and do the same with the SQL package. Running `Build.cmd` should build the code and Nuget packages, so that's one way of checking it works. From there on, I believe there's a script on the build server to whisk it off to Nuget.org (or maybe @sergeybykov does it by hand?).

**Comment by jthelin** [comment]
Any `.nuspec` files that are in the `src/NuGet\` directory will get processed automatically when the build runs.

You should see your new `.nuspec` gets processed when you run Build.cmd locally.

Posting to nuget.org will still require manual intervention, I believe? @sergeybykov can confirm.

**Comment by sergeybykov** [comment]
>Posting to nuget.org will still require manual intervention, I believe? @sergeybykov can confirm.

Yes, we do it manually (because of codesigning) for every official release.

**Comment by gabikliot** [comment]
Thank you Dmitry for pushing the coreclr port forward. Highly appreciated!

**Comment by veikkoeeva** [comment]
All good as far as my eye sees. :)

**Comment by sergeybykov** [comment]
Thank you, @dVakulen!

**Pull request merged**
