### PR TITLE
Migrated nuget package restore to use the new auto-restore approach

### LINKED ISSUE #478: Build.cmd fails on a clean environment without the Azure SDK pre installed
There is a bug in the nuget restore process of the build script, only restoring the orleans.csproj project. The Microsoft.WindowsAzure.ServiceRuntime dependency is missing from this project's packages.config file and so it is not installed.
Later, the code gen fails with
error CS0234: The type or namespace name 'ServiceRuntime' does not exist in the namespace 'Microsoft.WindowsAzure'
Which fails the build.

Looking at the CI build logs, the only reason it does not fail it due to the azure SDK being preinstalled on the build machine (assuming this is an Azure instance - it makes sense).

Possible quick fix is to add this dependency to the "orleans" project packages file.

A better long term solution would be to migrate the NuGet restore to it's new approach since the 2.7 Nuget version to avoid the problem in the first place. (restoring from all projects would have solved it)

### PR DESCRIPTION
**Pull request by yoadsn**
These are required by additional project which are not restored from the
build script.
Fixes #478

IMHO this is not the ultimate fix, there should be a change to the way nuget restore works for the build scripts. Avoid using the old approach which suffer problems during the build process such as presented in this case.

### CODE REVIEW

**Comment by jthelin** [comment]
> IMHO this is not the ultimate fix, there should be a change to the way nuget restore works for the build scripts. Avoid using the old approach which suffer problems during the build process such as presented in this case.

PR #481 should address the "ultimate fix" part, I think.

**Comment by yoadsn** [comment]
I have incorporates Jorgen's changes from #481 into #480 as well as another targets file in the solution folder whichi automatically handles packages restore and the download of the nuget exe as also described here http://www.cazzulino.com/ultimate-cross-platform-nuget-restore.html

**Comment by yoadsn** [comment]
Also changed the name of the PR to better reflect what is done.

**Comment by jthelin** [comment]
Looks good. Thanks @yoadsn 
I will close #481 and merge this instead.

**Comment by gabikliot** [comment]
Thank you Yoad for your contribution!

**Pull request merged**
