### PR TITLE
Optimization for TaskExtensions.Box

### PR DESCRIPTION
**Pull request by dVakulen**
Addresses #1074; implemented suggested by @ReubenBond  approach.

### CODE REVIEW

**Comment by sergeybykov** [comment]
I didn't see any noticeable perf gains in the load test, but seems like a good improvement anyway.

**Comment by gabikliot** [comment]
Not even in any of the Ping Load tests?

**Comment by sergeybykov** [comment]
Good point, I only ran Presence load test. In ping tests from last night I see ~3% throughput gain.

Good job, @ReubenBond & @dVakulen!

**Comment by gabikliot** [comment]
:+1: Good job!

**Pull request merged**
