### PR TITLE
Fix ordering in ASP.NET Co-hosting sample

### PR DESCRIPTION
**Pull request by ReubenBond**

### CODE REVIEW

**Comment by clement128** [comment]
hi @ReubenBond may I ask why change the ordering? thanks

**Comment by ReubenBond** [comment]
The silo needs to be started before accepting requests

**Comment by clement128** [comment]
@ReubenBond hmm that's interested, I used same ordering on production since few months ago, never encountered any error. it happen randomly?

**Comment by ReubenBond** [comment]
It can happen only during startup, for a brief period. If you don't receive traffic immediately, then it ought to be fine

**Comment by clement128** [comment]
thanks

**Pull request merged**
