### PR TITLE
Update Typical-Configurations.md

### PR DESCRIPTION
**Pull request by Cronan**
Added section on Reliable Production Deployment Using SQL Server (using programmatic configuration).

### CODE REVIEW

**Comment by sergeybykov** [comment]
The storage provider part can be confusing here because it is orthogonal to cluster membership configuration, and is not mentioned in other cases described on the page. I think we better take it out.

**Comment by sergeybykov** [comment]
Likewise, I think the whole logic of handling host name and address can be taken out, to leave the code to rely on the default behavior of silo when `HostNameOrIPAddress` isn't explicitly set. That will limit the scope of the example to what matters here.

**Comment by Cronan** [comment]
Thanks, good points, I'll make the changes. How do I set ProxyGatewayEndpoint programmatically without having an address?

**Comment by Cronan** [comment]
@sergeybykov Should I take out the logging stuff for the same reason as the storage provider part?

**Comment by sergeybykov** [comment]
Sorry, I wasn't clear. I think in this specific doc page we don't need to show how the IP address is obtained. We can just use the `address` variable without assigning a value to it:
```
ProxyGatewayEndpoint = new IPEndPoint(address, 30000);
```

**Comment by sergeybykov** [comment]
>Should I take out the logging stuff for the same reason as the storage provider part?

I think so.

**Comment by sergeybykov** [comment]
Thank you, @Cronan!

**Pull request merged**
