### PR TITLE
Orleans-RestorePackages

### PR DESCRIPTION
**Pull request by jthelin**
Orleans-RestorePackages

- Checked the NuGet restore settings by running the migrateToAutomaticPackageRestore.ps1 script, which found some projects with old style NuGet RestorePackages=True settings.

https://github.com/owen2/AutomaticPackageRestoreMigrationScript

- This is probably a more complete fix for issue #478

### CODE REVIEW

**Comment by jthelin** [comment]
Hmm. I need to look at this again, because CI build fails on server with this change set :(

**Comment by gabikliot** [comment]
Jorgen, it looks like your commit only removed some code, there is zero additions. Could that be the issue?

**Comment by yoadsn** [comment]
I agree with gabriel, although project files were cleared of the old restore targets and the nuget targets was removed there should be the added steps required to actually perform the restore.
Also, this will break src\Nuget\CreateOrleansPackages.bat which relies on the Nuget.exe to exist under the .nuget folder.
After the above changes the nuget.exe tools would not be auto downloaded onto that folder.

**Comment by yoadsn** [comment]
Jorgen, Please see again #480 which should go all the way, taking all your changes in and completing the migration to the new restore approach. HTH.

**Comment by jthelin** [comment]
Incorporated into #480 by @yoadsn

**Pull request merged**
