### PR TITLE
Update AzureWebSample to orleans 1.3.1

### PR DESCRIPTION
**Pull request by serbrech**
Part of #2359

### CODE REVIEW

**Comment by serbrech** [comment]
I'll still update the azure packages :)

**Comment by serbrech** [comment]
I tried to update the target framework to the latest (4.6.2), but then I got some other inconsitencies and well, it doesn't bring much.

**Comment by jdom** [comment]
You probably ran into issues with deploying to azure, as the previous family version did not support 4.6.2 out of the box. Fortunately, I see that the new OS family 5 does support it, finally! (from https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-guestos-update-matrix)
Nevertheless, I agree that there is no point in updating it to 4.6.2 anyway at this point...

**Comment by jdom** [comment]
For these, I think you can remove the `Orleans.Server` and `OrleansHost` package references from the silo project, since we are not really using the pre-built OrleansHost.exe (you can also remove the `appdir-placeholder.txt` file if it's there too).
The reason I noticed this, is from this other sample we are adding, which apparently was copied from AzureWebSample: https://github.com/sebastianburckhardt/orleans/pull/11

**Comment by jdom** [comment]
Thank you, @serbrech !

**Pull request merged**
