### PR TITLE
Removed header comments from all files.

### PR DESCRIPTION
**Pull request by attilah**

### CODE REVIEW

**Comment by jthelin** [comment]
What's the background to this change?

**Comment by attilah** [comment]
@sergeybykov agreed to remove the clutter. License.md and License.rtf is more than enough nowadays. 23 lines is half the screen on notebooks, when you open a file, and gives no information.

**Comment by sergeybykov** [comment]
From the legal perspective as I understand we are fine.

**Comment by jdom** [comment]
reviewed the diff that is shown in GitHub, and looks good. I think it's a nice statistical subset to claim that they are all probably good :P

**Pull request merged**
