### PR TITLE
Azure SDK plugin

### PR DESCRIPTION
**Pull request by richorama**
A plugin to the Azure SDK to make the deployment of Orleans super simple for Web/Worker roles.

To test, take the contents of `src\AzureSDKPlugin\bin\Debug` and copy to `C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.5\bin\plugins\Orleans`.

Then create a WorkerRole and reference the plugin in the `ServiceDefinition.csdef` file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<ServiceDefinition name="AzureCloudService4" xmlns="http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition" schemaVersion="2014-06.2.4">
  <WorkerRole name="WorkerRole1" vmsize="Small">
    <Imports>
      <Import moduleName="Orleans" />
    </Imports>
    <ConfigurationSettings>
    </ConfigurationSettings>
  </WorkerRole>
</ServiceDefinition>
```

The module will take care of the internal endpoints, local storage (not sure if this is actually required) and starting the silo.

It also exposes a `Microsoft.Orleans.DataConnectionString` setting which the user must enter.

Todo:

* Update the installer
* Update the documentation

### CODE REVIEW

**Comment by jthelin-microsoft** [comment]
I'm pretty sure that we would want to use the cut down OrleansConfiguration.xml contents from the AzureWebSample [which is currently being discussed in PR #144 ] rather than the local silo one in this change set. 

More realistically though, whatever copy is in this plugin should probably become the single "master" copy of the default silo config file for Azure silos, and we can add another ToDo item to switch AzureWebSample over to using this plug-in instead.

**Comment by richorama** [comment]
Sure. The plugin is designed to have a basic `OrleansConfiguration.xml` file which will work out of the box. The user can overwrite should they wish to include any customisations, such as storage providers.

**Comment by richorama** [comment]
I could do with some help with the installer, does anybody have any experience?

**Comment by veikkoeeva** [comment]
@richorama A long time ago I found the [WiX Toolset](https://wix.codeplex.com/) to be infinitely easier to deal with than just a plain MSI project. I even remember reading the Office team using it (I may remember wrong). Nothing much beyond that. If you have specfic questions, the best I can do is use some time on searching solutions.

**Comment by veikkoeeva** [comment]
@richorama @jthelin-microsoft Should we include a mention in the documentation that there's this new feature?

**Comment by sergeybykov** [comment]
@richorama You can also use https://github.com/dotnet/orleans/blob/master/src/Build/OrleansSetup.wixproj as a starting point for a WiX project.

I watched WiX growing over the years from an intern project by Rob Mensching to a popular internal tool to OSS. It's really good. Not at all because I contributed a tiny bit to it a long time ago. :-)

**Comment by richorama** [comment]
thanks, I'll seek WiX enlightenment

**Comment by richorama** [comment]
This seems to work now. What do we want to do with it? 

* Should this become the default way of running Orleans in Azure? (I think it needs a bit more testing first)
* Should a sample be created/edited?
* How do we want to reflect this in the documentation?
* Should we create templates for an `OrleansWorkerRole` and `OrleansWebRole` (these should be optional, as you may want a role to do multiple things) (not sure how to do this anyway)

**Comment by sergeybykov** [comment]
Let's give folks a few days to play with this and form opinions.

For example, now I have doubts about the installer. I suspect it will not work with an upgrade of the Azure SDK, e.g. to 2.6. Should we instead include a script for deploying the plug-in to a given (be default latest) version of Azure SDK? Such a script could be run multiple times, while the msi presumably will have to be uninstalled/re-installed for an Azure SDK upgrade.

**Comment by richorama** [comment]
Yes, the plugin has affinity to a particular Azure SDK version. But, doesn't Orleans effectively have the same affinity, given that the SDK releases normally ship with different Azure storage client library versions (among others) which are a shared dependency with Orleans?

**Comment by sergeybykov** [comment]
Orleans SDK does not require Azure SDK to be installed. It brings its dependencies on Azure binaries via NuGet, so it can be (after we fix the fixed versions issue) used with a future version of Azure SDK, at least in theory.

The change to OrleansSetup.wxs in the current form will make it blindly install files to the 2.5 directory whether or not the SDK is actually installed there or if a newer version of it is already installed. I'm thinking out loud if we need a) Orleans SDK msi to find the latest version of Azure SDK installed and install the plug-in to its folder; and/or b) have it include a script that would install the plug-in to the latest (default) or specified version of Azure SDK, so that one doesn't have to reinstall the Orleans SDK after a 2.6+ Azure SDK is installed.

Or am I overthinking this?

**Comment by veikkoeeva** [comment]
Maybe one option is to release this in some form and mark it as experimental. I'm thinking aloud here too as I haven't had time to check this. This looks like a useful addition.

In fact, I became to think already a bunch of PowerShell scripts to configure Hyper-V virtual switch (or anything OpenFlow compatible) on desktop to install "a development cluster" that would be similar on topology to an envinroment one, albeit on a same machine. With [DSC](http://blogs.technet.com/b/privatecloud/archive/2013/08/30/introducing-powershell-desired-state-configuration-dsc.aspx), [Chocolatey](https://chocolatey.org/)/[OneGet](http://blogs.technet.com/b/windowsserver/archive/2014/04/03/windows-management-framework-v5-preview.aspx), [MAML](http://www.jeff.wilcox.name/2014/04/wamlmaml/) and all the jazz.

**Comment by richorama** [comment]
@sergeybykov ah - ok - sorry, I'm still living in the past.

Perhaps the plugin should be a separate installer, which can then keep cadence with the Azure SDK.

And yes, you're right, the installer has a bug, and shouldn't install the plugin if the Azure SDK isn't there.

**Comment by sergeybykov** [comment]
@richorama My question is - do we even need an installer, especially in the msi form? Say I happened to have three versions of Azure SDK installed: 2.4, 2.5 and 2.6. If I installed the plug-in msi when I only had 2.4, do I need to uninstall it now, and reinstall for 2.5 or 2.6? In order to install side by side, we'd have to have three different msis with different product codes, which doesn't strike me as a scalable or manageable solution.

What if we instead had a script that would pop up a dialog asking to confirm installation to the highest found version of Azure SDK or to select one of the other installed version as the target? Orleans msi could launch this script or run it silently with the default. The same script could also be run later manually to install the plug-in to a future version of Azure SDK. Does this sound too crazy?

**Comment by jthelin** [comment]
Seems like the "installer" for this plugin would ideally be a repeatable tool / script that could be re-run when new Azure SDK version gets installed.

@richorama -- Is your AzurePluginManager tool something that could be used or modified to provide this functionality? https://github.com/richorama/APM/

Then the Orleans installer can just drop the plug-in binaries onto disk, and optionally offer to install them into the right Azure directory as a post-install action?

**Comment by richorama** [comment]
@jthelin yes, APM could indeed be used. One shortcoming it has, is it doesn't have any concept of versions on plugins (it handles the Azure SDK version) but you would probably need to have plugins called `Orleans1.0.1`, `Orleans1.0.2`  etc..., or just always install the latest

**Comment by jthelin** [comment]
@richorama -- Could you just clarify which OSS license terms the APM tool can be distributed under?

I could not see it mentioned in the GitHub repo. https://github.com/richorama/APM/

I'll also drop this link in here for posterity, because it is important background cross-reference ;)
http://richorama.github.io/2015/01/13/thoughts-on-deploying-orleans/

Thanks.

**Comment by richorama** [comment]
I have set it to MIT.

**Comment by jthelin** [comment]
I have pushed these changes from @richorama to a new "experimental" branch named '*experimental-AzurePluginHost*' so that we have them safely stored in the repo for reference and allowing Richard to go back to using his master branch again :)
https://github.com/dotnet/orleans/tree/experimental-AzurePluginHost

There are a few more tweaks and changes that we want and need to sort out before we can merge this change to 'master', and several other related discussions that are occurring at the moment on the overall direction for Azure hosting of Orleans, but at least this way others can start trying this Orleans Azure PlugIn out and give feedback.

**Comment by richorama** [comment]
@jthelin thanks!

To aid experimentation, I have added the Orleans plugin to my library.

If you have the [apm](https://github.com/richorama/APM) utility installed you can now get the plugin like this:

```
> apm install Orleans
```

**Comment by jthelin** [comment]
I will close this now, because we seem to be getting some later commits bleeding in to this feed.

Rest assured this topic is not forgotten :) and we have the experimental branch posted in Orleans central repo.

**Pull request closed without merging**
