### PR TITLE
New scalable protocol for Observers.

### PR DESCRIPTION
**Pull request by gabikliot**
Implementation of a new scalable protocol for Grain Observers.
No public API changes here yet.

### CODE REVIEW

**Comment by sergeybykov** [comment]
Can you squash all/most of the commits?

**Comment by gabikliot** [comment]
I don't think it's worth it. I have detailed messages on separate commits, that are actually useful if someone would to go later on to track the logic behind changes. There is maybe only one redundant commit, the last one. Don't think its worth it.

**Comment by jthelin** [comment]
If you click the "Files Changed" tab, then you can see the "combined" picture of the whole change together, which might be what @sergeybykov is wanting?

**Comment by sergeybykov** [comment]
No, I was just wondering if all the commits are really necessary. If yes, then that's fine.

**Pull request merged**
