### PR TITLE
Proposed fixes/changes for 1.3.1

### PR DESCRIPTION
**Pull request by sergeybykov**
I cherry-picked these commits from `master`. If you think we need more than that, please suggest.

### CODE REVIEW

**Comment by ReubenBond** [comment]
We should add these commits: https://github.com/dotnet/orleans/pull/2295/commits

**Comment by sergeybykov** [comment]
>We should add these commits: https://github.com/dotnet/orleans/pull/2295/commits

I added https://github.com/dotnet/orleans/pull/2295/commits/6fd80a1f4f8134ad278e057d8051484f5f5ce87a, https://github.com/dotnet/orleans/pull/2295/commits/92b6c6993f587a83f63c688f79a5e436be51080b, https://github.com/dotnet/orleans/pull/2295/commits/ead36ffa62ff4fb8e8ef691aeecf39f2974b84f3.

It looks like the change in https://github.com/dotnet/orleans/pull/2295/commits/8dfce841e3a92bec9c075451ee8a6181dfc9c895 was already subsumed by another change.

Please confirm.

**Comment by ReubenBond** [comment]
@sergeybykov yep, it looks like that bug isn't present in your 1.3.1 branch.

LGTM

**Comment by sergeybykov** [comment]
Added https://github.com/dotnet/orleans/pull/2350/commits/6d1ed08db6a5d1c732a3696fcdee118ffb389139.

**Comment by sergeybykov** [comment]
Added https://github.com/dotnet/orleans/pull/2350/commits/9c965fbf292f8ab3e1d21cafb7d6dc64381d252a.

@jdom, I think this one is ready to be merged, tested, and released.

**Pull request merged**
