### PR TITLE
codegen for IGrain interface inherited methods

### PR DESCRIPTION
**Pull request by shayhatsor**
this is a small change in code, but big on implications. IMHO this should be the default.

### CODE REVIEW

**Comment by shayhatsor** [comment]
well, I've just noticed that @kumbhare has a similar PR.

**Comment by jthelin** [comment]
/cc @kumbhare @shayhatsor 

It would definitely be a good idea (at the very least) to create a union of test cases from PR #515 and #512 to ensure we get really good coverage of some of the tricky corner cases, and of course validate each PR against the union set. 

A combined fix / solution that you guys agree on would be even better :)

**Comment by sergeybykov** [comment]
+1 :-)

**Comment by sergeybykov** [comment]
The change looks good to me.

**Comment by shayhatsor** [comment]
@jthelin :) No worries, It's all good. We'll work out the best solution.

**Comment by shayhatsor** [comment]
@jthelin, I've added tests similar to @kumbhare, I believe we have good coverage now.

**Comment by gabikliot** [comment]
I looked at both PRs: @kumbhare's #512 and @shayhatsor's #515. Both are solving the problem.
The actual code for the fix is a bit different.
#515 relies on asking `type.GetInterfaces();` from higher level grain type that implements IGrain and taking all interface methods.
#512 explicitly traverses the interfaces hierarchy recursively.
Both have very good test coverage.
#515 looks a bit simpler, so I think we will take it.
Thank you both @kumbhare and @shayhatsor!

**Pull request merged**
