### PR TITLE
Implemented Custom Serializer for GrainStateWithMetaDataAndETag

### PR DESCRIPTION
**Pull request by ibebbs**
Implemented Custom Serializer for GrainStateWithMetaDataAndETag so that the state could also provide a custom serializer rather than being stuck with the fallback serializer.
Consolidated GrainStateWtihMetaData into GrainStateWithMetaDataAndETag as former was not used anywhere and this made code cleaner.
Added unit tests for customer serializers

### CODE REVIEW

**Comment by ibebbs** [comment]
Apparently the 'UnitTests.General.ElasticPlacementTests.ElasticityTest_StoppingSilos' test is failing with the error 'Expecting a value in the range between 1030 and 1630, but instead got 1674 outside the range'.

These numbers are pretty obtuse and, as the test passes locally, I'm unsure how to go about resolving this failure, especially as I feel it is highly unlikely my change-set has impacted this test.

Any advice?

**Comment by sergeybykov** [comment]
@dotnet-bot test netfx-functional

**Comment by sergeybykov** [comment]
@ibebbs Looks like most likely a timing issue in the test.

**Comment by benjaminpetit** [comment]
`UnitTests.MembershipTests.ClientIdPartitionDataRebuildTests.ReconstructClientIdPartitionTest_Request` failed during the setup sequence, I wouldn't worry too much, it does not seems to be related to this PR.

I think Julian modified it a bit several days ago, if we see more failure on this test we ight want to fix something.

**Comment by sergeybykov** [comment]
@dotnet-bot test netfx-functional

**Comment by ReubenBond** [comment]
Thanks, @ibebbs :)

The changes are backwards compatible except for this one:
> Consolidated GrainStateWtihMetaData into GrainStateWithMetaDataAndETag as former was not used anywhere and this made code cleaner.

That change will cause existing state which is stored to break during deserialization. If the other changes are made without changing the existing members or inheritance hierarchy of the class, then this would be backwards compatible.

The root issue here is that there was no serializer being generated for `GrainStateWithMetaDataAndETag` and so it was using the fallback. It's fine to add a new serializer to a class which was previously using a fallback, that will not cause any issues. Modifying the class members & hierarchy will cause an issue, though.

**Comment by sergeybykov** [comment]
I'll close this for now because there seems to have been no progress on https://github.com/ibebbs/orleans/pull/1 since July.

**Pull request closed without merging**
