### PR TITLE
Build .NET Standard solution in CI 

### PR DESCRIPTION
**Pull request by benjaminpetit**
For #2145 

Not sure yet why I had to add `GenerateProjectSpecificOutputFolder=false` to the MSBuild commandline. Without it, every project were built in a subfolder of `OutDir`.

### CODE REVIEW

**Comment by benjaminpetit** [comment]
I think we need to install the .net 4.6.2 on the build machines

**Comment by galvesribeiro** [comment]
@benjaminpetit yes we do, Need to ping @mmitche to update the image...

**Comment by jdom** [comment]
This PR was superseded by #2343, although technically I did not enable it for CI yet. If you want, you can just enable it for CI once that other PR is merged.

**Comment by benjaminpetit** [comment]
Closing it, no needed with #2343

**Pull request closed without merging**
