### PR TITLE
Remove redundant NuGet package references, particularly for .NET Core.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**

### CODE REVIEW

**Comment by sergeybykov** [comment]
@teo-tsirpanis Thank you for the PR!

TBH I'm a bit nervous about removing those seemingly redundant dependencies. Some of them were added as fixes and workarounds for external bugs and dependency version ambiguities. For example, `Microsoft.Bcl.AsyncInterfaces` was added in #6031 as a workaround for #6028 

Some of those issues/bugs have probably been fixed by now. However, it's not clear to me how to validate that.

We also tend to avoid conditional references, such as
>Condition="'$(TargetFrameworkIdentifier)' == '.NETStandard'">

to keep things simpler.

**Comment by teo-tsirpanis** [comment]
@sergeybykov #6028 was about Orleans 3.0.0-RC1 when it was targeting only .NET Standard 2.0. `Microsoft.Bcl.AsyncInterfaces` is still needed on .NET Standard but not on .NET Core 3.0+ (notice that it does not target directly `netcoreapp3.0` and CI still succeeds after the explicit references are removed.

Furthermore, packages like [`System.Net.Http`](https://www.nuget.org/packages/System.Net.Http/) which stuck in version 4.3.* have not been updated since a couple of years and were only needed by libraries targeting .NET Standard 1.*. An extreme example is [`System.Data.Common`](https://www.nuget.org/packages/System.Data.Common/) whose latest version was released in 2016.

> We also tend to avoid conditional references [...] to keep things simpler.

I admit the complexity of the project files slightly raises but not much in my opinion; at least grouping the dependencies in an `ItemGroup` is better than a `<PackageReference Condition="..." Include="..."/>`. The benefits of this miniscule complexity however are tangible: the dependency tree becomes smaller, unmaintained packages are stopped being used, and the good practice of keeping dependencies at the minimum necessary is honored.

> [I]t's not clear to me how to validate that

First of all the CI succeeded. Second, we can take a look at the issues that led to the inclusion of these packages and try to reproduce them. I will further investigate.

**Comment by teo-tsirpanis** [comment]
Orleans targets .NET Standard 2.0 since 87690de which occured in September 2017. The `System.*` NuGet package references already existed for the times where Orleans was targeting .NET Standard 1.5, but were never removed until now.

---

As for the conditional references, I just thought of `'$(TargetFramework)' == 'netstandard2.0'` but the approach in the PR is more robust and will automatically work if Orleans hypothetically targets .NET Standard _2.1_ in the future.

**Comment by sergeybykov** [comment]
Since `master` branch is effectively 4.0, we don't actually need to be too cautious about changes like this. Worst case, we'll sort any issues once we have a preview or beta build out.

Thank you, @teo-tsirpanis!

**Pull request merged**
