### PR TITLE
(WIP) Bring TraceToConsole back to TestClusterOptions 

### PR DESCRIPTION
**Pull request by xiazen**
Brought `TraceToConsole `back to `TestClusterOptions `as a property,  instead as an FallBackOptions(which is the logic before). 

TraceToConsole is set to false by default. if set to true, then TestCluster will configure ConsoleLoggerProvider to both client and silo's DI container. It is a shortcut to configure console logging, compare to configure logging through ISiloBuilderFactory or IClientBuilder. But the two methods use the same infrastructure, which is through DI. 

Effort to address #3429

### CODE REVIEW

**Comment by xiazen** [comment]
do not merge, I want to see if this design is good or not. But if people think the design is good. Then

**Comment by attilah** [comment]
@dotnet-bot test functional please

**Comment by xiazen** [comment]
error CS1061: 'ILoggingBuilder' does not contain a definition for 'AddConsole' and no extension method 'AddConsole' accepting a first argument of type 'ILoggingBuilder' could be found (are you missing a using directive or an assembly reference?) [D:\j\workspace\functional_pr---83d31c72\src\OrleansTestingHost\OrleansTestingHost.csproj]
--


Functional failed on this. But why BVT doesn't fail on this? I think Jenkins env need to refresh or something, since apparently it's holding to old data

**Comment by attilah** [comment]
@dotnet-bot test bvt please

My guess that it will fail now.

**Comment by jdom** [comment]
Let's postpone the decision of whether to include this functionality for after beta, unless you think this must go in

**Comment by attilah** [comment]
As I expected it fails, needs to be rebased on master and fix the compilation error.

the error happens because a missing package reference in OrleansTestingHost project:
```xml
<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="$(MicrosoftExtensionsLoggingVersion)" />
```

**Comment by xiazen** [comment]
but this branch doesn't have that reference. why ci need to load that package? Why do I have to rebase with master for build to build? I don't get it.

**Comment by xiazen** [comment]
ping. Are you OK with the approach? If yes I will rebase.

**Comment by jdom** [comment]
Let's put it on the back-burner for the short term. We'll have to revamp the setup of the test cluster very soon, so not sure how it would affect this

**Comment by xiazen** [comment]
sounds good

**Pull request closed without merging**
