### PR TITLE
Migrated to Xunit

### PR DESCRIPTION
**Pull request by robrodi**
Converted all asserts to XUnit (#1793)

### CODE REVIEW

**Comment by jdom** [comment]
Thanks, Rob.
hehe, most likely the rebase went wrong... I can try to take a stab at pulling it locally and fixing it

**Comment by jdom** [comment]
LGTM :+1: 
I'm waiting for the last functional run and will merge after that

**Comment by sergeybykov** [comment]
@dotnet-bot Test this please.

**Comment by jdom** [comment]
Thanks a lot @robrodi !

**Pull request merged**
