### PR TITLE
A number of small ZK MBR table cleanup fixes.

### PR DESCRIPTION
**Pull request by gabikliot**
Only set maxStaleness for GatewayListProvider.
No need in log4Net.
Use CultureInfo.InvariantCulture when converting ZK rowVersion to string eTag.

### CODE REVIEW

**Comment by gabikliot** [comment]
@shayhatsor , these are small cleanup fixes. Nothing major, nothing was wrong. Just tidying up.

I did have a number of questions to you about the implementation:
1) In `InitializeMembershipTable` it seems like you are creating an empty node for Table Version. How do you make sure the first version is zero? Would it just be zero since default empty `int` value is zero?
2) You seem to handle etags for  table version and regular row differently. 
For regular row you use `(await rowDataTask).Stat.getVersion();`.
Who sets/changes this value upon every write?
For table version are you doing the same?
3) For table version ` expectedTableVersion` is the table version - 1. This works correctly now I think, but that was not the intent. You should be checking the table version row **etag**, not the table version **value** itself. You are relying now on the way MBR protocol increments those, but I would prefer you did not take this dependency.
3) Could you please add some high level description in the code about the data organization inside ZK: what kinds of node you have, how the MBR data is mapped to ZK nodes/data.
4) I did not understand how you map `IAmAlive`. `.setData(rowIAmAlivePath, newRowIAmAliveData, -1));` Is it a separate additional node? Does it have to be?

Thanks!

**Comment by gabikliot** [comment]
Put back the log4net.

**Comment by shayhatsor** [comment]
@gabikliot looks at #545

**Comment by gabikliot** [comment]
Closing since @shayhatsor implemented all those and more in #545.

**Pull request closed without merging**
