### PR TITLE
two new top level sections: Configuration and Programmer's Guide

### PR DESCRIPTION
**Pull request by shayhatsor**
Part of #1264.
I think that current documentation menu can be improved by this PR. I haven't removed any page (other than the link to Runtime Implementation Details - which only contains links which I've moved one level up).

### CODE REVIEW

**Comment by gabikliot** [comment]
Some changes in this PR are definitely good, but some I am not 100% sure about.

For example: moving Advanced-Concepts/External-Tasks-and-Grains into the 2nd item on Programmer's Guide: this section is for a REALLY advanced usage. I think it might scare away new comers. Everyone here is an expert of async and await but I saw so many people who get scared even hearing the concept of Synchronization Concept. And Orleans does, in all cases except those advanced usages, fully hide all this stuff. So putting in back in the front .... I am not sure.

`Application-Bootstrap-within-a-Silo` on the other hand - sure, it belongs in the Programmer's Guide.
`Timers-and-Reminders` as well.
Not sure about `Relational-Storage`.

I think I am OK with everything except for/External-Tasks-and-Grains , which I think still belongs to Advanced Documentation.

**Comment by shayhatsor** [comment]
moved `Advanced-Concepts/External-Tasks-and-Grains` and `Relational-Storage` to Advanced Documentation.

**Comment by gabikliot** [comment]
Thanks. Lgtm.

**Comment by sergeybykov** [comment]
Makes a lot of sense. Thank you, @shayhatsor for cleaning it up!

**Pull request merged**
