### PR TITLE
Cherry-picked fixes from master to 1.4.1 + VSIX

### PR DESCRIPTION
**Pull request by sergeybykov**
Includes a number of fixes from master and VSIX redone to work properly in VS 2015 and 2017.

### CODE REVIEW

**Comment by jdom** [comment]
What does #2833 bring? Just curious, as I thought there were no side-effects if that bug is there, and is only in preparation for the versioning story

**Comment by jdom** [comment]
Please include #2859, as this won't work on build agents that do not have VS2017 installed. That PR fixes it, as it was broken by #2820.

**Comment by benjaminpetit** [comment]
Yes Julian is right, #2833 was just in preparation for versioning

**Comment by sergeybykov** [comment]
Removed #2833.
Added #2859.

**Pull request merged**
