### PR TITLE
Upgraded Microsoft.Azure.EventHubs package to 3.0.0.

### LINKED ISSUE #5369: Unable to use Microsoft.Azure.EventHubs package greater than 1.0.3 with Microsoft.Orleans.OrleansServiceBus
It is not possible to use a version of `Microsoft.Azure.EventHubs` greater than `1.0.3` in the same application as Orleans if the EventHubs stream provider is being used.

The `Microsoft.Orleans.OrleansServiceBus` package depends on version `1.0.3` of `Microsoft.Azure.EventHubs` (released Aug 23, 2017) and breaking changes have been made in later releases.

Even though it is not called out specifically in the release notes for `1.1.0` the `EventHubClient.CreateReceiver` method signature was changed to include an optional `ReceiverOptions` parameter.

https://github.com/Azure/azure-event-hubs-dotnet/releases/tag/1.1.0

A `MissingMethodException` is thrown when the `EventHubAdapterReceiver` attempts to create the `PartitionReceiver` due to the additional parameter that was added to the overload being used.

```
System.MissingMethodException: Method not found: 'Microsoft.Azure.EventHubs.PartitionReceiver Microsoft.Azure.EventHubs.EventHubClient.CreateReceiver(System.String, System.String, System.String, Boolean)'.
   at Orleans.ServiceBus.Providers.EventHubAdapterReceiver.CreateReceiver(EventHubPartitionSettings partitionSettings, String offset, ILogger logger, ITelemetryProducer telemetryProducer)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Orleans.ServiceBus.Providers.EventHubAdapterReceiver.CreateReceiver(EventHubPartitionSettings partitionSettings, String offset, ILogger logger, ITelemetryProducer telemetryProducer)
   at Orleans.ServiceBus.Providers.EventHubAdapterReceiver.Initialize()
   at Orleans.ServiceBus.Providers.EventHubAdapterReceiver.GetQueueMessagesAsync(Int32 maxCount)
   at Orleans.Streams.PersistentStreamPullingAgent.ReadFromQueue(QueueId myQueueId, IQueueAdapterReceiver rcvr, Int32 maxCacheAddCount)
   at Orleans.AsyncExecutorWithRetries.ExecuteWithRetriesHelper[T](Func`2 function, Int32 callCounter, Int32 maxNumSuccessTries, Int32 maxNumErrorTries, TimeSpan maxExecutionTime, DateTime startExecutionTime, Func`3 retryValueFilter, Func`3 retryExceptionFilter, IBackoffProvider onSuccessBackOff, IBackoffProvider onErrorBackOff) 
```

A further breaking change was introduced to `Microsoft.Azure.EventHubs` in `2.0.0` and is mentioned in the release notes. Removal of the `Microsoft.Azure.EventHubs.PartitionReceiver.StartOfStream` property which is currently referenced by `Orleans.ServiceBus.Providers.EventHubConstants.StartOfStream` results in a `TypeInitializationException`.

https://github.com/Azure/azure-event-hubs-dotnet/releases/tag/v2.0.0

The inner `MissingFieldException` is a result of the property removal.

```
System.TypeInitializationException: The type initializer for 'Orleans.ServiceBus.Providers.EventHubConstants' threw an exception. ---> System.MissingFieldException: Field not found: 'Microsoft.Azure.EventHubs.PartitionReceiver.StartOfStream'.
   at Orleans.ServiceBus.Providers.EventHubConstants..cctor()
   --- End of inner exception stack trace ---
   at Orleans.ServiceBus.Providers.EventHubPartitionCheckpointEntity.Create(String streamProviderName, String serviceId, String partition) in D:\build\agent\_work\24\s\src\Azure\Orleans.Streaming.EventHubs\Providers\Streams\EventHub\EventHubPartitionCheckpointEntity.cs:line 17
   at Orleans.ServiceBus.Providers.EventHubCheckpointer..ctor(AzureTableStreamCheckpointerOptions options, String streamProviderName, String partition, String serviceId, ILoggerFactory loggerFactory) in D:\build\agent\_work\24\s\src\Azure\Orleans.Streaming.EventHubs\Providers\Streams\EventHub\EventHubCheckpointer.cs:line 92
   at Orleans.ServiceBus.Providers.EventHubCheckpointer.Create(AzureTableStreamCheckpointerOptions options, String streamProviderName, String partition, String serviceId, ILoggerFactory loggerFactory) in D:\build\agent\_work\24\s\src\Azure\Orleans.Streaming.EventHubs\Providers\Streams\EventHub\EventHubCheckpointer.cs:line 70
   at Orleans.ServiceBus.Providers.EventHubCheckpointer..ctor(AzureTableStreamCheckpointerOptions options, String streamProviderName, String partition, String serviceId, ILoggerFactory loggerFactory) in D:\build\agent\_work\24\s\src\Azure\Orleans.Streaming.EventHubs\Providers\Streams\EventHub\EventHubCheckpointer.cs:line 92
   at Orleans.ServiceBus.Providers.EventHubCheckpointer.Create(AzureTableStreamCheckpointerOptions options, String streamProviderName, String partition, String serviceId, ILoggerFactory loggerFactory) in D:\build\agent\_work\24\s\src\Azure\Orleans.Streaming.EventHubs\Providers\Streams\EventHub\EventHubCheckpointer.cs:line 70
   at Orleans.ServiceBus.Providers.EventHubAdapterReceiver.Initialize() in D:\build\agent\_work\24\s\src\Azure\Orleans.Streaming.EventHubs\Providers\Streams\EventHub\EventHubAdapterReceiver.cs:line 115
   at Orleans.ServiceBus.Providers.EventHubAdapterReceiver.Initialize() in D:\build\agent\_work\24\s\src\Azure\Orleans.Streaming.EventHubs\Providers\Streams\EventHub\EventHubAdapterReceiver.cs:line 115
   at Orleans.ServiceBus.Providers.EventHubAdapterReceiver.Initialize() in D:\build\agent\_work\24\s\src\Azure\Orleans.Streaming.EventHubs\Providers\Streams\EventHub\EventHubAdapterReceiver.cs:line 115
   at Orleans.OrleansTaskExtentions.SafeExecute(Func`1 action) in D:\build\agent\_work\24\s\src\Orleans.Core\Async\TaskExtensions.cs:line 151
   at Orleans.OrleansTaskExtentions.SafeExecute(Func`1 action) in D:\build\agent\_work\24\s\src\Orleans.Core\Async\TaskExtensions.cs:line 151
   at Orleans.OrleansTaskExtentions.SafeExecute(Func`1 action) in D:\build\agent\_work\24\s\src\Orleans.Core\Async\TaskExtensions.cs:line 151
   at Orleans.OrleansTaskExtentions.LogException(Task task, ILogger logger, ErrorCode errorCode, String message) in D:\build\agent\_work\24\s\src\Orleans.Core\Async\TaskExtensions.cs:line 138
   at Orleans.OrleansTaskExtentions.LogException(Task task, ILogger logger, ErrorCode errorCode, String message) in D:\build\agent\_work\24\s\src\Orleans.Core\Async\TaskExtensions.cs:line 138
   at Orleans.OrleansTaskExtentions.LogException(Task task, ILogger logger, ErrorCode errorCode, String message) in D:\build\agent\_work\24\s\src\Orleans.Core\Async\TaskExtensions.cs:line 138
   at Orleans.Streams.PersistentStreamPullingAgent.AsyncTimerCallback(Object state) in D:\build\agent\_work\24\s\src\Orleans.Runtime\Streams\PersistentStream\PersistentStreamPullingAgent.cs:line 348
   at Orleans.Streams.PersistentStreamPullingAgent.AsyncTimerCallback(Object state) in D:\build\agent\_work\24\s\src\Orleans.Runtime\Streams\PersistentStream\PersistentStreamPullingAgent.cs:line 348
```

It appears that the constant value `"-1"` has been moved to an internal property of the `EventPosition` class.

https://github.com/Azure/azure-event-hubs-dotnet/blob/8aae6b6ec1af44de69326288854f5811985db539/src/Microsoft.Azure.EventHubs/EventPosition.cs#L21

I have investigated the changes required to upgrade `Microsoft.Azure.EventHubs` in a fork.

- Modify `Directory.Build.props` to update `Microsoft.Azure.EventHubs` package to `2.2.1` and `System.Net.Http` to `4.3.3` (to prevent downgrade in other projects).
- The `EventHubConstants.StartOfStream` property can be replaced with the constant `"-1"` leaving the value as a `string`.
- `EventPosition` is only required when creating the `PartitionReceiver` which is done inside the `EventHubAdapterReceiver.CreateReceiver` method where the offset (`string`) and inclusive flag (`bool`) are already available.
- Update reflection based code in `EventHubUtils` to cater for internal changes to `EventData`. Reflection is no longer required for setting the `Offset`, `SequenceNumber`, `EnqueuedTime` and `PartitionKey` properties, but is still required to initialize `SystemProperties` with a new `SystemPropertiesCollection` when `null`.

The unit tests are passing with the exception of `EHBatchedSubscriptionMultiplicityTests.EHBatchedMultipleLinearSubscriptionTest`. This fixture contains integration style tests that I had to point at my own EventHub and Storage Table to get working. I wasn't sure if this failure was related to the upgrade so I ran the same test without the upgrade and it still fails for me locally. I assume there is a difference between my setup and the one used in your build system.

I would be happy to put together a PR with these changes if you are interested.

### PR DESCRIPTION
**Pull request by alexmg**
The `Microsoft.Azure.EventHubs` package was upgraded to `2.2.1` to resolve #5369. 

A `3.0.0` version of this package has recently been released. 

https://github.com/Azure/azure-event-hubs-dotnet/releases/tag/3.0.0

This PR extends the upgrade to `3.0.0` and takes advantage of the `EventData.SystemProperties` being made public to remove reflection based helpers.

### CODE REVIEW

**Comment by jason-bragg** [comment]
@dotnet-bot test functional please

**Comment by jason-bragg** [comment]
@alexmg, do you need streams using EH3.0?

The reason I ask is that 3.0 is the most recent version, which is most likely to have issues and the least likely to be in use.  We held upgrading to the 2.x series in part due to number of customers still using 1.x, but 2.x has been out long enough for a significant number of users to now be using 2.x.  We'd not planned to move to 3.x until 3.1 was out and users with 2.x had an opportunity to upgrade.  If you need 3.x we should discuss it, but if this upgrade is being made solely because 3.0 has been released, I'd prefer we wait.

I'll bring this up with the rest of the team.  We may decide to jump strait to 3.x or come up with an upgrade plan but knowing what you need will help inform our decision making.

**Comment by alexmg** [comment]
Hi @jason-bragg. Apologies, I intended to come back sooner and provide some additional context but got distracted with other tasks.

I don't have a specific requirement to use Orleans streams with `3.0.0` directly, but there are some improvements in `3.0.0` of `Microsoft.Azure.EventHubs.Processor` that I would like to use, and wanted to know if I could expect issues similar to #5369 if I made the update and indirectly brought the Orleans stream provider to the later version.

After making the changes I thought I would submit a PR so you had the option to jump as high as possible in the one upgrade if you wanted. Being a `3.0.0` version bump I thought there might be another breaking change that would prevent the `Microsoft.Azure.EventHubs.Processor` package from being upgraded but nothing obvious turned up while making the changes. The way things stand with the current release no one would have been able to upgrade past `1.0.3` so if they needed a later version they must be running it separate from the silo. Features like the direct client make the shared hosting scenario a lot more attractive so the number of users tying to use a newer package version might start to increase.

I completely understand if you would like to target a lower baseline version for those that are only using the Event Hubs stream provider. I will try to update my solution to the nightly package feed and confirm what happens if I update `Microsoft.Azure.EventHubs.Processor` to `3.0.0` and indirectly update the Orleans streams provider to the later version of `Microsoft.Azure.EventHubs`. Having the more widely used and tested `2.2.1` version being the baseline for the stream provider, but no breaking changes getting in the way of anyone wanting to use `3.0.0` for other purposes, would be a good place to land.

**Comment by alexmg** [comment]
@jason-bragg I did some quick testing using the packages from a local Orleans build that included the recent `2.2.1` upgrade in the stream provider.

After upgrading the `Microsoft.Azure.EventHubs.Processor` package to `3.0.0` for my `IEventProcessor` implementation that runs inside the silo the server started without issue. I was then able to receive events in my `IEventProcessor` and push them into Orleans streams using the Event Hub stream provider. Those events made it out to a test client that was subscribed to the Orleans streams.

It appears there are indeed no breaking changes from `2.2.1` to `3.0.0` that impact the Orleans stream provider and it happily uses the later version of `Microsoft.Azure.EventHubs`. I don't see any reason at present for you to push the default version higher than `2.2.1`. Being able to remove the reflection code for working with the `SystemPropertiesCollection` is nice but not a good enough reason by itself to move to `3.0.0`.

Thanks for taking the time to get the `2.2.1` upgrade done. I'll be sure to let you know if I notice a future update in the `3.x` series causing a problem with the Event Hubs stream provider.

**Pull request closed without merging**
