### PR TITLE
Update Docker-Deployment.md

### PR DESCRIPTION
**Pull request by galvesribeiro**
Including reference to OrleansContrib\Orleans.Clustering.Kubernetes

### CODE REVIEW

**Comment by benjaminpetit** [comment]
Could you remote/update the part regarding the gateway also?

**Comment by galvesribeiro** [comment]
@benjaminpetit what you mean? Sorry, not following.

**Comment by benjaminpetit** [comment]
In the Gateway configuration section:

> You may have noticed that we are not using the membership provider in our client configuration. The > reason for that (and I figured out after days suffering and talking with Docker folks) is because the way our client -> membership -> gateway(s) -> silo works, is not compatible with the way Docker overlay network is designed.

Which is not true, it is misleading some people. I know I had opened a PR weeks ago about this, but still not merged.

But it would be great if you could fix this in this PR!

**Comment by galvesribeiro** [comment]
Well, for Swarm it still sort of valid. But ok, let me remove that and update the PR.

**Comment by benjaminpetit** [comment]
Awesome, thanks you!

**Pull request merged**
