### PR TITLE
Fix several incorrect usages of Type and TypeInfo

### PR DESCRIPTION
**Pull request by jdom**
In preparation for the CoreCLR port #368

### CODE REVIEW

**Comment by jdom** [comment]
ping @ReubenBond & @galvesribeiro, as getting this reviewed and merged will help us get closer to the port, as this was insanely time consuming for some reason to get right.
After this is merged, I'll try to rebase my [coreclr-multi branch](https://github.com/dotnet/orleans/compare/master...jdom:coreclr-multi) to the latest (it is already on Core CLR RTM, just on an old version of Orleans master), and potentially update the relevant pieces in our main repo, so that we all have a stable starting point

**Comment by gabikliot** [comment]
LGTM.
When we first converted bunch of Type to TypeInfo there were some concerns about perf. I even wrote quite a detailed analysis of hot vs. cold paths here: https://github.com/dotnet/orleans/pull/617#issuecomment-122354233

You may find it useful.

**Comment by jdom** [comment]
Thanks Gabi. Most of the complexity of this PR is that I tried to avoid many conversions when possible. Nevertheless, have we benchmarked at all if this is a costly operation? In the full framework TypeInfo inherits from Type, so the conversion is non existent there (it just returns `this`) . This is not the case in CoreCLR, but I would imagine they do some caching themselves turning this into a non expensive operation. We could try it if you are concerned. 
We could treat that as an improvement in a separate PR anyway, since these changes are needed in coreclr, even if they could be optimized. In the full fx it should not be an issue

**Comment by jdom** [comment]
BTW, I'm kicking of a load test run just to be safe

**Comment by jdom** [comment]
The load test results (for the full .NET Framework which is all we can test now) came good, it should be good for merging

**Comment by veikkoeeva** [comment]
👍

**Pull request merged**
