### PR TITLE
Removed filtering from streaming infrastructure

### PR DESCRIPTION
**Pull request by jason-bragg**
Breaking changes to core.abstractions, so this is, at earliest, a 3.0 change

### CODE REVIEW

**Comment by ReubenBond** [comment]
@dotnet-bot test functional

**Comment by ReubenBond** [comment]
Failure seemed transient: https://ci.dot.net/job/dotnet_orleans/job/master/job/functional_prtest/2602/consoleFull

**Comment by jason-bragg** [comment]
PR updated to preserve backwards compatibility at network and storage layers.
Also rebased.

**Comment by xiazen** [comment]
@jason-bragg did you pushed the BatchObserver commit to Remove Filter PR by mistake?

**Comment by jason-bragg** [comment]
I rebased this on top of the batch work, as the batch work will go in first.  This is still wip.  Until the batch work is merged, probably shouldn't spend time on this PR as it will be unnecessarily noisy.

**Comment by jason-bragg** [comment]
Removed WIP tag.  I think this is ready for review.

**Comment by jason-bragg** [comment]
@dotnet-bot test this please

**Comment by cata** [comment]
Heads-up: we are using this feature in production and would like (a simplified version of) it to remain.
In essence, for our purposes it would be sufficient to:
* maintain the ability top attach custom data to a subscription
* provide the optional filtering predicate when emitting events rather than at subscription time, thus removing some of the concerns associated with the current implementation

I will file an issue regarding this shortly and try to propose an alternative to completely removing producer-sided filtering.
If possible, please postpone merging this PR until we can discuss the viability of the proposed alternative

**Comment by benjaminpetit** [comment]
Closing this PR, replaced by #6711

**Pull request closed without merging**
