### PR TITLE
Handle absolute path in IntermediateOutputPath to address issue 2864

### PR DESCRIPTION
**Pull request by andhesky**

### CODE REVIEW

**Comment by andhesky** [comment]
Fix for #2864

**Comment by sergeybykov** [comment]
Doesn't seem to work in vNext.

**Comment by andhesky** [comment]
Thanks I need to step away, but will take a look at vNext when I get a chance.

**Comment by sergeybykov** [comment]
@dotnet-bot test this please.

**Comment by attilah** [comment]
MSBuild has builtin function for this: HasTrailingSlash we should use this, instead of .Net calls.

[MSBuild Docs](https://msdn.microsoft.com/en-us/library/7szfhaft.aspx)

**Comment by attilah** [comment]
If @andhesky adds vNext fix it's LGTM.

**Comment by sergeybykov** [comment]
Thank you, @andhesky!

**Comment by jdom** [comment]
Thanks @andhesky, I created another PR to apply the changes to the vNext tree too: https://github.com/dotnet/orleans/pull/2871

**Comment by andhesky** [comment]
Thanks @jdom, I am currently traveling so a bit slow to respond.

**Pull request merged**
