### PR TITLE
Update Newtownsoft.Json to 10.0.3

### PR DESCRIPTION
**Pull request by jdom**
This fixes some issues with FormatterAssemblyStyle when using the .NET Standard version of the library

### CODE REVIEW

**Comment by ReubenBond** [comment]
@dotnet-bot test netfx-functional

**Comment by ReubenBond** [comment]
@dotnet-bot test netstandard-win-functional

**Comment by sergeybykov** [comment]
@dotnet-bot test netfx-functional

**Comment by attilah** [comment]
@dotnet-bot test netfx-functional

**Comment by jdom** [comment]
@dotnet-bot test netfx-functional

**Pull request merged**
