### PR TITLE
CounterStatistics improvment

### PR DESCRIPTION
**Pull request by tsibelman**
@gabikliot  Hope this time all will work as expected

### CODE REVIEW

**Comment by tsibelman** [comment]
The build still failing 

02:07:21 Failed   CodeGenRoundTripSerialization
02:07:21 Error Message:
02:07:21    The agent process was stopped while the test was running.
02:07:21 
02:07:35 Failed   GeneratorGrainControlFlow
02:07:35 Error Message:
02:07:35    The agent process was stopped while the test was running.
02:07:35 
02:07:49 Failed   RuntimeCodeGenTest
02:07:49 Error Message:
02:07:49    The agent process was stopped while the test was running.
02:07:49 
02:08:04 Failed   RuntimeCodeGenNestedGenericTest
02:08:04 Error Message:
02:08:04    The agent process was stopped while the test was running.
02:08:04 
02:08:18 Failed   StateClassTests_StateClass
02:08:18 Error Message:
02:08:18    The agent process was stopped while the test was running.

**Comment by jthelin** [comment]
> The agent process was stopped while the test was running.

That error message is not a good sign - it means the test process exe crashed and will have logged an error in the Windows Event Log.

I am trying to rerun the build to see if there is some way to see the error details.
http://dotnet-ci.cloudapp.net/job/dotnet_orleans/job/innerloop_prtest/561/

**Comment by jthelin** [comment]
OK, i pulled this PR down to my local machine, and the test problems repo for me there.

Here is the error logged in Windows Event Log

```
(QTAgent.exe, PID 8448, Thread 18) AgentProcess:CurrentDomain_UnhandledException: IsTerminating : System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Orleans.Runtime.CounterStatistic.IncrementBy(Int64 n) in e:\Depot\GitHub\orleans\src\Orleans\Statistics\CounterStatistic.cs:line 173
   at Orleans.Runtime.AsynchAgent.AgentThreadProc(Object obj) in e:\Depot\GitHub\orleans\src\Orleans\Runtime\AsynchAgent.cs:line 217
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

**Comment by tsibelman** [comment]
@jthelin Thank you, looks like it my code to blame after all I will take a look

**Comment by gabikliot** [comment]
`allStatisticsFromSpecificThread.Count < id` should be `<=` ?

**Comment by tsibelman** [comment]
Yes you correct already fixed it.

**Comment by tsibelman** [comment]
Found the bugs and fixed them, learned how to run and debug orleans test in the process

**Comment by gabikliot** [comment]
Great, thank you @tsibelman !

**Pull request merged**
