### PR TITLE
Using Roslyn CodeDOM provider to compile generated code to allow C# 6 features

### PR DESCRIPTION
**Pull request by Liversage**
Following up on https://github.com/dotnet/orleans/issues/755 I have modified `ClientGenerator` to use "Roslyn" to compile generated C# and VB.NET code.

However, there are some issues:

- Because the `Orleans` project is bootstrapped using code generation I had to add the "Roslyn" NuGet package to the Orleans project but it is only used during the bootstrap process.
- The bootstrap build step is in the `Orleans.csproj` file and I hardcoded the specific version of the "Roslyn" NuGet package in the build step so updating the NuGet package will require a manual change to `Orleans.csproj`.
- I do not know how this added dependency affects the generation of Orleans NuGet packages.
- I have not tested the VB.NET compilation.

Other than that the change allows me to use C# 6 features in my grain classes but the boostrap issue should probably be solved more elegantly.

### CODE REVIEW

**Comment by ReubenBond** [comment]
The DotNetCompilers package seems to be fragile, so that's likely the issue. You should check out #528 and #886, by the way.

**Comment by Liversage** [comment]
I have updated the title and description based on @ReubenBond's feedback.

**Comment by sergeybykov** [comment]
The CI build failed with

>Error : Orleans code generator found error : -- Code-gen FAILED -- [d:\j\workspace\dotnet_orleans\innerloop_prtest\src\OrleansRuntime\OrleansRuntime.csproj]
02:07:43          Exception = System.IO.DirectoryNotFoundException: Could not find a part of the path 'd:\j\workspace\dotnet_orleans\innerloop_prtest\Binaries\Debug\bin\roslyn\csc.exe'.

**Comment by Liversage** [comment]
Yes, of course! Apparently, the "Roslyn" NuGet package has a strange dependency on the folder structure used by ASP.NET projects. The binaries of an ASP.NET project are in `bin` and the Roslyn compiler goes into `bin\roslyn`. In most other projects binaries goes into `bin\Debug` (or `bin\Release`) and then Roslyn expects the compiler to be in `bin\Debug\bin\roslyn` but actually the compiler ends up in `bin\Debug\roslyn`. My guess is that the extra `bin` is related to ASP.NET projects and a proper fix probably involves tinkering with MSBuild properties in the "Roslyn" NuGet package.

I forgot that I fixed this issue on my machine by simply copying the Roslyn compiler files to be able to test so "It worked on my machine".

I do not know if it is worthwhile to create some sort of `.csproj` hack to fix this issue as the pull requests that ReubenBond has created seems to be more thorough attempts to fix some of the code generation issues?

**Comment by sergeybykov** [comment]
This one is not needed anymore, now that https://github.com/dotnet/orleans/pull/528 is merged and https://github.com/dotnet/orleans/pull/886 is about to be, correct?

**Pull request closed without merging**
