### PR TITLE
Add CI definition

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
test ci please

**Comment by mmitche** [comment]
test ci please

**Comment by mmitche** [comment]
@jason-bragg Are you guys using the artifacts generated in the azure dotnet-orleans container?

**Comment by jason-bragg** [comment]
I apologize, but I don't know what you mean by "artifacts generated in the azure dotnet-orleans container".  Can you clarify?

**Comment by gabikliot** [comment]
@mmitche , do you mean the actual bits that are build with every pull request? Yes, of course we are. We used to point people to http://dotnet-ci.cloudapp.net/job/dotnet_orleans/lastStableBuild/Azure/ from our readme.md ("The latest clean development branch build from CI is located"), but I guess it changed now, since the link is broken. Where is it now?

**Comment by mmitche** [comment]
test ci please

**Comment by gabikliot** [comment]
Testing. I pushed a new commit https://github.com/gabikliot/orleans/commit/2231fb5ac71e8c7b8302191087c42f3b5080d6ed.

**Comment by mmitche** [comment]
@gabikliot I'm moving the jobs to a new format that has the definition checked into your repo.  To do this I have to temporarily rename the job to accommodate the refactoring.  How easy is it for you guys to change the path?

**Comment by gabikliot** [comment]
You mean how easy is it for us to change the path in our readme.md? easy, not a problem. just tell to what.

**Comment by mmitche** [comment]
okay cool.  I'm going to move you guys to the new definition, and you'll get a slightly different link for artifacts, one sec.

**Comment by mmitche** [comment]
test ci please

**Pull request merged**
