### PR TITLE
Add support Microsoft.Data.SqlClient provider, fix #6229

### LINKED ISSUE #6229: SiloHostBuilder with Microsoft.Data.SqlClient provider
Thrown System.Collections.Generic.KeyNotFoundException: 'The given key 'Microsoft.Data.SqlClient' was not present in the dictionary.'

Stack trace
```
   at System.ThrowHelper.ThrowKeyNotFoundException[T](T key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Orleans.Clustering.AdoNet.Storage.DbConstantsStore.GetDbConstants(String invariantName)
   at Orleans.Clustering.AdoNet.Storage.DbConstantsStore.SupportsCommandCancellation(String adoNetProvider)
   at Orleans.Clustering.AdoNet.Storage.RelationalStorage..ctor(String invariantName, String connectionString)
   at Orleans.Clustering.AdoNet.Storage.RelationalStorage.CreateInstance(String invariantName, String connectionString)
   at Orleans.Clustering.AdoNet.Storage.RelationalOrleansQueries.<CreateInstance>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Orleans.Runtime.MembershipService.AdoNetClusteringTable.<InitializeMembershipTable>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Orleans.Runtime.MembershipService.MembershipTableManager.<Start>d__35.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Orleans.Runtime.MembershipService.MembershipTableManager.<>c__DisplayClass53_0.<<Orleans-ILifecycleParticipant<Orleans-Runtime-ISiloLifecycle>-Participate>g__OnRuntimeGrainServicesStart|0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.<OnStart>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Orleans.LifecycleSubject.<<OnStart>g__CallOnStart|7_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Orleans.LifecycleSubject.<OnStart>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.<Execute>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Orleans.Runtime.Silo.<StartAsync>d__65.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Orleans.Hosting.SiloWrapper.<StartAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Host.Program.<Main>d__0.MoveNext() in C:\git\Test\Host\Program.cs:line 35
```

"Microsoft.Orleans.Core" Version="3.0.2"
dotnet version 3.1.100

### PR DESCRIPTION
**Pull request by voronov-maxim**
Fixes #6229

### CODE REVIEW

**Comment by veikkoeeva** [comment]
@voronov-maxim I opened https://github.com/dotnet/orleans/pull/6237 earlier, but now that you opened this, there's a moment of reflection needed. See explanations in the other thread.

**Comment by veikkoeeva** [comment]
@voronov-maxim Looks like this is the way to go (explanation in the other thread). Do you think you have the energy to add the alternative MySQL provide too and test it? See at https://github.com/dotnet/orleans/issues/6230. If not, I can do that.

**Comment by voronov-maxim** [comment]
Hi @veikkoeeva, unfortunately I do not use MySql.

**Comment by veikkoeeva** [comment]
@voronov-maxim That is all right. I try to add MySQL this week in similar way than you. There seem to be some flakiness in the tests that looks like not being related to your changes.

**Comment by voronov-maxim** [comment]
Hi @veikkoeeva
> By the way, have you tested/verified this loads the library correctly?

After applying this change, my code worked without exception.

**Comment by ReubenBond** [comment]
> Do you think you have the energy to add the alternative MySQL provide too and test it? See at #6230. If not, I can do that.

@veikkoeeva do you want to have a separate PR for that?

**Comment by veikkoeeva** [comment]
@ReubenBond It's the easiest since @voronov-maxim doesn't have MySQL installed and I have. I've tried to open the PR for a few days now, but one has to sleep occassionally too. Maybe today. :)

**Comment by ReubenBond** [comment]
No worries & no rush - I'll merge this and we can add MySQL later

**Pull request merged**
