### PR TITLE
Experimental event sourcing rebased

### PR DESCRIPTION
**Pull request by sergeybykov**
This is rebased https://github.com/dotnet/Orleans/tree/experimental-event-sourcing ready to be merged to master, so that we can continue working on ES there.

### CODE REVIEW

**Comment by gabikliot** [comment]
Orleans.EventSourcing or OrleansEventSourcing ? I thought we said no . in the name, for consistency.

**Comment by veikkoeeva** [comment]
I see there's a comment
````
// We might need a different, more explicit, persstence API for ES.
// Reusing the current API for now.
await this.WriteStateAsync();
````
This rings true. I interpret this now so that all the events need to be in memory, and there's no way to prevent replaying it all into memory (how about memory consumption in general during runtime?). As it looks like it has become a habit already, I look this from the perspective of a relational store at Gitter [here](https://gitter.im/dotnet/orleans?at=55f2a1a983d96281368b8340) and think this would work if the persistence layer had knowledge of the event type (some kind of a ID) that could be passed down to the storage layer. 

In the database the query would do what is configured to do. For instance, return only a single entity having the "latest state". In the context of the particular given example, the latest ``PersonState``. But if so desired, the query could also return them all. It depends all on how the application developer wants to implement the scenario.

**Comment by sergeybykov** [comment]
@gabikliot The project/assembly name has not dot, the NuGet package has it. Consistent with the rest of codebase. Did I miss something?

**Comment by sergeybykov** [comment]
@veikkoeeva Yes, that's the next step - to define the persistence provider interface that would work for all of the important scenarios: loading all event, loading all events and latest snapshot, loading latest  snapshot and events since it, etc.

**Comment by gabikliot** [comment]
@sergeybykov , the folder name for [this folder](https://github.com/dotnet/orleans/pull/832/files#diff-44a901a462cf0393a3f788800d180c87R1) is src\Orleans.EventSourcing\XXX. We don't put dots in folder names. Did I miss something?

**Comment by sergeybykov** [comment]
You are right, I missed the directory name. Just pushed a commit that renamed the directory.

**Pull request merged**
