### PR TITLE
Stream delivery retry bug fix.

### PR DESCRIPTION
**Pull request by jason-bragg**
Backoff policy contained mutable state.  Backoff policy is not immutable.

### CODE REVIEW

**Comment by gabikliot** [comment]
I am not sure I can do a trusted review over the phone. 😞
My thoughts:
1.backoff has to be state full, by definition it counts retries.
2. It took long time to polish that class and I would be extremely careful changing it.
3. Mbr relies on that class, for critical operations, so I would be double careful.

Instead, I would try what I suggested before: First attempt without backoff, and use backoff only on failures.

It is totally possible you came up with a perfect fix in this pr, but I just can't understand it while looking on the phone.

**Comment by gabikliot** [comment]
More thoughts: You pushed the state maintainance on the caller now (it needs to count) which contradicts oop encapsulation principle . Plus, how the similar is done in for example azure storage library? 
It's a library class, has to be generic and "right" from all perspectives.

**Comment by jason-bragg** [comment]
"1.backoff has to be state full, by definition it counts retries."
The AsyncExecutorWithRetries call sequence maintains the retry count.  IBackoffProvider does not need to track it if it can be told it.  In this change, backoff policies become immutable heuristics, which are preferred for pluggable policies (IMO). 

"2. It took long time to polish that class and I would be extremely careful changing it."
Agreed.  Before submitting this, I duplicated the old code and new code in a test, with fixed random seed to make sure the behavior was preserved.  Behaviorally, they match.  We also have test for this in VSO, but due to the randomness in the algorithm, it's unclear how precise those tests can be.

"3. Mbr relies on that class, for critical operations, so I would be double careful."
See 2 comments.

"how the similar is done in for example azure storage library"
I'm unclear what you're referring to here.  The IBackoffProvider is a pluggable policy in the AsyncExecutorWithRetries algorithm, it's not, to my knowledge used separately, nor do I think it should be.  Please correct my understanding if I am in error here.

**Comment by gabikliot** [comment]
Azure library has an option to specify back retry policy, you just specify it, you don't call it with retry counter every time.

I am not talking about retry executor, but about exp back off. I back off is a pluggable interface, the concrete exp bavkoff is not. It's better to have it, exp back off, but fully encapsulated, in the best spit it of OOP.

Having test is great, but I wouldn't trust it as 100% ensuring correctness. Right? Not first time.

At the end, its about code maintenance (encapsulation helps a lot) and price of a bug.

**Comment by jason-bragg** [comment]
"Azure library has an option to specify back retry policy, you just specify it, you don't call it with retry counter every time."
The same is true with IBackoffProvider.  The user specifies it, but never uses it directly.  Just as the IRetryPolicy interface, the user specifies the implementation but never calls it directly.

Let's look at the two.

interface IBackoffProvider  
{
    TimeSpan Next(int currentRetryCount);  
}

public interface IRetryPolicy
{
    IRetryPolicy CreateInstance();
    bool ShouldRetry(int currentRetryCount, int statusCode, Exception lastException, out TimeSpan retryInterval, OperationContext operationContext);
}

The IRetryPolicy is passed information to determine the correct behavior, but can also contain mutable state.  It does this by using the CreateInstance call, to create a new instance of the state per retryable call sequence.  This is not unreasonable, especially because it is solely responsible for determining if the action should be retried.

The IBackoffProvider interface could support a similar pattern.  A similar CreateInstance call could be added to IBackoffProvider, and a new instance with mutable state could be created per call being retried.  However, the BackoffProvider's responsibilities are far more limited than IRetryPolicy.  It is only responsible for calculating the delay between attempts.  Further, the state being maintained in the ExponentialBackoffProvider is already being maintained in the AsyncExecutorWithRetries retry algorithm. 

Questions:
If a class of behaviors can be supported by immutable heuristics, isn't this preferable?
Given that the backoff provider is responsible only for providing the delay between retry attempts, are you of the opinion that implementations of such a narrow behavior is likely to require mutable state?

If you feel strongly that backoff providers will likely need mutable state, I can add a CreateInstance call to the interface, and create a new instance  only if retries are needed.  It should be noted, however, that this is a more significant change than the one under review, and given the current set of backoff providers, offers no immediate advantage.  It only provides advantage to possible future backoff providers.

"in the best spirit of OOP"
From the OOP perspective, I agree, but when thinking of the Backoff provider as a pluggable heuristic, it conforms more to a functional programing model, which is actually more inline with the AsyncExecutorWithRetries implementation.  In this case, its conformance depends on which programming model one sees fit to apply to the problem.

**Comment by gabikliot** [comment]
Any implementation will need to maintain state. The only question is if it is maintained by the caller or by the caller. The advantage of by the callee is encapsulation -> all the possible multiple callers, in the general case, are simpler.
If you push it to the caller than indeed the callee is simpler, immutable, "functional" but all the different callers are more complicated. Plus not possible to fully test in isolation.
Create instance or just new via constructor, like now, is the same. I see no conceptual difference.

The change I suggested is different from what u described above. I suggested not to use retry executor at all on first attempt.

Not feeling strong. Just find it weird we break encapsulation and think its the right way: creating more tight coupling, more inter component dependence. In the original way exp backoff worked on its own, no one needed to know what to pass to it and count.

**Comment by jason-bragg** [comment]
"but all the different callers are more complicated"
What different callers?  There are no different callers..?  IBackoffProvider is not, nor do I believe it was ever intended to be, used outside AsyncExecutorWithRetries, in the same way azure storage's IRetryPolicy was never intended to be called from outside the azure client libraries retry logic.  They both take the retry count as a call parameter passed by their calling logic, which does not matter at all to users because users never interact with these interfaces.

"I suggested not to use retry executor at all on first attempt."
Please take another look at the details of the proposed change and how AsyncExecutorWithRetries users use backoff providers.  If you're still convinced IBackoffProvider should track its own state, even when the caller is already tracking that state, I'll defer to your judgment, as the additional allocation per call sequence that requires retry is not enough overhead to warrant debate, but I see only advantages in backoff providers being pluggable heuristics rather then mutable objects.

**Comment by gabikliot** [comment]
Agree it's not worth further debate. Unfortunately I can't review it, its very hard over phone. Just be careful, there was some specific logic about overflows that was important.

**Comment by gabikliot** [comment]
Jason, did you see in the old code catching and ignoring over flow exc? In the new code, after 32 or 64 iterations the code will throw, which is a bug,and specifically could be very costly since will impact mbr.

**Comment by jason-bragg** [comment]
"after 32 or 64 iterations the code will throw"
That exception is caught, and maxDelay is used.

**Pull request merged**
