### PR TITLE
Added  a stat counter "Catalog.Activation.FailedToActivate".

### PR DESCRIPTION
**Pull request by gabikliot**

### CODE REVIEW

**Comment by jthelin** [comment]
For other's reference: this provides a nice self-contained example of how to add additional counters to Orleans runtime.

**Comment by gabikliot** [comment]
Fixed the typos and a bit more standardization of counter names.

**Comment by jthelin** [comment]
Unless I am misreading the diff, aren't some of the typo's still there?
"actications" should be "activations"

**Comment by gabikliot** [comment]
Fixed actications -> activations.

**Pull request merged**
