### PR TITLE
Updated SafeRandom to use a thread static instance instead of locks

### PR DESCRIPTION
**Pull request by jdom**
Updated SafeRandom to use a thread static instance instead of using locks, similar to http://blogs.msdn.com/b/pfxteam/archive/2014/10/20/9434171.aspx

### CODE REVIEW

**Comment by gabikliot** [comment]
Looks good. 
My only concern is if `RNGCryptoServiceProvider` , `ThreadStatic` and `MethodImplOptions.AggressiveInlining` are all coreclr complains. With our efforts moving forward towards https://github.com/dotnet/orleans/issues/368 we don't want to go back.

**Comment by gabikliot** [comment]
Checked that `ThreadStatic` is complaint.

**Comment by jdom** [comment]
I saw you just merged this... In case you want it, I did some quick test with a CoreCLR project. For some reason It didn't seem to find RNGCryptoServiceProvider (although I know it's supported), but it was easily fixed by replacing that field with:
> private static readonly RandomNumberGenerator globalCryptoRandom = RandomNumberGenerator.Create();
Which under the hoods creates a RNGCryptoServiceProvider anyway. This just required adding a dependency to System.Security.Cryptography.RandomNumberGenerator in the project's CoreCLR dependencies section.

I updated my branch with a new commit...

**Comment by jdom** [comment]
Since it was already merged, I don't think I can add a new commit to this PR. Feel free to pull it yourself, or let me know if you want me to create a new PR for it (in case you actually want that update to go in)

**Comment by gabikliot** [comment]
No problem. I will take care of it.

**Pull request merged**
