### PR TITLE
Added support for transaction client

### PR DESCRIPTION
**Pull request by jan-johansson-mr**
Hi @ReubenBond,

This PR introduces support for transaction client and introduces the types

- TransactionClient
- ITransactionClient
- ClientBuilderExtensions

# Transaction client

The client enables using of transaction(s) in a unit of work, where the ambient transaction can either be joined or suppressed if there exists one.

The following section illustrates the pattern using the client.

## Create transaction

    await transactionClient.RunTransaction(TransactionOption.Create, async () =>
    {
        ...
        await grainA.SetPhrase("Hi");
        await grainB.SetNumber(4);
        ...
    });

The client delegate always creates a new transaction (isolated within ambient transaction).

## Create or join transaction

    await transactionClient.RunTransaction(TransactionOption.CreateOrJoin, async () =>
    {
        ...
        await grainA.SetPhrase("Hi");
        await grainB.SetNumber(4);
        ...
    });

The client delegate will join ambient transaction, or create a new transaction.

## Join transaction

    await transactionClient.RunTransactione(TransactionOption.Join, async () =>
    {
        ...
        await grainA.SetPhrase("Hi");
        await grainB.SetNumber(4);
        ...
    });

The client delegate will join ambient transaction, or fail.

## Suppress transaction

    await transactionClient.RunTransaction(TransactionOption.Suppress, async () =>
    {
        ...
        await grainA.SetPhrase("Hi");
        await grainB.SetNumber(4);
        ...
    });

Any ambient transaction will not be passed on, nor will transaction be used.

## Supported transaction

    await transactionClient.RunTransaction(TransactionOption.Supported, async () =>
    {
        ...
        await grainA.SetPhrase("Hi");
        await grainB.SetNumber(4);
        ...
    });

The client delegate is not transactional but supports transactions. Ambient transaction will be passed on.

## Not allowed

    await transactionClient.RunTransaction(TransactionOption.NotAllowed, async () =>
    {
        ...
        await grainA.SetPhrase("Hi");
        await grainB.SetNumber(4);
        ...
    });

A not supported exception will be thrown if within an ambient transaction.

# Supported scenarios

The configured clients can be arbitrarily nested, e.g.,

    await transactionClient.RunTransaction(TransactionOption.Create, async () =>
    {
        ...
        await grainA.SetPhrase("Hi");
        ...
        await transactionClient.RunTransaction(TransactionOption.Create, async () =>
        {
            ...
            await grainA.SetPhrase("Hi");
            ...
            await transactionClient.RunTransaction(TransactionOption.Suppress, async () =>
            {
                ...
                await grainA.DoWork();
                ...
            });
            ...
            await grainB.SetNumber(4);
            ...
        });
        ...
        await grainB.SetNumber(4);
        ...
    });

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/orleans/pull/7805)

### CODE REVIEW

**Comment by jan-johansson-mr** [comment]
Okay @ReubenBond, let's try with  `ITransactionClient` :-)

Hmm... what about the `RunScope` delegate? Maybe it should be `RunTransaction` instead? Going to test it out and see how it look in code, and if it brings good semantics.

**Review by ReubenBond — APPROVED** [review]
I'll push a PR with some minor changes

**Comment by ReubenBond** [comment]
@jan-johansson-mr the tests you added didn't pass for me when I ran them. Did they pass for you?
I pushed a commit to connect some loose ends, please take a look.

What should the behavior of `CreateNestedTransactionScopeAndSetValueAndInnerFailAndAssert` be?

**Comment by jan-johansson-mr** [comment]
Hi @ReubenBond,

Alright, with respect to the earlier comments, I've updated the `CreateNestedTransactionScopeAndSetValueAndInnerFailAndAssert` test case to be accurate.

Thanks

## Upcoming documentation ##

Once the PR is complete, I'm going to write documentation around transaction client as a proposal or inspiration. My plan is to document the *got-ya* with transaction option `Create`, and when to use it safely and when to avoid.

**Comment by ReubenBond** [comment]
>  The intent is that since both are TransactionOption.Create, they should be independent of each other.

I believe the second one would be taking a dependency on the commit of the first, since it was allowed to observe a write made by the first (and will need to validate its r/w set at that point, too, to ensure it doesn't violate serializability.

It's waiting for a transaction which is waiting for it. I may be wrong.

**Comment by jan-johansson-mr** [comment]
> I believe the second one would be taking a dependency on the commit of the first, since it was allowed to observe a write made by the first (and will need to validate its r/w set at that point, too, to ensure it doesn't violate serializability.
> 
> It's waiting for a transaction which is waiting for it. I may be wrong.

You are absolutely right, that's what's going on, and also what I'll write about in the upcoming documentation, as a gotcha  :-)

**Review by ReubenBond — APPROVED** [review]

**Comment by ReubenBond** [comment]
Merged. If there are any other improvements which might need to be made here, feel free to issue a follow-up PR.
Many thanks for the contribution, @jan-johansson-mr! This is something I've wanted for a long time, too

**Comment by HermesNew** [comment]
Good idea.This is very important and urgently needed for the subsequent processing of the transaction.

**Pull request merged**
