### PR TITLE
Update MySQL-Persistence.sql 

### PR DESCRIPTION
**Pull request by aqa510415008**
MySQL-Persistence.sql execution error   ([4126](https://github.com/dotnet/orleans/issues/4126))

### CODE REVIEW

**Comment by sergeybykov** [comment]
@veikkoeeva What do you think?

**Comment by veikkoeeva** [comment]
@sergeybykov Let's pull it in and thank @aqa510415008 for helping everyone. :) I took the test and ran it to latest MySQL database, the result is
persistence deployed

Rationale: The one in current master also succeeded (as seen in the picture in the issue), but I'm all for mystifying this one since seem to work and we're safe to assume an issue exists with the current version.

**Comment by sergeybykov** [comment]
Thank you, @aqa510415008 and @veikkoeeva!

**Comment by ReubenBond** [comment]
It's a little odd that this is needed, since the command delimiter is already specified above, but it's harmless.

**Pull request merged**
