### PR TITLE
Remove legacy packages

### PR DESCRIPTION
**Pull request by ReubenBond**
Removes legacy configuration (`ClusterConfiguration`, `GlobalConfiguration`, `ClientConfiguration`, `NodeConfiguration`) and all dependent types/packages
Removes all ".Legacy" packages.
Removes `OrleansCounterControl`, `OrleansManager`, `Orleans.PowerShell` (doesn't work without legacy config)
Removes `AzureClient`, `AzureSilo`, `ProviderConfiguration`

### CODE REVIEW

**Comment by jdom** [comment]
Nice! No more reliance on the legacy config objects? I bet creating this PR wasn't fun, but it's long due

**Comment by ReubenBond** [comment]
That's the bulk of it. The PR was fun in a zen garden raking sort of a way 😁
Not finished yet, still ~40 tests failing, but it's well on its way.

**Comment by ReubenBond** [comment]
I had a little more time today, so now BVTs are passing. ~10 functionals to fix before we're laughing

**Comment by ReubenBond** [comment]
This PR is ready for review. Functionals & distributed tests pass (I have a separate PR for our distributed tests).

**Pull request merged**
