### PR TITLE
Subscription Management and Multiplicity 

### PR DESCRIPTION
**Pull request by jason-bragg**
Subscription Multiplicity
- Each subscribe call creates it's own subscription to a stream, and multiple subscriptions (even from different points in the stream if recovery token is provided) can be established by a single grain.
- Each subscription can also be independently unsubscribed.

Subscription Management
- UnsubscribeAsync call has been moved from IAsyncObservable to StreamSubscriptionHandle.
- ResumeAsync call has been added to the StreamSubscriptionHandle to resume processing of a stream during grain activation.

### CODE REVIEW

**Comment by jason-bragg** [comment]
I apologize for the size of this PR.  I'd intended to break it into smaller work items, but the intermediate changes would have broke production clients.

**Comment by gabikliot** [comment]
This is a follow up on earlier PR https://github.com/dotnet/orleans/pull/202.

**Comment by ca-ta** [comment]
@jason-bragg 
Jason, I have a question related to the removal of UnsubscribeAllAsync():
How would a client be able to unsubscribe from a stream S in the following failure scenario:
1. Client calls ```SubscribeAsync```
2. ```SubscribeAsync``` succeeds and returns a ```StreamSubscriptionHandle```
3. Client crashes (e.g. due to power failure)  before having the opportunity to persist the received ```StreamSubscriptionHandle``` or unsubscribe using it.

In the above scenario, should the client be a grain - how would one prevent this grain from receiving events from stream X in perpetuity? How would one remove the client from the pub-sub persisted client list?

Thanks - (am I missing/misunderstanding  something?)

@gabikliot  - I think it would be great to add some information to the streams documentation regarding behavior in the following scenarios:

**Comment by jason-bragg** [comment]
Hi ca-ta,
	Good question.  You’re understanding is correct.  This is currently a vulnerability in our API, though this PR does not necessarily introduced this hole as the UnsubscribeAllAsync was never implemented.  I removed the Unsubscribe all because it was not implemented and the direction we want to go is to provide better subscription management to the users rather than simply have a ‘nuke’ option, which is what unsubscribe all was.
	The first pass at improving subscription management is the introduction of a GetAllSubscriptionHandles call on IAsyncStream.  This call will return a list of all handles owned by the consumer for a given stream.  This list of handles can be used to resume or unsubscribe from the stream's existing subscriptions.  The introduction of this call is already coded but the change depends on this PR.  The PR for this capability will be sent out soon after this one is merged.

**Comment by gabikliot** [comment]
Catalin, we will certainly update the streams documentation in the above scenarios once we are done with the implementation.

**Comment by gabikliot** [comment]
@ca-ta Check it out here: https://github.com/dotnet/orleans/pull/261

**Comment by ca-ta** [comment]
@jason-bragg , @gabikliot  - Thank you guys, ``` GetAllSubscriptionHandles ``` is exactly what I needed.

@gabikliot  
* It would be awesome if you could merge #261 today
* regarding the codeplex discussion - SMS appears to work for me (I do need #261 for unsubscribing). I will update the thread when I have everything working.

**Comment by ca-ta** [comment]
@gabikliot - regarding #261 and merging it: I've cloned @jason-bragg 's repo and I'm currently happily using that (I hope my plea to merge #261 did not sound pushy - I apologize if it did)

**Comment by gabikliot** [comment]
No problem Catalin. We usually try to leave PRs open for 24 hours to allow community to provide feedback. In urgent or trivial cases we sometimes merge immediately. Thanks for understanding!

**Comment by gabikliot** [comment]
@ca-ta , https://github.com/dotnet/orleans/pull/261 has been merged.

**Comment by ca-ta** [comment]
@gabikliot Awesome - thanks! (switching back to dotnet:master... :-) )

**Pull request merged**
