### PR TITLE
Updated to use vs sdk nuget packages. Removed unused files.

### PR DESCRIPTION
**Pull request by attilah**
* Updated to use VS SDK Nuget Packages, instead of installed SDK.
* Removed unused nuget files.
* Fixed tool name in resource file to be in sync with VSIX.
* Added cross VS compability to project files (to be able to open in either version of VS).

### CODE REVIEW

**Comment by sergeybykov** [comment]
Overall looks good.

For some reason, when I create a SiloHost project, it still targets 4.5 instead of 4.5.1 even though you seem to have updated it. Grain interface and class project target 4.5.1. We can fix it as a separate change.

Another issue unrelated to this change is that the grain interfaces extend `IGrain` instead of `IGrainWithGuidKey` or `IGrainWithIntegerKey`. Again, we can fix this as a separate change.

If you rebase it, I think we can merge and proceed to the other fixes. It is more important to switch to consuming VS SDK via NuGets, so that we can integrate OrleansVSTools.sln into the build process.

**Comment by attilah** [comment]
@sergeybykov I've investigated the problem you mentioned. The target framework version fully depends on what are you selecting in the top portion of the New Project dialog. That part works well.

However I found some discrepancies and outdated nuget information in the Silo template (not yet examined the others).

The questions is, which nuget packages NEED to be installed in the SiloHost project? I mean the azure packages for example. Is there a reason to include them, or not?! We should get straight with this at this point I think.

On the other hand, since vstemplate is dumb, we've put $if$ statements into the packages.config.txt file for example for the target="net45" part. Since depending in the target framework that should be net45, net451, net452, etc. Since that value does not exists as a template variable, we've to have repeat the nuget package imports with different target values.

**Comment by attilah** [comment]
@sergeybykov now I've an updated VS extension and SiloHost project template with nuget package support, which is .net framework version agnostic, it works with 4.5, 4.51, 4.52, 4.6.

After creation runs fine with F5.

It is using beta8 DI, since that was the master yesterday :) but I'll update that to the RC1.

Please check it out and discuss on how to proceed to other C# project types. That work will be much smaller I think.

**Comment by sergeybykov** [comment]
@attilah I was out today. I'll take a look over the weekend. Thanks!

**Comment by sergeybykov** [comment]
@attilah Can you rebase this on top of master? It includes extraneous commits. I'll try to taka a look at just your commits in it in the meantime.

**Comment by sergeybykov** [comment]
@attilah When I try to open OrleansVSTools.sln in VS 2015, it fails to load the .fsproj projects even though I have Visual F# option installed. What am I missing?

**Comment by attilah** [comment]
I made the rebase, hopefully everything is correct ;-)

Regarding the F# error, please send me what you see in the output window or something, probably some "targets" files missing?

I can't remember I touched the F# beside the target framework version.

**Comment by ReubenBond** [comment]
LGTM :+1:

**Comment by sergeybykov** [comment]
Thank you, @attilah!

**Pull request merged**
