### PR TITLE
ORLEANS0010

### LINKED ISSUE #8345: Add analyzer+codefix to ensure grain methods each have a unique alias for version tolerance
See this issue/comment: https://github.com/dotnet/orleans/issues/8200#issuecomment-1461072813

We could add an analyzer to automate this process and help to ensure that developers are pushed to the right path, where all methods are explicitly named. Similarly, we could do this for types (grain interfaces and even pocos).

Alternatively, we could make sure that the analyzer can add the automatically generated aliases on-demand so that developers can add the alias just-in-time (before an update is made).

### PR DESCRIPTION
**Pull request by ledjon-behluli**
close #8345 

As per #8345 ORLEANS0010 analyzes:

* POCOs (class, struct, record, record struct) that have `GenerateSerializer` applied to them to distinguish from non-orleans types.
* Interfaces (and their methods which are not static or properties) that extend base grain interfaces.

Analyzer:

analyzer

Fixer:

fixer

Tests:

tests

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/orleans/pull/8643)

### CODE REVIEW

**Comment by ledjon-behluli** [comment]
I see that 1 test (*UnitTests.TimerTests.ReminderTests_TableGrain.Rem_Grain_Basic_ListOps*) failed, but I don't think this is related to my PR, but due to flakiness on the test itself, see pic:

image

**Comment by ReubenBond** [comment]
This is great! One thing which this is currently missing is a way to automatically distinguish overloads, such as in this contrived case:

``` csharp
public interface IPingGrain : IGrainWithStringKey
{
    Task<string> Echo(string value);
    Task<int> Echo(int value);
}
```

Another thing (which we need for the member id analyzers, too) is to error when two aliases are identical. If we had this, maybe the above is less important.

**Comment by ledjon-behluli** [comment]
@ReubenBond I understand points 1 & 2. 

Regarding the last point, do you mean that we should add GTAttr and GITAttr in addition to the AliasAttr?

**Comment by ReubenBond** [comment]
> Regarding the last point, do you mean that we should add GTAttr and GITAttr in addition to the AliasAttr?

Yes, we should consider it, but it should be a separate analyzer/codefix.

**Comment by ledjon-behluli** [comment]
> Another thing (which we need for the member id analyzers, too) is to error when two aliases are identical. If we had this, maybe the above is less important.

Would you say it makes more sense to create another analyzer & fixer to address this? (ORLEANS0011)

This would than act the following way(s):

1. When users apply the same Alias to methods manually, ORLEANS0011 error's and provides a fix.
2. When ORLEANS0010 applies the same Alias to the methods, ORLEANS0011 error's and provides a fix.

In case of no 2, it would act as a 2-step process, the same way as `GenerateSerializerAttribute` and `IdAttribute` work

Makes sense?

**Comment by ledjon-behluli** [comment]
@ReubenBond Another question: should a grain implementation also get `Alias` applied? 
Currently this PR supports POCOs with `GenerateSerializer`, and interfaces extending a grain interface (including their methods)

**Comment by ReubenBond** [comment]
> Would you say it makes more sense to create another analyzer & fixer to address this? (ORLEANS0011)

I am not yet sure. Your suggestion is probably correct, but I am not an expert on the codefix infrastructure. Would the two steps you mention be a single gesture in the UI (eg Visual Studio)?

**Comment by ReubenBond** [comment]
> Another question: should a grain implementation also get Alias applied?

Grain classes should never need Alias attributes because they should never be serialized. Grain interfaces might, since they do get serialized (via grain references) and you can have things like `List<IMyGrain>`, where the alias would be used if available.

**Comment by ledjon-behluli** [comment]
> > Would you say it makes more sense to create another analyzer & fixer to address this? (ORLEANS0011)
> 
> I am not yet sure. Your suggestion is probably correct, but I am not an expert on the codefix infrastructure. Would the two steps you mention be a single gesture in the UI (eg Visual Studio)?

No they would be 2 gesture, its the same way as `GenerateSerializer` and `Id` currently work! First the GenerateSerializer fixer adds the attribute to the class which has `Serializable` attribute applied to it, and afterwards the the `Id` one kicks in since now the POCO has `GenerateSerializer`. It would work the same way. Its a 2-step/gesture solution for both, and looks a bit annoying and unnecessary, but considering that these will happen either through users manually adding `GenerateSerializer` (and `Alias` as a matter of fact) or through a previous analyzer/fixer combo, I believe its easier to maintain as each analyzer deals with its own responsibility.

**Comment by ledjon-behluli** [comment]
> > Another question: should a grain implementation also get Alias applied?
> 
> Grain classes should never need Alias attributes because they should never be serialized. Grain interfaces might, since they do get serialized (via grain references) and you can have things like `List<IMyGrain>`, where the alias would be used if available.

In that case (*and if we decide to make a sepparate analyzer/fixer for Alias name clashing*), I would say that this PR has done its job and technically is ready to be merged.

**Comment by ledjon-behluli** [comment]
> > Another question: should a grain implementation also get Alias applied?
> 
> Grain classes should never need Alias attributes because they should never be serialized. Grain interfaces might, since they do get serialized (via grain references) and you can have things like `List<IMyGrain>`, where the alias would be used if available.

Open to create another analyzer that error's when users apply 'Alias' to grain implementations since they are not supposed to do? 

*I know myself I did apply so in the past out of lack of knowledge* 😅

I guess nothing really happens even they do so, but might make it clearer for the users 🤷‍♂️.

**Comment by ledjon-behluli** [comment]
@dotnet-policy-service agree

**Comment by ledjon-behluli** [comment]
@ReubenBond can you re-run the failed test since I dont have permission to do so.

I'll open new issues/PRs according to the convo

**Review by ReubenBond — APPROVED** [review]

**Comment by ReubenBond** [comment]
@ledjon-behluli Maybe one future improvement we can make is an assembly-wide / csproj attribute to prefix aliases, so that they have namespacing. Otherwise, the generated aliases are all in the same key space (imagine collisions on types named "User" or "Result").

This doesn't handle generic type arity yet. I'll push a commit to add support.

**Comment by ReubenBond** [comment]
Actually, I think the corresponding CodeFix here should prepend or append the assembly name, at least by default. It's not as pretty or clean, but it leads them down a safer path.

**Review by ReubenBond — APPROVED** [review]

**Comment by ledjon-behluli** [comment]
> Maybe one future improvement we can make is an assembly-wide / csproj attribute to prefix aliases, so that they have namespacing.

Good idea! I guess we can have 2 ways to go about it:

1. add a new field in the current `AliasAttribute` called 'ns' which for compatibility should be an optional parameter like: 
  `public AliasAttribute(string alias, string ns = "")`
2. have another attribute like `AliasPrefixAtttribute(string prefix)` that if specified we should take that value, otherwise take the project name itself.

No 1 I believe would be simplier as we'd just combine the alias + ns, but it feels like duck taping it.
No 2 feels right, and I am in favor of, but I believe it will require changes to the code-gen logic to include this extra alias. I am willing to work on it, but need some guidance. I believe `OrleansSerializationSourceGenerator.cs` is the place this happens?!

**Pull request merged**
