### PR TITLE
Update Garbage Collection configuration page

### PR DESCRIPTION
**Pull request by galvesribeiro**
Added a note informing users that the settings proposed on this page, only work if the silo is running on multi-core (virtual)machines

### CODE REVIEW

**Comment by centur** [comment]
refered blog bost <-- post ;)

**Comment by gabikliot** [comment]
Sounds like an Azure bug? Or .NET feature? 
Do you have a reference to official documentation stating that GC settings cannot be overwritten on a single core? Also, should not depend on virtual/physical, right? Or another Azure "feature"?

**Comment by gabikliot** [comment]
Found it:
https://msdn.microsoft.com/en-us/library/system.runtime.gcsettings.isservergc(v=vs.110).aspx
"Server garbage collection is available only on multiprocessor computers."

Has nothing to do with Azure or virtual machines. .NET feature.

**Comment by galvesribeiro** [comment]
@gabikliot  sorry for the confusion... The intention when I say `(virtual) machine` is just to say `machine or virtual machine`. I didn't even mentioned Azure or something else on the doc. If that isn't clear please let me know so I can change to something more clear for the reader.

**Comment by sergeybykov** [comment]
Thank you, @galvesribeiro!

**Comment by gabikliot** [comment]
I slightly edited the wording in the doc.

**Pull request merged**
