### PR TITLE
Fix test cluster deploy deadlock

### PR DESCRIPTION
**Pull request by MelnikovIG**
Fixes https://github.com/dotnet/orleans/issues/5166 , but has some breacking changes public test APIs

### CODE REVIEW

**Comment by benjaminpetit** [comment]
Thanks @MelnikovIG !

I am all for removing these `GetAwaiter().GetResult()` calls. I don't think it is an issue if we have breaking changes here, since it's only public test APIs.

However, here the changes are only on the return type of the method, so I can see that, if someone isn't careful when upgrading, will not see the change immediately, and will not await some of the calls.

We could rename the method with an "Async" suffix to them, to make the breaking change more obvious :). I know some people don't like the "async word everywhere", but I think it's not a bad thing when you mix async and synchronous calls on the same class.

I also see that you didn't changed the Stop method, any strong reason on why we shouldn't make this call also async (and maybe provide with some "legacy" synchronous stop method, for the dispose method for example) ?

**Comment by MelnikovIG** [comment]
@benjaminpetit marked breacking changes methods with async keyword, but i didnt changed stop methods yet, because they have a lot of dependencies.

@sergeybykov removed Orleans word from method names.

**Comment by MelnikovIG** [comment]
@benjaminpetit hm, some tests started fail with
```System.Runtime.Serialization.SerializationException: 'Type 'System.Threading.Tasks.Task`1' in assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' is not marked as serializable.'```
I think i need you help to handle this exception, its strange.

**Comment by MelnikovIG** [comment]
@dotnet-bot test functional

**Comment by MelnikovIG** [comment]
@dotnet-bot test functional

**Comment by MelnikovIG** [comment]
@dotnet-bot test bvt

**Comment by MelnikovIG** [comment]
@dotnet-bot test functional

**Comment by sergeybykov** [comment]
@MelnikovIG 👍 I kicked off a full functional run in VSO. Just to make sure because this touches TestCluster.

**Comment by benjaminpetit** [comment]
Thanks!

**Pull request merged**
