### PR TITLE
Renamed test category "Nightly" to "Functional"

### PR DESCRIPTION
**Pull request by sergeybykov**
Renamed test category "Nightly" to "Functional" to better reflect its purpose.

### CODE REVIEW

**Comment by gabikliot** [comment]
also need to change https://github.com/dotnet/orleans/blob/master/src/TestAll.cmd :"BVT|Nightly"

**Comment by sergeybykov** [comment]
Rebased and replaced with https://github.com/dotnet/orleans/pull/485.

**Comment by jthelin** [comment]
@sergeybykov You know you can rebase/squash and then (force) push to the same branch name to avoid creating additional PR don't you? 

That will just replace the change set to be merged for this PR but keep all the PR history.

**Comment by sergeybykov** [comment]
I didn't. :-)

**Pull request closed without merging**
