### PR TITLE
Update OneBoxDeployment libraries and code and fix annoyances

### PR DESCRIPTION
**Pull request by veikkoeeva**
- Changes NewtonSoft.Json to System.Text.Json.
- Changes System.Data.SqlClient to Microsoft.Data.SqlClient.
- Removes dependency on VS Enterprise in .sqlproj.
- Removes some unused Nuget dependencies.
- Fixes NullReference due to reference on old ASP.NET Core API analyzer.
- Updates all packages to the latest.
- Adds OneBoxDeployment specific global.json.

Updating the libraries make sense now that they are widely supported
and recommended. These changes anticipate also move to .NET 5 and
removing the last .NET dependency, which is the sqlproj project.

### CODE REVIEW

**Comment by veikkoeeva** [comment]
Work in progress still. :)

**Comment by sergeybykov** [comment]
@veikkoeeva Do you mean this PR is still work in progress or the sample after this PR?

**Comment by veikkoeeva** [comment]
@sergeybykov This PR is work in progress still. There are some issues that may affect people if they use this sample as-is. Such as that OpenAPI types show `application/json` also for errors, not just `application/problem+json` (it's a known problem in the libraries that isn't fixed but maybe can be mitigated), also web content root is not set correctly in tests (in case someone makes use of them, say, if adding Blazor app too), Serilog logging could use .NET diagnostics context (uses less resources, is nicer on log correlation) and it requires a bit of work to do with in-memory logging (during tests) etc. Have fixed these, I likely push changes during next weekend.

Then there is the case that the security headers that are added to the API have been deprecated and new ones are coming etc.

So I want to also show one way building a dependable system and solve perhaps annoying issues that may otherwise take days to sort out in real projects. In case someone is reading this, likely add Docker and Azure deployment scripts later (semi-made elsewhere). :)

**Comment by ReubenBond** [comment]
Is this still a WIP? We can label it as a draft, if so

**Comment by veikkoeeva** [comment]
@ReubenBond It is. I have hit some hard deadlines for about 1.5 weeks still. Not much to do, but I'd prefer to fix the small issues I know and know that one an hit if trying this.

**Comment by veikkoeeva** [comment]
@ReubenBond I think this fixes the most issues and updates to the latest so is good to merge.

I make a few more batches later. Some issues:
- Switching to the new storage API style (this still uses the legacy way).
- If someone adds a web application content root is not set as one expects.
- Dacpac may be a bit annoying since it requires command line tools (due to variables).

**Comment by veikkoeeva** [comment]
Ready to go, by the way. :)

**Comment by ReubenBond** [comment]
Thanks, @veikkoeeva :}

**Pull request merged**
