### PR TITLE
Fix 'dotnet pack --no-build'

### LINKED ISSUE #6073: error NETSDK1085 when creating package using dotnet cli 3.0.100
After updating `dotnet` tools to 3.0.100, creation of NuGet packages started to fail.

Looks like behavior might have changed in dotnet 3.* as compared to 2.* ([see changes](https://github.com/dotnet/sdk/commit/af4fc22af555a2cc647dc533436e764759ad827f)) and now 
`Microsoft.Orleans.CodeGenerator.MSBuild` violates `NoBuild` constraint. I believe this behavior is the same for 2.4.* and 3.0.* of `Microsoft.Orleans.CodeGenerator.MSBuild`.

#### Command: 
```powershell
dotnet pack --no-build .\Grains.Interfaces\Grains.Interfaces.csproj
```
#### Expected 
New NuGet package is created:
```powershell
Successfully created package '*********REDACTED*********\Grains.Interfaces\bin\Debug\Grains.Interfaces.1.0.0.nupkg'.
```
#### Actual
Error is thrown:
```powershell
C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(133,5): error NETSDK1085: The 'NoBuild' property was set to true but the 'Build' target was invoked. [*********REDACTED*********\Grains.Models\Grains.Models.csproj]
```

### Setup
I was able to reproduce issue by crating a simple project:
- `Grains.Interfaces.csproj` - contains one interface `ITestGrain : IGrainWithStringKey` with a single method `Task<int> CreateAsync(TestModel testModel);`
- `TestModel` is a POCO defined in `Grains.Models.csproj`
- `Grains.Interfaces.csproj` has reference to  `Grains.Models.csproj` and following NuGet configuration:
```xml
<PackageReference Include="Microsoft.Orleans.CodeGenerator.MSBuild" Version="2.4.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
<PackageReference Include="Microsoft.Orleans.Core" Version="2.4.3" />
<PackageReference Include="Microsoft.Orleans.Core.Abstractions" Version="2.4.3" />
```

### PR DESCRIPTION
**Pull request by ReubenBond**
Fixes #6073

@pechkarus @turowicz are either of you able to build this PR and test it? I tested locally with the repro sln I posted on the issue thread.

The fix is to use AfterTargets instead of DependsOnTargets. DependsOnTargets will invoke the requisite targets, whereas AfterTargets just signifies sequencing.

### CODE REVIEW

**Comment by ReubenBond** [comment]
Let's keep this as WIP while testing

**Comment by turowicz** [comment]
@ReubenBond added to my list. Will try today/tomorrow.

**Comment by turowicz** [comment]
@ReubenBond can you provide a zip file with the test project and dependencies that you need me to build?

**Comment by ReubenBond** [comment]
@turowicz I can provide you with signed nuget packages if that helps - otherwise perhaps you can build my branch from this PR and test that with your solution which was failing

**Comment by ReubenBond** [comment]
I tested this fix with the Orleans main solution and it passed tests. I think this is good to merge. If this ends up not working for you, @turowicz & @pechkarus, then we can take another look

**Pull request merged**
