### PR TITLE
Small telemetry correlation fix 

### PR DESCRIPTION
**Pull request by Vlad-Stryapko**
Updated the filter to correctly create an activity if traceParent is present in the context

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/orleans/pull/7506)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/orleans?pullRequest=7506) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/orleans?pullRequest=7506) before we can accept your contribution.<br/><br/>:x: Vlad-Stryapko [sign now](https://cla.dotnetfoundation.org/dotnet/orleans?pullRequest=7506)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/orleans?pullRequest=7506) it.</sub>

**Review by suraciii — COMMENTED** [review]
Do we want to modify the test to cover this? accessing `ActivityCreationOptions<ActivityContext>.TraceId` in sampler can reproduce it.

**Comment by Vlad-Stryapko** [comment]
@suraciii 
I've taken a look at tests and they should already cover it. 

For example https://github.com/dotnet/orleans/blob/dc7fd582e7f00e0f89a7790f99950f31fdb6109b/test/Tester/DiagnosticTests.cs#L93

It already has the following line:

`                Assert.Contains(activity.TraceId.ToHexString(), result.Id); // ensure, that trace id is persisted.
`

What's even more interesting is that I ran those tests and they succeeded. Then, I decided to add a separate test to compare trace ids, ran in in debug, saw that trace ids are different and the test failed. Now, the previously successful test fail as well. 

I'm not yet sure why the tests behave that way. Judging from the code itself, the tests you currently have should have caught the issue before.

**Comment by suraciii** [comment]
@Vlad-Stryapko If you access `options.TraceId` at here https://github.com/dotnet/orleans/blob/dc7fd582e7f00e0f89a7790f99950f31fdb6109b/test/Tester/DiagnosticTests.cs#L29 , some of tests would likely fail.

**Comment by suraciii** [comment]
> What's even more interesting is that I ran those tests and they succeeded. Then, I decided to add a separate test to compare trace ids, ran in in debug, saw that trace ids are different and the test failed. Now, the previously successful test fail as well.

Once you access the `TraceId` property, a new trace id will be generated, after that, `SetParentId` takes no influence, then tests fail.

**Comment by Vlad-Stryapko** [comment]
@suraciii 
Thanks, I got it. Merely accessing the TraceId in sampler indeed fails the test:

```
            static ActivitySamplingResult Sample(ref ActivityCreationOptions<ActivityContext> options)
            {
                var _ = options.TraceId;
                return ActivitySamplingResult.PropagationData;
            };
            static ActivitySamplingResult SampleUsingParentId(ref ActivityCreationOptions<string> options)
            {
                var _ = options.TraceId;
                return ActivitySamplingResult.PropagationData;
            };
```

The only thing I'm worried about is that I'd like this id to be used somewhere to make sure there are no compiler optimisations which would remove it.

**Pull request merged**
