### PR TITLE
Read only collections built in serialization

### PR DESCRIPTION
**Pull request by dVakulen**
Added <code>ReadOnlyCollection</code> and <code>ReadOnlyDictionary</code> built in serialization.

### CODE REVIEW

**Comment by sergeybykov** [comment]
This is great. Thanks! I'm curious, @dVakulen, are you using these types in your code? Is that how you decided you need to add built-in serializers for them?

**Comment by dVakulen** [comment]
No, I just like to write custom serializers. In fact this collections are used inside Orleans and because of missing built in serialization for them some already registered internal types were hitting the fallback serializer.

**Comment by sergeybykov** [comment]
Then I'm even more grateful!

**Comment by gabikliot** [comment]
Great indeed!

One suggestion: a lot of those methods now start looking very similar (sorted list, readonly list, list, ... * 3 (ser, desr, deep copy)).
Maybe next time we better refactor it a bit to avoid code duplication.

**Pull request merged**
