### PR TITLE
Hello-Orleans.TestingHost

### PR DESCRIPTION
**Pull request by jthelin**
- Add some simple automated tests to HelloWorld sample
   in order to demonstrate how to use the Microsoft.Orleans.TestingHost NuGet package.

### CODE REVIEW

**Comment by jthelin** [comment]
This change requested by @sergeybykov

**Comment by sergeybykov** [comment]
It still use the LocalSilo folder for running even though it doesn't actually need it. I think if we change output folder of HelloWorldNuget project to bin\Debug, add a reference to HelloWorldNugetGrains project to it, and remove post-build steps from HelloWorldNugetGrains, it will more clearly show that it doesn't need the SDK installed at all.

**Comment by jthelin** [comment]
You mean the old console app in this sample, not the new test case(s), right?

Yeah, that's an additional cleanup item I can shuffle in with this.

I pushed more commits to this PR so you can see the incremental steps,
but I will squash everything together once the PR build for that push completes.

**Comment by jthelin** [comment]
Build complete. Loading Squash.

**Comment by jthelin** [comment]
Added some extra comments to explain how TestingSiloHost is being used in these tests, and re-squash.

**Comment by pherbel** [comment]
@jthelin Good stuff

**Pull request merged**
