### PR TITLE
Update Declarative-Persistence.md

### PR DESCRIPTION
**Pull request by siva-github**
AddAzureTableStorageProvider() for emulator

### CODE REVIEW

**Comment by sergeybykov** [comment]
I'm confused - what's the reason for switching from Blob to Table here?

**Comment by siva-github** [comment]
Sorry, my bad! I thought it would be nice to use 'table' storage since the tutorial is using images of table storage - developer emulator (ASE). 

Also, if possible please  add the following option for people who start from 'Minimal Orleans Application'.It's easier to configure the storage provider in 'OrleansConfiguration.xml' using :
  <Globals>
  <StorageProviders>
     <Provider Type="Orleans.Storage.AzureBlobStorage" Name="TableStore"
      DataConnectionString="UseDevelopmentStorage=true" />
    </StorageProviders>
  </Globals>

and adding Microsoft.Orleans.OrleansProviders (nuget) to host.

I am new to programming and I thought this will help anyone like me who started from Minimal Orleans Application. Please excuse me if I am wrong. Thank you.

**Comment by sergeybykov** [comment]
> I thought it would be nice to use 'table' storage since the tutorial is using images of table storage - developer emulator (ASE).

But you are right - the illustrations are inconsistent with the content.

>Also, if possible please show the following option in the tutorial for the people who start from 'Minimal Orleans Application'.It's easier to configure the storage provider in 'OrleansConfiguration.xml' using 

We've moved away from promoting XML config a while ago. But we haven't updated the docs. I think instead of adding another XML snippet, we better rewrite the tutorial  with programmatic config.

**Comment by sergeybykov** [comment]
I merged this for the sake of consistency between text and images in the docs.
Thank you, @siva-github!

**Pull request merged**
