### PR TITLE
Remove strong naming

### PR DESCRIPTION
**Pull request by sergeybykov**
This will allow Orleans to freely consume non-strong-named dependencies, such as Microsoft.Framework.DependencyInjection.Abstractions.

### CODE REVIEW

**Comment by gabikliot** [comment]
+1

**Comment by sergeybykov** [comment]
I also removed the strong-naming hack for Microsoft.Framework.DependencyInjection.

One remaining issue is that we cannot take a dependency on Microsoft.Framework.DependencyInjection NuGets in Microsoft.Orleans.Runtime.nuspec yet because they are pre-released, and we are stable.

**Comment by jthelin** [comment]
Before we rush to rip out strong naming from everywhere, let's try to understand what the real cause of the problem is for issue #905.

The problems were introduced in PR #827. 
One of the major differences in that PR from our normal practices is use of fully versioned assembly names in references. For example:
``` xml
<Reference Include="Microsoft.Framework.DependencyInjection, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
  <HintPath>..\packages\Microsoft.Framework.DependencyInjection.1.0.0-beta7\lib\net45\Microsoft.Framework.DependencyInjection.dll</HintPath>
  <Private>True</Private>
</Reference>
```
We always try to use **just** assembly short name, and that was done partly to avoid hard version dependencies such as this! For example:
``` xml
<Reference Include="Microsoft.Framework.DependencyInjection">
  <HintPath>..\packages\Microsoft.Framework.DependencyInjection.1.0.0-beta7\lib\net45\Microsoft.Framework.DependencyInjection.dll</HintPath>
  <Private>True</Private>
</Reference>
```

We hit lots of versioning problems with the interns on the Geo project because their projects all used fully versioned assembly references, and those all magically disappeared (in favor of what was in the HintPath element) once the project files were switched to use assembly short names [as example above] 
BTW, it gets even worse once you start working with projects that are not all AnyCPU and that have 

Unfortunately NuGet package manager is pretty brain dead about the way it does version updates and often auto-adds the full name again when it does version updates. It is especially laughable when NuGet Package Manager writes a fully versioned assembly reference string, and then adds SpecificVersion=False  :(

So I am not sure whether this PR is really necessary or the right way to solve the issue #905.

To give us another data point, I have just submitted an alternate / different PR #911 that cleans up the assembly references in the project files (which i think we should do anyway, for consistency)

Having said this, there are various other reasons why NOT using strong naming might be desirable, so we quite probably may want to do your PR too ;)

http://blog.marcgravell.com/2014/06/snk-we-need-to-talk.html
http://strongnamingconsideredharmful.com/ 

:wink:

**Comment by veikkoeeva** [comment]
@jthelin "Geo project"? Do you care to elaborate? 

Your investigations strikes plausible. As for the other reasons, the Gitter firehose on occassion tells to drop strongnaming for the well-being of humanity. :)

**Comment by Allon-Guralnek** [comment]
@jthelin - What you wrote is correct, but only applies to the build process. PR #911 will help make the build process be less fussy about which assemblies it can use, but it won't affect the assembly binding that occurs at runtime. A signed assembly will still contain only strong-named assembly references (a hard requirement of signed assemblies), and therefore will still require a signed assembly to resolve that reference (which is, in the case of #905, not publicly available).

The only way a signed assembly can use code form an unsigned assembly is by loading it via reflection (as you do with grains). But of course, this is not an option for libraries which are used in code (i.e. directly, not via reflection).

**Comment by jthelin** [comment]
We do need to be cognizant about the full implications of this PR.

If Orleans assemblies are not strong named, then aren't we are now effectively mandating that Grain code **cannot** use strong naming either?

That will probably break a very large proportion of the existing Orleans code out there.

This is a change with BIG implications.

**Comment by jthelin** [comment]
Cross-posting the potential solutions that @Allon-Guralnek  noted on the original issue #905 thread.

@Allon-Guralnek wrote (wrt PR #911)

This would only affect the build process, not the runtime binding which fails. It would produce the exact same assembly and the same exceptions. The requirement in .NET is that signed assemblies only reference other signed assemblies. Since the OrleansRuntime assembly is signed, it's not possible to reference Microsoft.Framework.DependencyInjection, which is unsigned. So a signed version is created in the build process, before compilation, so you end up referencing aa signed version. There's nothing you can change in the project files to fix this. From what I understand, there are only three options:

1. Stop signing the Orleans assemblies, so they can have unsigned dependencies. This would allow using the official Microsoft.Framework.DependencyInjection NuGet package.
2. Include the signed DI assembly (the .dll file itself) with the OrleansRuntime NuGet package. This would fulfill the assembly reference requirement. 
3. Use an already signed DI NuGet package. Either ask your friends at Microsoft that publish it to sign it, or publish your own Orleans flavor of that NuGet, signed by you.

**Comment by Allon-Guralnek** [comment]
> If Orleans assemblies are not strong named, then aren't we are now effectively mandating that Grain code *cannot* use strong naming either?

That's true. But that raises the question, would assemblies containing grain code be strong-named by developers? In order to answer that, we need to understand the motivation to strong-name an assembly, i.e the benefits of strong names:

https://msdn.microsoft.com/en-us/library/wd40t7ad(v=vs.110).aspx

Going over that list, I can't see a single benefit for users of Orleans. Most of the benifits have to do with putting assemblies in the GAC, but I don't think that's a typical use-case for grain code (is it even supported?).

Therefore is running strong-named grain code really an important use-case that needs to be supported? Will it really break anyone?

Maybe this is a question that needs to be directed to the Orleans user-base. If I was asked, I would answer that dropping support for strong-named assemblies would not break my company's codebase, nor would it affect it in any way.

**Comment by jthelin** [comment]
Yes, I think we do need to understand from the community what is the real impact of the change, because it is pretty much a one-way trip once we take the red pill.

I know that .NET developer community opinion has flipped in recent years against using strong names, so may not actually be as big an issues as I fear. 
I did a quick search and most examples I found do not seem to be using SN.

**Comment by sergeybykov** [comment]
@jthelin 
> One of the major differences in that PR from our normal practices is use of fully versioned assembly names in references.

That's not the issue. The issue is that the M.F.DI assemblies aren't strong-named. Because of that, @attilah had to do that hack with us strong-naming them as part of the Orleans build, hence changing identities of the M.F.DI assemblies.

https://github.com/dotnet/orleans/issues/905 is just a side effect of that, but the real issue is that strong-named Orleans cannot depend on non-strong-named assemblies. That's the actual motivation for removing strong-naming from Orleans binaries.

The *fully versioned assembly* thing I think is misleading. This is what VS/NuGet put there, and I'm not convinced it's worth it to fight the tools, imperfect as they are. I'd like to understand what issues you've seen with interns with that (as a separate issue) because none of us here have experienced it.

>If Orleans assemblies are not strong named, then aren't we are now effectively mandating that Grain code cannot use strong naming either?

Yes.

> That will probably break a very large proportion of the existing Orleans code out there.

That's not my hunch. My impression is that the whole strong-naming nonsense has been primarily Microsoft thing, which was a requirement for releasing code externally until recently. It doesn't even make much sense on the backend. Why would somebody want to strong-name their grain binaries? There is absolutely no benefit in doing that.

CoreCLR allows strong-named assemblies to reference non-strong-named ones. The full CLR decided not to make the change.

> 2.Include the signed DI assembly (the .dll file itself) with the OrleansRuntime NuGet package. This would fulfill the assembly reference requirement. 

This is a bad option - redistributing somebody else's binaries under a different identity.

**Comment by jthelin** [comment]
@veikkoeeva 
> "Geo project"? Do you care to elaborate? 

https://github.com/OrleansContrib/meetups/issues/1#issuecomment-148417403

:)

**Comment by attilah** [comment]
LoL, @sergeybykov you took my PR? :-P I wanted to contribute this :D :sadpanda:

**Comment by sergeybykov** [comment]
@attilah Sorry! You said you had lost it. :-)

**Comment by jthelin** [comment]
> That's not the issue

> I'm not convinced it's worth it to fight the tools, imperfect as they are.

Agreed, it is a slightly different issue, but you have no idea what a huge mess the Geo interns got themselves into by "just letting the tools do their thing" At one point nothing at all would run because of mismatching different assembly references between various sub-projects & sub-systems. I had to spend a very long weekend hacking their project files in line with PR #911 to get things working again! :cry:

> because none of us here have experienced it.

Yes, we never really experienced this on Orleans project, but mostly because I got you all to do assembly references (and project cross references) right in project files from the get-go ;)

**Comment by sergeybykov** [comment]
>Agreed, it is a slightly different issue, but you have no idea what a huge mess the Geo interns got themselves into by "just letting the tools do their thing" At one point nothing at all would run because of mismatching different assembly references between various sub-projects & sub-systems. I had to spend a very long weekend hacking their project files in line with PR #911 to get things working again! :cry:

I'd like to understand what this was about. Strangely, We've never heard such complains from anybody else so far.

**Comment by attilah** [comment]
But I told you that I'll redo it when you say: It is time! :D

But now I've to say: I'll be back!

**Comment by jthelin** [comment]
> Why would somebody want to strong-name their grain binaries? There is absolutely no benefit in doing that.

I don't disagree about the lack of benefits of SN, but some companies have corporate policies about that sort of stuff. Hard to know real impact by observing from the Redmond microcosm.

I am not pushing back on this change itself, as long as we understand the one-way journey we are about to embark upon, and seems we all are cognizant of that.

> If Orleans assemblies are not strong named, then aren't we are now effectively mandating that Grain code cannot use strong naming either?
> Yes.

Merging #911 is separate thing, but is good build hygiene and consistency that I foresee will save us many headaches in future. ;)

**Comment by veikkoeeva** [comment]
@jthelin 
> >"Geo project"? Do you care to elaborate?
>
> OrleansContrib/meetups#1 (comment)
:+1:

**Comment by sergeybykov** [comment]
I think there is a compromise here, which I don't like thought. We could try to strong-name just Orleans.dll, so that one could compile strong-named grain assemblies.

**Comment by attilah** [comment]
Noooo, please nooooo ;-)

Once we're getting DI onto the client side too, then strongnaming problem will arise again!

**Comment by sergeybykov** [comment]
@attilah 
>Noooo, please nooooo ;-)

>Once we're getting DI onto the client side too, then strongnaming problem will arise again!

Exactly. Let's bite the bullet now. If somebody is really is a dire situation, they can do the strong-naming hack against Orleans binaries.

**Comment by attilah** [comment]
Yes the same way as I did, it is really non-obtrusive, and it does not take too much to add it to any project thanks to that Nuget package. We can even add this possibility to the release notes later :D

**Comment by sergeybykov** [comment]
I like the release notes idea - point to a prescription of what to do if you need strong-named Orleans.

**Comment by sergeybykov** [comment]
I removed specific version info from OrleansRuntime' references to DI assemblies as @jthelin suggested.

**Comment by sergeybykov** [comment]
If you think this will break your code, please voice your concerns. Now that https://github.com/dotnet/orleans/pull/528 is merged, we need to decide on whether we remove strong naming before next release that we plan to have fairly soon.

**Comment by sergeybykov** [comment]
Rebased and updated. Still don't hear any objections from the community about this.

**Comment by ReubenBond** [comment]
I am all for this

**Comment by veikkoeeva** [comment]
:+1:

**Comment by veikkoeeva** [comment]
Spotted this: [To Strong Name or not to Strong Name?](http://lanyrd.com/2015/dot-net-unboxed/sdtmcd/):

> Tuesday 27th October, 2015
>
>9:45am to 10:25am (CST)
>
>In the past few years, requests for .NET OSS libraries to add a strong name have often resulted in massive comment threads, with lots of strong opinions and confusion about whether there is ever a reason to use strong naming. Let’s try to dispel some of the confusion. We’ll look at the pain that strong naming has caused, the reasons people might want to use strong names, and what the workarounds are if you need a strong named version of a library which doesn’t have one.
>
> About the speaker
> This person is speaking at this event.
Daniel Plaisted
>
> I work on the .NET Framework at Microsoft. Ask me about Portable Class Libraries or MEF!

**Comment by galvesribeiro** [comment]
Guys, Do we have a progress on that matter? What is missing in order to rip of the strong name?

**Comment by sergeybykov** [comment]
Nothing other than giving people time to object. We were also waiting for the codegen change to go in first, which is now in.

**Comment by ReubenBond** [comment]
The community has had enough time now, I think we should merge this :)

**Comment by galvesribeiro** [comment]
:+1:  @ReubenBond

**Comment by jkonecki** [comment]
Remove, remove, remove! ;-)

**Pull request merged**
