### PR TITLE
Fixed wrong reserved word escape indicators and a spelling error

### PR DESCRIPTION
**Pull request by dVakulen**
For issue #872

### CODE REVIEW

**Comment by gabikliot** [comment]
Can you please separate the 2 last commits about "Coreclr compatibility: Delegate.CreateDelegate -> MethodInfo.CreateDelegate" from that PR and submit them as a different PR?
Both in order not to confuse unrelated things, being able later on to track changes separately and also to be to able to discuss and review each change separately.
I am ready to merge the SQL changes, but would like to review  Coreclr compatibility separately.

**Comment by dVakulen** [comment]
Done. Just accidentally pushed those two while this PR wasn't accepted.

**Comment by veikkoeeva** [comment]
@dVakulen I'm not one of the core maintainers, but could you squash the commits into one? Git may not be your friend (yet), so if that's problematic and you would like to proceed anyhow, pop by in Gitter and we'll get it sorted. :)

**Comment by dVakulen** [comment]
Commits squashed.

**Comment by gabikliot** [comment]
Thank you.

**Pull request merged**
