### PR TITLE
fix for #637 - Exception in RegisterOrUpdateReminder with SQL system store

### PR DESCRIPTION
**Pull request by kucheruk**

### CODE REVIEW

**Comment by veikkoeeva** [comment]
@kucheruk There are actually two places where is this condition due to SQL Server 2000 code branch, and the newer ones.

**Comment by gabikliot** [comment]
As I explained in https://github.com/dotnet/orleans/issues/637#issuecomment-124152405, we actually do not need to compare eTags at all in the case of the Upsert operation. It should be a blind overwrite. So you can either remove the comparison with etag in your code all together or leave what you wrote `AND ETag = @etag OR @etag IS NULL` which reads to me as "I don't care about etag". So this looks like the right fix.
@veikkoeeva , please notice that we do still need to set the **new etag** to some random Guid upon every write (every Upsert) and return it back when read. We just don't need to use it for comparison in `Upserts`.

**Comment by veikkoeeva** [comment]
@gabikliot, @kucheruk As per
> Therefore: we do still need to set the new etag to some random number upon every write (every Upsert) and return it back when read. We just don't need to use it for comparison in Upserts. 

Looking at the code, I would say there should not be ``etag`` comparison at all. Not even with the ``IS NULL`` condition as it works only when Orleans explicitly sends a null etag to the database when it calls to [SqlReminderTable.UpsertRow](https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/ReminderService/SqlReminderTable.cs#L77). This is what looks like is happening, but removing that condition altogether makes it more robust and the intent in SQL clear (I think, especially if one wants to provide test SQL scripts) and as an added bonus there's less code and less bit on the wire (not much, but less nevertheless :)).

Therefore I would suggest removing the etag comparison altogether from ``UpsertReminderRowKey`` [here](https://github.com/dotnet/orleans/blob/master/src/OrleansProviders/SQLServer/CreateOrleansTables_SqlServer.sql#L498) and [here](https://github.com/dotnet/orleans/blob/master/src/OrleansProviders/SQLServer/CreateOrleansTables_SqlServer.sql#L996). Then it doesn't need to send as a parameter either in [OrleansRelationalExtensions.UpsertReminderRowAsync](https://github.com/dotnet/orleans/blob/master/src/Orleans/RelationalStorage/OrleansRelationalExtensions.cs#L419) and can be removed. The etags are generated in the database as before and returned as before.

Now, as this got a bit more to do, @kucheruk do you need advice how to test changes in the Orleans code with your own deployment? Writing a test would be more cool, of course, as it would also bring the backend implementations on the same line, so to speak, but would also be more laborous and hence not strictly warranted. :)

**Comment by gabikliot** [comment]
The fixes look good to me, tests as well. What do you think @veikkoeeva ?

**Comment by veikkoeeva** [comment]
@gabikliot Looks good to me. The checks have been removed and also unneeded code removed. The only other way to know if all is good is to actually give it a spin. Well done.

**Comment by gabikliot** [comment]
Thank you Evgeniy! Great catch and a good fix, plus a test.

**Pull request merged**
