### PR TITLE
Optimized PublicOrleansTaskExtentions.Ignore()

### PR DESCRIPTION
**Pull request by jdom**
Optimized PublicOrleansTaskExtentions.Ignore() to avoid going through the async state machine unnecessarily.
I had this code in my repo for very long, and since this is a heavily used method, I think it's worth optimizing.

I did run some benchmarks, and the improvements in perf are from 2 times to 16 times (depending on whether the preceding task completed synchronously or not, and whether it failed or not). The point is, in all situations I found improvements in perf.

The Benchmark results are as follows:

#### Completed synchronously
```
                  Method |     AvrTime |    StdDev |          op/s |
------------------------ |------------ |---------- |-------------- |
        IgnoreUsingAwait | 137.0142 ns | 0.4176 ns |  7,298,515.37 |
 IgnoreUsingContinueWith |  14.4233 ns | 0.0593 ns | 69,332,185.35 |
```

#### Failed synchronously
```
                  Method |    AvrTime |    StdDev |       op/s |
------------------------ |----------- |---------- |----------- |
        IgnoreUsingAwait | 20.7958 us | 0.1675 us |  48,086.69 |
 IgnoreUsingContinueWith |  1.2535 us | 0.5995 us | 797,791.52 |
```
 
#### Completing asynchronously
```
                  Method |       AvrTime |      StdDev |         op/s |
------------------------ |-------------- |------------ |------------- |
        IgnoreUsingAwait | 1,163.1511 ns | 211.5803 ns |   859,734.17 |
 IgnoreUsingContinueWith |   668.6211 ns | 132.1161 ns | 1,495,615.61 |
``` 

#### Failing asynchronously
```
                  Method |    AvrTime |     StdDev |       op/s |
------------------------ |----------- |----------- |----------- |
        IgnoreUsingAwait | 26.9202 us | 12.1708 us |  37,146.83 |
 IgnoreUsingContinueWith |  4.3352 us |  0.0552 us | 230,672.58 |
```

The benchmark code itself is in this gist: https://gist.github.com/jdom/65cd644bbcab9a41a75a

### CODE REVIEW

**Comment by gabikliot** [comment]
Julian, is there any concern that task returned by CW (the `task.ContinueWith`) will be broken with CancellataionException in case that CW does not run (if the actual task succeeded), since you specified `TaskContinuationOptions.OnlyOnFaulted`. And in such a case the non-observed cancelled task will escalate to Finalizer thread with UnobservedException? Is this possible?

**Comment by gabikliot** [comment]
Did you use `TaskScheduler.Default` deliberately? Instead of `TaskScheduler.Current`.

**Comment by jdom** [comment]
@gabikliot there is no need to observe a canceled task (there is no raised, it is only surfaces as an OperationCanceledException if you await it, so no need to observe any of it, whether it is because the previous task was Canceled, or because the previous task ended as faulted so that the continuation task is Canceled).

Regarding the usage of `TaskScheduler.Default`, yes, it's deliberate. Nevertheless, because I used `TaskContinuationOptions.ExecuteSynchronously`, there is no background thread or anything, the TaskPoolScheduler guarantees that it can run in the same thread.

**Comment by gabikliot** [comment]
So a failed task results in Unobserved Exception if it is not awaited. 
But cancelled task does NOT result in Unobserved Exception if it is not awaited?

As for `TaskScheduler.Default` - I think based on what you wrote it even makes more sense to use TaskScheduler.Current. So we are running on some TaskScheduler X. The task we are about to ignore was created and runs on  TaskScheduler X. Now you are asking to do CW `ExecuteSynchronously` but on a different TaskScheduler? What is the benefit? Sounds like an extra overhead of switching to a different scheduler, instead of inlining and executing synchronously on X.
No? I got it wrong?

**Comment by gabikliot** [comment]
BTW, to be clear, I am not trying to pick up on that PR.
I think this PR is great!
Actually, I clearly remember that our initial version of `Ignore` used to do exactly that. Then I got second thoughts exactly about the questions I am asking you now, plus I saw a bunch of other places doing `Ignore` with `await` and not with `CW`, and so to be 1000% sure and err on the correctness side I switched it use `await`. 
I am totally fine to moving back to `CW`, just want to be 100% sure.

**Comment by jdom** [comment]
correct, a canceled task does not result in an exception. Period. Neither observed nor unobserved. It only materializes as an exception when awaiting it.

Regarding the scheduler, there is no need to *transition* to another thread or anything, the scheduler code just invokes the continuation without any further transitioning. `TaskScheduler.Current` *might* also do the same (not try to be smart about where to schedule it and avoid transitions), but it might not. I was told to do this by Stephen Toub in an email some time ago:

> [Toub] Whenever you use ContinueWith, I recommend being explicit about the TaskScheduler you want to target.  If you don’t specify one, it’ll end up being TaskScheduler.Current, which if you’re inside of a Task will be whatever scheduler is associated with that Task, and that means you need to test more cases.  If you instead specify TaskScheduler.Default (which targets the ThreadPool), in particular for your own internal continuations like the one in StartAsGenericTask, that’ll limit the variability in behaviors you need to test for.
[jdom] I’m using TaskContinuationOptions.ExecuteSynchronously because we expect very short continuations. Should I still use the Default scheduler?
[Toub] That’s fine.  The default scheduler will always allow inlining of continuations, meaning that with ExecuteSynchronously, TPL will be able to execute the continuation synchronously on the thread completing the antecedent without needing to queue to some other thread.

**Comment by gabikliot** [comment]
Got you about canceled task!

Re: `TaskScheduler.Default` - so in case of `ExecuteSynchronously`, it will inline on the current thread but switch the TaskScheduler from Current (X in my example) to Default (thread pool)?

**Comment by gabikliot** [comment]
This is OK to merge from my perspective. Looks good.
Not sure about the timing of 1.2.0 merge, so not going to merge until 1.1.0 is out.

**Comment by sergeybykov** [comment]
1.1.0 is already in a branch. We are not holding any PRs that are ready.

**Comment by jdom** [comment]
thanks for merging. 
BTW, for the record @gabikliot , I'm not sure what you mean by "switch the TaskScheduler from Current to Default", the task scheduler only comes in before invoking/inlining the continuation, but because the `Ignore` method doesn't return a task, this ThreadPool scheduler is only used to execute the continuation inline and there is no "permanent" switch or anything like that. People can still await the original task by using the Current scheduler and so on if they want (nevertheless Ignore is typically used when you don't care to continue it, but still)

**Comment by gabikliot** [comment]
@jdom, I was indeed talking about  the ThreadPool scheduler that is only used to execute the continuation inline (of course there is no "permanent" switch or anything like that). The current thread executes the Ignore method of TaskScheduler X. Now this thread needs to execute CW inline, but it needs to change the Current scheduler from X to ThreadPool, just for this CW. Don't know how expensive or not it is (maybe just one line, maybe more), but looks redundant. That is what I was asking about: " it will inline on the current thread but switch the TaskScheduler from Current (X in my example) to Default (thread pool)"

**Comment by jdom** [comment]
I think I understand what you are asking now. Well there is not really a "switch", as I understand it, each Task is scheduled on a scheduler, so if we were to use Current, it would be at least exactly the same overhead as scheduling on Default. Nevertheless we know Default always inlines and is very optimized for this particular scenario. We cannot know that about Current (although most of the times it will be the OrleansTaskScheduler, and I haven't checked how it handles this situation), but it can't be better than the heavily tuned default scheduler, either if it is the OrleansTaskScheduler or a custom one.

**Comment by gabikliot** [comment]
:+1:

**Comment by gabikliot** [comment]
Great points about inlining in our scheduler.
Unrelated to that PR you might want to take a look at how we currently do inlining:

Per activation scheduler: https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/Scheduler/ActivationTaskScheduler.cs#L105
Global scheduler: 
https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/Scheduler/OrleansTaskScheduler.cs#L309

You might find out those can be optimized further to do more inlining, or do the checks more efficiently. I can tell you for sure that getting the most optimized inlining was not on my radar when implementing those, it was mostly to get it right and inline only what is allowed to be inlined without breaking the single threaded execution semantics. So there might be opportunities for optimizations. I can provide more details on how the scheduler works.

**Comment by jdom** [comment]
ok, I'm not that familiar to optimize them right now, but it something we might consider in the future.
But for sure it shows that in this particular implementation at least (the `Ignore()` extension method), we certainly don't need the Orleans context or anything like that. I almost kept the default CW overload (which is to use Current) until I remembered Toub's conversation. I'm more glad now that I did the change. The benchmarks I had were outside the Orleans scheduler entirely, so I would expect even less CPU overhead now :)

**Comment by veikkoeeva** [comment]
:+1: * :100: I learn just by watching this! :D

**Pull request merged**
