### PR TITLE
migrate Activate Deactivate Tests from VSO

### PR DESCRIPTION
**Pull request by NingnaD**

### CODE REVIEW

**Comment by gabikliot** [comment]
I would avoid creating Internal grains and Internal grain interfaces projects. The grains (and interfaces) should only use public (not internal) APIs. The internal Test project is for white box testing of run-time internal components. I would try to keep this separation and try to put the vast majority of the tests in the non-internal Test project.

**Comment by jthelin** [comment]
Yes, I had to do something similar to what @gabikliot suggests to avoid using internal interfaces for the stream filter tests PR #937 

@NingnaD -- There is possibly some overlap between this PR and #937 because `IActivateDeactivateWatcherGrain` is included in that PR too.
https://github.com/dotnet/orleans/pull/937/files#diff-2bafb341b1d36fa7584e5bfb057e6cbf

**Comment by sergeybykov** [comment]
See my comment https://github.com/dotnet/orleans/pull/937#issuecomment-155944073.

There is indeed some overlap, and it is killing me now. I think we should go with the approach that we've taken with @NingnaD, and refactor those grain interfaces/classes/tests as a second phase.

**Comment by sergeybykov** [comment]
@NingnaD This was a bad rebase - reverted a bunch of recent changes.

**Comment by jthelin** [comment]
I think still requires CLA to be signed before we can merge?

**Comment by sergeybykov** [comment]
Ningna signed the CLA I believe. Don't merge it just yet anyway. I had some test issues in VSO that I need to investigate.

**Comment by jthelin** [comment]
@sergeybykov You should check with the Open Tech guys (eg Asir) about the CLA records, because the CLA Bot does not appear to know about that. 
Status tag is supposed to be auto-updates by the Bot when online CLA process is followed, but something in the chain might be broken.

DotNet Foundation projects need their own CLA because it is separate legal entity, but once signed applies to to all DotNet projects. 
Azure and Microsoft projects use different CLA, and likely other different groups too.

**Comment by sergeybykov** [comment]
Ningna did receive a confirmation email. I manually reset the tag.

**Comment by jthelin** [comment]
I will merge this so we can move things forward and build upon this start, but with the understanding that we do need to go back and address @gabikliot concerns about not depending on internal runtime implementation functions at some point.

**Comment by sergeybykov** [comment]
Oh, no! It wasn't ready to be merged - the corresponding updates to the VSO tests were breaking something in an non-obvious way. That's why we kept open while I tried to figure out the VSO issues.

**Comment by sergeybykov** [comment]
I think I better revert this merge, so that the VSO test issue won't become a blocker for merging other PRs.

**Comment by jthelin** [comment]
Oops. My bad. :(

Adding a status update comment to this thread would have been useful @sergeybykov !

**Comment by sergeybykov** [comment]
Sorry, my fault. I kept thinking it was one test run from being ready to merge for a week. I should have updated the status.

**Pull request merged**
