### PR TITLE
Coreclr compatibility: xUnit test migration (TesterInternal project)

### PR DESCRIPTION
**Pull request by galvesribeiro**
This PR has the following goals:

1. Remove the MSTest runner from **TesterInternal** project and replace it with xunit.runner
2. Keep MSTest assertion APIs for now so there will be no changes on the assertion and test logic so far
3. Keep the test code with the minimal changes as possible.
4. Make the **TesterInternal** and **Tester** project to run on Jenking/CI with xunit.runner
5. Move one step forward to #368 by (finally)removing the dependency of MSTest and adopting xunit which is the most supported test runner for DNX/CoreCLR/.NetCore and is what ASP.Net and .Net Core teams are already using on it.

Special thanks to @jdom for kindly pre-review and fix this big/hard PR on my fork for weeks before I actually create this PR, and for @centur for teach me how to use Theories in xunit. Kudos for both of you! :)

Note: There will be 1 more commit to this PR after the core team and community reviews here before the merge that will move **TesterInternal** project from src/ to test/ to be together with already merged/migrated (#1288) **Tester** project and conform with xunit pattern for .Net Core/xproj projects.

### CODE REVIEW

**Comment by galvesribeiro** [comment]
@dotnet-bot please test it

**Comment by galvesribeiro** [comment]
@dotnet-bot test this please

**Comment by jthelin** [comment]
Great job folks! :+1:

**Comment by jdom** [comment]
Running functionals with TestAll.cmd script (which uses the xunit console runner) have several failing tests, but using the vstest to run xunit (as our current CI build does) has the same failure rate as we had before. So there is no extra issues when merging this now. We'll try to solve the issues when running using the xunit console later.
Thanks @galvesribeiro !

**Comment by sergeybykov** [comment]
Thank you, @galvesribeiro! We are a huge leap closer to the CoreCLR goal now.

**Pull request merged**
