### PR TITLE
Added relational data storage documentation

### PR DESCRIPTION
**Pull request by veikkoeeva**
This adds relational data storage implementation documentation.

### CODE REVIEW

**Comment by veikkoeeva** [comment]
I change some other parts of the documentation where relationa storage is mentioned (e.g. not only SQL Server, but other databases too should be possible).

**Comment by gabikliot** [comment]
Great! Thanks!

**Comment by gabikliot** [comment]
I did a tiny tweak to the docs, to adjust some broken links.

**Comment by veikkoeeva** [comment]
:+1:

**Comment by sergeybykov** [comment]
This is excellent. Thank you, Veikko!

**Pull request merged**
