### PR TITLE
Testing for PreferLocalPlacement grain failure handling

### PR DESCRIPTION
**Pull request by jthelin**
This change adds some additional test cases for failure modes around [PreferLocalPlacement] grains. They use the existing `PreferLocalPlacementTestGrain` already in the code base.

- Test case PreferLocalPlacementGrain_ShouldMigrateWhenHostSiloKilled

- Test case PreferLocalPlacementGrain_ShouldNotMigrateWhenOtherSiloKilled

I think these test cases should always work ok, but they currently they only work intermittently.

__i believe these failures are being caused by some unrelated bug(s) in gateway routing that I would like to check the community wisdom about.__

The underlying problem looks like the test client is trying to route the message through the gateway on the silo that was killed, but does throws back the underlying `SiloUnavailableException` when it cannot communicate with that [now dead] gateway silo rather than resending through the connection to the other [still alive] gateway silo.

**Requesting more eyes to confirm the logic in the test cases are correct and should work?**

Note: This PR does not yet contain any fix(es) for the [presumed] underlying gateway issue, so is NOT ready to be merged into master branch yet.

Thoughts?

Failure mode:

```
Orleans.Runtime.SiloUnavailableException : 
The target silo became unavailable for message: Request *cli/6cc4dc86@3e67d7b8->S127.0.0.1:40001:0*grn/62F215C3/f9816ab2 #8: global::UnitTests.GrainInterfaces.IPreferLocalPlacementTestGrain:GetEndpoint(). 
Target History is: <S127.0.0.1:40001:0:*grn/62F215C3/f9816ab2:>

Result Standard Output:	

******************** Starting test ********************
Silo Primary : Address = 127.0.0.1:5888 Proxy gateway: 127.0.0.1:40000
Silo Secondary_1 : Address = 127.0.0.1:5889 Proxy gateway: 127.0.0.1:40001
Proxy grain was originally located on silo 127.0.0.1:5888
PreferLocalPlacement grain was originally located on silo 127.0.0.1:5888
Killing other silo SiloHandle:127.0.0.1:5889 not hosting locally placed grain
```

### CODE REVIEW

**Comment by gabikliot** [comment]
Totally possible it is related to client-GW.
We had one open issue about it: https://github.com/dotnet/orleans/issues/1775
so this may be related.
What would help is to make this test predictable. Using fixed grain id and not random will hopefully eliminate the randomness (we use grain id to hash to GW) and make it fail all the time.
Also, make sure you are shutting the silos down gracefully and not stopping abruptly.

**Comment by gabikliot** [comment]
Can we merge those 2 tests and mark them as Skip for now?
That will allow me to start looking into the issue without messing with multiple branches.

**Comment by jthelin** [comment]
Yes, i will do that @gabikliot 

Sorry - i haven't had any free time to dig into the problem in any greater detail this week due to other work priorities :(

**Comment by jthelin** [comment]
This is ready to merge now @gabikliot

**Pull request merged**
