### PR TITLE
Added test for usage of abstract/enum types from external libraries

### PR DESCRIPTION
**Pull request by randa1**
Following #1064 and #1072.

It's worth noting that the tests fail only if the types are used in generics - the serialization for `DoStuff(AbstractType p1)` will work but for `DoStuff(IEnumerable<AbstractType> p1)` will fail.

Currently the tests have the `Ignore` attribute as they are failing until there will be a fix from @ReubenBond.

### CODE REVIEW

**Comment by randa1** [comment]
Build has failed for this reason:
```
The process cannot access the file because it is being used by another process
```

Any way I can re-invoke it in Jenkins?

**Comment by gabikliot** [comment]
push another dummy, empty line or something, commit.

**Comment by jthelin** [comment]
I re-ran the build for this commit and got the same error, so i think it is some type of systemic problem resulting from this change and not just a transient build server issue.
http://dotnet-ci.cloudapp.net/job/dotnet_orleans/job/innerloop_prtest/361/

**Comment by jthelin** [comment]
I also mapped this PR branch onto my local machine, and i can repo the problem locally too, so unfortunately it is definitely a problem originating from this change set. :(

Make sure you do clean [delete the `Binaries` directory] before running the Build.cmd.

I haven't yet grokked what is in the changes set that might have caused the issue.

**Comment by randa1** [comment]
Thanks @jthelin, I'll take a look

**Comment by randa1** [comment]
Closing this PR, I'll open a new one with one good commit

**Pull request closed without merging**
