### PR TITLE
Relational Storage - Refactored and added full MySQL support

### PR DESCRIPTION
**Pull request by shayhatsor**
ok , it's a lot. I know.
My goal was to simplify the work of future integrations with other relational providers.
Keep in mind that I haven't changed any logic and kept all previous methods. The only change in logic I can think of is that I've added more strictness to ETag evaluation, but it acts as more of an assert than anything.
EDIT: AFAIK, there are currently no tests for the statistics publisher subsystem. we should add some to provide full test coverage.

### CODE REVIEW

**Comment by veikkoeeva** [comment]
@shayhatsor I try to give a look at this in the evening. I see you are up to some of the changes that didn't make it earlier regarding cross-db support and especially testing. A good thing.

Some notes -- and tangentials that might not be evident:
* There might be a need to support different parameter indicators. I chose `@` as a generic one as it works for SQL Server and MySQL. I've been thinking to add that to `ExecuteAsync` in `RelationalStorage` with some sort of query string modification. This is arguably more about general functionality, but in case it's easier to construct query strings dynamically too (and use reflection).
* With regards to query reflection, currently there's not compilation or caching of reflection results.
* With regards to parameter indicator, I've been thinking to add this "modificator" as an interceptor. Also a logger with the same design, the SQL formatting class already added there is planned to be used as part of a "pretty printer" of the query and the parameters with their values (if I remember correctly, or then I'd need another kind of a construct).
* I'm not sure about the reason of making `ExecuteAsync` in `RelationalStorage` non-static. In general I'm OK with that, though I prefer putting as much arguments as possible as parameters (without making it too cluttered or suffer a loss of performance) and collecting just the results, which generally results to function that might as well be static.
* Though `IRelationalStorage` as an interface doesn't need necessarily be used instead of `RelationalStorage`, it would seem prudent to use the interface so that the real implementation could be mocked if needed. This way it might be easier to instantiate relational storage with, say, an in-memory one returning pre-canned responses. I think Orleans infrastructure code doesn't yet directly support that. I didn't take a long enough look to see in which situations were it changed.
* Hmm, could there be a check for default installation ports (configurable?) to see if a given DB is present and prevent running tests for a DB that does not exist? A bit in the vein of how Storage Emulator is checked.

**Comment by veikkoeeva** [comment]
Also, my desktop is still wrapped in a cardboard box and I think I skip install MySQL on my wife's laptop, but I'll read the code with better thought. From a cursory look, looks good though.

**Comment by shayhatsor** [comment]
@veikkoeeva thanks for your input, regarding your suggestions:
> There might be a need to support different parameter indicators.

I know, but with this refactoring in place it'd be easy to add in case it's needed.
> I'm not sure about the reason of making `ExecuteAsync` in `RelationalStorage` non-static

In my opinion, a method shouldn't be static if it can be encapsulated in an instance. I've actually wanted to move all the methods from `RelationalStorageExtensions` to `RelationalStorage`, but thought it can be done later. most of them aren't used by current code anyway.
> Though `IRelationalStorage` as an interface doesn't need necessarily be used instead of `RelationalStorage`, it would seem prudent to use the interface

Well, I wanted to remove it. It seems to me that it would make more sense adding `IOrleansQueriesRunner`. but I'll have another look at my design, **I think I can simplify it**.
>could there be a check for default installation ports (configurable?) to see if a given DB is present

will be very easy to implement in the refactored code

**Comment by veikkoeeva** [comment]
@shayhatsor Well, if all one needs are parameters in a function and the output of it, there is no need it to be non-static (that's how it'd be in F#, for instance). In any event, adding interceptors would be instance specific.

Simplifying sounds good. I see you added refletion whereas I used strings. The original intention was to have an easy mechanism to add properties or overwrite them. Some of that were guided by thinking that I didn't know what I would need, so I did it that way. Just to provide some history. The codebase is moving fast and I don't want to be the sole memory of it now that you and some others are pushing it forwards. :)

Regarding notes about reflection and compiling delegates, you probably see that the design comes close to micro-ORM design. At least in intent, I haven't looked that hard to Dapper or others there are.

About stats test, you are right about that too. Especially formatting should be tested. I, probably also some others, have also ideas about refactoring the stats design of the DB, maybe some other parts too like "suspecting silos". One idea is also to make it so that no UPDATEs, only INSERTs and SELECTs and SELECT would just give the latest. That way one might be able to correlate better with the statistics as to what has happened in the silo. Maybe not as the default option, but kind of a "debug and tracing" script to test design. Especially coupled with when we get interception about grain communication graphs (I think of cliques).

**Comment by shayhatsor** [comment]
> The codebase is moving fast and I don't want to be the sole memory of it now that you and some others are pushing it forwards. :)

The **only** reason I was able to refactor the code is because your work made it possible for me to start from a good working code. I've made sure to not change 99% of the methods. This PR is more of a reshuffle than anything. I'll prepare a simpler version and push it soon.

**Comment by sergeybykov** [comment]
Seems like an effort in the right direction, although I don't understand most of the code. It's good that we have resident SQL experts @veikkoeeva and @jthelin to weigh in. :-)

>AFAIK, there are currently no tests for the statistics publisher subsystem. we should add some to provide full test coverage.

The more the merrier.

**Comment by veikkoeeva** [comment]
@shayhatsor OK, I'll wait a bit longer. Just ping if you need eyes. There's [Slush](http://www.slush.org/) for a few days still and I'm somewhat occupied.

**Comment by shayhatsor** [comment]
@veikkoeeva I've repushed the PR. I like it now ;)

**Comment by shayhatsor** [comment]
Notes on the `MySql` script:
* Most of the queries are kept as raw strings, same as the `MSSql` script. The rest are implemented as stored procedures because `MySql` doesn't support `IF ELSE` statements outside of functions/procedures.
* The `MSSql` & `MySQL` scripts are very similar. I've made sure they can be easily compared and reviewed.
* In the `MySql` script, I haven't added the `Description` field to the `OrleansQuery` table. It's currently unused in orleans. I think it should be removed from the `MSSql` script too.
* Following #985 the `Version` field in `OrleansMembershipVersionTable` is redundant. It should be removed from the scripts and the code. The `ETag` is the version. This change can be done later and will further reduce the hassle of introducing new relational implementations.

**Comment by veikkoeeva** [comment]
@shayhatsor Ack. I'll be here in about six hours and start looking at the code.

**Comment by veikkoeeva** [comment]
@shayhatsor I realize neither of use owns the code, but if we are working on common code, we should be comfortable with it &ndash; leave our mark, so to speak. Let's have the following as discussion points on how to proceed.

* Have you thought about why would someone issuing a query be interest on Orleans specific etag functionality or database specific implementation details such as escaping characters? In other words, why couple `IRelationalStorage` surface with these things? I think it would be better to move this etag functionality elsewhere and make implementation details invisible outside of this assembly. Escape characters actually would need to paired with a list of reserved words per database vendor and then the query augumented in `RelationalStorage` as is one plan with logging.

Background: The purpose of `IRelationalStorage` is to be an interface to ADO.NET functionality and be oblivious of anything to do with Orleans. It could be seen as a substitution of EF context or some micro-ORM surface. (Right or wrong, I plan to use SqlUtils as my ORM and avoid one depdency.)

The reason for introducing this is that using vendor specific libraries directly, such like `SqlCommand` or `MySqlCommand`, looks like is a no-go in a codebase that should support multiple databases with a minimum of a hassle. Using the generic functionality is, I think, very non-obvious especially if one wants to involve transactions (see Internet for the various ways the issue is either ignored or is vendor specific). Now it looks like there's a mixing of responsibilities.

* I see the previous has something to do with MySQL returning etags as longs instead of opaque binary blob. Can MySQL return it as a binary blob? If it could return the etag as an opaque binary blob, would it make away for the need for the new subclasses?

* From previous, why is `RelationalStorage` subclassed as per vendor? I see this is as *one way* of introducing differing functionality as per vendor in the code and as you have done with MySQL etags. Do we have an another known case for this?

Currently what I see is three more classes and constants spread across these classes, which is more shuffling around in the code when one wants to do something. To my eye it would be easier to put the constants to a dictionary and query by key. That is, to see them in one place. If needed, one can provide a façade [QueryConstantsBag](https://github.com/dotnet/orleans/blob/538e579e926ca7a12c310be2e3fa978e95a4ee6c/src/OrleansSQLUtils/Storage/QueryConstantsBag.cs) that does much of the same as `OrleansQueries` you have now introduced and without reflection, I think.

* You put the Orleans specific queries defined as extension methods to `IRelationalStorage` to [RelationalOrleansQueries](https://github.com/dotnet/orleans/pull/1008/files#diff-884ba45bfcf853bcd6d499c449e96401R39). Could this add something to some testing scenario (that using `IRelationalStorage wouldn't easily allow)`? Does to code become more discoverable? Faster?

Background: I was first thinking to use the reflection based code in which case this part wouldn't be needed as the code would have been quite short. Then I though that OK, this is code is likely changing slowly so it makes sense to hand-roll them for improved efficiency. As the the resulting code is quite long, I introduce them as internal extension methods to `IRelationalStorage` with the intention they wouldn't be seen across the public API surface. So, as a code organization tool to make the queries more easily discoverable. I was thinking that if I need testing, I could do it via `IRelationalStorage` and so there wouldn't be a need to introduce new classes. It could be I haven't though about something.

* I didn't see from the testing code, but could it "sniff" that if some smoke test fails with some exception telling the DB isn't there that the tests are skipped? The first round of SQL Server tests just bluntly assumed everyone has a VS and so LocalDb with default parameters. This ceases to be true when Orleans goes cross-platform, if not earlier even. Anyway, I'm fairly sure not everyone has MySQL installed. Not my wife at least. :)

**Comment by shayhatsor** [comment]
@veikkoeeva here are my thoughts :
> I realize neither of use owns the code, but if we are working on common code, we should be comfortable with it – leave our mark, so to speak

If by leaving a mark you mean making the project better, then I agree. I'm here to learn.
>why couple `IRelationalStorage` surface with these things? I think it would be better to move this etag functionality elsewhere and make implementation details invisible outside of this assembly

I see your point, I think it should be moved to `RelationalStorage`.
> MySQL returning etags as longs instead of opaque binary blob. Can MySQL return it as a binary blob? If it could return the etag as an opaque binary blob, would it make away for the need for the new subclasses?

Probably, but I got weird exceptions from the MySQL provider and the script was less readable. I'll look into it again. Then we can do without the new classes for now.
> it would be easier to put the constants to a dictionary and query by key. That is, to see them in one place.

Yes, if we're removing the new classes we should use an internal dictionary. I don't like `QueryConstantsBag` since it's too error prone. I believe there should be a read only dictionary that maps from an ado invariant name to a concrete class. e.g. an `AdoInvariantConstants` class that'll contains the database specific implementation details such as escaping characters.
>  If needed, one can provide a façade to QueryConstantsBag that does much of the same as  OrleansQueries  you have now introduced and without reflection, I think.

Most of the changes I've made were to not use strings as soon as possible. IMHO **strings are the root of all evil**. I think the reflection solution is clean and less error prone.
>You put the Orleans specific queries defined as extension methods to  IRelationalStorage  to RelationalOrleansQueries. Could this add something to some testing scenario (that using  IRelationalStorage wouldn't easily allow) ? Does to code become more discoverable? Faster?

the `RelationalOrleansQueries` uses the underlying storage to load and execute the queries, therefore I think it should stay. It implements the `IRelationalOrleansQueries` which might be redundant, I thought it might be good for testing - but now I think not.
> could it "sniff" that if some smoke test fails with some exception telling the DB isn't there that the tests are skipped?

should be easy to add. but this PR is too big as it is
>I'm fairly sure not everyone has MySQL installed. Not my wife at least. :)

A wife **must** stand by her husband. Therefore I'd think that she must always have all the DBs installed. with default settings, of course :)

Thanks for your invaluable input.

**Comment by veikkoeeva** [comment]
@shayhatsor No problem. I think I came across needlessly (unintentionally) poignant. Take with a pinch of salt. It has been a long week and still one day to go. I came across many things when running things on MySQL daily, so if there's something with binary, it wouldn't surprise me.

**Comment by shayhatsor** [comment]
@veikkoeeva No worries. 
P.S. I've pushed a new version with all the fixes. And to sweeten the deal, I've added a cache for the `DbProviderFactory` instances. It turns out that `DbProviderFactories.GetFactory` uses reflection to fetch the singleton instance on every call.

**Comment by sergeybykov** [comment]
Is this ready to be merged?

**Comment by shayhatsor** [comment]
@sergeybykov I believe so, but I'd like to first get @veikkoeeva's opinion. 
by the way, I'm not sure if you've noticed that after this PR is merged, Orleans can finally be deployed using 100% free and open source technologies : Zookeeper (or MySQL) for membership and MySQL for reminders and statistics. We should document this !

**Comment by sergeybykov** [comment]
@shayhatsor That will be a great milestone to document and celebrate indeed!

**Comment by gabikliot** [comment]
This fantastic @shayhatsor !

You know that now means?
That Orleans can now run fully hosted on **ANY** cloud provider that supports VMs with Windows and hosted MySQL. And all major public cloud providers support both nowadays:
1) AWS: https://aws.amazon.com/windows/products/ec2/ and https://aws.amazon.com/rds/mysql/
2) GCP (Google Cloud Platform): https://cloud.google.com/compute/docs/windows-quickstart https://cloud.google.com/sql/

**Comment by veikkoeeva** [comment]
Guys, sorry for the delays! I've been picking up sleep, "real work" and then some more endeavours lately -- but mostly sleep, and this got delayed. Only minor things like if there will be more database specific constants in `DbConstants`, maybe we'd need to figure out another way than constructor parameters. Maybe just add them directly to constant fields and/or to a collection to be easily enumerated/printed if there's a need for that. They chance slowly if ever, so that'd work.

I'm good with this, this was good job @shayhatsor!

**Comment by shayhatsor** [comment]
@veikkoeeva thanks, @sergeybykov let's merge

**Comment by sergeybykov** [comment]
Thank you, @shayhatsor and @veikkoeeva! Orleans is now even more open than it was just yesterday.

**Pull request merged**
