### PR TITLE
Remove SQL scripts from AdoNet NuGet packages

### PR DESCRIPTION
**Pull request by sergeybykov**
Based on the discussion in #4867, this PR is a replacement for #6044. It removes SQL scripts from the AdoNet provider packages. The prevailing opinion is that we shouldn't have them pollute the AdoNet packages, and that we don't even want a readme.md there.

We can separately decide how to let developers know where to find the scripts.

### CODE REVIEW

**Comment by mxplusb** [comment]
Has this been captured in the docs? I can update the docs if point me in the right direction.

**Comment by sheng-jie** [comment]
After remove the folder, it's not easy to find the script files even follow the [Configuring ADO.NET Providers](https://dotnet.github.io/orleans/Documentation/clusters_and_clients/configuration_guide/configuring_ADO.NET_providers.html) and [ADO.NET Grain Persistence](http://aka.ms/orleans-sql-scripts).

So the docs should be updated and be clearly.

**Comment by mxplusb** [comment]
@sergeybykov any thoughts?

**Comment by sergeybykov** [comment]
Please help me understand where the problem is.

[ADO.NET Grain Persistence](https://dotnet.github.io/orleans/Documentation/grains/grain_persistence/relational_storage.html) points to [ADO.NET Database Configuration](https://dotnet.github.io/orleans/Documentation/clusters_and_clients/configuration_guide/adonet_configuration.html) as requirement #3 at the top of the page.

[ADO.NET Database Configuration](https://dotnet.github.io/orleans/Documentation/clusters_and_clients/configuration_guide/adonet_configuration.html) list all the scripts in the tables.

Is that these links to individual script files don't make it obvious that one needs to download and run them?

**Comment by sheng-jie** [comment]
@sergeybykov The doc doesn't describe where to find the script for creating OrleansQuery Table.

**Comment by sergeybykov** [comment]
I submitted #6118 that hopefully addresses this.

**Pull request merged**
