### PR TITLE
Describe configuration for connecting azure web apps.

### PR DESCRIPTION
**Pull request by naeemkhedarun**

### CODE REVIEW

**Comment by gabikliot** [comment]
Great! Thank you!

**Comment by sergeybykov** [comment]
Excellent!

**Comment by gabikliot** [comment]
http://dotnet.github.io/orleans/Advanced-Concepts/Using-Azure-Web-Apps.

**Comment by veikkoeeva** [comment]
"New-AzureNetworkSecurityGroup -Name "Default" -Location "North Europe", I feel right at home. :+1:

**Pull request merged**
