### PR TITLE
Reactive Caching Sample Leftovers

### PR DESCRIPTION
**Pull request by JorgeCandeias**
Here are the rest of the changes for now. If #5485 surfaces a better approach, I'll come back to this.

Not super happy with [this commit](https://github.com/dotnet/orleans/commit/54ab4c1abae8e9b2a8d0f3266bd8777e9108bead) though. Is there any way we can disable the timeout warnings only for specific calls?

Also, very grateful for the tips on the previous PR! 👍

### CODE REVIEW

**Comment by sergeybykov** [comment]
>Not super happy with this commit though. Is there any way we can disable the timeout warnings only for specific calls?

I don't think masking the timeouts is a good thing to do. That would point people to a wrong direction. Maybe the code should simply add a timer for a period shorter than the timeout (e.g. 8 seconds in this sample) to make sure the `Task` gets resolved before the call times out?

I tried adding the following lines to ProducerGrain.cs while removing the log filtering, and it seems to work without timeouts:
```csharp
private TimeSpan timeoutTimerDelay = TimeSpan.FromSeconds(8);
private IDisposable _timeoutTimer;
…

_wait = new TaskCompletionSource<VersionedValue<int>>();

_timeoutTimer = RegisterTimer(_ =>  
{
          if (!_wait.Task.IsCompleted)
         _wait.TrySetResult(_state);
         _wait = new TaskCompletionSource<VersionedValue<int>>();
          return Task.CompletedTask;
},
null,
timeoutTimerDelay,
timeoutTimerDelay);
```

**Comment by JorgeCandeias** [comment]
I agree, that's a better approach, thank you for the feedback. I'm wondering if this could be even cleaner by returning a `Task.WhenAny()` to the caller, where one of the tasks is a delay with `timeoutTimerDelay` (a different one per call and resolving to an empty `VersionedValue<T>` by design) and the other one is the task from the `TaskCompletionSource`. Maybe it would let each call make better use of its timeout allowance, instead of having more recent calls break early because of the timer. Not yet sure if this will work though. I'll push some changes either way.

**Comment by sergeybykov** [comment]
>I'm wondering if this could be even cleaner by returning a Task.WhenAny() to the caller, where one of the tasks is a delay with timeoutTimerDelay

We have an extension method for that - `OrleansTaskExtentions.WithTimeout()`. I didn't employ it here just to avoid throwing timeout exceptions as it would.

**Comment by JorgeCandeias** [comment]
A few changes:

* Promoted the concept of version to its own `VersionToken` that makes explicit the special case of "No Version" (aka "move along, nothing to see here yet").
* `PublisherGrain` now fulfills a long poll with any new value it generates or... an explicit default of "none" just before each calling promise breaks.
* `ReactiveGrain` now has a `RegisterReactivePollAsync()` method that starts to look a bit like an API method. This sets up the long polling behaviour in one go.

The logs still show timeouts, but these are now due to the sample itself logging them, not to Orleans breaking promises.

**Comment by JorgeCandeias** [comment]
Forgot to remove the logging filters. Will do that later, please don’t accept this yet.

**Comment by JorgeCandeias** [comment]
Done.

**Comment by sergeybykov** [comment]
Thank you, @JorgeCandeias!

**Pull request merged**
