### PR TITLE
Cherry-picked fixes for 1.5.1

### PR DESCRIPTION
**Pull request by sergeybykov**

### CODE REVIEW

**Comment by ReubenBond** [comment]
Please also include:
#3249
#3250

**Comment by sergeybykov** [comment]
Added #3249, #3250, and #3258.

**Comment by ReubenBond** [comment]
In our meeting yesterday, @xiazen and @jason-bragg mentioned a bug in queue balancing logic which they wanted to fix in 1.5.1. Is #3267 that PR? i.e, can we ship once we merge that PR and include it here?

**Comment by sergeybykov** [comment]
@xiazen thinks now that that bug is "compensated" in 1.5.0 (and before) with another logic. So there's no need to patch it in 1.5.1. She is double-checking with @gabikliot.

**Pull request merged**
