### PR TITLE
Remove dependencies on Orleans SDK from project templates

### PR DESCRIPTION
**Pull request by sergeybykov**
Removed references to %OrleansSDK% environment variable and dependencies on Orleans SDK.
Removed post-build steps of copying files to LocalSilo folder of Orleans SDK.
Fixed paths to NuGet packages to work correctly when .sln and project files are in the same folder.
Added "using System.Threading.Tasks;" to .cs files.

### CODE REVIEW

**Comment by sergeybykov** [comment]
@jthelin Do we need also to update the SiloHost template to use Microsoft.Orleans.TestingHost NuGet?

**Comment by gabikliot** [comment]
So after that change the only dependence on the SDK will remain in the Samples? Should we update them all to use Nugets after this is merged?

**Comment by sergeybykov** [comment]
Yes, we'll update samples after that. They were produced with the old project templates and hence inherited the dependencies.

**Comment by gabikliot** [comment]
Agree.

**Comment by jthelin** [comment]
Regarding SiloHost vs TestingHost packages, i would tend to keep those things separate.

They both use the same Host class(es) under the covers, but the usage scenarios are quite different.

The TestingHost is designed for automated testing using a runner framework, whereas the SiloHost part is something for standalone developer hosting of an app for local testing of grains before publishing to final hosting environment such as Windows Server.

Azure provides another alternative hosting approach, with its local compute emulator for local testing, although in that case i could still imagine you might want to write / run some standalone test cases of the core grain logic separate from the Azure hosting part.

**Comment by sergeybykov** [comment]
So this PR is good top merge then?

**Comment by jthelin** [comment]
+1 LGTM

**Pull request merged**
