### PR TITLE
Remove deprecated call interceptor APIs

### PR DESCRIPTION
**Pull request by ReubenBond**
These APIs were marked as deprecated and can now be removed. They are replaced by `IGrainCallFilter`, which can be added at the silo or grain level.

* `IProviderRuntime.GetInvokeInterceptor`
* `IProviderRuntime.SetInvokeInterceptor`
* `InvokeInterceptor`
* `IGrainInvokeInterceptor`

### CODE REVIEW

**Comment by jdom** [comment]
This was deprecated since at least 1.5.0?

**Comment by ReubenBond** [comment]
Yes, they were marked as `[Obsolete]` in https://github.com/dotnet/orleans/pull/3083, which was included in [1.5.0](https://github.com/dotnet/orleans/releases/tag/v1.5.0)

**Comment by stephenlautier** [comment]
@ReubenBond how to use this per Silo level? Do you have any doc about this? 
From this PR changes i figured more or less how to use per grain level, but if you need it globally no idea where to register it. Thanks

**Comment by ReubenBond** [comment]
@stephenlautier check out http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Interceptors.html#silo-wide-grain-call-filters

**Comment by stephenlautier** [comment]
@ReubenBond perfect! Thanks!

**Pull request merged**
