### PR TITLE
Fix partial build

### PR DESCRIPTION
**Pull request by benjaminpetit**
Tentative to bring #4740 to the master branch

### CODE REVIEW

**Comment by ReubenBond** [comment]
I take it that this supersedes #4741? That's fine - apologies for not rebasing that PR already

**Comment by ReubenBond** [comment]
I'll just merge when functionals pass. I tested locally. It's hard to have much confidence in this PR since all versions are now fixed at 2.1.0 (because of Transactions changes in Core.Abstractions)

**Comment by ReubenBond** [comment]
@dotnet-bot test functional

**Comment by benjaminpetit** [comment]
@ReubenBond ahhhh sorry I completely missed #4741 ...

**Pull request merged**
