### PR TITLE
Fix DI cycle involving OrleansJsonSerializer

### LINKED ISSUE #4873: StackOverflowException when adding OrleansJsonSerializer as a SerializationProvider
Workaround: use this gist instead https://gist.github.com/ReubenBond/45ef767aff071302ee62731b5c706dd7

Repro:
```C#
var client = new ClientBuilder()
    .Configure<ClusterOptions>(o => o.ClusterId = o.ServiceId = "s")
    .UseLocalhostClustering()
    .Configure<SerializationProviderOptions>(o =>
        o.SerializationProviders.Add(typeof(OrleansJsonSerializer).GetTypeInfo()))
    .Build();
var s = client.ServiceProvider.GetRequiredService<SerializationManager>();

var silo = new SiloHostBuilder()
    .Configure<ClusterOptions>(o => o.ClusterId = o.ServiceId = "s")
    .UseLocalhostClustering()
    .Configure<SerializationProviderOptions>(o =>
        o.SerializationProviders.Add(typeof(OrleansJsonSerializer).GetTypeInfo()))
    .Build();
s = silo.Services.GetRequiredService<SerializationManager>();
```

Only the silo fails, the client doesn't have a dependency cycle.

### PR DESCRIPTION
**Pull request by ReubenBond**
Fixes #4873

### CODE REVIEW

**Comment by sergeybykov** [comment]
@dotnet-bot test functional

**Comment by xiazen** [comment]
why is the StackOverFlowException in issue #4873 ? it isn't very clear to me that where is this dependency cycle ?

**Comment by ReubenBond** [comment]
@xiazen serialization providers are instantiated in the SerializationManager ctor and SerializationManager is used pervasively.

The loop involves GrainFactory -> InsideRuntimeClient -> SerializationManager -> OrleansJsonSerializer (which needs GRainFactory)

**Comment by xiazen** [comment]
oic. LGTM

**Pull request merged**
