### PR TITLE
OrleansTestingHost Package - Part 2

### PR DESCRIPTION
**Pull request by jthelin**
Some final tweaks and fixes to the new TestingSiloHost following on from PR #405
- Eliminate some final places with "UnitTest" in class / file names.
- Normalize namespace in OrleansTestingHost package to align with naming convention in other packages.
- Split out some remaining public classes into their own source code files, for easier understanding of the OrleansTestingHost package contents.
- Include some default testing silo / client config files in NuGet package.
- Include NuGet package init.ps1 script to correctly handle install of silo / client config files into target project.

Then, change existing Tester projects over to use the new TestingSiloHost package.

### CODE REVIEW

**Comment by veikkoeeva** [comment]
@jthelin To continue...

The scenario I have in mind is to run "cluster" locally. I'll get to the point later, but allow me to take a bit of your time and paint scene.

An example project could be two servers with Windows Services and whatnot, two web frontends and then an Orleans system of say, three silos. Having this working on a single developer machine by simply pressing F5 will allow even more novice developers form a picture how the overall system is supposed to interact with its constituent pieces and mocked integration points. It's easy to draw a A4 sized poster having nice pictures and then mapping the projects to appropriate nodes (e.g. a deployment diagram). Arrangement such as this allows also [exploratory testing](https://en.wikipedia.org/wiki/Exploratory_testing), real testers, do testing "real time" (not only hitting the system on sprint late or something like that). For instance, every time feature branch hits master, a tester can either continue testing with the local version or pull the newest from origin master.

Maybe less rational idea is that it's nice to *feel the system*. That is, it's not just tests running occasionally or dumping something to servers (in enterprise setting, access to servers isn't granted), but when developing the front-end, one could have the silos and others systems up (on one's leisure) and debug the web front-end against "a live system". The "feel the system" here, while not real servers, relays some feel of how the topology fits together and how the grains and other parts work together and that knowledge is to some extent transferable to reasoning the real system too.

One could run something like [chaos monkey](http://techblog.netflix.com/2010/12/5-lessons-weve-learned-using-aws.html) (heh, this is a bit like the colocation mentioned in the blog post) during a coffee break with coworkes just for the fun of it and observe the system and see it should be doing what planned. Part of the "feel the system" is feeding into human curiosity and pattern recognizer mind to spot what has not been thought about and make a good use of debugger that is readily available if something unexpected happens (as it will).

I noticed [OrleansHostWrapper](https://github.com/dotnet/orleans/blob/5e964005d0cb88f38f30123ba079ddb46513adbf/src/OrleansVSTools/VSProjectSiloHost/OrleansHostWrapper.cs) while developing my [gist](https://gist.github.com/veikkoeeva/4414609e828375c898f3), but I don't wish the wrapper to bundle an arguments parser (I'd prefer something like [UnionArgParser](https://nessos.github.io/UnionArgParser/tutorial.html) in any event) and whatnot together. I'd like to be a bare-bones cluster manager I can run both in my testing project (with the framework of my choice) as easily as in my gist. Moreover, I'd like to be able to shut down, restart and add silos at my leisure. Easy configurability and the possibility to decide if running in the same process or even in separate processes (this might have production usage too). My gist has some problems in that I'll change the naming stuff, redo a bit about the [configuration part](https://gist.github.com/veikkoeeva/4414609e828375c898f3#file-gistfile1-fs-L93) and many other things. One issue is that I may want to run an Orleans cluster in a console application (or more likely with [TopShelf](http://topshelf-project.com/)) in a faul-tolerant style when I get the SQL server part done. My hunch is that it should be nearly as fast as in-memory system.

Arranging a projects like this has worked rather well, at least in the projects I've been involved in. :) The last one, which is on the finishing lines (makes me too busy), has several servers running IIS, Windows Services, reverse proxies (with things like TLS termination), integration points and so forth and this has worked well. We stub out integration points and don't run reverse proxies (we could configure IIS Express instances if it it made sense), but otherwise the system locally mimicks that of production. Common problems are that, for instance, front-end developers may find that, for some reason, the data loading/inserting feels sluggish. The reason could be as simple as overly broad query to database, missing index (or bad index as loading data to system from an integration point soiled them), too much data put on the line or whatever, but it can be examined quickly, on the spot, in debugger, when it occurs sometimes as simply as checking the call stack. Which makes the more web oriented guys on occassion step through stored procedures too in order to trace something down (but that's another story, though great in educational sense).

So, in essence, I'd like to have an easy way to have the silos running like the APIs and front-ends on IIS Express on my example project and it'd be super-nice if I could put the same arrangment to test projects and run a more formal battery through it (as in the example project). In the particular project example I mentioned, we have the code and we share the test data with outside testers. It takes mere seconds to bulk-load about 300 MiB to LocalDb and if so needed, if the testers have found something, we can just backup their database, load it in on local system and see how it might have happened.


Assuming in future Orleans relational database there's less destruction on data (i.e. less UPDATE and DELETE clauses), it could be sensible to just load data in for troubleshooting locally and observe the system state or run analytical queries to dig out certain aspects. This scenario, and the above configurability in local debugging and testing (and production) may also explain my enthusiasm on having DI and interceptors and whanot so as to have the possibility to have a good visualization on what happens in the system should there be a need.

I'm not sure if this answers any of your questions or gives thoughts. This is more of a "systems thinking" point for me. In any event, what I'm after isn't doable in this PR (probably not even in several ones) and my vision is not something that is shared. Though if you have questions, I'm glad to answer them.

**Comment by veikkoeeva** [comment]
I'll refer to to what I wrote at [#362](https://github.com/dotnet/orleans/issues/362#issuecomment-101176590362). A different facet, the same prism. :)

**Comment by jthelin** [comment]
I would tend to characterize what @veikkoeeva is describing above as a "__One-Box__" deployment setup.

There are certainly lots of merits in that, although I do think it is slightly different from the local test silo scenario.

Let's merge the testing host package into master, and i'll spin up a new discussion thread so we can talk about option for One-Box deployment scenarios.

**Comment by jthelin** [comment]
One-Box Deployment Scenarios #411

**Pull request merged**
