### PR TITLE
Rename CounterControl.exe -> OrleansCounterControl.exe

### PR DESCRIPTION
**Pull request by jthelin**
Rename CounterControl.exe -> OrleansCounterControl.exe

- Rename CounterControl.exe so that Orleans related .exe's are easy to identity.

This is a first step towards cleaning up "silo deployment package" for better compatibility with choco / scoop /homebrew / etc.

### CODE REVIEW

**Comment by sergeybykov** [comment]
What's the compatibility issue here?

**Comment by jthelin** [comment]
By not being explicit and consistent with naming then chance of name collision.

The exe package managers (choco / scoop /homebrew / etc) do some kind of symlink / stub exe hook from a common bin directory which is already on users path to each of the executables in each package.

So if any other packages use the `CounterControl` name [which is suitable generic that could happen], then either Orleans exe package would not install correctly and/or there will be non-deterministic name conflict.

**Comment by jthelin** [comment]
To provide more context, the other executables in the "silo binaries" package that gets used on a server machine are:
- OrleansHost.exe
- OrleansManager.exe
- and the anomaly: [Orleans]CounterControl.exe

Arguable "ClientGenerator.exe" should also be renamed to "OrleansCodeGen.exe" but that assembly is only in the development tools package and never directly visible to users. 
But I can submit separate PR to clean that up too, if desired.

**Comment by sergeybykov** [comment]
@jthelin Shouldn't we also rename CounterControl.csproj to OrleansCounterControl.csproj.

**Comment by jthelin** [comment]
Updated.

**Comment by jthelin** [comment]
Rebased to fix merge conflicts with master.

**Pull request merged**
