### PR TITLE
CreateOrleansTables_SqlServer.sql: Removed support for SQL Server 2000 and 2005

### PR DESCRIPTION
**Pull request by shayhatsor**
Following @sergeybykov's [comment](https://github.com/dotnet/orleans/pull/1682#issuecomment-213001965). Also, it seems [DateTime2](https://msdn.microsoft.com/en-us/library/bb677335.aspx) is supported from SQL Server 2008 and above, but Microsoft has [stopped support for SQL Server 2005](https://www.microsoft.com/en-us/server-cloud/products/sql-server-2005/). So this PR is for removing support for SQL Server 2005 too.

### CODE REVIEW

**Comment by shayhatsor** [comment]
It seems [DateTime2](https://msdn.microsoft.com/en-us/library/bb677335.aspx) is supported from SQL Server 2008 and above, but Microsoft has [stopped support for SQL Server 2005](https://www.microsoft.com/en-us/server-cloud/products/sql-server-2005/). So this PR is for removing support for SQL Server 2005 too.

**Comment by veikkoeeva** [comment]
I'm OK for removing the SQL Server 2005 specific bits, but I would like to maintain the view as I'd like to dump that information when starting up. I have at least two things to help in trouble shooting:

- Dump data in the beginning
- Dump queries pretty-printed with parameters in `Verbose3` (maybe add via a general interceptor) 

These could help in trouble-shooting. I'm not adamant on having the view though, up for discussion.

**Comment by shayhatsor** [comment]
@veikkoeeva, what do you mean by "Dump data in the beginning", which data ?
About the queries dump, I agree that could be useful.
About the view, I'd rather we remove it. With this PR, we won't have any version specific code. And for trouble-shooting, I don't think that the server version would be helpful in our scenarios.

**Comment by shayhatsor** [comment]
@veikkoeeva, we can get the server version with ADO.NET [ServerVersion](https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlconnection.serverversion).

**Comment by veikkoeeva** [comment]
@shayhatsor Or using the [DbConnection](https://msdn.microsoft.com/en-us/library/system.data.common.dbconnection.serverversion(v=vs.110).aspx) version of it. I'm not sure if this will work for all DBs, but I'm inclined to say this is better than the view.

Dump some data on database, such as its version, about the queries (as discussed elsewhere). Server version could be handy, say, when thinking on how the query engine optimizes things. It's possible to ask, though, and reintroduce informational view if needed later.

With this discussion, I'm OK with the removal. We can add `ServerVersion` sometime later too. @amccool?

**Comment by amccool** [comment]
I can't see people needing to move to Orleans and still having to support a sql server version over 8 years old.   I think it's very reasonable to ask for 2012+ for minimum.

**Comment by shayhatsor** [comment]
This PR is about removing the code which was tailored for SQL 2000 & 2005.
I believe we are in agreement about that, @sergeybykov please merge.

**Comment by sergeybykov** [comment]
Thank you, @shayhatsor!

**Pull request merged**
