### PR TITLE
Fix memory leak in timers

### PR DESCRIPTION
**Pull request by vansha**
See https://github.com/dotnet/orleans/commit/b9bad19cbf58c0570f590cc2eaceace366183325#commitcomment-24577719 for details

### CODE REVIEW

**Comment by yevhen** [comment]
Critical.

**Comment by sergeybykov** [comment]
Great catch! Thank you, @vansha and @Yevhen!

**Comment by yevhen** [comment]
Guys, when we can expect patch release with this fix?

**Comment by sergeybykov** [comment]
We are looking into a couple of other reported issues to assess if they need fixes in 1.5.2. Should clear those this week. I don't see yet why we can't release 1.5.2 by end of the week, unless we get blocked with code signing.

**Pull request merged**
