### PR TITLE
Correctly count number of items in LRU

### LINKED ISSUE #8741: LRU: AddOrUpdate incorrectly increments current count
Calling `LRU.AddOrUpdate` with an existing item will cause the current count to increase by 1.

### PR DESCRIPTION
**Pull request by koenbeuk**
Fixes #8741 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/orleans/pull/8742)

### CODE REVIEW

**Comment by modabas** [comment]
I think, moving increment count into static add function builders may be a problem, and may cause incrementing count way above real value at startup with many concurrent operations.
Also does LRU.GetOrAdd need a fix? It seems to work properly and does not increment count at update. For LRU.AddOrUpdate, if intent is not to increment count on update, perhaps following code may work (didn't test)

```
    public TValue AddOrUpdate<TState>(TKey key, Func<TState, TKey, TValue> addFunc, TState state)
    {
        var generation = GetNewGeneration();
        var storedValue = cache.AddOrUpdate(
            key,
            static (key, state) =>
            {
                var (_, outerState, addFunc, generation) = state;
                return new TimestampedValue(addFunc(outerState, key), generation);
            },
            static (key, existing, state) =>
            {
                var (self, outerState, addFunc, generation) = state;
                return new TimestampedValue(addFunc(outerState, key), self.GetNewGeneration());
            },
            (Self: this, State: state, AddFunc: addFunc, Generation: generation));

        var result = storedValue.Value;

        if (storedValue.Generation == generation)
        {
            Interlocked.Increment(ref count);
            AdjustSize();
        }

        return result;
    }
```

**Comment by modabas** [comment]
I have put together a quick [test app](https://github.com/modabas/LRU). Added a CacheCount property to LRU class that returns actual item count in cache to demonstrate what i meant.

**Comment by koenbeuk** [comment]
> I think, moving increment count into static add function builders may be a problem, and may cause incrementing count way above real value at startup with many concurrent operations.

Thanks for catching that, this indeed seems to be an issue. I've updated this PR to use the logic as you proposed.

**Review by ReubenBond — APPROVED** [review]

**Comment by mikescandy** [comment]
It seems this is the cause of an issue we're having in our production deployment that I haven't noticed until recently
image

Aug 23 is when we upgraded from 7 to 7.2.1, which includes the live grain migration and the new lru logic.
For context, I see the count exploding only for a stateless worker grain that we call for an health check
It would be awesome if this release could be release asap :)

**Comment by rwkarg** [comment]
@mikescandy Release is out with the updates:
https://github.com/dotnet/orleans/releases/tag/v7.2.4

> It seems this is the cause of an issue we're having in our production deployment that I haven't noticed until recently image
> 
> Aug 23 is when we upgraded from 7 to 7.2.1, which includes the live grain migration and the new lru logic. For context, I see the count exploding only for a stateless worker grain that we call for an health check It would be awesome if this release could be release asap :)

**Pull request merged**
