### PR TITLE
Suggested fixes for v1.2.3

### PR DESCRIPTION
**Pull request by jdom**
All of these should be non-breaking changes.
Main fixes we want in are the stacktrace preservation fix and the ones related to the GenerateSerializer attribute.
The other are nice to have bug fixes that look harmless, so feel free to push back if you see issues with those commits, as they are not deemed mandatory for v1.2.3

### CODE REVIEW

**Comment by shayhatsor** [comment]
AFAIK, #1872 hasn't been addressed yet. @sergeybykov [considered it for v1.2.3](https://github.com/dotnet/orleans/issues/1872#issuecomment-228904593). It is a regression bug.

Also, #1787 should be included.

**Comment by dsarfati** [comment]
Possibly include #1918 since there are some some issues with 1.2.2 non-silo tests.

**Comment by jdom** [comment]
@shayhatsor, thanks for suggesting #1787. I'm not very familiar with the state of relational in 1.2.2. So can you confirm this change would be completely non-breaking for users upgrading from 1.2.X?
Regarding #1872, was there any PR merged about it. Of course it might be non-breaking if we want to include it in 1.2.3.

**Comment by shayhatsor** [comment]
@jdom, #1787 is not a breaking change. Regarding #1872, you're right, there's no PR about it, I just thought I should mention it because it's a regression bug that blocks upgrades.

**Comment by ReubenBond** [comment]
I think we should include #1874 (Commit: https://github.com/dotnet/orleans/commit/332e20ae73924a45bd9cae5ea0b03408bb82dc02)

**Comment by jdom** [comment]
@ReubenBond, didn't review it myself, can you confirm it would be non breaking for users of 1.2.x?

**Comment by ReubenBond** [comment]
There are no breaking changes in that PR, and the binaries should be compatible (no public interfaces have been modified), but I haven't personally tested an in-place update of the binaries.

**Comment by jdom** [comment]
Thanks, that's good enough

**Comment by shayhatsor** [comment]
@jdom, please include #1927.

**Comment by jdom** [comment]
> @jdom, please include #1927.

Done, thanks

**Pull request merged**
