### PR TITLE
Update Introduction.md

### PR DESCRIPTION
**Pull request by shayhatsor**
minor updates that seem right to me.

### CODE REVIEW

**Comment by jthelin** [comment]
LGTM. 

The only potentially "contentious" point here might be changing "Project Orleans" to just "Orleans" -- which I am ok with generally, but is obviously related to the larger discussion going on currently in #1171 etc. about branding and naming.

So I will leave this open for a little longer so that @sergeybykov and others have a change to look at this and comment.

**Comment by shayhatsor** [comment]
In current documentation you rarely find `project orleans`... but there are lots of mentions of `Orleans`, so I figured we should currently normalize to `Orleans` and later change to whatever is decided here #1171
If this PR is merged, the last traces of `project orleans` are in: `Contributing.md`, `Links\index.md` and `Links\Orleans-Thinking-Big-and-Small.md` which goes to show that `Orleans` is the de-facto name.

**Comment by gabikliot** [comment]
OK for dropping the project.

**Comment by shayhatsor** [comment]
Just noticed that all `#### Something` in this file aren't are rendered as regular text. e.g. `#### Background`. @gabikliot probably knows how to convince it to work.

**Comment by gabikliot** [comment]
Yes, fixed it. It has to be ### and not ####.

**Comment by shayhatsor** [comment]
fixed that on my end too.

**Comment by sergeybykov** [comment]
Thank you, @shayhatsor!

**Pull request merged**
