### PR TITLE
Memory usage for activation data improved.

### PR DESCRIPTION
**Pull request by SebastianStehle**
This PR creates a memory optimized version of the Grain lifecycle subject. The ConcurrentDictionary creates a lot of sparse arrays and consumes a lot of memory. In the context of the grain I think that concurrency is not a topic.

With concurrent dictionary (100k Grains)
image

With simple list (100k Grains)
image

### CODE REVIEW

**Comment by SebastianStehle** [comment]
I was expecting this feedback. For me it seems that there are 3 lifecycle subjects:

* Clients
* Silos
* Grains

For my understanding thread safety is not needed for all three of them, but I am not sure.

**Comment by SebastianStehle** [comment]
I just changed the base implementation to use a list instead.

**Comment by SebastianStehle** [comment]
Before making more improvements it would be great to also consider other feature requests like:

* https://github.com/dotnet/orleans/issues/4519
* https://github.com/dotnet/orleans/issues/5905

I think the grain structure in general is hard to use, because it its not easy to add functionalities and it could also be easier to test grains.

**Comment by sergeybykov** [comment]
I like this. If we don't have concurrency in the use cases today, no need to pay the perf price. If we might see a concurrent use, should we simply add an optional lock that would be used only if `LifecycleSubject` is instantiated with a concurrency flag?

Allocations caused by LINQ are a concern. We see some workloads where grains are activated to handle a single request. The impact of such allocations is even worse in those cases.

**Comment by SebastianStehle** [comment]
The numbers are from a test where 50.000k grains are created, each for one request, but I have not seen the impact of the linq statements in the analysis.

**Comment by jason-bragg** [comment]
The concurrency issue, imo, is not as much a question of what we do today, because the lifecycle is an extensibility point, but more a question of what do we support.  If modification of the lifecycle needs be performed in a single thread, then we need have some means of ensuring that users are aware of this and that patterns we support ensure this. 

Grains:
The patterns described in the grain lifecycle docs look to be thread safe.  Thoughts?

https://dotnet.github.io/orleans/Documentation/grains/grain_lifecycle.html

Silo
The patterns described in the silo lifecycle docs look to be thread safe.  Thoughts?

https://dotnet.github.io/orleans/Documentation/clusters_and_clients/silo_lifecycle.html

The patterns described in the lifecycle core system would require thread safe implementations, but thats mainly describing the abstractions, so we can deal with thread safety when we get there.

https://dotnet.github.io/orleans/Documentation/implementation/orleans_lifecycle.html

From the above, I think it's safe to make this change, as the proscribed patterns are safe with this change.  Someone please sanity check me here.

**Comment by sergeybykov** [comment]
Thank you, @SebastianStehle!

**Pull request merged**
