### PR TITLE
afedin: Make compatible with blazor webasm

### PR DESCRIPTION
**Pull request by alexanderfedin**

### CODE REVIEW

**Comment by ReubenBond** [comment]
Hi @alexanderfedin, thanks for the PR. This looks like it's not ready in terms of removing all threading (for example, unless I missed it, Watchdog is still running in a separate thread). You can convert the PR to a draft while you work on it.

It would be interesting to be able to run Orleans on Blazor WASM / WASM in general. Is the only thing which needs to change the threading code? I would have imagined that some code which used reflection or emits IL would also need changing.

Please keep stylistic changes separate (eg, the using directive cleanup) so that this PR is more manageable.

**Comment by alexanderfedin** [comment]
> Hi @alexanderfedin, thanks for the PR. This looks like it's not ready in terms of removing all threading (for example, unless I missed it, Watchdog is still running in a separate thread). You can convert the PR to a draft while you work on it.
There were only things like Thread.Sleep that from System.Threading namespace, so I've changed them to be Task.Delay
If you point me to the code where Watchdog is, that would be great.

> It would be interesting to be able to run Orleans on Blazor WASM / WASM in general. Is the only thing which needs to change the threading code? I would have imagined that some code which used reflection or emits IL would also need changing.
No, having all threading code is not going to be enough, as Blazor does not allow plain vanilla TCP connections or listener-side WebSocket ones. I suppose to make it work with WebRTC and Kademlia DHT, so the whole Orleans cluster shall run in the browsers and be scalable as hell. Just imagine - joining a new client means adding a new server. Most of the clients do nothing for 80% of their runtime, so the system shall scale faster than the number of client grows.

> Please keep stylistic changes separate (eg, the using directive cleanup) so that this PR is more manageable.
Do you want these kind of changes to be in separate PRs?

**Comment by ReubenBond** [comment]
Keeping stylistic changes in a separate PR is indeed helpful.

I think the networking code could be converted to HTTPS/2 or WebSockets or WebRTC without too much difficulty. You may need a way to map SiloAddress to a URI, but that is not infeasible. Regarding using a Kademlia implementation, that could be a separate discussion. There are a lot of things to consider there around failure modes and consistency guarantees.

As for converting Watchdog to use `Task.Delay`, that is *ok* for Blazor, but I would prefer we keep using Thread.Sleep for the non-WASM cases. The Watchdog intentionally avoids the ThreadPool & TaskScheduler today, so that it is less affected by ThreadPool starvation.

**Comment by alexanderfedin** [comment]
> Keeping stylistic changes in a separate PR is indeed helpful.
I usually do code cleanup as I go, but if you think that this should be done separately, then I'll follow your advice.

> I think the networking code could be converted to HTTPS/2 or WebSockets or WebRTC without too much difficulty. You may need a way to map SiloAddress to a URI, but that is not infeasible. 
I suppose that in order to do that networking should be abstracted out more than it is now. Wanna keep an ability to connect through regular TCP and add UDP, WebSocket and WebRTC, so it should use whatever is available at the moment. WebRTC will be the toughest one as it needs some existing channel to do the connection handshake. I am willing to copy that behavior from WebTorrent, so it can use millions of existing machines for discovery (DHT-based) and handshake messaging relay.

> Regarding using a Kademlia implementation, that could be a separate discussion. There are a lot of things to consider there around failure modes and consistency guarantees.
You are right, and I see these failure modes and consistency things very close to whatever Orleans does now when it is deployed across multiple clusters.

> As for converting Watchdog to use `Task.Delay`, that is _ok_ for Blazor, but I would prefer we keep using Thread.Sleep for the non-WASM cases. The Watchdog intentionally avoids the ThreadPool & TaskScheduler today, so that it is less affected by ThreadPool starvation.
Do you mean that you wanna avoid changing the thread on 'await Task.Delay(...)'?
Mono.Wasm does support multithreading in desktop Chromium, but it does not do it well or does not do it at all on Edge, Safari and mobile browsers. Having 'Thread.Wait(...)' anywhere might mean that nobody else shall be able to execute.
I'll check if there is an easy way to see that the code is running on Blazor or not, so Orleans will use 'Task.Delay(...)' on Blazor only.

**Comment by ReubenBond** [comment]
> Do you mean that you wanna avoid changing the executing thread on 'await Task.Delay(...)'?

Using `Task.Delay` is fine on WebAssembly, but not on other targets - so a change there could be potentially conditional on an `#if` statement

**Comment by ReubenBond** [comment]
Closing this for now. Feel free to open again/another.

**Pull request closed without merging**
