### PR TITLE
avoid lazy initialization when disposing OutboundMessageQueue

### PR DESCRIPTION
**Pull request by sillyousu**
update #4965

### CODE REVIEW

**Comment by sillyousu** [comment]
I try to investigate the failing test but block by the following error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1005	Assets file 'C:\Users\a\source\repos\orleans\test\Extensions\ServiceBus.Tests\obj\project.assets.json' doesn't have a target for '.NETFramework,Version=v2.0'. Ensure that restore has run and that you have included 'net20' in the TargetFrameworks for your project.	ServiceBus.Tests	C:\Program Files\dotnet\sdk\2.1.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	198	
```

**Comment by xiazen** [comment]
rerun the test in case it is test issue, not code issue. SOmetimes tests fail intermittently because of test issue

**Comment by xiazen** [comment]
@dotnet-bot test functional please

**Comment by xiazen** [comment]
thanks for the contribution, Tests passes now.

**Pull request merged**
