### PR TITLE
Support of ValueTask as a grain method return type

### PR DESCRIPTION
**Pull request by kutensky**
#2480
Added support of ValueTask as a return type of grain method.
It's a first step of ValueTask support. For now it's just allow users to use ValueTask as a return type to improve their grain performance. Later on we can try to improve our own performance by using ValueTask instead of Task.
Even so, if users start using ValueTask they will have more freedom of writing their code and when we implement full support of ValueTask, they will suddenly fill performance improvement without need of changing their code.

### CODE REVIEW

**Comment by kutensky** [comment]
Hi @ReubenBond . I have some strange error in my pull request. There is 2 errors:
1.  DependencyInjection.Tests
It fails before the test starts. Error message is "The following constructor parameters did not have matching fixture data: BaseTestClusterFixture fixture".
But problem is that fails even on master branch. 
2. EHStatisticMonitorTests.
It pass on my location machine.

Could you give any advise?

**Comment by kutensky** [comment]
@dotnet-bot test functional

**Comment by ReubenBond** [comment]
@dotnet-bot test this please

**Comment by kutensky** [comment]
@dotnet-bot test functional

**Comment by xiazen** [comment]
@kutensky the error message you posted for DependencyInjection.Tests is not the actual error which caused the test fail to start. I believe there's more inner stack trace which can give us more insight.

**Comment by xiazen** [comment]
and about the EHStatisticMontoring test, it fails intermittently because the test rely on timing a lot. So it failing might be benign. Rerun the test using the command Reuben is talking about, it will likely succeed.

**Comment by kutensky** [comment]
@xiazen, @ReubenBond  Thanks for your help. After restarting tests, it says that all tests passed.

**Comment by ReubenBond** [comment]
Great work @kutensky! Apologies for the delay in merging this

**Comment by icanhasjonas** [comment]
Is there a reason for comparing strings instead of generic types?

```cs
  var same = method.ReturnType.GetGenericTypeDefinition().FullName == "System.Threading.Tasks.Task`1";
```

vs

```cs
  var same = method.ReturnType.GetGenericTypeDefinition() == typeof(Task<>);
```

**Comment by kutensky** [comment]
@icanhasjonas I don't see any.

**Pull request merged**
