### PR TITLE
Execute lifecycle on OrleansTaskScheduler

### PR DESCRIPTION
**Pull request by ReubenBond**

### CODE REVIEW

**Comment by ReubenBond** [comment]
@dotnet-bot test this please

**Comment by jason-bragg** [comment]
@dotnet-bot test functional please

**Comment by jason-bragg** [comment]
@dotnet-bot test functional please

**Comment by jason-bragg** [comment]
not sure what's going on here.  Everything works locally..  will try again.

**Comment by jason-bragg** [comment]
@dotnet-bot test functional please

**Comment by jason-bragg** [comment]
hmm.  The tests in these 5 assemblies didn't complete within 1.5 hours, though locally all but "tester" seem to run in under a few minutes.

TesterInternal
Tester
TesterZooKeeperUtils
Orleans.Transactions.Tests
Orleans.TestingHost.Tests

I'll investigate more.

Wild speculations:
- Could the fact that everything is now being started on a single thread be leading to a performance problem that is making tests run too long?
- Could an exception thrown in the shutdown be causing the scheduler to not be stopped, and lead to some sort of resource leak which becomes exaggerated over extended test runs?
- Could someone be using our test cluster to mine bitcoins, slowing down our tests?

**Comment by ReubenBond** [comment]
I'm thinking that there was probably a deadlock because I shared the scheduling context for both lifecycle and providers

**Comment by ReubenBond** [comment]
@dotnet-bot test this please

**Pull request merged**
