### PR TITLE
MySQL Script: Minor syntax tweak to support previous server versions

### PR DESCRIPTION
**Pull request by shayhatsor**
addresses the first part of https://github.com/dotnet/orleans/pull/2288#issuecomment-254070763.
Tested on MySql 5.6.34 and 5.7.15

### CODE REVIEW

**Comment by shayhatsor** [comment]
@veikkoeeva, this is a minor tweak. please take a quick look to see if i've missed anything.

**Comment by veikkoeeva** [comment]
@shayhatsor LGTM. The issue was about every instance with the `WHERE NOT EXISTS` structure and you have addressed them all.

**Comment by shayhatsor** [comment]
@jdom, please merge

**Comment by jdom** [comment]
sure thing, trusting your and @veikkoeeva 's judgment. BTW, I assume this is non-breaking and could go into 1.3.1?

**Comment by veikkoeeva** [comment]
@jdom Yes, this is non-breaking and better. For good or worse, should bring less people talking to Gitter. :P

**Pull request merged**
