### PR TITLE
Fixes for 1.1.2 release

### PR DESCRIPTION
**Pull request by sergeybykov**

### CODE REVIEW

**Comment by ReubenBond** [comment]
LGTM. Are there any other commits which should make it into the v1.1.2 patch release?

**Comment by sergeybykov** [comment]
This is all I found. https://github.com/dotnet/orleans/pull/1182 is another candidate but I had some merge challenges with it. Also https://github.com/dotnet/orleans/pull/1141, but I wasn't sure.

**Comment by gabikliot** [comment]
Why cherry pick? Why not take just all master?

**Comment by centur** [comment]
#1182 will be great to have (as we have some related issues in our code marked as TODO: Wait for Orleans fix :)

**Comment by galvesribeiro** [comment]
If the intent is to just get only fixes and very small improvements, LGTM.

**Comment by sergeybykov** [comment]
@gabikliot 1.1.2 is meant to be a patch release, with big fixes only. No new functionality or major changes, such as, for example, elimination of `GrainState`. We'll cut 1.2.0 with those changes when there is enough of them to warrant a major release.

**Comment by sergeybykov** [comment]
@centur I added https://github.com/dotnet/orleans/pull/1182.

**Comment by ReubenBond** [comment]
LGTM

**Comment by centur** [comment]
@sergeybykov :+1: appreciate that.

**Pull request merged**
